<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Aprobar</name>
   <tag></tag>
   <elementGuidId>c8fa3b1a-7659-437e-a448-c228f3052678</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='__xmlview13--myInbox_POSITIVE-BDI-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview13--myInbox_POSITIVE-BDI-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>fdc621cf-179b-453b-9a92-e27f0b33444a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview13--myInbox_POSITIVE-BDI-content</value>
      <webElementGuid>a87c67be-cb58-4cbc-8125-06413c4a191c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>8a421791-889b-4cbc-9776-b62b0cb75c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aprobar</value>
      <webElementGuid>fbca4188-b1f2-4f49-a0b3-d54cbdedb023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview13--myInbox_POSITIVE-BDI-content&quot;)</value>
      <webElementGuid>ab593891-bd3d-4275-b726-99c99f88c053</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='__xmlview13--myInbox_POSITIVE-BDI-content']</value>
      <webElementGuid>0926bcfc-072e-4dd9-95f8-488a337bf572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__xmlview13--myInbox_POSITIVE-content']/bdi</value>
      <webElementGuid>4eda39c2-12ea-49ed-a9ce-40562f9835f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fin de contenido lateral. Para ocultar, pulse la barra espaciadora.'])[2]/following::bdi[1]</value>
      <webElementGuid>50160e51-cd81-428c-a811-b918e95c3a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ocultar detalles'])[1]/following::bdi[1]</value>
      <webElementGuid>39056a84-9303-4060-950f-f3254e4c5854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rechazar'])[1]/preceding::bdi[1]</value>
      <webElementGuid>038769e4-d94a-4ad7-a343-7fe3ec9fbe05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitud/Respuesta de Información'])[1]/preceding::bdi[2]</value>
      <webElementGuid>4485f0dc-1f66-4698-b090-52ae28e0d3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aprobar']/parent::*</value>
      <webElementGuid>00f66be4-4ffc-41f1-bf8c-6d97052e2c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span/span/bdi</value>
      <webElementGuid>9a3e2dda-fb03-4dd4-95e4-fbfa43314413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = '__xmlview13--myInbox_POSITIVE-BDI-content' and (text() = 'Aprobar' or . = 'Aprobar')]</value>
      <webElementGuid>6c84d2b1-9e1d-4b46-9e70-699969df11f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
