<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Grupo-Perfil Proyecto Inversin</name>
   <tag></tag>
   <elementGuidId>a321a247-975b-4df6-9535-d873e41014d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u7677-second</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Grupo-Perfil Proyecto Inversión']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a1fab253-eba7-406d-bfa4-c381f9b47d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u7677-second</value>
      <webElementGuid>864dd386-86f8-4cb9-9b1d-cc9ef6399b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsListbox__value lsListbox__value--hover</value>
      <webElementGuid>812e5461-6b1f-49dd-8080-e4c095b02b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemid</name>
      <type>Main</type>
      <value>u7677</value>
      <webElementGuid>4b2c3d94-fa7f-42e0-a90c-e2263176c1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>389a8aec-7484-4442-8899-ec24b8bc82b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>u7677-ariaItemValues</value>
      <webElementGuid>ccb1114c-7353-4971-9c0f-b3b78cffb0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grupo-Perfil Proyecto Inversión</value>
      <webElementGuid>007dc5fe-ace4-4aa9-a2c4-fec08d15ee79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u7677-second&quot;)</value>
      <webElementGuid>d78dc624-9113-4d91-8514-0a64179adf0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Creación Proyecto/Page_Project Builder/iframe_Ms_application-Project-process-iframe</value>
      <webElementGuid>bda18790-a76b-4173-bf1b-1a40590611d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='u7677-second']</value>
      <webElementGuid>5c04f116-b678-4ab9-a5b7-86a19616ad62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PROJ-PROFLSAPLCJWB-scrl']/div[2]/div[44]</value>
      <webElementGuid>15ec40fa-d093-4ae5-b0c6-4f79c857b842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupo-Perfil Proyecto Gasto'])[1]/following::div[1]</value>
      <webElementGuid>2c260253-a47c-4f58-81db-014a7b5039a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupo-Perfil Proy. Estadísco Gasto'])[1]/following::div[2]</value>
      <webElementGuid>9dab08c8-a1e9-47e1-a7c7-f5aaf5952498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupo-Perfil Proyectos de Stock'])[1]/preceding::div[1]</value>
      <webElementGuid>2019ef50-0785-486e-94bb-00a57a2b2f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendu - sans lissage'])[1]/preceding::div[2]</value>
      <webElementGuid>fa737326-9e41-439e-b270-4624703ec411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grupo-Perfil Proyecto Inversión']/parent::*</value>
      <webElementGuid>89f99efe-c66b-480a-b731-cc23925a17a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[44]</value>
      <webElementGuid>c3cdd6b7-f330-4630-8ff0-ab937b7fd424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'u7677-second' and (text() = 'Grupo-Perfil Proyecto Inversión' or . = 'Grupo-Perfil Proyecto Inversión')]</value>
      <webElementGuid>caec065a-1e10-466a-aea4-ec46f7e9f6e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
