<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Copier donnes slectionnes</name>
   <tag></tag>
   <elementGuidId>91791b2e-e9a6-4f5d-9c3c-e96981811791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaseorder-createPOfromContract-component---master--idCopySelectedItemsNew-BDI-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='application-zpurchaseorder-createPOfromContract-component---master--idCopySelectedItemsNew-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>c6adc30e-1450-4770-b921-f5adb5b2359d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaseorder-createPOfromContract-component---master--idCopySelectedItemsNew-BDI-content</value>
      <webElementGuid>a23a3972-52fd-4fbc-b6c9-660cb8d7af53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>edce9dfd-ff1e-4e0b-8d49-872fa20ac810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copier données sélectionnées</value>
      <webElementGuid>05dfe931-3054-48ec-9325-e04d691f7804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaseorder-createPOfromContract-component---master--idCopySelectedItemsNew-BDI-content&quot;)</value>
      <webElementGuid>eb0ed334-6989-4391-905a-e669b777f1d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='application-zpurchaseorder-createPOfromContract-component---master--idCopySelectedItemsNew-BDI-content']</value>
      <webElementGuid>4c7a6c9f-fabc-47ce-87ef-3083950acbe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-zpurchaseorder-createPOfromContract-component---master--idCopySelectedItemsNew-content']/bdi</value>
      <webElementGuid>4ccb801d-7495-4772-9b8a-4dd0b1cf8fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lancer'])[1]/following::bdi[1]</value>
      <webElementGuid>aed7e078-cbe9-4af2-a7fd-c975746cf804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options'])[1]/preceding::bdi[1]</value>
      <webElementGuid>ec03365b-910f-4b7e-b928-1739d12d88e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agrandir'])[1]/preceding::bdi[1]</value>
      <webElementGuid>17c69097-56c0-43ea-919c-dfb230caaeee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Copier données sélectionnées']/parent::*</value>
      <webElementGuid>ebd48508-c386-4b8c-a598-1dcf6ace9699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/bdi</value>
      <webElementGuid>fd2303a2-45bb-40cd-b941-06bc7cabee6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'application-zpurchaseorder-createPOfromContract-component---master--idCopySelectedItemsNew-BDI-content' and (text() = 'Copier données sélectionnées' or . = 'Copier données sélectionnées')]</value>
      <webElementGuid>8c7cbbcb-3277-40b3-ad10-92e8518e28eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
