<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_42-A150</name>
   <tag></tag>
   <elementGuidId>d2445bad-7842-40cb-9c92-e7254abe6a01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__dialog1-table-rows-row1-col0 > div.sapUiTableCellInner.sapUiTableFirstColumnCell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='__dialog1-table-rows-row1-col0']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>81a9f09f-a984-4ee5-8f07-e9d0f3ccacc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiTableCellInner sapUiTableFirstColumnCell</value>
      <webElementGuid>cf2b5b68-2ef1-45c2-8a51-0e295d6d767f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>42-A150</value>
      <webElementGuid>d41fa492-bd5c-46de-9018-91f238902faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__dialog1-table-rows-row1-col0&quot;)/div[@class=&quot;sapUiTableCellInner sapUiTableFirstColumnCell&quot;]</value>
      <webElementGuid>4b57ca43-1787-4f23-97d7-709c649fdf8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='__dialog1-table-rows-row1-col0']/div</value>
      <webElementGuid>95c0d987-c620-463d-b17f-f6bc1a5776c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HIST-REND-DPT SEA14'])[1]/following::div[1]</value>
      <webElementGuid>958f26d9-50ad-41c4-9c0e-fcc2835caba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Désignation'])[1]/following::div[8]</value>
      <webElementGuid>e3f829b9-3681-4abe-841d-b4b2289f5aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REND- SSD A150'])[1]/preceding::div[1]</value>
      <webElementGuid>23088382-718d-44c6-bc3f-298d72863d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REND-DPT A88'])[1]/preceding::div[3]</value>
      <webElementGuid>4e522aad-031a-4ac7-9ac5-76b692e951c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div</value>
      <webElementGuid>a1ee1219-f290-47d1-a02c-b7670f53b0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '42-A150' or . = '42-A150')]</value>
      <webElementGuid>34df4ad3-4437-4b52-8c0f-ade4fbd61d6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
