<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Afficher plus_application-zpurchaseord_188661</name>
   <tag></tag>
   <elementGuidId>15359d61-d1c4-434e-8f0f-565283d7c54d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaseorder-createPOfromContract-component---cartView--idButtonPosition-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-zpurchaseorder-createPOfromContract-component---cartView--idButtonPosition-img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f5b58d7c-115a-47ba-a1a6-dd4ab8a845d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaseorder-createPOfromContract-component---cartView--idButtonPosition-img</value>
      <webElementGuid>1b4eb991-b4f2-4a34-833c-6d4d68c9b14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-zpurchaseorder-createPOfromContract-component---cartView--idButtonPosition-img</value>
      <webElementGuid>999eb792-cb04-4f10-95a0-093c3091505e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>740ab97a-b961-4776-bc33-067db522b96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3261e957-c12d-48e5-9cad-c77c92780de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>0bab5358-549e-4779-a70a-90b03a1890e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapMBtnCustomIcon sapMBtnIcon sapMBtnIconLeft</value>
      <webElementGuid>d997250b-ba79-4d26-bcb1-ef0ef8072c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaseorder-createPOfromContract-component---cartView--idButtonPosition-img&quot;)</value>
      <webElementGuid>61d00785-071b-4e24-88b2-02fd20b3f668</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-zpurchaseorder-createPOfromContract-component---cartView--idButtonPosition-img']</value>
      <webElementGuid>cc898e0e-a5a1-4ea6-a56b-21a98e294e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-zpurchaseorder-createPOfromContract-component---cartView--idButtonPosition-inner']/span</value>
      <webElementGuid>a3d24c02-d1c0-4151-bda0-dc8d296de09c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/footer/div/button/span/span</value>
      <webElementGuid>56c7290d-b207-4dda-b202-578ed62ca166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-zpurchaseorder-createPOfromContract-component---cartView--idButtonPosition-img']</value>
      <webElementGuid>7f9a02cf-6ba4-4207-9e90-6d6db4ccf92e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
