<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Commentaires au fournisseur_applic_f2ef6b</name>
   <tag></tag>
   <elementGuidId>dad0ecd3-95cc-47b0-bb90-287fbe6b5ddd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaseorder-createPOfromContract-component---detail--idHF01-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='application-zpurchaseorder-createPOfromContract-component---detail--idHF01-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>df8e1f6a-7532-4ccb-871f-2af9550562db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaseorder-createPOfromContract-component---detail--idHF01-inner</value>
      <webElementGuid>32d101c4-4f93-48d2-8d14-6416cd64a39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-zpurchaseorder-createPOfromContract-component---detail--idHF01E-label</value>
      <webElementGuid>35d9eeec-f742-4ee7-a364-f8afc261a3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>14e30b8f-bf6f-4b18-a36d-d65bdc12fdb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>23efd685-b863-46e6-b915-a9bd58eedf4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner sapMTextAreaInner</value>
      <webElementGuid>dd0aebed-3bb8-4088-a81b-266be73f876b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaseorder-createPOfromContract-component---detail--idHF01-inner&quot;)</value>
      <webElementGuid>4675c9f7-5244-4efb-b05d-c70600d7a2eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='application-zpurchaseorder-createPOfromContract-component---detail--idHF01-inner']</value>
      <webElementGuid>fe4f12b1-8b5f-42f6-b381-47492f57c20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaseorder-createPOfromContract-component---detail--idHF01-content']/textarea</value>
      <webElementGuid>65098b52-8c0f-4e3d-a750-720f2ad5e37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commentaires au fournisseur'])[1]/following::textarea[1]</value>
      <webElementGuid>289b9064-bdcf-47b7-91d4-11762a3a9d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Afficher plus'])[1]/preceding::textarea[1]</value>
      <webElementGuid>26b4c425-1b9e-4239-89f5-46345ebd1d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postes'])[4]/preceding::textarea[1]</value>
      <webElementGuid>d905e7d3-571c-484d-8530-627ae4ec95da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/textarea</value>
      <webElementGuid>54c910fc-3cbf-4f61-b6a5-1f0496cc0a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'application-zpurchaseorder-createPOfromContract-component---detail--idHF01-inner']</value>
      <webElementGuid>08a9fd1c-5cac-4717-b201-d3fab9c344bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
