<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Workflow 3</name>
   <tag></tag>
   <elementGuidId>e8a4c5b3-619e-4cf3-9aee-12783a35f141</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='tree#C108#5#1#Text#i']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a6391ddc-a7f0-465e-84f8-1650a0b4b1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tree#C108#5#1#Text#i</value>
      <webElementGuid>63043fa1-b2d4-4205-94eb-6cffa7c47b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>TV</value>
      <webElementGuid>78b3b899-f3b6-426b-9b2a-839811d555f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;Workflow 3&quot;,&quot;2&quot;:false,&quot;7&quot;:&quot;INHERIT&quot;,&quot;14&quot;:true,&quot;15&quot;:true,&quot;17&quot;:{&quot;ctmenu&quot;:true,&quot;focusable&quot;:&quot;X&quot;}}</value>
      <webElementGuid>b42cd340-98ff-4cb3-8cc0-ef2a6f486165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1b6d3858-0de5-458a-a1dc-be7bc728cecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>41db19bc-d867-47f0-a0ac-1d5dd13d3f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d29ac7cd-d430-48f5-b414-d916b280c693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsTextView lsControl--noWrapping lsTextView--usedInTable lsTextView--design-standard  lsTextView--nowrap</value>
      <webElementGuid>f4496456-b682-4d1c-93f6-56be9a2243a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Workflow 3</value>
      <webElementGuid>158e6a9a-0ee9-495e-b5fd-743b6777bfc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tree#C108#5#1#Text#i&quot;)</value>
      <webElementGuid>de03fac8-dd17-4b02-80af-a666a89a481f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VIM creacion de facturas sin pedido con wf autorizacion/Page_Business Workplace de MA_RSANCHRO/iframe_Ms_application-zgui_opt_vim_wp-displ_b9e7ed</value>
      <webElementGuid>94a3a69a-38dc-497c-a1d6-0909edf59019</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='tree#C108#5#1#Text#i']</value>
      <webElementGuid>4ee24822-bb96-45ff-9e05-1635fde77372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='tree#C108#5#1#Text#i-r']/span</value>
      <webElementGuid>56bf5272-f4cc-44f7-a846-11da6df44bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nivel 2 Desplegado'])[1]/following::span[6]</value>
      <webElementGuid>38b69a2a-444c-42aa-9556-a064e3af94bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documentos 3'])[1]/following::span[9]</value>
      <webElementGuid>5a1ec2aa-4110-446e-9c3b-3613b56d810f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nivel 3 Comprimidos'])[1]/preceding::span[3]</value>
      <webElementGuid>5488ddd2-ec3b-4ca3-8c06-876d24dd7ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='agrupados por tareas'])[1]/preceding::span[8]</value>
      <webElementGuid>a9a279e7-cce6-456e-a016-8b82c60679d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Workflow 3']/parent::*</value>
      <webElementGuid>25756118-c6ea-4951-85fd-c93344d4507d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/table/tbody/tr/td[3]/div/table/tbody/tr/td[3]/div/span/span</value>
      <webElementGuid>4b4c52b9-3fa3-42d3-9782-a1d51dc857a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'tree#C108#5#1#Text#i' and (text() = 'Workflow 3' or . = 'Workflow 3')]</value>
      <webElementGuid>85bca4e3-1759-43c2-b73c-270a8737bf2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
