<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ir</name>
   <tag></tag>
   <elementGuidId>4c5a6dd5-eab8-4d57-b8ca-431335531c07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-ZPM_SMART-ListMeasDoc-component---main--iSmartFilterBar-btnGo-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-ListMeasDoc-component---main--iSmartFilterBar-btnGo-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6fdda061-c6cc-43e1-ab68-31836c6ad76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-ListMeasDoc-component---main--iSmartFilterBar-btnGo-inner</value>
      <webElementGuid>fb226fe3-76b1-45f2-8f9e-5ae61a67eaf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnInner sapMBtnHoverable sapMFocusable sapMBtnText sapMBtnEmphasized</value>
      <webElementGuid>9160b5d1-10a1-41ca-b2b9-6dd7e595059b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ir</value>
      <webElementGuid>1b96442d-b752-461d-8508-309ee678ceec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-ListMeasDoc-component---main--iSmartFilterBar-btnGo-inner&quot;)</value>
      <webElementGuid>ede866cc-30c7-49b6-9af8-f6a5be9b63a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-ListMeasDoc-component---main--iSmartFilterBar-btnGo-inner']</value>
      <webElementGuid>c50e600a-a803-483b-903a-46b51091c14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='application-ZPM_SMART-ListMeasDoc-component---main--iSmartFilterBar-btnGo']/span</value>
      <webElementGuid>27630dfe-4f30-44e0-b695-ffcaf8f69ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar vista'])[1]/following::span[2]</value>
      <webElementGuid>ff5ad86c-76b4-4b32-9ee1-8c8d327a3df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[5]</value>
      <webElementGuid>4b11e68e-a014-4a27-827c-b93a2d716a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ocultar barra de filtros'])[1]/preceding::span[2]</value>
      <webElementGuid>5b29e1bb-2734-434c-aea8-9ed4efef8a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/button/span</value>
      <webElementGuid>ef3e385a-054f-40e7-8fac-d4454b111f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-ZPM_SMART-ListMeasDoc-component---main--iSmartFilterBar-btnGo-inner' and (text() = 'Ir' or . = 'Ir')]</value>
      <webElementGuid>0fa616e7-7998-4654-adcb-5a860c56d7ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
