<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Crear</name>
   <tag></tag>
   <elementGuidId>bc8c56f8-3cf6-4f53-a751-ec2e5e574086</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='com.abertis.mm.zpurchaserequisitionlr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosPurchaseRequisitionLR--Create-Own-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1ca19464-d9a1-4b61-9f33-0d986e9a5258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>com.abertis.mm.zpurchaserequisitionlr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosPurchaseRequisitionLR--Create-Own-inner</value>
      <webElementGuid>891247af-6271-434b-844e-9a027871d4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnInner sapMBtnHoverable sapMFocusable sapMBtnText sapMBtnIconFirst sapMBtnEmphasized</value>
      <webElementGuid>618fd437-6dc7-484a-bde8-0c3f5699f6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Crear</value>
      <webElementGuid>64d4e4c1-d20d-4136-9171-6c8f58c31d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;com.abertis.mm.zpurchaserequisitionlr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosPurchaseRequisitionLR--Create-Own-inner&quot;)</value>
      <webElementGuid>f88ca343-4548-4999-a7a4-73e1cc8fef37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='com.abertis.mm.zpurchaserequisitionlr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosPurchaseRequisitionLR--Create-Own-inner']</value>
      <webElementGuid>eeafd61d-509d-4681-a584-d3fc7ab56454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='com.abertis.mm.zpurchaserequisitionlr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosPurchaseRequisitionLR--Create-Own']/span</value>
      <webElementGuid>5cd1ffdc-73e7-4aea-a637-15f8f10840e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posiciones de Solicitudes de pedido (11)'])[1]/following::span[1]</value>
      <webElementGuid>cceb35e6-df06-4728-bc9b-13ce4d07be79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Más'])[2]/following::span[5]</value>
      <webElementGuid>cd7fe4f2-b4bc-4459-8706-8ba10742a2fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear con referencia'])[1]/preceding::span[4]</value>
      <webElementGuid>71021a46-570a-4b07-ac15-1a507711deed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/button/span</value>
      <webElementGuid>ebc09f24-f051-41b9-849d-75ee428fc419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'com.abertis.mm.zpurchaserequisitionlr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosPurchaseRequisitionLR--Create-Own-inner' and (text() = 'Crear' or . = 'Crear')]</value>
      <webElementGuid>bad52224-f4af-47d1-9830-d5cc33ed408f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
