<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pgina de inicio_sapUiIconTitle</name>
   <tag></tag>
   <elementGuidId>e56e4ccb-9d09-47ec-8dbf-03ce8988df09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__icon0']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sapUiIconTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>851844db-8e81-4aaf-ae16-c197ac93754c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Menú de todas mis aplicaciones</value>
      <webElementGuid>49053ecd-4311-49d6-b16e-c92fe195ace4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2786bb69-42b8-4b89-a453-a5bc79ccaeef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIconTitle</value>
      <webElementGuid>0f72aa01-5773-4e19-8217-2669171c954b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__icon0&quot;)/span[@class=&quot;sapUiIconTitle&quot;]</value>
      <webElementGuid>c79dfd38-7655-4e61-a13f-ef8080dd828a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__icon0']/span</value>
      <webElementGuid>ed33c810-d581-46cd-88e9-c0b6d568c61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span</value>
      <webElementGuid>b5142e67-e2ff-4964-9cff-959f6c824f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Menú de todas mis aplicaciones']</value>
      <webElementGuid>585b212b-66ec-4340-80f6-b6885f1ac7e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
