<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Avvio</name>
   <tag></tag>
   <elementGuidId>b897a638-2b0b-4e93-9418-5782235305ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//bdi[(text() = 'Avvio' or . = 'Avvio')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/button/span/span/bdi</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>181872d7-951f-4b1e-bdb3-0c345af3f824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>com.abertis.mm.zpowithcontract::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo-BDI-content</value>
      <webElementGuid>9eb3ec5f-d74a-4fab-95e7-4d3da364b8db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Avvio</value>
      <webElementGuid>cf59aabc-2f74-4df6-9ee9-d91d54964df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;com.abertis.mm.zpowithcontract::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo-BDI-content&quot;)</value>
      <webElementGuid>0ceb3e66-cfe1-49d4-b64b-ad12c8c687db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='com.abertis.mm.zpowithcontract::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo-BDI-content']</value>
      <webElementGuid>ab1017d6-e3ea-4718-a603-4d9d36d6e5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='com.abertis.mm.zpowithcontract::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo-content']/bdi</value>
      <webElementGuid>e7a79ece-c90d-4502-8491-e5fa5fbbe8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adatta filtri (1)'])[2]/following::bdi[1]</value>
      <webElementGuid>b393f8e7-32fd-482f-8b4a-c49f6c78d866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adatta filtri (1)'])[1]/following::bdi[1]</value>
      <webElementGuid>f6bce6e7-d97d-464c-ab5d-580f3243920d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avvio'])[2]/preceding::bdi[1]</value>
      <webElementGuid>4777c305-b3a8-4bcd-ab2e-e8aaa4f3831a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprimi testata'])[1]/preceding::bdi[1]</value>
      <webElementGuid>bc53c5a4-4a33-4b28-8766-3e55373f5009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Avvio']/parent::*</value>
      <webElementGuid>e63a2fc6-452b-46fc-96f7-91f2ba08366c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button/span/span/bdi</value>
      <webElementGuid>e7889849-bcfd-4ca5-b04f-4d516bba3eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'com.abertis.mm.zpowithcontract::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo-BDI-content' and (text() = 'Avvio' or . = 'Avvio')]</value>
      <webElementGuid>6b6b1142-9a11-411c-a4e7-e0bd4a0f9950</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
