<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Equipo_application-ZPM_SMART-ListEqui_63c20f</name>
   <tag></tag>
   <elementGuidId>758cba9a-a11b-4dff-8432-c4e65cfd07bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-ListEquip-component---main--smartFilterBar-filterItemControlA_-Equnr-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='application-ZPM_SMART-ListEquip-component---main--smartFilterBar-filterItemControlA_-Equnr-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e202b567-3bf5-41dc-96c8-88d58d06c12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-ListEquip-component---main--smartFilterBar-filterItemControlA_-Equnr-inner</value>
      <webElementGuid>ccbe3c08-17d1-4097-a8c8-b06534b7317c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>79a97e10-2afe-4d1a-bd7c-4b75f7af4adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-ZPM_SMART-ListEquip-component---main--smartFilterBar-filterItem-EquipmentSet-Equnr</value>
      <webElementGuid>0a92b8c7-88c8-4554-a344-2d6eafbe3d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text244</value>
      <webElementGuid>6c861262-f6c0-4f0b-8ece-80a5b0be357a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>a1630754-5306-40a1-874a-3bfe44630de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-roledescription</name>
      <type>Main</type>
      <value>Entrada de varios valores</value>
      <webElementGuid>ae6c91e7-31f7-407a-959e-860693a5a5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a1c6e012-26d4-4244-8984-93851c1476b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>30f2510f-72dc-4cfc-88c4-f5e5f0835b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>2e681e0d-8bfa-4d7d-b3b4-5772edd59f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-ListEquip-component---main--smartFilterBar-filterItemControlA_-Equnr-inner&quot;)</value>
      <webElementGuid>5aae7eaa-d560-4dbe-9f97-a676c23ef466</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-ZPM_SMART-ListEquip-component---main--smartFilterBar-filterItemControlA_-Equnr-inner']</value>
      <webElementGuid>a2061725-e036-4deb-8404-771ceb31fa43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-ZPM_SMART-ListEquip-component---main--smartFilterBar-filterItemControlA_-Equnr-content']/input</value>
      <webElementGuid>5df0b750-f7e3-49dc-8346-96bb121eed0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>84a7e1b5-e5a4-46a4-bcec-4e91d6630e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-ZPM_SMART-ListEquip-component---main--smartFilterBar-filterItemControlA_-Equnr-inner' and @type = 'text']</value>
      <webElementGuid>78efd478-f00d-4217-981a-388057cfe454</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
