<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BuscadorCompra</name>
   <tag></tag>
   <elementGuidId>5d855790-a730-4d3f-a983-55f176bdca05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='com.abertis.mm.zgrdesdepo::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PEDIDOSCOMPRA--listReportFilter-btnBasicSearch-I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0cae01ac-857d-486f-82fe-f2ad0df8b694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>dc78417d-6113-421a-85c5-a42bf0798d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dfc59e5b-85b4-4668-9165-c5a66e279d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>com.abertis.mm.zgrdesdepo::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PEDIDOSCOMPRA--listReportFilter-btnBasicSearch-I</value>
      <webElementGuid>413f2506-c03f-412c-9ebc-b7fdd7faa9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSFI</value>
      <webElementGuid>74e88920-8218-4141-8406-f0858ac625b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>e2b77f50-c47e-4679-bb14-48da58073d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;com.abertis.mm.zgrdesdepo::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PEDIDOSCOMPRA--listReportFilter-btnBasicSearch-I&quot;)</value>
      <webElementGuid>42f1bf26-32a9-4264-901a-aee5ad1511a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='com.abertis.mm.zgrdesdepo::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PEDIDOSCOMPRA--listReportFilter-btnBasicSearch-I']</value>
      <webElementGuid>e75bc9a8-f505-475e-a658-dc2a5d987504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='com.abertis.mm.zgrdesdepo::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PEDIDOSCOMPRA--listReportFilter-btnBasicSearch-F']/input</value>
      <webElementGuid>8ea1cbe6-3c32-461e-b3a7-dc15656d9264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3cf5b3eb-29f9-4aab-9d0d-a89e596ad697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'com.abertis.mm.zgrdesdepo::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PEDIDOSCOMPRA--listReportFilter-btnBasicSearch-I' and @placeholder = 'Buscar']</value>
      <webElementGuid>0740a2d5-490a-4a2a-b707-9b5b3ad8f54e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
