<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Grupo</name>
   <tag></tag>
   <elementGuidId>cb401506-9797-4067-afba-bf077567fa73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/div/div/div/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>97db253e-e5c3-4a85-a4c6-3bbd225c5e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>com.abertis.mm.zgrdesdepo::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PEDIDOSCOMPRA--template::IconTabFilter-PedidosGrupo-icon</value>
      <webElementGuid>5fde449c-adb8-4eb6-80f6-cc9ee9da964e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>com.abertis.mm.zgrdesdepo::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PEDIDOSCOMPRA--template::IconTabFilter-PedidosGrupo-icon</value>
      <webElementGuid>1bbade57-9452-4712-9cb2-d079825c241b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>deb6adc7-3c84-4324-a692-b34978e769d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>938e7319-1078-41d8-9e97-38256bf33da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>39f443bd-31a4-4144-891e-3449b2d67cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapMITBFilterIcon sapMITBFilterDefault</value>
      <webElementGuid>910c1e1c-6599-46fd-a543-690ff4db82d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;com.abertis.mm.zgrdesdepo::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PEDIDOSCOMPRA--template::IconTabFilter-PedidosGrupo-icon&quot;)</value>
      <webElementGuid>3bb76a61-e805-48d0-a344-13ae2e90f12c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='com.abertis.mm.zgrdesdepo::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PEDIDOSCOMPRA--template::IconTabFilter-PedidosGrupo-icon']</value>
      <webElementGuid>4e167a35-b52e-4148-abc1-e4985d1d457c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='com.abertis.mm.zgrdesdepo::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PEDIDOSCOMPRA--template::IconTabFilter-PedidosGrupo-tab']/span</value>
      <webElementGuid>95b021b3-d3c3-40fe-9afa-466828e91794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/span</value>
      <webElementGuid>07b32b36-24d7-4c05-9905-671a2fe4c4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'com.abertis.mm.zgrdesdepo::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PEDIDOSCOMPRA--template::IconTabFilter-PedidosGrupo-icon']</value>
      <webElementGuid>ef96c9af-0ebc-4e36-8c51-cf8a7600e025</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
