<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Plus_application-PurchaseContract-cr_6ea6a7</name>
   <tag></tag>
   <elementGuidId>59c0a1e4-dad7-4ff3-b6cf-87deb5c0d178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-PurchaseContract-create-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='application-PurchaseContract-create-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f2ff5034-5333-46ef-b982-46452d266cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-PurchaseContract-create-iframe</value>
      <webElementGuid>416a3537-97c4-42e4-806f-899414a19242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-PurchaseContract-create-iframe</value>
      <webElementGuid>21c70f82-a3c8-4b54-8ca8-0322bc3d9bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application-PurchaseContract-create-iframe</value>
      <webElementGuid>9f72d9f1-b081-4eac-b34c-e4c157561202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-orig-src</name>
      <type>Main</type>
      <value>/sap/bc/gui/sap/its/webgui;~sysid=R3Q;~service=3200?~transaction=ME31K&amp;sap-client=100&amp;sap-language=FR&amp;~nosplash=1&amp;sap-iframe-hint=GUI&amp;sap-ie=edge&amp;sap-theme=abertis_theme_corp%40https%3A%2F%2Fsaps4-pre.abertis.com%2Fsap%2Fpublic%2Fbc%2Fthemes%2F~client-100%2F~cache-EffUt0nnNFsxi7WxmjEKOoghmzc&amp;sap-touch=0&amp;sap-target-navmode=inplace&amp;sap-keepclientsession=2&amp;sap-ushell-timeout=25&amp;sap-shell=FLP1.120.28</value>
      <webElementGuid>d5ac4727-9b18-4277-bd57-40ac37bef794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Application</value>
      <webElementGuid>086af764-6abb-481d-90bc-28a18b6e4adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-iframe-idx</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8c47a118-dd02-4d76-b8e2-63c1c923c9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay ;battery ;camera ;display-capture ;geolocation ;gyroscope ;magnetometer ;microphone ;midi ;clipboard-write ;clipboard-read ;fullscreen ;serial ;</value>
      <webElementGuid>2ef56c8a-e529-4a16-99c4-68a5594c0347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUShellApplicationContainer</value>
      <webElementGuid>8a511b5f-c234-4c64-9b23-f7aa8b446946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-PurchaseContract-create-iframe&quot;)</value>
      <webElementGuid>02d0a487-291b-411f-8c7e-9dcaad4eeff7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='application-PurchaseContract-create-iframe']</value>
      <webElementGuid>d4e354c0-a884-4ab8-8521-ea6fb4af0740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-PurchaseContract-create']/iframe</value>
      <webElementGuid>86b5e137-eed5-471c-960f-9e7adf1e58a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>b7deb882-ae00-4d60-ab5e-28b4586cdecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'application-PurchaseContract-create-iframe' and @name = 'application-PurchaseContract-create-iframe' and @title = 'Application']</value>
      <webElementGuid>aba90842-17a5-4d46-9037-8267aaee8829</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
