<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CA - CatalDE - DeutschEN - EnglishES_e3f430</name>
   <tag></tag>
   <elementGuidId>c868879a-d920-4c43-9038-50e8c4435d67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='LANGUAGE_SELECT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LANGUAGE_SELECT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4e356067-750b-4c1a-b3af-d30cd78e965c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LANGUAGE_SELECT</value>
      <webElementGuid>a552ad00-e787-4bd2-b3b6-17a75a8d5cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>513b286d-e383-435e-8968-3cb7abd875b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginSelect</value>
      <webElementGuid>02af51c6-937a-4f41-9938-e8beeadc9170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Language</value>
      <webElementGuid>d7b52dd4-a546-4cf1-bfa5-5a2a840e7e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>LANGUAGE_LABEL</value>
      <webElementGuid>d198ebf7-71fc-4f7d-92c5-c8c78aa77091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA - CatalàDE - DeutschEN - EnglishES - EspañolFR - FrançaisHR - HrvatskiIT - ItalianoPT - PortuguêsSV - Svenska</value>
      <webElementGuid>5c80ad3c-3a6f-4512-94ea-bf8d140592a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LANGUAGE_SELECT&quot;)</value>
      <webElementGuid>b1555d5f-0647-4b37-9c35-20896aa8e248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='LANGUAGE_SELECT']</value>
      <webElementGuid>0dce6722-d056-4318-b608-47cff3f256c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LANGUAGE_SELECT_BLOCK']/select</value>
      <webElementGuid>eac8efb3-6b18-4d14-8ec8-43a644aba4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/following::select[1]</value>
      <webElementGuid>49ba5a70-f8c4-417c-86a8-f679875cb42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::select[1]</value>
      <webElementGuid>5d7dda92-f9b2-4e12-ab6b-3a2864c6d9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log On'])[1]/preceding::select[1]</value>
      <webElementGuid>f6d0e8d6-706d-4a3f-8176-f5adc89d0665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/preceding::select[1]</value>
      <webElementGuid>0f92dd27-16a9-436e-b2e0-8cc988e81801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a07dd944-213d-49b5-ace6-19b025b27eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'LANGUAGE_SELECT' and @title = 'Language' and (text() = 'CA - CatalàDE - DeutschEN - EnglishES - EspañolFR - FrançaisHR - HrvatskiIT - ItalianoPT - PortuguêsSV - Svenska' or . = 'CA - CatalàDE - DeutschEN - EnglishES - EspañolFR - FrançaisHR - HrvatskiIT - ItalianoPT - PortuguêsSV - Svenska')]</value>
      <webElementGuid>31505923-47ae-4ab7-a315-18ac9a7b09ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
