<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Centro de coste_application-zpurchase_908edc</name>
   <tag></tag>
   <elementGuidId>14c749c1-0b6f-4934-85eb-36a6a800b8ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createTP-component---detail--idPShortText-__clone230-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='application-zpurchaserequisition-createTP-component---detail--idPShortText-__clone230-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1ccaecf-3020-400f-9bb1-5e17c2ca5203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createTP-component---detail--idPShortText-__clone230-inner</value>
      <webElementGuid>3ebb3d1f-4912-46a8-81af-5826145e5a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>8e8618d2-0482-49fd-afa3-3b41b22a0bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>992a1978-604b-4149-98b3-c201093f7d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f92ed1d1-4330-45f4-952d-c20e767b4f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>5482f60e-505e-4e3a-baad-1e7c9c32fcc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createTP-component---detail--idPShortText-__clone230-inner&quot;)</value>
      <webElementGuid>a4cbacea-a02c-47f4-a570-3cbd42ed948a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-zpurchaserequisition-createTP-component---detail--idPShortText-__clone230-inner']</value>
      <webElementGuid>bc87d426-6dea-4746-8dd5-8ce077672e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaserequisition-createTP-component---detail--idPShortText-__clone230-content']/input</value>
      <webElementGuid>1004922b-8aeb-4abf-a0b4-d54d9c8469ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/div/input</value>
      <webElementGuid>7be2be7d-4633-498f-887f-6c1b36cf456a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-zpurchaserequisition-createTP-component---detail--idPShortText-__clone230-inner' and @type = 'text']</value>
      <webElementGuid>822db409-1f94-4187-aa66-1296e404e2f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
