<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Verificar</name>
   <tag></tag>
   <elementGuidId>cddcf97b-410a-4309-8bfc-04f399c26e34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createTP-component---detail--checkButton-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-zpurchaserequisition-createTP-component---detail--checkButton-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c682bfcb-8d8d-4377-9ebc-ad992ee5fa43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createTP-component---detail--checkButton-inner</value>
      <webElementGuid>76ca0011-4876-4090-99ef-2d000ed5d396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnInner sapMBtnHoverable sapMFocusable sapMBtnText sapMBtnIconFirst sapMBtnDefault</value>
      <webElementGuid>f9417d0a-0d63-4d68-9414-078c1c127a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verificar</value>
      <webElementGuid>00d063b2-6ea2-437e-8112-d259eddfb225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createTP-component---detail--checkButton-inner&quot;)</value>
      <webElementGuid>f7fed395-7d4b-43d0-a174-80b30c3155e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-zpurchaserequisition-createTP-component---detail--checkButton-inner']</value>
      <webElementGuid>81fdb8c3-1dac-4f9a-8782-3a628a303cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='application-zpurchaserequisition-createTP-component---detail--checkButton']/span</value>
      <webElementGuid>4c287668-11f5-4026-8b54-768f67c62f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitud Licitación (ASPI)'])[2]/following::span[2]</value>
      <webElementGuid>0905fa55-0b12-4408-8c60-585522fc88bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitud Licitación (ASPI)'])[1]/following::span[3]</value>
      <webElementGuid>c4ade55b-3b1b-4a70-9bf3-8ae9ad9298da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Más Datos'])[1]/preceding::span[4]</value>
      <webElementGuid>67fc246d-d484-45f9-be6b-9f372055d5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button/span</value>
      <webElementGuid>9e52ad9c-ec73-4d93-bb40-2a137877c8e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-zpurchaserequisition-createTP-component---detail--checkButton-inner' and (text() = 'Verificar' or . = 'Verificar')]</value>
      <webElementGuid>56f84397-5f1a-4f23-be70-aa7122c52b54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
