<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Centro de coste_application-zpurchaser_2eb417</name>
   <tag></tag>
   <elementGuidId>fc0a7774-1f13-4108-951f-e7061107b4ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createTP-component---detail--idPMaterial-__clone230-vhi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'application-zpurchaserequisition-createMP-component---detail--idPPlant-')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>313dae74-4aa9-4873-8b4d-2e7e3bc20525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createTP-component---detail--idPMaterial-__clone230-vhi</value>
      <webElementGuid>085d91bb-a317-4c4a-830d-08f875d3ac7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createTP-component---detail--idPMaterial-__clone230-vhi</value>
      <webElementGuid>55c87313-4910-4e9c-8bf7-748af6c18dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee43925f-0218-405d-9de8-baedd0eef3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Mostrar ayuda para entradas</value>
      <webElementGuid>1be46ae3-229c-42bb-a0ca-e33b5ae1aef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>aabd129f-e9eb-428c-84ab-95ebd2c73547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapUiIconPointer sapMInputBaseIcon</value>
      <webElementGuid>d84013ab-4ecd-4944-aa54-7dcacb8355a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createTP-component---detail--idPMaterial-__clone230-vhi&quot;)</value>
      <webElementGuid>4fe8ffb0-2d2b-42ed-99fc-370b156d5063</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-zpurchaserequisition-createTP-component---detail--idPMaterial-__clone230-vhi']</value>
      <webElementGuid>64ea6a23-1220-4d34-ad39-0bc61e0985e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaserequisition-createTP-component---detail--idPMaterial-__clone230-content']/div/span</value>
      <webElementGuid>abe4653a-e87b-4019-a146-d1415e4d8187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/div/div/span</value>
      <webElementGuid>ae3b2eeb-6827-4bbf-816e-bfd8adb61867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-zpurchaserequisition-createTP-component---detail--idPMaterial-__clone230-vhi']</value>
      <webElementGuid>646b7759-2780-4f30-9282-d8a771ae6873</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
