<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Proveedores Invitados_application-_7a5879</name>
   <tag></tag>
   <elementGuidId>fa693608-43cd-40e8-af8c-3fbe3bcf6ff6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createTP-component---detail--idHB07-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='application-zpurchaserequisition-createTP-component---detail--idHB07-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>45372c49-8867-42fc-893b-f51a5442c39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createTP-component---detail--idHB07-inner</value>
      <webElementGuid>6c089777-4db3-48c3-8c5d-276e7239536b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1a56f835-af2b-4119-a735-8dbb7cf2eeca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b70bf68f-0f60-4ecd-bca4-55a22347457e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner sapMTextAreaInner</value>
      <webElementGuid>ed90b549-e7c3-4956-9c98-62640b6b721b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f8d66dc5-a10d-40cc-b346-e59cc5e187b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createTP-component---detail--idHB07DetailE-label</value>
      <webElementGuid>ec9644e3-c2fe-4ece-9f8f-0d90f5de9396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createTP-component---detail--idHB07-inner&quot;)</value>
      <webElementGuid>eba767b8-95aa-4d76-b77f-b10d5ad72ce1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='application-zpurchaserequisition-createTP-component---detail--idHB07-inner']</value>
      <webElementGuid>3a499910-1ba3-4287-942c-2e0c9d90739a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaserequisition-createTP-component---detail--idHB07-content']/textarea</value>
      <webElementGuid>3b6f48f9-4380-4878-b868-1b77e9e3436b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proveedores Invitados'])[1]/following::textarea[1]</value>
      <webElementGuid>06f885d6-e929-4bc5-9186-0f460a919f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Objeto Compra/Contratación'])[1]/following::textarea[2]</value>
      <webElementGuid>026c37f7-5772-4b94-a2fd-2643e4eba559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mostrar más'])[1]/preceding::textarea[1]</value>
      <webElementGuid>681dc1b0-f46e-4a77-ad12-51b148b4b5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posiciones'])[4]/preceding::textarea[1]</value>
      <webElementGuid>1e1745eb-9ce2-4659-b5ff-4a64f04667b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/textarea</value>
      <webElementGuid>235ec8b4-82b4-4b3f-a044-1f43fea0d377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'application-zpurchaserequisition-createTP-component---detail--idHB07-inner']</value>
      <webElementGuid>0407dec8-a7a8-4bf9-9f00-2971d2c7c66c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
