<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_sap-password</name>
   <tag></tag>
   <elementGuidId>757ce922-25f4-414c-ba9c-2a08da7a9204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PASSWORD_FIELD-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PASSWORD_FIELD-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98b0eb37-2273-447b-b4a7-417917bc641e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PASSWORD_FIELD-inner</value>
      <webElementGuid>85830a6b-deca-4810-94da-14882df960d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fb201c7e-8597-4232-9b3c-d1027661694c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b08c5110-1cd0-435a-8852-4504b311e4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginInputField</value>
      <webElementGuid>63cf71ae-e4b6-4065-9a98-41af2b65a99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sap-password</value>
      <webElementGuid>e756dfc4-ecec-44ab-88c2-36199341c115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>verbatim</value>
      <webElementGuid>3e25295f-b6d5-440d-a7eb-6c3abb0f3355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>079cbc68-d7d4-46c4-9dcc-28835e8c8612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>f3017893-29d4-4563-a908-7055bf16a1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>55a44ae9-aaaf-4fec-972d-d6ae05f5cf4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3686c912-cdf5-43dc-a986-e64b3dfa8a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>PASSWORD_LABEL</value>
      <webElementGuid>4ebe6f56-6124-4f10-b8ea-7ed304310050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PASSWORD_FIELD-inner&quot;)</value>
      <webElementGuid>510637af-bddc-4025-ad45-a79024ea62bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PASSWORD_FIELD-inner']</value>
      <webElementGuid>2b356224-7cc8-4f9a-bae7-d6578ecffe83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PASSWORD_BLOCK']/input</value>
      <webElementGuid>d18afb94-b859-464a-b798-1371aa2985a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>581e73a0-8330-46c5-afa2-46f4c61f1e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PASSWORD_FIELD-inner' and @type = 'password' and @name = 'sap-password' and @placeholder = 'Password' and @title = 'Password']</value>
      <webElementGuid>55e6e1d2-99a5-4a66-b614-145deec191fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
