<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ContabilizarResaltado</name>
   <tag></tag>
   <elementGuidId>9c1a0583-f61f-416d-90cc-c6ef80cf8573</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:50::btn[11]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>47136d8b-8165-4ae2-a595-d699bc785368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f224b5b8-36e3-430a-a214-28df3281cb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:50::btn[11]</value>
      <webElementGuid>96c85148-cba9-4768-b4f2-89ea60ad8868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>B</value>
      <webElementGuid>8a1977ba-0a24-44e2-aabc-129099135ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;Contabilizar&quot;,&quot;2&quot;:&quot;EMPHASIZED&quot;,&quot;4&quot;:&quot;Contabilizar (Ctrl+S)&quot;,&quot;17&quot;:&quot;C&quot;,&quot;18&quot;:&quot;CTRL_S&quot;,&quot;21&quot;:true,&quot;25&quot;:&quot;TOGGLE&quot;,&quot;27&quot;:{&quot;SID&quot;:&quot;wnd[0]/tbar[0]/btn[11]&quot;,&quot;Type&quot;:&quot;GuiButton&quot;,&quot;SubType&quot;:&quot;toolbar&quot;}}</value>
      <webElementGuid>1cae7c68-747c-4eb6-b2ab-02cff6b09bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Press&quot;:[{},{&quot;1&quot;:&quot;action/3&quot;,&quot;2&quot;:true,&quot;3&quot;:true}]}</value>
      <webElementGuid>8d887f0d-dde0-4e4e-af57-5269b5938a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>65db3581-b7dc-42f3-b53b-b5198129569f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Contabilizar (Ctrl+S)</value>
      <webElementGuid>e980564c-6366-42b2-81b9-8b74e4773177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>C</value>
      <webElementGuid>bdfa4b9d-d4df-4f3d-8792-f6511f361fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>C</value>
      <webElementGuid>c36592c6-6848-4807-baa6-9c3749093153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>53322371-da49-46d0-9952-411b11099704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d7a20866-b140-4633-b783-81a86ae32ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsButton lsButton--base urNoUserSelect urBtnRadius lsButton--useintoolbar lsButton--active lsButton--focusable lsButton--up lsButton--design-emphasized lsButton--hoverable</value>
      <webElementGuid>d8e99365-529d-427b-8f9d-92fd50bdca18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toolbaritem-id</name>
      <type>Main</type>
      <value>M0:50::btn[11]-r</value>
      <webElementGuid>55b25fd5-5ceb-4d99-b59f-4a89e138980c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ls-firstitem</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>72d1ae29-2d75-4c58-abb3-fc1bfb310760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contabilizar Resaltado</value>
      <webElementGuid>982d4a27-459c-4f84-a567-181c57ac8f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:50::btn[11]&quot;)</value>
      <webElementGuid>91940c7d-0815-462a-8546-8164f4b4c00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Eliminar diferencias Invent/Page_Eliminar diferencias 100009770 Imagen _ff9671/iframe_Ms_application-PhysicalInventoryDocu_1d60b6</value>
      <webElementGuid>eb6d11ae-e15e-455c-bf03-1a9620821b35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M0:50::btn[11]']</value>
      <webElementGuid>0b798072-03f0-41b9-8dac-b433387ad739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='M0:50::btn[11]-r']/div</value>
      <webElementGuid>fa542e80-5bad-455e-8f3d-5ac72019a104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='d'])[1]/following::div[8]</value>
      <webElementGuid>dccc6be7-1d62-4a0e-8dfc-15b298a5d079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/span[2]/div</value>
      <webElementGuid>51140450-2a36-4f45-8ff6-f9c4be1e1df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M0:50::btn[11]' and @title = 'Contabilizar (Ctrl+S)' and (text() = 'Contabilizar Resaltado' or . = 'Contabilizar Resaltado')]</value>
      <webElementGuid>909b1b23-6fb3-42b8-afc4-2a9140bd75d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
