<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Marcando este campo se puede desglosa_bfb6e3</name>
   <tag></tag>
   <elementGuidId>8e3f7994-f19d-4519-9209-ed9e5a100e08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'application-zpurchaserequisition-createMP-component---detail--idPQuantity-')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createMP-component---detail--idPQuantity-__clone141-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c71273fb-6b49-4f01-ba0d-51c767b0da5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createMP-component---detail--idPQuantity-__clone141-inner</value>
      <webElementGuid>8f799798-ba8a-4d30-84ff-825fa979aaeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce046141-aa4c-4ddb-ae86-3c35ee4d214e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0a0d31b5-a920-4c5f-8ee5-33803a310a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>e1d133ea-094a-4ecf-8fef-41b36dc4e434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createMP-component---detail--idPQuantity-__clone141-inner&quot;)</value>
      <webElementGuid>9edb47b5-1b86-42a1-b221-fba50ddd0286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-zpurchaserequisition-createMP-component---detail--idPQuantity-__clone141-inner']</value>
      <webElementGuid>69d8627e-4f82-4b82-b968-4d61dfc65aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaserequisition-createMP-component---detail--idPQuantity-__clone141-content']/input</value>
      <webElementGuid>f02454c0-80bf-44c1-b4af-4cfbb6d70a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div/div/input</value>
      <webElementGuid>eb177ddb-29c2-447a-8738-75edf6c9e819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-zpurchaserequisition-createMP-component---detail--idPQuantity-__clone141-inner' and @type = 'text']</value>
      <webElementGuid>e8de387c-5033-4052-96f5-340369679fe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
