<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Savare</name>
   <tag></tag>
   <elementGuidId>75b96881-9026-4d09-8a11-07bc0b6f0723</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaseorder-createPOfromContract-component---detail--saveButton-BDI-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='application-zpurchaseorder-createPOfromContract-component---detail--saveButton-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>6baf76b3-6022-4b13-a7b7-c99876f22182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaseorder-createPOfromContract-component---detail--saveButton-BDI-content</value>
      <webElementGuid>16960801-0812-4ecd-8933-6452da39b222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>b43e08e5-036d-46c0-aa74-aec7e8c0d161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Savare</value>
      <webElementGuid>3a449eff-a946-4633-a6d6-a54f7b1ad1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaseorder-createPOfromContract-component---detail--saveButton-BDI-content&quot;)</value>
      <webElementGuid>b4691209-9bd0-45fc-8527-fe52fa86f06d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='application-zpurchaseorder-createPOfromContract-component---detail--saveButton-BDI-content']</value>
      <webElementGuid>5cc2f81e-a930-4e11-b879-900a45bf6dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-zpurchaseorder-createPOfromContract-component---detail--saveButton-content']/bdi</value>
      <webElementGuid>bf99ddbe-eecf-4b14-a94d-03d5dcf240ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrazione preliminare'])[1]/following::bdi[1]</value>
      <webElementGuid>4447b8c1-f3e3-430f-a408-a453a57d0baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mostra di più'])[2]/following::bdi[3]</value>
      <webElementGuid>79f6f72b-a1c1-4bab-899b-61f5acebe5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancellare'])[2]/preceding::bdi[1]</value>
      <webElementGuid>639e0a41-86f7-4403-8531-378dcd8e4ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Savare']/parent::*</value>
      <webElementGuid>01144459-f8a7-4802-9046-25743f5d066e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/button[3]/span/span/bdi</value>
      <webElementGuid>d6d470ee-67c6-4444-8eba-fc157fb846d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'application-zpurchaseorder-createPOfromContract-component---detail--saveButton-BDI-content' and (text() = 'Savare' or . = 'Savare')]</value>
      <webElementGuid>16dfd41c-88eb-465c-9447-bcab1c3fcd50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
