<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Notificacin final_sapMSwtLabel sapMSwt_f93253</name>
   <tag></tag>
   <elementGuidId>cd7c5593-6aeb-46f0-a11b-fbe0cc34406e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='iFinal-textoff']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sapMSwtLabel.sapMSwtLabelOff</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>23e79976-6174-4ece-9b38-612a86aea7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSwtLabel sapMSwtLabelOff</value>
      <webElementGuid>613a9fa7-9e6f-401b-9b2e-76da09e9c868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iFinal-textoff&quot;)/span[@class=&quot;sapMSwtLabel sapMSwtLabelOff&quot;]</value>
      <webElementGuid>14400685-08d1-4d8a-8f8e-1dd2a0589f9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iFinal-textoff']/span</value>
      <webElementGuid>11596276-2f8c-474c-8338-b880ba0e23b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div/div[2]/span</value>
      <webElementGuid>49f2228d-b942-49d0-80e0-6ac2a985471b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
