<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_200100050798</name>
   <tag></tag>
   <elementGuidId>df111cce-bfb5-4d60-bc55-57935e0c9a32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[contains(@id, 'application-ZPM_SMART-GESTICKET-component---main--idCLItemPress')]/span[text()='${orderId}']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__text132-__clone96</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>02e7d397-997a-4f44-9034-ffe1e73b34f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text132-__clone96</value>
      <webElementGuid>5d998c5a-fd00-486d-8852-ee01f3744fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text132-__clone96</value>
      <webElementGuid>16c257f4-cbcd-4488-8a49-5bdf1d42c63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>cafc2b9d-4d7d-46fc-b7a5-ef7a98647cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextBreakWord sapMTextMaxWidth</value>
      <webElementGuid>4ef2f376-03dc-459a-b5bd-2e66523819cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>200100050798</value>
      <webElementGuid>63355783-474d-4374-bad1-53872b7d73a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text132-__clone96&quot;)</value>
      <webElementGuid>4d68c9b0-be33-4638-b55f-3e4a99df14af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__text132-__clone96']</value>
      <webElementGuid>c3bfb6f6-9441-47be-a360-60ac91f04524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='application-ZPM_SMART-GESTICKET-component---main--idCLItemPress-__clone96-cell0']/span</value>
      <webElementGuid>01761da8-a411-4974-95a2-531a34ea1ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pto. Trabajo Ejec.'])[2]/following::span[1]</value>
      <webElementGuid>0f87412a-b620-4461-b6bd-b0d023610ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desc. Emplazamiento'])[1]/following::span[2]</value>
      <webElementGuid>599ce65e-c88a-4a69-b14c-a184b81ac5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIB. DMNV KKMP'])[1]/preceding::span[1]</value>
      <webElementGuid>a3050dc4-43ff-437c-8ca8-6e24efd276f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test'])[1]/preceding::span[2]</value>
      <webElementGuid>773d0be9-2ee9-4092-b038-7bc944224b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='200100050798']/parent::*</value>
      <webElementGuid>4eb0d12c-1079-4d88-a923-ba3747fcae96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/span</value>
      <webElementGuid>e0f864bc-4783-45c6-94c4-a8111af66b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__text132-__clone96' and (text() = '200100050798' or . = '200100050798')]</value>
      <webElementGuid>9d583e9c-2363-45b1-8bf5-a9cc3d95db5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
