<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Advertencia emitida_application-ZPM_SM_94591d</name>
   <tag></tag>
   <elementGuidId>1eb02740-4bf6-4c7b-8cdb-2785ca79acd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-ZPM_SMART-GESTICKET-component---Detalle--idCrearNotifBtn-application-ZPM_SMART-GESTICKET-component---Detalle--idProductsTable-0-img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTICKET-component---Detalle--idCrearNotifBtn-application-ZPM_SMART-GESTICKET-component---Detalle--idProductsTable-0-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8dd80f4b-890d-4152-ad0e-0debe10ca8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTICKET-component---Detalle--idCrearNotifBtn-application-ZPM_SMART-GESTICKET-component---Detalle--idProductsTable-0-img</value>
      <webElementGuid>46c9376d-f84c-4f36-b216-b77ae382596f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTICKET-component---Detalle--idCrearNotifBtn-application-ZPM_SMART-GESTICKET-component---Detalle--idProductsTable-0-img</value>
      <webElementGuid>380d5e03-e76f-49cd-9224-9dda359ca788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>a98a4103-26c5-4358-9101-96b448eba0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c1fe8649-4a1b-4fd2-ba65-64c8e4e6be50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2cb219e7-0ff2-47ef-9726-6ebb50912f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapMBtnCustomIcon sapMBtnIcon sapMBtnIconLeft</value>
      <webElementGuid>f58d920e-a517-4576-b210-ee4dc8ce8075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTICKET-component---Detalle--idCrearNotifBtn-application-ZPM_SMART-GESTICKET-component---Detalle--idProductsTable-0-img&quot;)</value>
      <webElementGuid>46c8b2e5-c3fe-4a4a-8c89-f32efe03fc21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-GESTICKET-component---Detalle--idCrearNotifBtn-application-ZPM_SMART-GESTICKET-component---Detalle--idProductsTable-0-img']</value>
      <webElementGuid>d9973b95-4f0c-471c-88e6-9a64bb6fb530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-GESTICKET-component---Detalle--idCrearNotifBtn-application-ZPM_SMART-GESTICKET-component---Detalle--idProductsTable-0-inner']/span</value>
      <webElementGuid>513171da-07a0-42f5-8a93-0accf5ce402a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/button/span/span</value>
      <webElementGuid>28ba11a1-27ab-453f-b0c2-58d610594716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-ZPM_SMART-GESTICKET-component---Detalle--idCrearNotifBtn-application-ZPM_SMART-GESTICKET-component---Detalle--idProductsTable-0-img']</value>
      <webElementGuid>bde65281-8034-4442-bc1a-bedec4882a04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
