<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_La organizacin-compras1113noest asignad_a29f11</name>
   <tag></tag>
   <elementGuidId>347fdcb6-a214-4c4b-8199-bc64a80ffc7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M1:46']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d7cba1d2-4d31-4414-9a47-5e34519d7269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M1:46</value>
      <webElementGuid>73f7291f-010a-49a4-9c24-ab6ea85be82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>RL</value>
      <webElementGuid>674e6413-0445-4e14-9d5b-ae3d31252341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:4.00,&quot;2&quot;:1.25,&quot;4&quot;:{&quot;SID&quot;:&quot;wnd[1]/usr&quot;,&quot;Type&quot;:&quot;GuiUserArea&quot;}}</value>
      <webElementGuid>64ccb25f-9e47-41c0-a9fd-6735c6477e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Scroll&quot;:[{},{&quot;posX&quot;:0,&quot;posY&quot;:0}]}</value>
      <webElementGuid>8d8c5adf-8717-42c6-8db6-99d4359a8a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bnoposrefcontainer</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>b3fde59d-01be-4615-b250-fcc4829df407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>2d70914d-4271-4bb4-a4c5-86753d5c2838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsRasterLayout  lsRL--relative lsRasterLayout--lrpad lsResponsivePadding</value>
      <webElementGuid>a7a0b7ee-e692-4fb2-b619-a9301780c678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-style</name>
      <type>Main</type>
      <value>;height:100%;width:100%</value>
      <webElementGuid>e830adc2-2991-464d-b399-afb10d733078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>La organización-compras1113noestá asignada a ninguna sociedadIndique una sociedadSociedad</value>
      <webElementGuid>7036644f-9c35-4967-ac92-63eb1b52c8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M1:46&quot;)</value>
      <webElementGuid>a7e732c8-42a4-4710-ad52-65ec4dc0cef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Contratos Autopistas/Page_Crear Pedido abierto  Acceso/iframe_Ms_application-PurchaseContract-crea_3eec77</value>
      <webElementGuid>1edb371d-ea01-4ec1-a342-19daa6dbc975</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M1:46']</value>
      <webElementGuid>c99a37cf-916b-44a5-9bf8-aa3a2d78efd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='SAPMM06E514_1-contentsection']/div[2]</value>
      <webElementGuid>d75aef85-7a7e-40b5-a231-6b24980d6b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrada sociedad'])[1]/following::div[3]</value>
      <webElementGuid>7621db23-f05b-4492-835f-a83027ed1aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]</value>
      <webElementGuid>b7a36731-4aa5-45a5-bce2-12673fbede64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M1:46' and (text() = 'La organización-compras1113noestá asignada a ninguna sociedadIndique una sociedadSociedad' or . = 'La organización-compras1113noestá asignada a ninguna sociedadIndique una sociedadSociedad')]</value>
      <webElementGuid>827e24d6-af12-41b8-8bcb-2bd44713b858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
