<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Doc.5500000004 se contabiliz en sociedad 1375</name>
   <tag></tag>
   <elementGuidId>eb033856-b460-4ddc-b55d-0cafaef41dc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:1[3,2]_c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f3a3f88e-c53e-433c-b2d6-2ff6cbd31b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>1d9184d1-7cbd-4b81-bd64-1a1f8e4afac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2fd98c3f-d56e-40b1-9c96-d8fcea7dc16d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>415ef230-6c7c-4bba-a30b-ddf2126b8f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>089d19ea-09af-42d0-b47c-b603d53b534b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1[3,2]_c</value>
      <webElementGuid>f059641a-f0f9-4e80-84dd-856f48b8e9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>CBS</value>
      <webElementGuid>24b75946-2d69-4e91-a97c-cb65144e5c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;x&quot;:0,&quot;1&quot;:&quot;FREETEXT&quot;,&quot;5&quot;:&quot;Doc.5500000004 se contabilizó en sociedad 1375&quot;,&quot;7&quot;:true,&quot;14&quot;:&quot;SERVER&quot;,&quot;17&quot;:false,&quot;20&quot;:false,&quot;21&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/tblRSBDC_PROTOCOLTC_PROT_DIS/txtBDC_PROTOCOL_DB-LONGTEXT[1,2]&quot;,&quot;Type&quot;:&quot;GuiTextField&quot;,&quot;value&quot;:&quot;Doc.5500000004 se contabilizó en sociedad 1375&quot;,&quot;maxlen&quot;:132,&quot;focusable&quot;:&quot;X&quot;},&quot;25&quot;:&quot;FILL_FIXED_LAYOUT&quot;}</value>
      <webElementGuid>96db731f-8d6a-46c2-9f51-8623941d9363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Select&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Validate&quot;:[{},{}],&quot;ListAccess&quot;:[{},{}]}</value>
      <webElementGuid>ac25ae19-f620-41a1-8054-dffe96b5e5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InputField</value>
      <webElementGuid>bb350044-2a2b-45f3-b508-40063e045619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>132</value>
      <webElementGuid>e1832bd3-307e-411c-8334-dd4665108bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField__input</value>
      <webElementGuid>c8fd2e24-4dc0-4930-8ded-aaeca6e9b0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Doc.5500000004 se contabilizó en sociedad 1375</value>
      <webElementGuid>81f04cee-4d91-437d-bae7-454cf64f6d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1[3,2]_c&quot;)</value>
      <webElementGuid>e7f45ed0-3f8d-460f-bd21-9405750f0e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Supervision Batch Input/Page_Log BI para nombre juego datos BI_PWGLI04/iframe_Ms_application-zgui_sm35-processBatc_86a647</value>
      <webElementGuid>0835f6e2-b44b-477b-adad-e6802aa40bb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1[3,2]_c']</value>
      <webElementGuid>38ee94f8-876f-409a-928f-13ec6e759081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1[3,2]_c-r']/span</value>
      <webElementGuid>32b81014-5238-4252-a85d-384873113ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[3]/following::span[8]</value>
      <webElementGuid>154620b9-8d34-453b-af1c-294dbec45f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAPMF05A'])[1]/following::span[14]</value>
      <webElementGuid>ed31f1de-2f3b-4a8c-9d96-7c76f5e9a798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FB01'])[2]/preceding::span[1]</value>
      <webElementGuid>28921a5e-3223-4696-af56-2b55adba3211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[4]/preceding::span[11]</value>
      <webElementGuid>580aa9cc-9adc-46f1-8b3d-ff2d6dfbc45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Doc.5500000004 se contabilizó en sociedad 1375']/parent::*</value>
      <webElementGuid>6238addf-cf6f-4c95-ac9e-8966d4488c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/span/span</value>
      <webElementGuid>4a2f1295-322c-475b-8d32-d4eb4d039991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'M0:46:1[3,2]_c' and @name = 'InputField' and (text() = 'Doc.5500000004 se contabilizó en sociedad 1375' or . = 'Doc.5500000004 se contabilizó en sociedad 1375')]</value>
      <webElementGuid>6b825af3-f788-4b56-97de-cf853c661823</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
