<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Confermare</name>
   <tag></tag>
   <elementGuidId>43429a1f-071f-4cd7-9e6c-4ddce03bdc75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='idCreateTimeBtn-BDI-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idCreateTimeBtn-BDI-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>2e7898d0-89b0-43ac-bb50-931ddfb134cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idCreateTimeBtn-BDI-content</value>
      <webElementGuid>2d66863a-39a2-4edd-89e6-2fb8be6db302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>f35959c6-e009-4c40-bd47-aee8a73568de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confermare</value>
      <webElementGuid>f8d7e642-5f49-4ed7-b1e5-066d7d0b4782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idCreateTimeBtn-BDI-content&quot;)</value>
      <webElementGuid>02b2c3b5-b94c-4270-a6c5-2c29422b59ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='idCreateTimeBtn-BDI-content']</value>
      <webElementGuid>549f7bd2-f722-44c6-846d-d1d19d41b8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='idCreateTimeBtn-content']/bdi</value>
      <webElementGuid>d76276fe-a51c-49f6-afb8-4e72b6fb14c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testo esplicativo'])[1]/following::bdi[1]</value>
      <webElementGuid>fa1e2d80-647a-4dc0-8d56-25ccafa3c964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operazione completata'])[1]/following::bdi[2]</value>
      <webElementGuid>d6b41635-9c4f-4f3e-9c43-aa34214496fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annulla'])[1]/preceding::bdi[1]</value>
      <webElementGuid>59e19246-217c-41c1-984e-0186c0b600a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::bdi[2]</value>
      <webElementGuid>ef1793ae-747c-4fe3-b07e-a304ef51c7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confermare']/parent::*</value>
      <webElementGuid>b92e21c4-a4a2-4937-967e-66663a50089d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/footer/div/button/span/span/bdi</value>
      <webElementGuid>a0a96a60-33e7-4cb3-99d9-43cf51c50294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'idCreateTimeBtn-BDI-content' and (text() = 'Confermare' or . = 'Confermare')]</value>
      <webElementGuid>ce469a09-a0a1-4218-a64a-45df92354079</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
