<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ticket_application-ZPM_SMART-GESTICKE_9f2af5</name>
   <tag></tag>
   <elementGuidId>3985b07e-73c1-4a05-84ba-f8228e5e2975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-Orderid-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-Orderid-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c019d18-1fde-477d-a1b1-5f0eebf45e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-Orderid-inner</value>
      <webElementGuid>305dc48d-25c1-437c-900c-12a913e5acd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>ae76d672-572a-4011-86a4-ff2d73b2e5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItem-OrdenesSet-Orderid</value>
      <webElementGuid>4d81e5c7-fe41-47c9-93a4-c307a937002a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text229</value>
      <webElementGuid>7e146ae1-805a-48e6-8c55-beabb7dfb63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>49a49ea4-47ce-4b6c-ae39-4fcc9412a553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-roledescription</name>
      <type>Main</type>
      <value>Inserimento multivalore</value>
      <webElementGuid>6ffc5964-6d06-49bb-9a2d-a9ffc671964c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e672898-942b-41a6-9f85-6a40ced8a314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f9a084f4-5156-4723-b41f-d8c7d1c813fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>7071c88f-662c-4bc7-809a-430068ea2fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-Orderid-inner&quot;)</value>
      <webElementGuid>6c37c760-c938-4720-b99b-cdcd11bb10d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-Orderid-inner']</value>
      <webElementGuid>fe77aaf6-3b04-4eb4-bbe8-543b5a210ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-Orderid-content']/input</value>
      <webElementGuid>e7258104-e153-4cde-9345-c01610e931d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>b0b09509-9297-47a8-8d2c-db5d1aca9d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-Orderid-inner' and @type = 'text']</value>
      <webElementGuid>47ad38cd-966a-4485-963c-e3af885d5f56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
