<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tecnico_sapUiIconTitle</name>
   <tag></tag>
   <elementGuidId>22dc976e-1100-4e55-9c41-5617019dfae5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__token6-icon']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__token6-icon > span.sapUiIconTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8cc7256a-a520-47c5-9327-d27ad60d468b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rimuovi</value>
      <webElementGuid>a2e807e6-b308-4492-9265-190e7de5dc89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>219e9fd0-cb92-44c6-8d75-142b3f6947b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIconTitle</value>
      <webElementGuid>b5d5b29f-3107-4c36-99ef-368585847850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__token6-icon&quot;)/span[@class=&quot;sapUiIconTitle&quot;]</value>
      <webElementGuid>350596e2-009c-4684-afcd-1ab4d14987f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__token6-icon']/span</value>
      <webElementGuid>2ec85eaf-0c50-47d0-8a10-24ca8142e75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>31f5494a-4572-4fa1-80fa-0a3f1f0ae8da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Rimuovi']</value>
      <webElementGuid>d0bafabd-b6a7-4ac3-aba1-4d42d2ddf9da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
