<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ir</name>
   <tag></tag>
   <elementGuidId>9e3f02b8-974a-4086-bd26-98025f27c308</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='com.abertis.mm.zmycontractslr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>df42cd1c-77e8-4748-bd23-32a953cbcb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>com.abertis.mm.zmycontractslr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo-inner</value>
      <webElementGuid>8268188e-beab-45b2-bbcb-f89f42d7a6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnInner sapMBtnHoverable sapMFocusable sapMBtnText sapMBtnEmphasized</value>
      <webElementGuid>4dd028a0-4e23-4b86-998d-9b467fa635ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ir</value>
      <webElementGuid>a85c97c7-83b1-41c2-a598-cabec4e9e9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;com.abertis.mm.zmycontractslr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo-inner&quot;)</value>
      <webElementGuid>17bd4042-7500-4368-915a-da87cacb332f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='com.abertis.mm.zmycontractslr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo-inner']</value>
      <webElementGuid>1873fac5-96f7-49eb-b2c8-2eabd64b071a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='com.abertis.mm.zmycontractslr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo']/span</value>
      <webElementGuid>248b8496-83b9-4ee0-8d69-4f70e68e3c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material'])[1]/following::span[8]</value>
      <webElementGuid>47811fd8-968e-4e76-a7c0-28beb0aa973f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contrato'])[1]/following::span[15]</value>
      <webElementGuid>4203cdee-e75c-440e-aaa2-ad2a8a79b79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adaptar filtros'])[1]/preceding::span[4]</value>
      <webElementGuid>2dfce30a-1b59-4a0c-aad6-549e2e1c95ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/span</value>
      <webElementGuid>9a4ea17e-371f-467e-ae06-fe66feada3e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'com.abertis.mm.zmycontractslr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo-inner' and (text() = 'Ir' or . = 'Ir')]</value>
      <webElementGuid>0d1050a9-6728-4c84-ae57-0fdc250e753a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
