<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_SolicitudRespuesta de Informacin</name>
   <tag></tag>
   <elementGuidId>309a174b-7a3c-4468-9cad-7db1bb897d0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='__button55-BDI-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__button55-BDI-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>9005979f-8415-4f4f-af05-1a48dc759a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__button55-BDI-content</value>
      <webElementGuid>9fe3566e-be71-4213-9f7c-f3aff84812e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>275fb50e-ae43-4451-9c58-3a21c6da3971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solicitud/Respuesta de Información</value>
      <webElementGuid>8c2215f8-b503-4ca8-ab18-33c429b4f574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__button55-BDI-content&quot;)</value>
      <webElementGuid>7098271e-787c-4c92-9e97-d374746c0259</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='__button55-BDI-content']</value>
      <webElementGuid>46b8113b-9fb3-4367-b21c-7ac57fa138c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__button55-content']/bdi</value>
      <webElementGuid>8e4ef415-fb00-4291-8660-4233b186ffbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rechazar'])[1]/following::bdi[1]</value>
      <webElementGuid>91d11230-f64f-4638-a077-4f27d85aebc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aprobar'])[1]/following::bdi[2]</value>
      <webElementGuid>46287927-9414-4a21-9835-52cd3dde188d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Solicitud/Respuesta de Información']/parent::*</value>
      <webElementGuid>30b44981-38ba-4df3-91fb-884029949738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/span/span/bdi</value>
      <webElementGuid>37ca126f-a53e-4e97-8e28-9125d0b23421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = '__button55-BDI-content' and (text() = 'Solicitud/Respuesta de Información' or . = 'Solicitud/Respuesta de Información')]</value>
      <webElementGuid>d46d2f76-a9cf-47bf-9268-cfc250f94e1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
