<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_sap-password</name>
   <tag></tag>
   <elementGuidId>41daaaef-2994-44d2-b544-83a19f249336</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PASSWORD_FIELD-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PASSWORD_FIELD-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e256c39e-a601-4556-87f6-b287805eff99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PASSWORD_FIELD-inner</value>
      <webElementGuid>6f6a1b54-5cb2-43a6-b9c1-cc7a4ab6d363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>25dbea70-7fa4-4e45-8dfb-80ef79f71141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4a446394-fe89-4bbf-b4e9-4da3d99d55b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginInputField</value>
      <webElementGuid>a056b3b8-ca11-4361-ba40-611fe9a09d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sap-password</value>
      <webElementGuid>09f36826-e916-4538-a552-c1dff1f68ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>verbatim</value>
      <webElementGuid>dff499c3-5066-4524-833d-165d40ce6745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>49f1751f-6320-462f-904f-afdec05c6a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>d322e8c5-1a02-4898-b21f-26695d212117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>22469205-67c7-43aa-8031-8b323e513792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e9fff7c4-c47f-40b4-9b05-e9f6560fb2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>PASSWORD_LABEL</value>
      <webElementGuid>0a64520a-5bed-4271-b2ab-a7edbe6677e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PASSWORD_FIELD-inner&quot;)</value>
      <webElementGuid>d8f690de-e0d1-406f-a5b0-8406c1bf2ba1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PASSWORD_FIELD-inner']</value>
      <webElementGuid>e57d6ca2-5cea-4acc-8ab4-b0b96a9af9b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PASSWORD_BLOCK']/input</value>
      <webElementGuid>22ed8ae0-9443-461b-bade-ca3f0454764e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>3c99797d-ca2b-4df8-9986-ba304e8741fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PASSWORD_FIELD-inner' and @type = 'password' and @name = 'sap-password' and @placeholder = 'Password' and @title = 'Password']</value>
      <webElementGuid>648e240c-1ba1-4068-ad72-d99e8d597780</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
