<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Iniciar</name>
   <tag></tag>
   <elementGuidId>91c51669-26c6-4b4e-9db9-3525234cb4ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/button/span[1]/span/bdi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>ca3c26eb-0952-4dac-bfc4-cb8a6b4b5d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>com.abertis.mm.zpurchaserequisitionlr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosPurchaseRequisitionLR--listReportFilter-btnGo-BDI-content</value>
      <webElementGuid>664a9f13-f802-44f0-a95d-147989e41677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Iniciar</value>
      <webElementGuid>0a0c1242-dd2a-45ad-8a84-6322f97e57d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;com.abertis.mm.zpurchaserequisitionlr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosPurchaseRequisitionLR--listReportFilter-btnGo-BDI-content&quot;)</value>
      <webElementGuid>6a427557-4e3a-4cc1-9395-baf25008117c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
