<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CA - CatalDE - DeutschEN - EnglishES_e3f430</name>
   <tag></tag>
   <elementGuidId>8f108791-2025-4f3b-8e06-ab5ce2a77ca7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LANGUAGE_SELECT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='LANGUAGE_SELECT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fb3c906f-3078-448b-be64-e994d411d90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LANGUAGE_SELECT</value>
      <webElementGuid>21314645-6bf7-46d3-b3f9-50f563aa229c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7475b1f8-d6f3-4a2b-8c12-fa6f20d97281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginSelect</value>
      <webElementGuid>6392869a-4b3b-4491-8271-ca9ca2b00470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Language</value>
      <webElementGuid>56b26efa-b127-4e56-ac19-c17b5adeac07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>LANGUAGE_LABEL</value>
      <webElementGuid>4e076c27-c356-49a5-aba3-023853997a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA - CatalàDE - DeutschEN - EnglishES - EspañolFR - FrançaisHR - HrvatskiIT - ItalianoPT - PortuguêsSV - Svenska</value>
      <webElementGuid>81c67f48-0400-4f6c-a1ae-b9279d7915ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LANGUAGE_SELECT&quot;)</value>
      <webElementGuid>e71fa90d-057b-49ef-8cb9-88ee361e7637</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='LANGUAGE_SELECT']</value>
      <webElementGuid>74c35d1d-dda0-415b-97dc-f10924be2cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LANGUAGE_SELECT_BLOCK']/select</value>
      <webElementGuid>0353c1ab-7ca8-4e9d-90a4-988ab1cc5e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/following::select[1]</value>
      <webElementGuid>fb30298b-f23a-4794-860b-209774af4637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::select[1]</value>
      <webElementGuid>5eb6c7ea-abdb-460a-b7b0-33ae9480ac21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log On'])[1]/preceding::select[1]</value>
      <webElementGuid>5a779e59-a579-4efc-82e4-7f307eda7d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/preceding::select[1]</value>
      <webElementGuid>46d3736b-45cf-40b6-91c1-f513cef63df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>aa82fb33-84f2-4634-a2ca-4241935a28c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'LANGUAGE_SELECT' and @title = 'Language' and (text() = 'CA - CatalàDE - DeutschEN - EnglishES - EspañolFR - FrançaisHR - HrvatskiIT - ItalianoPT - PortuguêsSV - Svenska' or . = 'CA - CatalàDE - DeutschEN - EnglishES - EspañolFR - FrançaisHR - HrvatskiIT - ItalianoPT - PortuguêsSV - Svenska')]</value>
      <webElementGuid>f2f5dcea-c0e9-483f-9ee1-6b44eb87123d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
