<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sig.fe.cont_InputField</name>
   <tag></tag>
   <elementGuidId>baa905e0-476e-4d81-8609-686fb48c8f22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:1:2B262:1[1,1]_c']&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cae0fd3e-a062-43bf-a7b0-e24b8eb666f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>59d34948-930a-44c0-8cd9-a266e2602af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8c3a00f5-2f4b-4104-b5ba-db4f88b12d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9e920ae5-c781-4dec-8b6a-c4e007001d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:2B262:1[1,1]_c</value>
      <webElementGuid>90e1cf04-923c-4e10-a628-6fb45fe7fe93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>CBS</value>
      <webElementGuid>17761fad-b761-4ee0-9f80-0cfd1682b243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;x&quot;:0,&quot;1&quot;:&quot;FREETEXT&quot;,&quot;3&quot;:&quot;M0:46:1:2B262:1::1:1_TALB&quot;,&quot;7&quot;:true,&quot;14&quot;:&quot;SERVER&quot;,&quot;17&quot;:false,&quot;20&quot;:false,&quot;21&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/tabsF110_TABSTRIP/tabpPAR/ssubSUBSCREEN_BODY:SAPF110V:0202/tblSAPF110VCTRL_FKTTAB/txtF110V-BUKLS[0,0]&quot;,&quot;Type&quot;:&quot;GuiTextField&quot;,&quot;value&quot;:&quot;&quot;,&quot;maxlen&quot;:50,&quot;focusable&quot;:&quot;X&quot;},&quot;25&quot;:&quot;FILL_FIXED_LAYOUT&quot;}</value>
      <webElementGuid>91d233d5-efa9-482d-a70b-f951db47fd53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Change&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Select&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Validate&quot;:[{},{}],&quot;DeleteItem&quot;:[{},{&quot;3&quot;:true}],&quot;ListAccess&quot;:[{&quot;ResponseData&quot;:&quot;delta&quot;,&quot;TransportMethod&quot;:&quot;full&quot;,&quot;EnqueueCardinality&quot;:&quot;none&quot;},{&quot;3&quot;:true,&quot;8&quot;:&quot;history&quot;,&quot;limitlen&quot;:&quot;X&quot;}]}</value>
      <webElementGuid>c3255576-7c6b-4feb-9a97-44b84dd2a724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InputField</value>
      <webElementGuid>c3f517b9-13d4-4519-9587-814781441a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c36fabe1-33f5-4cb6-bfd9-92dafe7c84b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField__input</value>
      <webElementGuid>951187df-313b-4f3c-a803-01412d75219e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:2B262:1[1,1]_c&quot;)</value>
      <webElementGuid>5e91ba41-8502-4db1-90cf-f5e7b593da58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Ejecucion lote pagos/Page_Pagos_Automaticos/Automatic Payment Iframe</value>
      <webElementGuid>e2b4706d-8f68-418c-ade7-b4d142270a2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:2B262:1[1,1]_c']</value>
      <webElementGuid>f58b316f-5c7b-4872-b678-587842cfdb8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:2B262:1[1,1]_c-r']/span</value>
      <webElementGuid>2aab20c0-dd1e-4d8c-bd5f-9f77524e8f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/table/tbody/tr/td/div/span/span</value>
      <webElementGuid>e31614f4-f67e-4933-9e24-5932e554049c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'M0:46:1:2B262:1[1,1]_c' and @name = 'InputField']</value>
      <webElementGuid>309428df-ff80-4ba3-81bf-ebd79da84e41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
