<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_OK</name>
   <tag></tag>
   <elementGuidId>616c3091-5f26-45ff-a3ae-cefba6d86fae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__mbox-btn-0-BDI-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='__mbox-btn-0-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>d6b28961-e400-48ca-a9d0-9d6a71fcacb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__mbox-btn-0-BDI-content</value>
      <webElementGuid>e1dd61e0-a1fc-4c10-9ef7-5ea67e3456a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>15ccaf2b-5dd3-4af1-b070-c0841b2087d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>237a9d36-3ec7-4a2e-8b94-0dd731bef0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__mbox-btn-0-BDI-content&quot;)</value>
      <webElementGuid>0fda6580-cac5-4bbe-ac74-2d21b0a4d992</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='__mbox-btn-0-BDI-content']</value>
      <webElementGuid>d829cfa1-2bc7-4720-9fae-51b4a1a3e5b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__mbox-btn-0-content']/bdi</value>
      <webElementGuid>31925340-d4a3-4a5f-8c64-bd1c24278875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Le conferme verranno create senza valutazione, sei sicuro?'])[1]/following::bdi[1]</value>
      <webElementGuid>e9d4a490-6ac4-4fb4-b40d-f5ea706f95a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conferma'])[1]/following::bdi[1]</value>
      <webElementGuid>4350cd92-9318-4fb3-a3be-bc04714c8b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annulla'])[1]/preceding::bdi[1]</value>
      <webElementGuid>56def18d-5889-4ecf-be1b-f3a7bf7a708c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::bdi[2]</value>
      <webElementGuid>d67455c7-00dd-4b92-93ab-7bb11d3bec02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>464962e3-ffe5-458b-a948-22509623119d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bdi</value>
      <webElementGuid>b81e9193-cc20-47f5-bfd1-a2b8e1cd5963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = '__mbox-btn-0-BDI-content' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>854a5630-eb4d-465c-b1d9-504ba9b82081</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
