<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Avvio</name>
   <tag></tag>
   <elementGuidId>d64363cc-5cd0-42e1-95af-e7054b09fd4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-BDI-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>c437f63c-ddb9-46f6-84bc-856bee5f48f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-BDI-content</value>
      <webElementGuid>a6c3a0ad-ccac-4d98-8c29-db62e015181e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>0d280914-0947-47b3-bd1a-cedee05305dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Avvio</value>
      <webElementGuid>50ae29d9-9433-444f-ab9a-08be0dc3f883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-BDI-content&quot;)</value>
      <webElementGuid>58763cfc-0e99-4424-9c1e-1f91e92c058d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-BDI-content']</value>
      <webElementGuid>1e4373d0-b923-4502-8341-db34652dcae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-content']/bdi</value>
      <webElementGuid>afb4b514-e671-4aaa-9d0e-ab7b49811b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleziona view'])[1]/following::bdi[1]</value>
      <webElementGuid>dff83b73-ce07-4ed5-8a77-1599f82dbeec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::bdi[1]</value>
      <webElementGuid>40117f6d-dc7e-40f5-a5db-a8aa880abd5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nascondi barra filtri'])[1]/preceding::bdi[1]</value>
      <webElementGuid>9dd483a5-cead-43b8-af8d-ed238a019f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtri (2)'])[1]/preceding::bdi[2]</value>
      <webElementGuid>980121db-c64c-4b0b-8bb6-d96dd3e52818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Avvio']/parent::*</value>
      <webElementGuid>b5ddb739-0a16-4258-937c-a21a97204b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bdi</value>
      <webElementGuid>6e757709-020f-44b3-a134-7205910d547a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-BDI-content' and (text() = 'Avvio' or . = 'Avvio')]</value>
      <webElementGuid>160418ee-73d2-4e85-ace2-2d701e5e896a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
