<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Anno attuale</name>
   <tag></tag>
   <elementGuidId>d8378975-45cc-4370-9610-47bf3e1bc408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-StartDate-option-THISYEAR-titleText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-StartDate-option-THISYEAR-titleText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8164a25f-bcf7-442e-b12f-2b4b9d0d5020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-StartDate-option-THISYEAR-titleText</value>
      <webElementGuid>913baaae-b7ea-4e27-817d-720bc45a0457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>ac5f3c43-3442-4217-bb7c-6861f995fab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anno attuale</value>
      <webElementGuid>da51cb0c-0e39-41e5-a608-e81cc8747fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-StartDate-option-THISYEAR-titleText&quot;)</value>
      <webElementGuid>d8531c50-2016-4844-b56a-39f09ae038fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-StartDate-option-THISYEAR-titleText']</value>
      <webElementGuid>f64f1e11-091d-4705-9fb4-79a1b601b22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-StartDate-option-THISYEAR-content']/div/div/span</value>
      <webElementGuid>e3d06fba-6671-43ba-870c-5cb70c3ff032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anni'])[1]/following::span[1]</value>
      <webElementGuid>50c241b3-0ad4-4ec1-bcbf-02c20443f85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quarto trimestre'])[1]/following::span[2]</value>
      <webElementGuid>4e973539-b824-4551-926b-cc3846aa55f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ultimo anno'])[1]/preceding::span[1]</value>
      <webElementGuid>af57c6c8-3f31-4448-a277-d7262fa7333b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anno successivo'])[1]/preceding::span[2]</value>
      <webElementGuid>8a83bc73-11d8-4847-9746-2f17d0ead8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Anno attuale']/parent::*</value>
      <webElementGuid>c9b3558a-05f0-435c-9b76-36d4702130a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[33]/div/div/div/span</value>
      <webElementGuid>b49cc375-4f6c-4dfc-88bf-2da024942c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-StartDate-option-THISYEAR-titleText' and (text() = 'Anno attuale' or . = 'Anno attuale')]</value>
      <webElementGuid>5175e6a3-21b6-4e56-827d-5d5ea6966cd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
