<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_OK</name>
   <tag></tag>
   <elementGuidId>18c025c3-37e7-4fc6-99ed-94f51d6c0159</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='iStartDateTime-OK-BDI-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iStartDateTime-OK-BDI-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>ae1fc15d-28c2-41f1-9807-56bdf706f7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iStartDateTime-OK-BDI-content</value>
      <webElementGuid>ec743169-f25a-4ca8-9d64-36dc65d90c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>b9db8a3c-6b27-46ac-845d-c210ce34b0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>832863cc-6789-4d21-a945-ddd54bc048b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iStartDateTime-OK-BDI-content&quot;)</value>
      <webElementGuid>b520a4fb-3179-46fe-8eb1-5c0872abff70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='iStartDateTime-OK-BDI-content']</value>
      <webElementGuid>e756c9df-20c1-4a50-bac6-40173a065dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='iStartDateTime-OK-content']/bdi</value>
      <webElementGuid>07c5aae5-0ab7-425c-b1ce-7a7db836546a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annulla'])[2]/following::bdi[4]</value>
      <webElementGuid>ddf989f2-10bd-4a48-ae5f-ad2454280d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dom'])[1]/following::bdi[4]</value>
      <webElementGuid>8f95d0ef-a246-45d4-bbe0-9f00a9af0a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annulla'])[3]/preceding::bdi[1]</value>
      <webElementGuid>c0da3a58-527e-4a36-b2ac-f80d5704a828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::bdi[2]</value>
      <webElementGuid>1f65ca98-2c04-46bb-b1a5-9faed9fba561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>a86039d2-c148-42cd-8d47-22435c01ead3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/footer/div/button/span/span/bdi</value>
      <webElementGuid>f145ef7b-c42e-450b-b528-b9a688064b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'iStartDateTime-OK-BDI-content' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>20a5f792-0c3a-4d83-822c-3562ac1d357d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
