<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Standard</name>
   <tag></tag>
   <elementGuidId>da4c84c9-1f27-4a71-8e7d-cc38031c257d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='__item32-application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-list-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__item32-application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-list-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a0ee4e37-97b1-4026-b7d4-c69c3bb65a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__item32-application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-list-0</value>
      <webElementGuid>7547acdc-d314-4c63-b97a-b56c0ddbc1de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__item32-application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-list-0</value>
      <webElementGuid>63cd4029-4be7-4be7-8cd5-3cbc98c5ca1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d6552c1d-252e-434e-bf02-d4577360db2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cf3144d8-d77e-4570-9589-2071f3757cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>25f27050-b756-43a2-9134-b9dc9d62988a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ca15b920-7776-49e7-bd51-0b2d94cd5c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bf1c0112-2674-49f2-96b8-538047511eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSelectListItemBase sapMSelectListItem sapMSelectListItemBaseHoverable sapMSelectListItemBaseSelected sapMSelectListItemBasePressed</value>
      <webElementGuid>c7a49076-88b2-47f3-b621-c357f55680cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Standard</value>
      <webElementGuid>0e94d99e-3a9b-49fa-a6c1-7c830ddd0e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__item32-application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-list-0&quot;)</value>
      <webElementGuid>17302a83-c0c2-4961-8da9-08e5c46f4996</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='__item32-application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-list-0']</value>
      <webElementGuid>d2a2ac78-4bee-4112-bdd4-c8c2b1cf71ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-list']/li</value>
      <webElementGuid>afa9d5e1-8990-4364-b19a-3894c6f95819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Le mie view'])[1]/following::li[1]</value>
      <webElementGuid>4e58c2d5-fcfb-4bce-9912-88f607566d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salva con nome'])[1]/preceding::li[1]</value>
      <webElementGuid>14cd8bc4-7987-4714-90b0-1e96d42209fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestisci'])[1]/preceding::li[1]</value>
      <webElementGuid>0dc17898-6a49-4591-a5bb-d9e83c5eb0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Standard']/parent::*</value>
      <webElementGuid>97bd82d9-c2d0-4400-8c09-6cabef5997d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>fe687ba2-bbac-4274-9e79-d8344a4aed68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '__item32-application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-list-0' and (text() = 'Standard' or . = 'Standard')]</value>
      <webElementGuid>dabd1b5b-5113-4604-9ac3-9512f3bd0194</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
