<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Acreedor Datos generales</name>
   <tag></tag>
   <elementGuidId>c6942cfe-94ee-4a04-8a26-1e3782f9ebf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:1:1:2:2:1::0:7-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>61107358-c61e-4434-bdc3-ade7c7b8186a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:1:2:2:1::0:7-text</value>
      <webElementGuid>16802c25-5389-49c1-a480-34a971158858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsTabStrip--item-text</value>
      <webElementGuid>229625f4-05af-4baa-8e37-0e75e0b8699b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acreedor: Datos generales</value>
      <webElementGuid>61c8e405-b1dc-4658-8328-989d5a42ddb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:1:2:2:1::0:7-text&quot;)</value>
      <webElementGuid>b9f82939-5356-452d-9588-92f853335482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BP Crear Proveedor New ID/Page_Crear Organizacin Rol ProveedorDatos Sociedad/iframe_Ms_application-BusinessPartner-creat_97ef72</value>
      <webElementGuid>8ae6d88f-a588-4d3d-aebe-7934ac41a5d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:1:2:2:1::0:7-text']</value>
      <webElementGuid>a0768745-3e8e-4b3e-854e-18154682f062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46:1:1:2:2:1::0:7-title']/span</value>
      <webElementGuid>41822903-636d-47eb-88bb-0320941c9097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos jurídicos'])[1]/following::span[1]</value>
      <webElementGuid>3aaf07ed-06fd-41e5-87fc-26feb1ee5622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[1]/following::span[2]</value>
      <webElementGuid>27be40db-8611-45d8-a743-dae78d3d1f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acreedor: Datos de control'])[1]/preceding::span[1]</value>
      <webElementGuid>10a1e19f-3aa4-4d70-b1cf-dfbee11be32d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vinculados'])[1]/preceding::span[2]</value>
      <webElementGuid>ba36ee6c-a364-4603-b5f7-b340967c75b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Acreedor: Datos generales']/parent::*</value>
      <webElementGuid>a7c3c833-6a81-4724-903c-ed23cde701a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/span</value>
      <webElementGuid>83ee3ca8-35ea-430a-b4c1-2edbfd69707e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'M0:46:1:1:2:2:1::0:7-text' and (text() = 'Acreedor: Datos generales' or . = 'Acreedor: Datos generales')]</value>
      <webElementGuid>aedb6a91-b4b3-4bb7-879d-f48efdbdcb89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
