<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Orden_application-ZPM_SMART-GESTPREVE_e275c9</name>
   <tag></tag>
   <elementGuidId>f173ac5e-c0a5-44ad-a6ec-555fcfd52fe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b663623-b6c4-415d-9192-df05d78bc933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner</value>
      <webElementGuid>0f92f7ce-43de-4848-8f66-bc120acf3601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>60a19a8b-aff6-4702-b51e-63939e7dcdef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItem-OrdenesSet-Orderid</value>
      <webElementGuid>a0f35350-0b7d-4a8c-9ab2-034e10917932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text189</value>
      <webElementGuid>c3b63126-e51d-4980-8637-8953cf97bdc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>b2b535cd-c036-4cac-93f3-3a5ed66ed3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-roledescription</name>
      <type>Main</type>
      <value>Entrada de varios valores</value>
      <webElementGuid>3332a263-28ad-47ee-84d2-ae97807ba727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1fd23ddd-433e-431d-b648-fda9f34da422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7e2ca45f-b26f-49f9-8a16-52455f610dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>a27bffab-2472-4014-b6f1-7efc6b20cdcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner&quot;)</value>
      <webElementGuid>8613b9c5-43d6-4efa-a807-3e3a839cb3db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner']</value>
      <webElementGuid>edad032d-47ed-462b-857e-0a1f20b66e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-content']/input</value>
      <webElementGuid>2e48fd84-a8fc-46a5-b04b-c5c2b1e85ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>8549e8fa-1652-460f-83d2-0a087e8f6f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner' and @type = 'text']</value>
      <webElementGuid>6794ce50-26fb-49db-8dab-abffa20e774d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
