<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Visualizar otras aplicaciones</name>
   <tag></tag>
   <elementGuidId>ee8a5f99-fd0c-4663-b3b7-e9f35a1845ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='eshCompGenId_0-ushell-search-result-list-0-appItemContainer--showMore--content--text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eshCompGenId_0-ushell-search-result-list-0-appItemContainer--showMore--content--text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3c5de7a1-c167-45fd-8a7e-f57fc9422c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eshCompGenId_0-ushell-search-result-list-0-appItemContainer--showMore--content--text</value>
      <webElementGuid>0196258b-4e64-4cad-9884-0414d6a864ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>eshCompGenId_0-ushell-search-result-list-0-appItemContainer--showMore--content--text</value>
      <webElementGuid>048ecbed-4c64-4054-9836-69b8713675a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>f28d0934-5746-4bf1-837a-689c26238af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextMaxWidth sapMTcInnerMarker</value>
      <webElementGuid>000b9d7a-21ed-4578-8344-4cca87d0de56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visualizar otras aplicaciones</value>
      <webElementGuid>ec5c191b-6b9a-4a0b-984a-1f3f0b348719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eshCompGenId_0-ushell-search-result-list-0-appItemContainer--showMore--content--text&quot;)</value>
      <webElementGuid>8430f5bc-66a8-4967-a0b7-cc83c3becdb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='eshCompGenId_0-ushell-search-result-list-0-appItemContainer--showMore--content--text']</value>
      <webElementGuid>679d2ea3-c5ca-41c9-83ba-94803ed1eaea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eshCompGenId_0-ushell-search-result-list-0-appItemContainer--showMore--content-content']/span</value>
      <webElementGuid>dde5d7c9-dc02-42b1-bc9b-7157c48f885f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPT/VIM_VA2'])[2]/following::span[3]</value>
      <webElementGuid>2b324343-de93-4226-8cfb-2dca3e95d575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Visualizar otras aplicaciones']/parent::*</value>
      <webElementGuid>611561e2-0f1b-4015-8994-084771554009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/span</value>
      <webElementGuid>e0883e26-3e97-4bba-a639-5661824c167f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'eshCompGenId_0-ushell-search-result-list-0-appItemContainer--showMore--content--text' and (text() = 'Visualizar otras aplicaciones' or . = 'Visualizar otras aplicaciones')]</value>
      <webElementGuid>4f1f5b7b-38bb-42ec-a708-31f513facba3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
