<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Plus_application-PurchaseContract-cr_6ea6a7</name>
   <tag></tag>
   <elementGuidId>f444f835-e8af-42f7-8023-7a7bea626575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-PurchaseContract-create-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='application-PurchaseContract-create-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>61c5f142-367b-4e19-b23b-414bbf5c1ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-PurchaseContract-create-iframe</value>
      <webElementGuid>6f2c843e-957c-4080-b49c-cc4edf33ac4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-PurchaseContract-create-iframe</value>
      <webElementGuid>c82ac01c-9d17-4e67-a9a7-bfb836723c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application-PurchaseContract-create-iframe</value>
      <webElementGuid>c8428aad-a2e1-42c6-89a2-71274b845474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-orig-src</name>
      <type>Main</type>
      <value>/sap/bc/gui/sap/its/webgui;~sysid=R3Q;~service=3200?~transaction=ME31K&amp;sap-client=100&amp;sap-language=FR&amp;~nosplash=1&amp;sap-iframe-hint=GUI&amp;sap-ie=edge&amp;sap-theme=abertis_theme_corp%40https%3A%2F%2Fsaps4-pre.abertis.com%2Fsap%2Fpublic%2Fbc%2Fthemes%2F~client-100%2F~cache-EffUt0nnNFsxi7WxmjEKOoghmzc&amp;sap-touch=0&amp;sap-target-navmode=inplace&amp;sap-keepclientsession=2&amp;sap-ushell-timeout=25&amp;sap-shell=FLP1.120.28</value>
      <webElementGuid>168118d6-d6fa-4d12-b10b-f4b36d181f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Application</value>
      <webElementGuid>2222015e-95c7-496e-aea3-a13151fac053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-iframe-idx</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6b6a0290-8cc5-4673-9903-3dd2dc648167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay ;battery ;camera ;display-capture ;geolocation ;gyroscope ;magnetometer ;microphone ;midi ;clipboard-write ;clipboard-read ;fullscreen ;serial ;</value>
      <webElementGuid>6c6efee6-7a34-4d01-9b09-fc07263f1bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUShellApplicationContainer</value>
      <webElementGuid>07b810e4-7ebe-43bf-881d-1edea7178a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-PurchaseContract-create-iframe&quot;)</value>
      <webElementGuid>75d7cdc8-a2f4-4db2-b867-3e0766cbcd04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='application-PurchaseContract-create-iframe']</value>
      <webElementGuid>5485b26e-fbff-4d82-b378-a59cb32b69bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-PurchaseContract-create']/iframe</value>
      <webElementGuid>47f7b9f5-c848-4669-8cf2-e0b940946ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4a99d9ad-a79b-4260-bf47-8930d0ca3900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'application-PurchaseContract-create-iframe' and @name = 'application-PurchaseContract-create-iframe' and @title = 'Application']</value>
      <webElementGuid>231ad0ec-eb0d-42be-adc9-cab024e3f915</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
