<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>01ea765c-8c56-43d8-a063-53ced9f88206</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='__YMUJYF5VR8C74TZSVJICZ7WC-cl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__YMUJYF5VR8C74TZSVJICZ7WC-cl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1704c0af-90c3-4325-901e-67eb7602cb54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__YMUJYF5VR8C74TZSVJICZ7WC-cl</value>
      <webElementGuid>a41bfebc-1217-4a78-9afc-af4821562c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help4-close help4-control-button help4-control help4-exposed</value>
      <webElementGuid>81df0658-ed3a-4002-a608-ed31f969ae8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Chiudere lightbox</value>
      <webElementGuid>7efcc403-32e1-42e6-b283-9b0338210aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c37e835-efbf-4ade-be9a-ce67888baf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>17475485-b3d1-4de4-9bbd-eeb645ac389c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__YMUJYF5VR8C74TZSVJICZ7WC-cl&quot;)</value>
      <webElementGuid>c72324f6-a0cf-4937-a379-ad621508f623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='__YMUJYF5VR8C74TZSVJICZ7WC-cl']</value>
      <webElementGuid>72763db0-1db8-4cf0-9ffc-af49a7a5e2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__YMUJYF5VR8C74TZSVJICZ7WC-head']/button</value>
      <webElementGuid>62f16cb2-12ed-42a0-8d87-343cc45a88ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analisi'])[1]/following::button[2]</value>
      <webElementGuid>7f1e9031-b299-4526-a3e2-a898ee616ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cercare temi dell’help'])[1]/preceding::button[1]</value>
      <webElementGuid>8df399b0-696a-4e9c-8140-ffae061ab212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>ca4e5dfb-c5ae-49aa-80ea-1ac9d2838d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '__YMUJYF5VR8C74TZSVJICZ7WC-cl' and @title = 'Chiudere lightbox' and (text() = '' or . = '')]</value>
      <webElementGuid>71499bb7-99af-419f-9d9a-cb1b5992528e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
