<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Cerrar</name>
   <tag></tag>
   <elementGuidId>f3537dcf-4fe6-446d-a203-b8f350bf0f02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__button96-BDI-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='__button96-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>ff539609-bc1d-4adf-91b7-c58060d458c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__button96-BDI-content</value>
      <webElementGuid>000a839a-d357-422a-8047-a9ba1262d3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>1ccd477f-934e-4ba1-b347-ee7d5f1187a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cerrar</value>
      <webElementGuid>eb9ec2a2-18ae-49b4-91c4-216d4729b439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__button96-BDI-content&quot;)</value>
      <webElementGuid>10111a2e-af05-400e-a82c-9bd5c14933cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='__button96-BDI-content']</value>
      <webElementGuid>9e4ec8cc-d6b1-43dc-aef4-ebb28c641377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__button96-content']/bdi</value>
      <webElementGuid>a2f72f1a-1315-4c82-8ba9-11cb41c8bb6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se ha creado la Entrada de Mercancías 2024/5002352336'])[1]/following::bdi[1]</value>
      <webElementGuid>1903b411-5351-4902-87fa-e7a2e8bc9dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceso completado con éxito'])[1]/following::bdi[1]</value>
      <webElementGuid>745f07c6-a59d-47ac-ac23-33039a8aa0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::bdi[1]</value>
      <webElementGuid>fa408385-bdb8-43c8-8b0c-8da5317aecf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrada de Mercancías'])[2]/preceding::bdi[1]</value>
      <webElementGuid>3516de8e-095a-4cb6-bfc3-e5710e127618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cerrar']/parent::*</value>
      <webElementGuid>437ecbab-b12e-4013-bd10-04bb0acb4b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bdi</value>
      <webElementGuid>4722df5c-1bdf-41ed-93d7-f28ab5230bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = '__button96-BDI-content' and (text() = 'Cerrar' or . = 'Cerrar')]</value>
      <webElementGuid>2ca55b02-93b3-4eca-aa38-ca2ba4409d05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
