<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gruppo acquisti</name>
   <tag></tag>
   <elementGuidId>12216d58-b06f-4ca5-870c-6bd265c47961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createTP-component---detail--idHPurchaseGroup-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='application-zpurchaserequisition-createTP-component---detail--idHPurchaseGroup-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f70dbac2-85bd-44b3-81a6-d5f9263a0e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createTP-component---detail--idHPurchaseGroup-inner</value>
      <webElementGuid>fe9d5e37-09a8-4255-ae0f-e2ea71d49b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d55501ff-e6e4-4302-986b-6f01f30a1ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>R10</value>
      <webElementGuid>4c1d1bac-961e-409d-a74e-e5f6667e153f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a8593d33-c5d2-4761-8a68-cb0c51b86117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__element31-label</value>
      <webElementGuid>32bf5837-dc74-4a00-a063-cbab682df48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text158 application-zpurchaserequisition-createTP-component---detail--idHPurchaseGroup-SuggDescr</value>
      <webElementGuid>5dcdc78b-54df-4eee-9d99-657b2f51439a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>70a7c351-281e-4a0a-8849-844edaebf839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf014abf-d091-4fdf-ac0c-dc06dde95965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aa9f4fd9-1c31-42dc-bef4-cf0a180f1c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>3c14bd84-6b9d-4ff2-bf66-77a53a4d1f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createTP-component---detail--idHPurchaseGroup-inner&quot;)</value>
      <webElementGuid>5fe40128-6d91-45ea-8833-33ff5cc4d2f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-zpurchaserequisition-createTP-component---detail--idHPurchaseGroup-inner']</value>
      <webElementGuid>905b3542-f9a1-4bd1-b48d-ec70324d9ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaserequisition-createTP-component---detail--idHPurchaseGroup-content']/input</value>
      <webElementGuid>203170b0-591a-4f9a-a74f-c622bed0c9f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>eaffa636-9845-4837-ba75-03ccfbed2c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-zpurchaserequisition-createTP-component---detail--idHPurchaseGroup-inner' and @type = 'text']</value>
      <webElementGuid>c180cf77-058e-45fe-b7c9-cc6f7ce682c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
