<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ElementoWBS_1</name>
   <tag></tag>
   <elementGuidId>b709163c-c45e-462e-9f2c-05a3ad540c61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createTP-component---detail--idPWBSElement-__clone25-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div[2]/div/section/div/div[2]/div[2]/div[2]/div/div/div/div/div[2]/div[1]/div/div/div/div/section/div/div[2]/div/section[2]/section[2]/div[2]/div/div[1]/div/div/div/table/tbody/tr/td[14]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8acb830f-99c2-4a8f-9029-743d2644caa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createTP-component---detail--idPWBSElement-__clone25-inner</value>
      <webElementGuid>cf8ae155-521b-4040-9ff7-c45c9f69586a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>d11f2ffe-0bbf-4541-a578-734ab35de0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__label72</value>
      <webElementGuid>3cd4fb21-285d-4b1d-bee2-6b04de35b529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text164 application-zpurchaserequisition-createTP-component---detail--idPWBSElement-__clone25-SuggDescr</value>
      <webElementGuid>1cf4c9ea-764e-4c5c-89df-6a0dd6a2fefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>a81ed82b-e7b2-4552-8867-94533b502a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71ad4726-c31b-42fc-968b-0c4e8c1561b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>09977be2-681e-4d6f-8ae1-30f2daae02a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>6f12e761-7b94-4f23-9847-575f610e078b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createTP-component---detail--idPWBSElement-__clone25-inner&quot;)</value>
      <webElementGuid>d2a599eb-325f-474a-9152-513ef8513df6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-zpurchaserequisition-createTP-component---detail--idPWBSElement-__clone25-inner']</value>
      <webElementGuid>dee8d3ed-b7cb-49fa-9016-c9c003dcd58d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaserequisition-createTP-component---detail--idPWBSElement-__clone25-content']/input</value>
      <webElementGuid>96fe86dc-bdc4-493e-bc9f-c57c615e8a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[15]/div/div/input</value>
      <webElementGuid>b0e4da73-7c1a-45c7-9dd8-37849d23a9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-zpurchaserequisition-createTP-component---detail--idPWBSElement-__clone25-inner' and @type = 'text']</value>
      <webElementGuid>0f9f60ab-5bd4-4408-91ab-974214eb9d6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
