<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TpImpMX</name>
   <tag></tag>
   <elementGuidId>5ad75608-6a41-41ac-b37d-73d04b642893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createTP-component---detail--idPAccountAssignmentCategory-__clone26-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[5]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98eb7e6e-2f3a-435d-9a59-6b45ec4517d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createTP-component---detail--idPAccountAssignmentCategory-__clone26-inner</value>
      <webElementGuid>4e5ca0d5-3c00-4f2b-b7f3-144e7e009748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>K</value>
      <webElementGuid>11ce295d-a54a-4ed8-b4b5-9d50f915ecce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__label146</value>
      <webElementGuid>f73f9fa1-55c6-4b05-ad0b-5ae287fdf018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4aec9b18-6879-4dca-94e9-75f67e3359e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4b014ae5-7264-4b40-9e16-31572d68b90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ae229636-f4ba-40fb-949e-ec6ec2fa2249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79a82958-6782-4692-94d9-6eb930dbb1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner sapMComboBoxInner</value>
      <webElementGuid>9dd3f6ac-9be5-4446-905c-04da51aa2ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createTP-component---detail--idPAccountAssignmentCategory-__clone26-inner&quot;)</value>
      <webElementGuid>5a8cb684-ea8a-401c-90b6-ae0b92386b46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-zpurchaserequisition-createTP-component---detail--idPAccountAssignmentCategory-__clone26-inner']</value>
      <webElementGuid>2dfcf09e-ebcc-4060-9229-1d4cdc036ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaserequisition-createTP-component---detail--idPAccountAssignmentCategory-__clone26-content']/input</value>
      <webElementGuid>a5e82d91-4936-499d-884f-a809983ab56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div/input</value>
      <webElementGuid>bb67fd71-9a68-47f4-8d05-15b9cb824325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-zpurchaserequisition-createTP-component---detail--idPAccountAssignmentCategory-__clone26-inner' and @type = 'text']</value>
      <webElementGuid>82c9d828-dae4-47d9-b947-5eb7a1214200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
