<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fornitore</name>
   <tag></tag>
   <elementGuidId>509f3458-a3a2-4cba-93b5-c919ce4dd3b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2232f80-191d-4c68-a86e-3d69526cb2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-inner</value>
      <webElementGuid>11584c32-673f-431a-bcde-8260573afc5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e8416f57-1325-4150-9806-d3039bdc88ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eaccc96f-da69-458b-b320-b2d9d4ba0518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__element2-label</value>
      <webElementGuid>79833e0d-2ecc-4eb1-8527-3efe93b874e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text164 application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-SuggDescr application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-message</value>
      <webElementGuid>35c3ab3f-dc64-40af-8160-ca7e965f0cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>54485671-63c1-45cc-9445-d2932f9c2496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f69401f-df45-4776-8a7f-e43e5a62e807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ce0d4276-d61d-48e0-a779-c12ab680d34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>15d706d5-269f-471d-949b-f1bfe5a0fc5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-inner&quot;)</value>
      <webElementGuid>8d56b6f0-ff86-4a8d-8bab-1901b1f439eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-inner']</value>
      <webElementGuid>50de2cf2-c4c3-48a2-b957-c5304a6762d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-content']/input</value>
      <webElementGuid>70d25d0b-11ae-46b8-8bbb-dd9779c3f8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c7a6bf0d-678f-4c7e-a0e8-ec0fcfdda42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-inner' and @type = 'text']</value>
      <webElementGuid>6e369468-3eb3-4364-a9cd-815254be2e10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
