<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_exito</name>
   <tag></tag>
   <elementGuidId>649bd300-3df4-40fa-ac64-9c1633af23ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[8]/header/div/div[2]/div/h2/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__success11-title-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>83dc97ed-00cf-45dc-b3a7-71b3340cbd04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__success11-title-inner</value>
      <webElementGuid>e2c96fff-11e5-4af4-87e1-ac9cdbc6a6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Êxito</value>
      <webElementGuid>dc650f37-ab8f-4f22-b63b-b0c2f50a5155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__success11-title-inner&quot;)</value>
      <webElementGuid>2fcc55ce-87e4-4891-929e-7b58db271884</webElementGuid>
   </webElementProperties>
</WebElementEntity>
