<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ObjetodeCompra</name>
   <tag></tag>
   <elementGuidId>49902692-80bc-45a0-98ac-2795052e3739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createTP-component---detail--idHB02-inner</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'application-zpurchaserequisition-createTP-component---detail--idHB02-inner']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='application-zpurchaserequisition-createTP-component---detail--idHB02-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f7298f3d-cae6-4bb4-bb7e-217cea6d88bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createTP-component---detail--idHB02-inner</value>
      <webElementGuid>dff6650d-8cee-4af4-9e0e-0446f6817cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4644b1bd-a36f-4444-b1c0-09cd57bf058e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createTP-component---detail--idHB02E-label</value>
      <webElementGuid>6bc6f77e-b447-4e75-b32d-63476d160cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>aaf73a68-98cb-4235-a741-e56f0f0b2217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>5fb72616-31df-4391-a5a2-810519a0a8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner sapMTextAreaInner</value>
      <webElementGuid>cb070c50-9fc2-4270-96cb-a073c1897c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createTP-component---detail--idHB02-inner&quot;)</value>
      <webElementGuid>f9dbad40-1e64-4168-8b0f-cba6660b8f3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='application-zpurchaserequisition-createTP-component---detail--idHB02-inner']</value>
      <webElementGuid>353991d9-3a2a-414c-bf1c-9496ce4d7423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaserequisition-createTP-component---detail--idHB02-content']/textarea</value>
      <webElementGuid>0b4127f7-d24f-4aea-9c70-c60d31e8499d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>459e8261-7b17-4c1d-9882-beb71b3914cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'application-zpurchaserequisition-createTP-component---detail--idHB02-inner']</value>
      <webElementGuid>e4be058f-3f4a-4713-bd3b-8234bceec714</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
