<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Ms_application-MaintenanceOrder-crea_93f4a2</name>
   <tag></tag>
   <elementGuidId>9b417bf0-abac-4f32-8eea-9d638cdc426b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='application-MaintenanceOrder-create-iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-MaintenanceOrder-create-iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>76c8988a-3ecf-44f1-a0ae-c9214717c1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-MaintenanceOrder-create-iframe</value>
      <webElementGuid>c5f36e9d-3779-4a91-8960-89d2b8bd221e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-MaintenanceOrder-create-iframe</value>
      <webElementGuid>b4c4d16b-4ea0-48c1-aaba-970ec41f78e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application-MaintenanceOrder-create-iframe</value>
      <webElementGuid>43a553c2-d573-4991-bcad-9510316471e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-orig-src</name>
      <type>Main</type>
      <value>/sap/bc/gui/sap/its/webgui;~sysid=R3Q;~service=3200?~transaction=IW31&amp;sap-client=100&amp;sap-language=ES&amp;~nosplash=1&amp;sap-iframe-hint=GUI&amp;sap-ie=edge&amp;sap-theme=abertis_theme_corp%40https%3A%2F%2Fsaps4-pre.abertis.com%2Fsap%2Fpublic%2Fbc%2Fthemes%2F~client-100%2F~cache-FoBFe1cm.XhV1zLC6kMEvY1pkm4&amp;sap-touch=0&amp;sap-target-navmode=inplace&amp;sap-keepclientsession=2&amp;sap-ushell-timeout=25&amp;sap-shell=FLP1.120.28</value>
      <webElementGuid>14cbc730-d774-4df1-903e-bdc613be74bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aplicación</value>
      <webElementGuid>32941392-6461-41e9-a86b-2317e0410a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-iframe-idx</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3e096b50-cc5d-46ea-9a25-000d237853fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay ;battery ;camera ;display-capture ;geolocation ;gyroscope ;magnetometer ;microphone ;midi ;clipboard-write ;clipboard-read ;fullscreen ;serial ;</value>
      <webElementGuid>88bba03c-da44-401a-ab22-d00c5ae5c58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUShellApplicationContainer</value>
      <webElementGuid>a6cf12ff-4b9b-42b0-affc-98639de7093f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-MaintenanceOrder-create-iframe&quot;)</value>
      <webElementGuid>469fbf8b-b2e9-4183-af9c-bdf8c82e8670</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='application-MaintenanceOrder-create-iframe']</value>
      <webElementGuid>64ca9746-b708-47cf-afd2-16abf66bc652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-MaintenanceOrder-create']/iframe</value>
      <webElementGuid>41d41d16-e107-480e-96e6-4cf476c8699f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>70f61cea-ed9c-4e9e-999a-4ce6a0838815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'application-MaintenanceOrder-create-iframe' and @name = 'application-MaintenanceOrder-create-iframe' and @title = 'Aplicación']</value>
      <webElementGuid>c391679b-0088-425a-aca2-e3fae1838105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
