<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Campos usuario</name>
   <tag></tag>
   <elementGuidId>6cd128cf-787f-40bf-a777-b19f0adc8aa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:1:4:1::0:5-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f307c4fb-779a-4165-9dbc-ecdd1d9934ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:4:1::0:5-text</value>
      <webElementGuid>8537a0cb-f8cd-426c-b3d0-c126cfebf3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsTabStrip--item-text</value>
      <webElementGuid>479e51ca-5889-4b1b-acc2-4c867cd3d472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Campos usuario</value>
      <webElementGuid>3dff92b5-f2ad-495a-8241-9bed76402340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:4:1::0:5-text&quot;)</value>
      <webElementGuid>7dce8751-96ef-4001-815f-66b4b9e027ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Creacion Elemento PEP/Page_Project Builder Proyecto I.AAE.0084/iframe_Ms_application-Project-process-iframe</value>
      <webElementGuid>38a32299-7fec-4825-ab7d-5c33733d3fba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:4:1::0:5-text']</value>
      <webElementGuid>68c77f7e-8abb-4c96-a198-34e5d59cb125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46:1:4:1::0:5-title']/span</value>
      <webElementGuid>5b72a4e6-f35d-4f31-8592-d2af3c47e099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Control'])[1]/following::span[1]</value>
      <webElementGuid>5e661c75-f2a3-49f9-9a45-8b4ea607ecd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asign.'])[1]/following::span[2]</value>
      <webElementGuid>fd989440-ec9a-4db8-a5a4-99e35976fa92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestión'])[1]/preceding::span[1]</value>
      <webElementGuid>e2810347-eba4-42da-be5b-46087236c25f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Superior'])[1]/preceding::span[2]</value>
      <webElementGuid>d6bdcde1-30e7-46d9-84b9-5084d6cce510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Campos usuario']/parent::*</value>
      <webElementGuid>afe806eb-7408-4053-8245-1ff6f9b7e9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div[5]/div/span</value>
      <webElementGuid>8e516b88-5756-4aad-a6a4-fa434e0bedb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'M0:46:1:4:1::0:5-text' and (text() = 'Campos usuario' or . = 'Campos usuario')]</value>
      <webElementGuid>bfeca140-ea2b-41cb-816d-f5205e04ca96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
