<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Fechas</name>
   <tag></tag>
   <elementGuidId>536a8296-41c9-48ce-b66d-982c779ae973</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:1:4:1::0:1-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b33c483e-46dc-4ee1-8344-f478cf86fd4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:4:1::0:1-text</value>
      <webElementGuid>853f8734-450d-4a54-93b2-807ac728b58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsTabStrip--item-text</value>
      <webElementGuid>2608b9cc-a275-4ed8-86ba-2b6cea6949d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fechas</value>
      <webElementGuid>718ea3e4-bfac-4318-9130-688d537d3c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:4:1::0:1-text&quot;)</value>
      <webElementGuid>007fbacd-4082-4759-9d23-6e7bc02d392c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Creacion Elemento PEP/Page_Project Builder Proyecto I.AAE.0084/iframe_Ms_application-Project-process-iframe</value>
      <webElementGuid>b885762e-388e-44df-85e4-d7f184d851b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:4:1::0:1-text']</value>
      <webElementGuid>f2b033a5-82c6-47bd-93e3-a05c4b2b79b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46:1:4:1::0:1-title']/span</value>
      <webElementGuid>355394cc-1c68-4db2-a1e0-176a1d876981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dat.básic.'])[1]/following::span[1]</value>
      <webElementGuid>cb60451c-8d6f-42f5-b46e-6862a95b33d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R'])[1]/following::span[19]</value>
      <webElementGuid>1f8f9f7a-f963-4ff7-84cb-c5b78ff30b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asign.'])[1]/preceding::span[1]</value>
      <webElementGuid>8cd955c6-ae0e-45b7-bb88-9223fb2bf1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Control'])[1]/preceding::span[2]</value>
      <webElementGuid>9899e453-b0e1-430e-af89-ca2ef1c2262b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fechas']/parent::*</value>
      <webElementGuid>49b061c2-dc53-4da4-a8cf-2672405e8813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>d4801879-bff3-4a2c-a0ba-8b34c1c12147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'M0:46:1:4:1::0:1-text' and (text() = 'Fechas' or . = 'Fechas')]</value>
      <webElementGuid>4c967cae-9551-4802-9a76-a31379743ae7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
