<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Txt.expl</name>
   <tag></tag>
   <elementGuidId>d4134d42-34f5-4755-b88d-9fa309de0a5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:1:4:1::0:16-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>955af102-e08b-4e57-a471-4e3de8548eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:4:1::0:16-text</value>
      <webElementGuid>0b79f0b0-fe51-4697-8e42-4f0143e91f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsTabStrip--item-text</value>
      <webElementGuid>8d59bd05-22a1-4469-9435-cdf6dec309f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Txt.expl.</value>
      <webElementGuid>2e40809c-6a12-4115-ae1e-db4628625b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:4:1::0:16-text&quot;)</value>
      <webElementGuid>e45522e6-38a9-479c-bc6a-1c0f8fd7c1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Creacion Elemento PEP/Page_Project Builder Proyecto I.AAE.0084/iframe_Ms_application-Project-process-iframe</value>
      <webElementGuid>00647c78-c3dd-4277-8f24-a2a62b8daa15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:4:1::0:16-text']</value>
      <webElementGuid>91def1ba-01b1-4bea-85f9-66ea9595f522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46:1:4:1::0:16-title']/span</value>
      <webElementGuid>e2ba46f2-216a-4ea6-80fc-bff543345223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Progreso'])[1]/following::span[1]</value>
      <webElementGuid>78f3b7f8-2ad9-4e6f-a2fb-6ba3f95c7de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Superior'])[1]/following::span[2]</value>
      <webElementGuid>9769f453-64ef-429a-a570-1a6722649bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ampl.cliente'])[1]/preceding::span[1]</value>
      <webElementGuid>d2c4c797-4e01-4950-b0a0-bef7dc2ee70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cProjects'])[1]/preceding::span[2]</value>
      <webElementGuid>2d224a52-8b5c-4e7a-b8f0-7cec989389fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Txt.expl.']/parent::*</value>
      <webElementGuid>af9a0cf8-a28c-4fa7-808d-69e78ab052fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/span</value>
      <webElementGuid>80c1f3ba-a55a-4cb5-9e7d-b71418958ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'M0:46:1:4:1::0:16-text' and (text() = 'Txt.expl.' or . = 'Txt.expl.')]</value>
      <webElementGuid>c490945c-a67a-4e49-8951-d339fc0130fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
