<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Elemento facturacin</name>
   <tag></tag>
   <elementGuidId>f0acb346-436f-43fb-911b-4053f34a3cd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:1:4:1:2B256::9:57']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1f22ae6c-82be-48f4-ba72-fbdc4d4c304e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>C_standards</value>
      <webElementGuid>d60321d7-ed7f-4741-b1d3-32381a619d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;CheckBox&quot;,&quot;4&quot;:&quot;Elemento facturación&quot;,&quot;5&quot;:&quot;Indicador: Elemento de facturación&quot;,&quot;9&quot;:&quot;E&quot;,&quot;10&quot;:&quot;CHECKBOXLAST&quot;,&quot;14&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/subDETAIL_AREA:SAPLCNPB_M:1010/subVIEW_AREA:SAPLCJWB:3999/tabsTABCJWB/tabpGRND/ssubSUBSCR1:SAPLCJWB:1210/chkPRPS-FAKKZ&quot;,&quot;Type&quot;:&quot;GuiCheckBox&quot;,&quot;focusable&quot;:&quot;X&quot;},&quot;16&quot;:true,&quot;18&quot;:true}</value>
      <webElementGuid>5e7f1239-b585-4178-9c9d-eb8968c83328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Enter&quot;:[{},{&quot;1&quot;:&quot;vkey/0/ses[0]&quot;,&quot;2&quot;:true}],&quot;Change&quot;:[{},{&quot;1&quot;:&quot;action/7&quot;,&quot;3&quot;:true}],&quot;DoubleClick&quot;:[{},{&quot;1&quot;:&quot;action/2&quot;,&quot;2&quot;:true,&quot;3&quot;:true}]}</value>
      <webElementGuid>fc331afc-7b81-4d95-bb3c-5083b740ae0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-currentselectionstate</name>
      <type>Main</type>
      <value>API_DRIVEN</value>
      <webElementGuid>fac49ed0-ffcb-4e52-b286-26703a8c9191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsSelector--generic lsSelector--text lsSelector--withColon--pushedToEnd lsSelector--strechedForEllipsis lsSelector--pushedToEnd--spacing lsSelector--withColon lsCheckBox lsCheckBox--unchecked  </value>
      <webElementGuid>dff6e2be-7fce-4d2c-87f8-bf7d1f999b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cf6ef6d8-20c9-4403-be9a-82014884a619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>54a55ee7-3a1b-403e-a265-9440c3e79fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Indicador: Elemento de facturación</value>
      <webElementGuid>2d7e0f5c-e6d8-4ac3-9a8c-61f6f99a0afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>E</value>
      <webElementGuid>1a1470b2-ff5b-4aaa-9357-82c8ed8636fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>E</value>
      <webElementGuid>6b07a471-327d-455d-8aa6-5f52ac13c926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CheckBox</value>
      <webElementGuid>fb033079-acb3-480b-813c-18f098df77f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:4:1:2B256::9:57</value>
      <webElementGuid>f6021868-0cf6-466c-8e73-347c63b0ab7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6fb05164-72de-432d-9b68-f17e3ea4cc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8be34f02-9c60-46d9-84eb-40629d6b1d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f5daf7dd-cf2d-4414-b413-9d98b3ac88b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b899e5db-5c6f-4db6-99f0-f0cd41975041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Elemento facturación</value>
      <webElementGuid>f464ec17-dbb8-40ec-ba93-3ddba0b8d5e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e14a5820-050a-44f7-a26e-0da8db404542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-controlusage</name>
      <type>Main</type>
      <value>API_DRIVEN</value>
      <webElementGuid>0c5d1d80-69b5-4203-beef-326108fdd26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>:Elemento facturación</value>
      <webElementGuid>7b17c48c-6b94-4222-ab0b-ad01014aeba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:4:1:2B256::9:57&quot;)</value>
      <webElementGuid>462cac1b-d899-4465-b2d7-084961fe31a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Creacion Elemento PEP/Page_Project Builder Proyecto I.AAE.0084/iframe_Ms_application-Project-process-iframe</value>
      <webElementGuid>475d5f81-fca6-4195-b9d6-4aa48032fc66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:4:1:2B256::9:57']</value>
      <webElementGuid>ac4fb4a4-69b7-413f-9351-3b292bb39189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u3F85']/span</value>
      <webElementGuid>32a7d8c3-219e-4703-a8d4-eed482b062e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[6]/following::span[1]</value>
      <webElementGuid>72b1201e-ff6a-495f-b398-76105cfb0439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/table/tbody/tr[2]/td/table/tbody/tr/td/div/div/div/div[3]/span</value>
      <webElementGuid>3f2b1f21-5be7-4353-a3cf-e547cfe76951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Indicador: Elemento de facturación' and @name = 'CheckBox' and @id = 'M0:46:1:4:1:2B256::9:57' and (text() = ':Elemento facturación' or . = ':Elemento facturación')]</value>
      <webElementGuid>2fb441a9-9c72-40e5-a13b-e301f1273e29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
