<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__1</name>
   <tag></tag>
   <elementGuidId>6896a4d8-b905-4d8f-a675-73e20b6fddd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='grid#C377#15,5#bt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1c5809df-6e1c-4c67-abf6-6215bf646f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ffe3a504-30f8-4796-b768-6e987b2614a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grid#C377#15,5#bt</value>
      <webElementGuid>8a9bedee-388a-4c83-a708-9f7735a92e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>B</value>
      <webElementGuid>ef3a50c9-4059-40ca-8e76-78d613d6d634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;x&quot;:0,&quot;3&quot;:&quot;100%&quot;,&quot;4&quot;:&quot;Omitir&quot;,&quot;9&quot;:true,&quot;11&quot;:&quot;https://saps4-pre.abertis.com/sap/public/icmandir/its/ls/theming/UR/c2/sap_belize/svg/libs/SAPGUI-icons.svg#s_b_anwe&quot;,&quot;20&quot;:true}</value>
      <webElementGuid>7856f189-dc2c-420a-9e2b-96fefaf201b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Press&quot;:[{},{&quot;0&quot;:&quot;GuiGridView&quot;,&quot;id&quot;:&quot;C377&quot;,&quot;st&quot;:&quot;bt&quot;}]}</value>
      <webElementGuid>b6758401-21f3-4a15-9edc-e1cc7cdce8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b0267444-62f1-42ef-966f-3d787d8d9bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Omitir</value>
      <webElementGuid>ce74213d-ba57-41e5-ac68-885ca01a22f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Omitir</value>
      <webElementGuid>2a869595-3301-4099-a9a3-f2aefb9b4b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8a4af73b-d98f-4f6a-abee-8ea4ded017e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8ff281f2-3122-4803-9042-30c55c0ce549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsControl--explicitwidth lsControl--fullwidth lsButton lsButton--base lsButton--overflow urNoUserSelect urBtnRadius lsButton--onlyImage lsButton--active lsButton--focusable lsButton--up lsButton--design-standard lsButton--hoverable</value>
      <webElementGuid>54ce3c02-e772-4156-a9e2-c0326b81da0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-style</name>
      <type>Main</type>
      <value>;padding-left:0px;padding-right:0px</value>
      <webElementGuid>adc89d1b-e3cb-4cfd-bad0-fd946b969955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>104969b8-cc1c-4725-9fed-99f7c4fb2bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid#C377#15,5#bt&quot;)</value>
      <webElementGuid>1eb4132a-fa49-411f-9041-a66acacdbce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VIM Creacion factura sin pedido sin diferencias/Page_Proceso Gestin de facturas sin pedido _193606/iframe_Ms_application-zgui_opt_vim_wp-displ_b9e7ed</value>
      <webElementGuid>02c88237-77df-4724-8d2f-4a19955c41e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='grid#C377#15,5#bt']</value>
      <webElementGuid>0465ee1a-470c-4c00-8eae-6fac9e4c318f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='grid#C377#15,5']/div/div</value>
      <webElementGuid>51312c9b-56a1-4578-90cd-54e636cae2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprobar información fiscal (Sin pedido)'])[1]/following::div[5]</value>
      <webElementGuid>6b84d8bb-58c6-42cf-85ee-3b94d12f5376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprobar datos contables ES'])[1]/following::div[12]</value>
      <webElementGuid>0905058e-9feb-47fd-a53c-66ae4b685033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[4]/preceding::div[7]</value>
      <webElementGuid>bb2a74cb-5906-40c2-873e-8e739927754e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td[5]/div/div</value>
      <webElementGuid>e8c33a48-469c-4602-8577-f9b8fa8ab58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'grid#C377#15,5#bt' and @title = 'Omitir' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>473f552e-689b-493f-8e9e-330a08645db5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
