<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Debe_InputField_1</name>
   <tag></tag>
   <elementGuidId>c790f948-06c3-4c43-8d5c-f05d40f3a9ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M0:46:1:2:1:2B257:1:2B258:1[1,15]_c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa1bc27d-3db3-4f1d-9ff1-6cf090971817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>CBS</value>
      <webElementGuid>8371dd9e-c05d-49d2-9829-f17df13ad2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;1&quot;:&quot;FREETEXT&quot;,&quot;2&quot;:false,&quot;3&quot;:&quot;M0:46:1:2:1:2B257:1:2B258:1::1:15_TALB&quot;,&quot;5&quot;:&quot;16099&quot;,&quot;7&quot;:true,&quot;12&quot;:true,&quot;14&quot;:&quot;SERVER&quot;,&quot;16&quot;:true,&quot;20&quot;:false,&quot;21&quot;:&quot;{\&quot;SID\&quot;:\&quot;wnd[0]/usr/subSUB_MAIN:/OPT/SAPLVIM_IDX_UI:1001/subSUB_TAB_STRIP:/OPT/SAPLVIM_IDX_UI:1002/tabsTAB_MAIN/tabpTAB2/ssubTAB_MAIN_SUBSCREEN:/OPT/SAPLVIM_IDX_UI:1200/tabsTAB_SUB/tabpSUB_TAB2/ssubTAB_SUB_SUBSCREEN:/OPT/SAPLVIM_IDX_UI:1210/tbl/OPT/SAPLVIM_IDX_UITCTRL_ITEM_1210/ctxt/OPT/CIDX_ITEMS-KOSTL[14,0]\&quot;,\&quot;Type\&quot;:\&quot;GuiCTextField\&quot;,\&quot;value\&quot;:\&quot;16099\&quot;,\&quot;maxlen\&quot;:10,\&quot;focusable\&quot;:\&quot;X\&quot;,\&quot;showTypeAhead\&quot;:\&quot;true\&quot;}&quot;,&quot;23&quot;:&quot;&quot;,&quot;25&quot;:&quot;FILL_FIXED_LAYOUT&quot;,&quot;32&quot;:&quot;&quot; }</value>
      <webElementGuid>37b59bc1-4ba2-4edd-a704-1fdd4c99343c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:2:1:2B257:1:2B258:1[1,15]_c</value>
      <webElementGuid>e15cce0e-a2ef-452a-8916-fb4f28126ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98c92e4f-d947-4592-8fe2-8c7fc8335d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>696dd311-dd6e-4ba9-b37f-391c317f884c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>deb67ec7-e105-4d67-8312-9dbd53bef2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>46bee63f-9a09-40de-8c42-e54b7afb944c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField__input</value>
      <webElementGuid>1cef2895-b454-4251-a51a-d0b5bc468814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>16099</value>
      <webElementGuid>a4222ff9-9c77-4171-b4c8-82e008544cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>8f742cbe-a439-47e3-b0c8-b4555d8cfc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>910ab4a8-c624-4e35-ac02-8ab3d9596895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value> ARIA_CB_F4Lookup_TUT</value>
      <webElementGuid>8176a411-c37e-4e05-a382-81531a9b0c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InputField</value>
      <webElementGuid>4c20f193-ee06-4534-9ede-8b677773a4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:2:1:2B257:1:2B258:1[1,15]_c&quot;)</value>
      <webElementGuid>41b8ea11-910d-4473-b371-572711f1c9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VIM Creacion factura sin pedido sin diferencias/Page_Proceso Gestin de facturas sin pedido _193606/iframe_Ms_application-zgui_opt_vim_wp-displ_b9e7ed</value>
      <webElementGuid>3c265cd4-ae9e-498e-80cb-a8a9970311ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M0:46:1:2:1:2B257:1:2B258:1[1,15]_c']</value>
      <webElementGuid>0ef86e27-3dd0-43b9-80b9-75226917cb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:2:1:2B257:1:2B258:1[1,15]_c-r']/input</value>
      <webElementGuid>fde05b56-9244-4dd7-825d-6d3e60f67b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[15]/div/span/input</value>
      <webElementGuid>6b42f30a-2953-450e-9699-bc7f60c975a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'M0:46:1:2:1:2B257:1:2B258:1[1,15]_c' and @type = 'text' and @name = 'InputField']</value>
      <webElementGuid>dc2d5da8-81e1-4898-8b13-be3a8b5156bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
