<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Acquisti</name>
   <tag></tag>
   <elementGuidId>221f7ecd-9631-425f-87c9-693055ac8780</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__item0-anchorNavigationBar-2 > div.sapUshellAnchorItemInner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Acquisti' or . = 'Acquisti')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c4052fb8-21e4-4c04-b85c-c1a3b4d4fc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUshellAnchorItemInner</value>
      <webElementGuid>2e2ab447-a486-4975-bdb2-497d4938b55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acquisti</value>
      <webElementGuid>8ef9c96d-4cdc-47d2-8ac3-79dc20342cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__item0-anchorNavigationBar-2&quot;)/div[@class=&quot;sapUshellAnchorItemInner&quot;]</value>
      <webElementGuid>1c44b729-8580-424d-860f-e75f1290cd7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='__item0-anchorNavigationBar-2']/div</value>
      <webElementGuid>2b67fada-50a5-4a8d-a241-a2e6a5734679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approvazioni'])[1]/following::div[1]</value>
      <webElementGuid>b42d5e20-b352-4246-be59-a1de289debff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La mia pagina iniziale'])[1]/following::div[2]</value>
      <webElementGuid>e8b1e801-591b-45b8-8e45-87785c8aa51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrate Merci &amp; Verifiche'])[1]/preceding::div[1]</value>
      <webElementGuid>39a02837-ab4d-434c-9f7d-17334b26a06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scorri alla fine'])[1]/preceding::div[2]</value>
      <webElementGuid>99eac52c-4eb5-4267-9195-c3b406df3523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Acquisti']/parent::*</value>
      <webElementGuid>bdbe62a2-ef07-41e6-a766-0309e0431a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div</value>
      <webElementGuid>b858a1f5-91c7-4062-b5ca-e5fd08a51a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Acquisti' or . = 'Acquisti')]</value>
      <webElementGuid>f6cadaab-d03d-46c8-a1ab-03e091ca7abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='__item2-anchorNavigationBar-2']/div</value>
      <webElementGuid>1fc67398-1093-4470-b752-2ebf9ef39bc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
