<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_200100050680</name>
   <tag></tag>
   <elementGuidId>a239189e-e3b7-4104-8a5c-7f1a7e759742</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__text134-__clone100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__text134-__clone100']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e1932797-dbc2-4b78-8615-e1107251951d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text134-__clone100</value>
      <webElementGuid>2f0e6fd0-dbe4-4b36-9324-b4350e703755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text134-__clone100</value>
      <webElementGuid>22fb9efd-93e6-4e0e-b562-26b722b265b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>751cf4cd-590c-4aa8-bbe1-55c4083616f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextBreakWord sapMTextMaxWidth</value>
      <webElementGuid>6a2795d1-2215-4c0f-8c67-5d0ccf136608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>200100050680</value>
      <webElementGuid>3b8a8ff7-1fc9-45c2-a331-9f56b96f3e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text134-__clone100&quot;)</value>
      <webElementGuid>f951bb0f-305a-4bf8-82ef-d4ed5767f286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__text134-__clone100']</value>
      <webElementGuid>809c27b0-bb1c-4454-8d0e-81256b085a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='__item10-__clone100-cell0']/span</value>
      <webElementGuid>7aeaefa1-6f87-41c4-80d1-c7686ed15ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pto. Trabajo Ejec.'])[2]/following::span[1]</value>
      <webElementGuid>7b43920d-d79c-4361-9a10-59836540a673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desc. Emplazamiento'])[1]/following::span[2]</value>
      <webElementGuid>b57cc277-a4fb-4857-809d-61908df98662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ABIE DMNV KKMP'])[1]/preceding::span[1]</value>
      <webElementGuid>cd57bb0d-24a0-4b94-82a2-772a6db287b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Esazione Settimanale - Primo Tronco'])[1]/preceding::span[2]</value>
      <webElementGuid>9182cd08-21a3-41dc-bb09-ec4ce33137d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='200100050680']/parent::*</value>
      <webElementGuid>18bc1f64-5d03-4b8c-beec-00ead8131562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/span</value>
      <webElementGuid>ff6f5224-f7a1-49cd-a598-cb4fa6ad60da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__text134-__clone100' and (text() = '200100050680' or . = '200100050680')]</value>
      <webElementGuid>617b48e2-f1ec-4e71-a0db-883eb195c01d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
