<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rilasciato___xmlview2--iliberado-switch</name>
   <tag></tag>
   <elementGuidId>56215d03-b54a-4c22-a5f3-aa4e20414c01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id, '--iliberado') and @role='switch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview2--iliberado-switch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1bdcf6a3-d7a7-4677-8bb7-7f39312571e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview2--iliberado-switch</value>
      <webElementGuid>b936502f-7e28-4d75-a952-a0e695d62eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>38443d23-1f15-46d0-a38c-46fe2546611b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSwt sapMSwtTrans sapMSwtOff sapMSwtAcceptReject sapMSwtHoverable sapMSwtPressed</value>
      <webElementGuid>b94a0867-a471-4718-827a-0ce7e8fd7f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview2--iliberado-switch&quot;)</value>
      <webElementGuid>0b8c7a59-c2e1-40bb-8eeb-4833908cbefe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__xmlview2--iliberado-switch']</value>
      <webElementGuid>5907888b-12f9-4228-88df-35735855f676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__xmlview2--iliberado']/div</value>
      <webElementGuid>60f37f23-7d9f-4169-896b-ed51096cf029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rilasciato'])[1]/following::div[3]</value>
      <webElementGuid>9fc9e522-6cf2-4618-822c-1da1116b07fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ info'])[1]/following::div[6]</value>
      <webElementGuid>684f350a-830e-459d-bad9-3ffc4c5deb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passo 3'])[1]/preceding::div[6]</value>
      <webElementGuid>d56ba60d-5089-4186-8245-df96781b3426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div</value>
      <webElementGuid>54cf96bc-f3a9-450b-a699-427f014a7eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__xmlview2--iliberado-switch']</value>
      <webElementGuid>ce41ab5a-db30-44c9-89a8-4885953a550b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
