<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Equipment___xmlview2--smartFilterBar-_a4e3ed</name>
   <tag></tag>
   <elementGuidId>3c1ec498-8f3d-494a-afdd-232ed4fc8fdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, '--smartFilterBar-filterItemControlA_-Equnr-inner')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview2--smartFilterBar-filterItemControlA_-Equnr-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebd0348c-fd16-4317-97c2-7ddeddf937ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview2--smartFilterBar-filterItemControlA_-Equnr-inner</value>
      <webElementGuid>136ef1bd-77ad-49db-984d-c04b7d7637d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>bb4beb6c-c6f6-42c5-b599-1fd56d783398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__xmlview2--smartFilterBar-filterItem-EquipmentSet-Equnr</value>
      <webElementGuid>b32535cf-e553-4984-8810-dcdea79aaaab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text274</value>
      <webElementGuid>5f9916fc-7e74-4c2c-be66-41f9198d9c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>8a5de22b-46cc-40d3-9854-9df8fedf6eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-roledescription</name>
      <type>Main</type>
      <value>Inserimento multivalore</value>
      <webElementGuid>1d9dacf7-0827-407c-a21f-52fe326b904e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>00d66a63-0c0f-4f15-acc0-5a46f7ded96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a1dc4a81-eb1b-44ca-b8ff-89e36fede475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>5ca7895d-bafd-430f-82ee-afc74b2e60a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview2--smartFilterBar-filterItemControlA_-Equnr-inner&quot;)</value>
      <webElementGuid>c7f59a02-4987-4cf1-a141-53a97a813dad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__xmlview2--smartFilterBar-filterItemControlA_-Equnr-inner']</value>
      <webElementGuid>49c12569-ecc0-4346-9027-fd72dc8430e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__xmlview2--smartFilterBar-filterItemControlA_-Equnr-content']/input</value>
      <webElementGuid>8c5face9-db8d-425e-a684-0fdf3bc8d260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>5e7be625-b40a-4e8f-ae35-5e989d099b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '__xmlview2--smartFilterBar-filterItemControlA_-Equnr-inner' and @type = 'text']</value>
      <webElementGuid>a1b4c4ac-7a07-402b-9ab0-de5e91609a96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
