<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Ir</name>
   <tag></tag>
   <elementGuidId>c09af9eb-4baa-4c75-b283-133bf6fdde0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='com.abertis.mm.zmycontractslr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>92ca8044-4c7f-4be2-9b01-00b55a1aef41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>com.abertis.mm.zmycontractslr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo-inner</value>
      <webElementGuid>413b5343-f526-425e-b3e4-ec98eb7ef853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnInner sapMBtnHoverable sapMFocusable sapMBtnText sapMBtnEmphasized</value>
      <webElementGuid>a2510192-9fcf-402b-9233-285a75f08133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ir</value>
      <webElementGuid>fcfaf782-d60b-453b-a78a-ff9ab125df1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;com.abertis.mm.zmycontractslr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo-inner&quot;)</value>
      <webElementGuid>b6eb00ad-5a27-411c-862f-d4839e02b250</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='com.abertis.mm.zmycontractslr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo-inner']</value>
      <webElementGuid>396bd514-8291-48d4-b911-78f141df0c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='com.abertis.mm.zmycontractslr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo']/span</value>
      <webElementGuid>1da0e8f0-7997-4367-bf03-6e0d7f4a5d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material'])[1]/following::span[8]</value>
      <webElementGuid>fd85ff74-d15a-4a2f-8a94-6d36ca5169ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contrato'])[1]/following::span[15]</value>
      <webElementGuid>4ef82c8e-1cc6-491e-a3b3-47f8f1060c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adaptar filtros'])[1]/preceding::span[4]</value>
      <webElementGuid>dece513e-2d40-42f5-8d3e-37cc9619e9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/span</value>
      <webElementGuid>16915fe9-6a42-4ab8-863d-91422144dad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'com.abertis.mm.zmycontractslr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--listReportFilter-btnGo-inner' and (text() = 'Ir' or . = 'Ir')]</value>
      <webElementGuid>2f48a4c0-bc33-4f54-bd52-5aa4e87f3836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
