<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Group</name>
   <tag></tag>
   <elementGuidId>73f8be39-9b66-4e4d-81c2-d946ab52105c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='com.abertis.mm.zmycontractslr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--template::IconTabFilter-Group']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e2adf72e-1fdb-4b75-b3f9-1c305c4e9a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMITBFilterWrapper</value>
      <webElementGuid>c56d9a34-5d76-41bd-917c-933ff88d8435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Group</value>
      <webElementGuid>46d4e96d-8890-4a5b-b842-9b533b869253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;com.abertis.mm.zmycontractslr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--template::IconTabFilter-Group&quot;)/div[@class=&quot;sapMITBFilterWrapper&quot;]</value>
      <webElementGuid>5765705e-c409-4fce-9f8c-2b8da0ad573e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='com.abertis.mm.zmycontractslr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosContractLR--template::IconTabFilter-Group']/div</value>
      <webElementGuid>45758f3f-8725-4ec1-be3b-c3ec672ef3ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Propio'])[1]/following::div[4]</value>
      <webElementGuid>b28ccc13-42e6-4442-b445-f36c0ddb4b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anclar cabecera'])[1]/following::div[12]</value>
      <webElementGuid>813d6e52-de2a-4f77-a300-f80bba8df2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Más'])[2]/preceding::div[4]</value>
      <webElementGuid>298bf65e-27b5-4796-9207-de3107fad019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div[2]/div</value>
      <webElementGuid>f01b76c4-6d6c-483c-a8f0-e3921360e66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Group' or . = 'Group')]</value>
      <webElementGuid>0fe1a00d-deaa-4515-923b-a9aef57ddda9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
