<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Espaol</name>
   <tag></tag>
   <elementGuidId>a5e1d84a-86cb-4eda-a1aa-fb1dcc7066c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Español']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u41CB-second</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0b5e5aa-d9d8-4c2c-acd3-560560ae6392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u41CB-second</value>
      <webElementGuid>6d6d13fd-a0b5-4a2b-8ca4-4f311e533cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsListbox__value lsListbox__value--hover</value>
      <webElementGuid>f6027095-3213-44d0-9c58-74009bd2d586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemid</name>
      <type>Main</type>
      <value>u41CB</value>
      <webElementGuid>e7299e2d-8a31-4fb0-9bc1-8c27dd49a1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>786546a2-d907-41de-81d8-9614c2448d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>u41CB-ariaItemValues</value>
      <webElementGuid>0588b647-796f-4a5a-a2aa-f53d196c5228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Español</value>
      <webElementGuid>d30932dd-116c-4ab0-89df-7196a7cf86fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u41CB-second&quot;)</value>
      <webElementGuid>836911ff-ade8-4637-b1cb-804e75ec6b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BP Crear Cliente new/Page_Crear Organizacin Rol Cliente Datos Sociedad/iframe_Ms_application-BusinessPartner-creat_97ef72</value>
      <webElementGuid>394faf54-97bb-46e7-85d5-c094e17f2910</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='u41CB-second']</value>
      <webElementGuid>650e9905-59eb-4fae-a653-e8e2faab41e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ADDR1_DATA-LANGUSAPLSZA1-scrl']/div[2]/div[11]</value>
      <webElementGuid>76b6ef0d-3712-49cc-844c-9141c78f5de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inglés'])[1]/following::div[1]</value>
      <webElementGuid>d3d1baa4-67c2-47c8-b0c4-c049d32a3ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Griego'])[1]/following::div[2]</value>
      <webElementGuid>7abbdf0c-e83c-433b-9513-381037498037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estonio'])[1]/preceding::div[1]</value>
      <webElementGuid>6e45347c-55bb-4722-9de9-8fb37caad342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finlandés'])[1]/preceding::div[2]</value>
      <webElementGuid>85c68f67-6d43-421a-ae5c-2478ed072d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Español']/parent::*</value>
      <webElementGuid>5cf878cf-3126-4ce2-9d0e-3bf03ca46238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[11]</value>
      <webElementGuid>81f15a12-a117-4b19-a654-75a29ca1ddbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'u41CB-second' and (text() = 'Español' or . = 'Español')]</value>
      <webElementGuid>7caf5c8d-4d00-48f2-b3ce-7a98a91fcb35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
