<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Ms_application-BusinessPartner-creat_97ef72</name>
   <tag></tag>
   <elementGuidId>6a7f7a41-184f-43cd-8ff4-50dc3df76723</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='application-BusinessPartner-create-iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-BusinessPartner-create-iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b0b0bd7c-dc41-4788-9cb4-59494b15f225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-BusinessPartner-create-iframe</value>
      <webElementGuid>d0abad50-b2c1-427f-84a2-3aa8587a6ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-BusinessPartner-create-iframe</value>
      <webElementGuid>7868103f-ea11-4b7b-90a5-5226bb8f5cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application-BusinessPartner-create-iframe</value>
      <webElementGuid>6f3dcd62-8ec2-4a26-83bd-46aee27f28b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-orig-src</name>
      <type>Main</type>
      <value>/sap/bc/gui/sap/its/webgui;~sysid=R3Q;~service=3200?~transaction=BP&amp;sap-client=100&amp;sap-language=ES&amp;~nosplash=1&amp;sap-iframe-hint=GUI&amp;sap-ie=edge&amp;sap-theme=abertis_theme_corp%40https%3A%2F%2Fsaps4-pre.abertis.com%2Fsap%2Fpublic%2Fbc%2Fthemes%2F~client-100%2F~cache-FoBFe1cm.XhV1zLC6kMEvY1pkm4&amp;sap-touch=0&amp;sap-target-navmode=inplace&amp;sap-keepclientsession=2&amp;sap-ushell-timeout=25&amp;sap-shell=FLP1.120.28</value>
      <webElementGuid>a3b4abdd-c029-457e-a475-7f4766e51df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aplicación</value>
      <webElementGuid>b7776cad-8f7b-4040-aa40-84a4ceae55b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-iframe-idx</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>23701a90-1ec8-4945-ada6-11c549e179a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay ;battery ;camera ;display-capture ;geolocation ;gyroscope ;magnetometer ;microphone ;midi ;clipboard-write ;clipboard-read ;fullscreen ;serial ;</value>
      <webElementGuid>b2f1d984-0f49-48ee-aa6f-97674c6cd93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUShellApplicationContainer</value>
      <webElementGuid>36f11580-d03b-402a-9f35-2a755eb3a48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-BusinessPartner-create-iframe&quot;)</value>
      <webElementGuid>ec46f5f3-310f-4dda-a196-c8454f5d26fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='application-BusinessPartner-create-iframe']</value>
      <webElementGuid>50a341a1-f8ea-4dda-a3cd-f84d4185e654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-BusinessPartner-create']/iframe</value>
      <webElementGuid>ebdd3782-6df5-4d9b-be2b-e8ea31e6f4a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>27e70ac3-40d9-4cc4-8e29-f00ae8c30c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'application-BusinessPartner-create-iframe' and @name = 'application-BusinessPartner-create-iframe' and @title = 'Aplicación']</value>
      <webElementGuid>ac4a32c6-3693-4762-9995-8fab3a5fdc31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
