<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_C_InputField_1</name>
   <tag></tag>
   <elementGuidId>c92fe7c5-4870-4a88-bd49-0f13a619a727</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M0:46:1:1:2:2:1:2B256:1:13:1:1::1:22']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbae60d7-6664-4700-bfc4-e0f5408e18f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:1:2:2:1:2B256:1:13:1:1::1:22</value>
      <webElementGuid>13aa00e4-cd67-42c1-9aa5-8afba348f95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>CBS</value>
      <webElementGuid>84b511a8-c534-4587-bcdf-4f310f83cb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;x&quot;:0,&quot;1&quot;:&quot;FREETEXT&quot;,&quot;3&quot;:&quot;M0:46:1:1:2:2:1:2B256:1:13:1:1::1:22_TALB&quot;,&quot;7&quot;:true,&quot;13&quot;:&quot;C&quot;,&quot;14&quot;:&quot;SERVER&quot;,&quot;17&quot;:false,&quot;20&quot;:false,&quot;21&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/subSCREEN_3000_RESIZING_AREA:SAPLBUS_LOCATOR:2000/subSCREEN_1010_RIGHT_AREA:SAPLBUPA_DIALOG_JOEL:1000/ssubSCREEN_1000_WORKAREA_AREA:SAPLBUPA_DIALOG_JOEL:1100/ssubSCREEN_1100_MAIN_AREA:SAPLBUPA_DIALOG_JOEL:1101/tabsGS_SCREEN_1100_TABSTRIP/tabpSCREEN_1100_TAB_01/ssubSCREEN_1100_TABSTRIP_AREA:SAPLBUSS:0028/ssubGENSUB:SAPLBUSS:7016/subA05P01:SAPLBUA0:0400/subADDRESS:SAPLSZA1:0300/subCOUNTRY_SCREEN:SAPLSZA1:0301/txtADDR1_DATA-STREET&quot;,&quot;Type&quot;:&quot;GuiTextField&quot;,&quot;value&quot;:&quot;&quot;,&quot;maxlen&quot;:60,&quot;focusable&quot;:&quot;X&quot;},&quot;22&quot;:&quot;pstxt&quot;,&quot;29&quot;:&quot;M0:46:1:1:2:2:1:2B256:1:13:1:1::1:1&quot;}</value>
      <webElementGuid>55698528-0c0f-4bbe-903c-3616ad0e5f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Change&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Select&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Validate&quot;:[{},{}],&quot;DeleteItem&quot;:[{},{&quot;3&quot;:true}],&quot;ListAccess&quot;:[{&quot;ResponseData&quot;:&quot;delta&quot;,&quot;TransportMethod&quot;:&quot;full&quot;,&quot;EnqueueCardinality&quot;:&quot;none&quot;},{&quot;3&quot;:true,&quot;8&quot;:&quot;history&quot;,&quot;limitlen&quot;:&quot;X&quot;}],&quot;DoubleClick&quot;:[{},{&quot;1&quot;:&quot;action/2&quot;,&quot;2&quot;:true,&quot;3&quot;:true}],&quot;ClipboardTablePaste&quot;:[{},{&quot;0&quot;:&quot;GuiTextField&quot;,&quot;1&quot;:&quot;action/25&quot;,&quot;2&quot;:true,&quot;3&quot;:true}]}</value>
      <webElementGuid>1e73e297-7017-405e-8e92-73bc4954a879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cust-sid</name>
      <type>Main</type>
      <value>UIuNXKBrZvDhw+yR/BgfqA==</value>
      <webElementGuid>d01ffe56-d6ff-44bc-9765-6e251262223e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce6b7146-ebfc-4bd3-b57d-0f8a3319b828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>C</value>
      <webElementGuid>a34e036c-1cf2-4e97-8030-96f075faf38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>C</value>
      <webElementGuid>e0f52c87-e652-49af-b959-f13c073efa0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>26b630b8-da89-4e4d-8866-d6d53bf87049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>6133268e-f50c-43c2-935c-0cefe75aed0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cfa59f0f-efeb-4d09-80fe-39a339774100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f95b9595-d9b0-4b28-a5c9-30c35fadbf3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Calle</value>
      <webElementGuid>a222bc2c-528f-42e3-812a-098f4a8a2ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField__input</value>
      <webElementGuid>c8a297bf-acef-48fd-8ada-3561ba17d82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>282d825b-e81f-497c-90d3-d6b62f04cb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>M0:46:1:1:2:2:1:2B256:1:13:1:1::1:1</value>
      <webElementGuid>e0335ea1-7094-43cf-b9c2-0004d4ca9966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InputField</value>
      <webElementGuid>b39b0146-5cd8-4fb0-90d1-7ced4af74768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:1:2:2:1:2B256:1:13:1:1::1:22&quot;)</value>
      <webElementGuid>c420fcdd-524b-4dab-8fb8-16a0b4bfc055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BP Crear Cliente new/Page_Crear Organizacin Rol Cliente Datos Sociedad/iframe_Ms_application-BusinessPartner-creat_97ef72</value>
      <webElementGuid>fc5a2c10-7bb9-41d5-b09e-7878ed22a07c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M0:46:1:1:2:2:1:2B256:1:13:1:1::1:22']</value>
      <webElementGuid>53b8ed53-e714-4bc3-b72d-8849dc21c533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='M0:46:1:1:2:2:1:2B256:1:13:1:1::1:22-r']/tbody/tr/td/input</value>
      <webElementGuid>cf0e0643-fb7e-4110-a320-62f1c5cb7388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>1531094d-6a6a-4411-8773-8bce26dc823a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'M0:46:1:1:2:2:1:2B256:1:13:1:1::1:22' and @type = 'text' and @title = 'Calle' and @name = 'InputField']</value>
      <webElementGuid>e6bb3e66-11ba-4234-84e9-85e22f3f8f34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
