<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_I_M046112212B256113111122-btn</name>
   <tag></tag>
   <elementGuidId>7f54fafa-1402-4692-9506-d041ad5632bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:1:1:2:2:1:2B256:1:13:1:1::11:22-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9e537e76-e7cc-4d82-b2e9-0e86b48ea08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:1:2:2:1:2B256:1:13:1:1::11:22-btn</value>
      <webElementGuid>eec93fff-075e-4ae6-bc0e-3a35deb22c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField__help</value>
      <webElementGuid>8525f73e-7454-4a9b-b409-d4e7fd77a232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>26b9a6d5-5677-4759-a372-91e3736f4e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>08587884-b5ba-45b2-bbb9-f8c7fc8208fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:1:2:2:1:2B256:1:13:1:1::11:22-btn&quot;)</value>
      <webElementGuid>046a4680-f6cf-4708-87d1-d46891be6277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BP Crear Cliente new/Page_Crear Organizacin Rol Cliente Datos Sociedad/iframe_Ms_application-BusinessPartner-creat_97ef72</value>
      <webElementGuid>3dc69fcd-e9a9-4fb4-8548-d5feb0e74673</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:1:2:2:1:2B256:1:13:1:1::11:22-btn']</value>
      <webElementGuid>b4ff290f-554b-4e33-a0a3-ffed0b7a71ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='M0:46:1:1:2:2:1:2B256:1:13:1:1::11:22-r']/tbody/tr/td[2]/span</value>
      <webElementGuid>2af6ff86-657d-4014-a43f-4799bd4ac21b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div[2]/table/tbody/tr/td[2]/span</value>
      <webElementGuid>29817361-3848-49f0-a5d1-a43e1a251b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'M0:46:1:1:2:2:1:2B256:1:13:1:1::11:22-btn']</value>
      <webElementGuid>7d6513a5-0c1b-4ab8-8cbd-e313ebe92054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
