<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Seleccin de fila desactivada_InputField</name>
   <tag></tag>
   <elementGuidId>8a1353df-9310-43a0-90b7-749ebd51b348</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M0:46:2:3B256:2:2[1,2]_c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d213b940-aa1a-456b-be7a-f188defdc638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>CBS</value>
      <webElementGuid>15cfb66b-2516-4fa0-a56f-7df730dcc166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;1&quot;:&quot;FREETEXT&quot;,&quot;2&quot;:false,&quot;3&quot;:&quot;M0:46:2:3B256:2:2::1:2_TALB&quot;,&quot;7&quot;:true,&quot;12&quot;:true,&quot;14&quot;:&quot;SERVER&quot;,&quot;16&quot;:true,&quot;20&quot;:false,&quot;21&quot;:&quot;{\&quot;SID\&quot;:\&quot;wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\\\\01/ssubSUBSCREEN_BODY:SAPMV45A:4400/subSUBSCREEN_TC:SAPMV45A:4900/tblSAPMV45ATCTRL_U_ERF_AUFTRAG/ctxtRV45A-MABNR[1,0]\&quot;,\&quot;Type\&quot;:\&quot;GuiCTextField\&quot;,\&quot;value\&quot;:\&quot;\&quot;,\&quot;ctmenu\&quot;:true,\&quot;maxlen\&quot;:40,\&quot;focusable\&quot;:\&quot;X\&quot;,\&quot;showTypeAhead\&quot;:\&quot;true\&quot;}&quot;,&quot;23&quot;:&quot;&quot;,&quot;25&quot;:&quot;FILL_FIXED_LAYOUT&quot; }</value>
      <webElementGuid>b04b4d3a-f962-4a58-ba2c-b7fa14c9e6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:2:3B256:2:2[1,2]_c</value>
      <webElementGuid>1a725078-725a-47fc-b1d0-46c6068b6832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f74387a-3791-4db8-a1da-aac59804e132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8a22b033-635b-41ba-bd8a-105feef2ca31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5ff1f61e-dc79-4ca6-9fba-d156e6c0a5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>84842ec2-65a4-47ae-ae07-5f7ecfcdcedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField__input</value>
      <webElementGuid>a5709fc4-17ca-4826-9c44-c53e6ace06ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>9f4c3351-da5f-4489-946b-44bc1763cd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3c776aac-7d8d-4617-915a-62adb206bb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value> ARIA_CB_F4Lookup_TUT</value>
      <webElementGuid>49f70bb1-9e7b-4a86-9ebd-fca85a47502a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InputField</value>
      <webElementGuid>f189c64f-bcfd-47ec-bc39-361f16ccf481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:2:3B256:2:2[1,2]_c&quot;)</value>
      <webElementGuid>5eea8daa-113f-4de5-81f5-6804fa744c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SD Creacion pedido/Page_Crear Pedido Resumen/iframe_Ms_application-SalesDocument-create-iframe</value>
      <webElementGuid>78d3d9f5-4e2c-4ece-9b3a-205f9af1ea78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M0:46:2:3B256:2:2[1,2]_c']</value>
      <webElementGuid>ec6359f7-c71e-458f-86bc-d2a11faadf5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='M0:46:2:3B256:2:2[1,2]_c-r']/input</value>
      <webElementGuid>dbccd4ac-1ae9-41d2-aa5e-4ec164169804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/input</value>
      <webElementGuid>827843f6-61cc-4116-991b-8ec6830c1f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'M0:46:2:3B256:2:2[1,2]_c' and @type = 'text' and @name = 'InputField']</value>
      <webElementGuid>6e887dd8-5e95-490b-ae98-83ef832a4094</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
