<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_D_M04623B256221,9_c-r</name>
   <tag></tag>
   <elementGuidId>086e21ea-8956-4d62-af45-2e1fd97db905</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:2:3B256:2:2[1,9]_c-r']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>30d2b66a-a6eb-4692-a030-69404e8cd387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:2:3B256:2:2[1,9]_c-r</value>
      <webElementGuid>4b4a376c-1c2b-4d0b-87a1-d1c2cd5894a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField lsField--empty lsField--table lsField--monospace lsField--hasellipsis lsField--list lsField--hpif lsField--interactiontarget lsField--endofline lsField--haslabelfor</value>
      <webElementGuid>0888b2b0-9cdf-480c-81bd-f1d2fe7af220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:2:3B256:2:2[1,9]_c-r&quot;)</value>
      <webElementGuid>81254a23-92dd-4f01-9b77-2c2668f5813a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SD Creacion pedido/Page_Crear Pedido Resumen/iframe_Ms_application-SalesDocument-create-iframe</value>
      <webElementGuid>6dac2b9f-588a-4127-b75d-f7ebba0009ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:2:3B256:2:2[1,9]_c-r']</value>
      <webElementGuid>dfe8ce97-73bf-4256-ac5e-e2b9e867af7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='M0:46:2:3B256:2:2[1,9]']/div/span</value>
      <webElementGuid>6cf04c66-6c23-433c-9fde-060bdab9ad8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D'])[3]/following::span[3]</value>
      <webElementGuid>c2cd18bb-ebe9-4862-aea5-3f73f5f2db5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAD'])[1]/following::span[5]</value>
      <webElementGuid>b6e795cb-bf61-468d-b812-a236a9323487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EUR'])[1]/preceding::span[3]</value>
      <webElementGuid>dab059d2-3323-4ef2-9385-a74ed48c0205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UN'])[2]/preceding::span[9]</value>
      <webElementGuid>33290093-8590-48d8-be02-c062c972998a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/span</value>
      <webElementGuid>65aac7c5-75c0-4062-af04-09d0737a22a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'M0:46:2:3B256:2:2[1,9]_c-r']</value>
      <webElementGuid>512ec246-7ab7-4ed4-b8be-36d0643556db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
