<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pedido 95206 se ha grabado</name>
   <tag></tag>
   <elementGuidId>8fb3f20f-e896-486a-86bb-d2bb60f97507</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='wnd[0]/sbar_msg-txt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>42055b27-b706-4672-add7-67df8f4c7ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>12986ae7-8660-435c-980c-aaa927bc4111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>39720c07-0759-4be4-b041-fc2bc4b65d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wnd[0]/sbar_msg-txt</value>
      <webElementGuid>50beebf9-7c7c-4548-bf9d-10afe9bd32d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsMessageBar__text lsMessageBar__text--overflow</value>
      <webElementGuid>805f718f-00bc-46ce-8bee-1175fd7ce22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pedido 95206 se ha grabado.</value>
      <webElementGuid>f12bf204-09ce-4f93-9932-3ae68bff4805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pedido 95206 se ha grabado.</value>
      <webElementGuid>db34bfa0-e6d2-4692-92ac-abe17f7d1ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wnd[0]/sbar_msg-txt&quot;)</value>
      <webElementGuid>b110b98c-86ce-4bf1-af3b-0e3683b33524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SD Creacion pedido/Page_Crear Pedido Resumen/iframe_Ms_application-SalesDocument-create-iframe</value>
      <webElementGuid>9707f235-e31e-401c-b1a4-753f6cbdad19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='wnd[0]/sbar_msg-txt']</value>
      <webElementGuid>1a43e681-7cca-4e84-8b3d-e28760248a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wnd[0]/sbar_msg']/span[2]</value>
      <webElementGuid>4cd803c1-96c6-49a2-8119-3dd0486e92cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vacía'])[3]/following::span[19]</value>
      <webElementGuid>721525a9-6496-44b9-98c2-6b6bb2db7f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D'])[5]/following::span[44]</value>
      <webElementGuid>42eb64e3-27a9-4b95-b82f-7431ec4a88d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='G'])[2]/preceding::span[2]</value>
      <webElementGuid>017f73ed-aa16-41e0-ab0a-416c51042327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pedido 95206 se ha grabado.']/parent::*</value>
      <webElementGuid>89c828b4-436d-4b1a-8e8a-27a524fca170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/span[2]</value>
      <webElementGuid>87354345-1141-4c76-be1e-27a2b3e5dee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'wnd[0]/sbar_msg-txt' and @title = 'Pedido 95206 se ha grabado.' and (text() = 'Pedido 95206 se ha grabado.' or . = 'Pedido 95206 se ha grabado.')]</value>
      <webElementGuid>6159c567-173b-4c21-8a92-b44dc2fb7fdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
