<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ltimo trimestre</name>
   <tag></tag>
   <elementGuidId>ce98d283-6782-422f-9772-07192725481e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-StartDate-option-LASTQUARTER-titleText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-StartDate-option-LASTQUARTER-titleText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>79715c55-cb2d-45a5-af20-f209414493b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-StartDate-option-LASTQUARTER-titleText</value>
      <webElementGuid>fea13168-ef55-4b64-91fc-8d7c274a214e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>72021107-4f5a-4472-882e-81b40a88c689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Último trimestre</value>
      <webElementGuid>11ad7cdc-a0f9-4250-a45c-d0171846923d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-StartDate-option-LASTQUARTER-titleText&quot;)</value>
      <webElementGuid>95945fa9-defb-4737-b538-61d2ca4147d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-StartDate-option-LASTQUARTER-titleText']</value>
      <webElementGuid>237ce2de-3f05-42a0-afc6-a595278a6107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-StartDate-option-LASTQUARTER-content']/div/div/span</value>
      <webElementGuid>bd01f6b1-e0d1-4744-a695-0a8b70e8d23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Este trimestre'])[1]/following::span[1]</value>
      <webElementGuid>5dc0040a-22e1-4730-886b-988b65da3999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trimestres'])[1]/following::span[2]</value>
      <webElementGuid>4bb5f2ad-db05-4dd5-9898-2889dad708ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Próximo trimestre'])[1]/preceding::span[1]</value>
      <webElementGuid>8538f2cf-b3e1-4fc5-b12a-361b95c130c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primer trimestre'])[1]/preceding::span[2]</value>
      <webElementGuid>d36bd856-9ba9-4b51-af17-748b5bcefecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Último trimestre']/parent::*</value>
      <webElementGuid>2ea49654-a9e6-46a3-94a5-07816757520f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[26]/div/div/div/span</value>
      <webElementGuid>f6cfe60e-bb50-458f-a52f-cf2a104ab9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-StartDate-option-LASTQUARTER-titleText' and (text() = 'Último trimestre' or . = 'Último trimestre')]</value>
      <webElementGuid>a9ab178e-7734-43e4-abd6-a558e9bba2c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
