<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DOCUMENTOS DE MEDICIN___filter2-icon</name>
   <tag></tag>
   <elementGuidId>cd68f3d2-57d6-4a3c-8566-5fefa0e70d7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__filter2-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__filter2-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9925ce1e-1393-413d-8e53-ae926365671d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__filter2-icon</value>
      <webElementGuid>65449503-7027-4e18-ab1e-bf09c410a0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__filter2-icon</value>
      <webElementGuid>8dd0c4b9-9245-4786-91f7-411473169f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>dad2f6c9-1c12-49dc-8678-e5ee359a4c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7a3bd470-ffe4-4bca-ab66-91813070192a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>881badc4-4562-474f-818f-818104e80c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapMITBFilterIcon sapMITBBadgeHolder sapMITBFilterDefault</value>
      <webElementGuid>6de6f2a7-7ee4-459c-b391-3fafda97ea52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__filter2-icon&quot;)</value>
      <webElementGuid>799ab1ce-fae4-4783-86a7-f97eaa84a72c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__filter2-icon']</value>
      <webElementGuid>46da0489-9a22-415f-a4be-c6ed02aa022b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__filter2-tab']/span</value>
      <webElementGuid>0a89e977-5ce1-49d7-98f5-e6d1fb50872a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/span</value>
      <webElementGuid>9ee7c56a-58ea-4a42-b977-6f995cbd8e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__filter2-icon']</value>
      <webElementGuid>867b955c-3fa4-48bf-bd0b-2ae5466b7bdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
