<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Opciones_application-ZPM_SMART-ListEqu_e4de3f</name>
   <tag></tag>
   <elementGuidId>5c139c97-6ed6-4b9a-84cc-e153941aa59c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-ListEquip-component---main--smartTableEquipment-btnExcelExport-internalSplitBtn-textButton-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-ZPM_SMART-ListEquip-component---main--smartTableEquipment-btnExcelExport-internalSplitBtn-textButton-img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cc247ca3-28da-4533-a331-e3cd5b95b164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-ListEquip-component---main--smartTableEquipment-btnExcelExport-internalSplitBtn-textButton-img</value>
      <webElementGuid>34ad95c6-265c-4fe1-9382-a4febf6c73e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-ZPM_SMART-ListEquip-component---main--smartTableEquipment-btnExcelExport-internalSplitBtn-textButton-img</value>
      <webElementGuid>096bfeac-9cef-4e3c-81c1-8b3478b822af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>abbdbf7e-435a-4963-b698-511d46eecdcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6c5249f2-4b28-46c9-9683-9dcd4a8aee46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>62ed7d0c-1852-4a1f-b472-514d8973131f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapMBtnCustomIcon sapMBtnIcon sapMBtnIconLeft</value>
      <webElementGuid>46624f7a-a37a-4869-b99a-ca554aa6632d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-ListEquip-component---main--smartTableEquipment-btnExcelExport-internalSplitBtn-textButton-img&quot;)</value>
      <webElementGuid>f085deb9-5d56-45de-9dd4-83a364a2d5c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-ListEquip-component---main--smartTableEquipment-btnExcelExport-internalSplitBtn-textButton-img']</value>
      <webElementGuid>6ae8fcbe-3655-481d-bcf7-376b745aad67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-ListEquip-component---main--smartTableEquipment-btnExcelExport-internalSplitBtn-textButton-inner']/span</value>
      <webElementGuid>5544d416-d46c-4313-9b00-fc4cd37665ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/button/span/span</value>
      <webElementGuid>bbdd5193-477b-4ed6-af0e-bd906574f4ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-ZPM_SMART-ListEquip-component---main--smartTableEquipment-btnExcelExport-internalSplitBtn-textButton-img']</value>
      <webElementGuid>d7e1e1b7-09a7-490f-b2a3-9a2c23b862fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
