<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Creacin de rdenes Correctivo</name>
   <tag></tag>
   <elementGuidId>26696867-9333-4dca-8110-0adc044cd1a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__item2-allMyAppsView--sapUshellAllMyAppsDataSourcesList-11-titleText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__item2-allMyAppsView--sapUshellAllMyAppsDataSourcesList-11-titleText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2892e4a7-0062-4e8d-9b22-8dfa55affac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__item2-allMyAppsView--sapUshellAllMyAppsDataSourcesList-11-titleText</value>
      <webElementGuid>9a477d9b-53c0-4833-abb3-6d3b8f1706f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>e9e21dd9-425d-453f-8940-172febc27e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Creación de Órdenes Correctivo</value>
      <webElementGuid>12737657-8963-47e2-ae91-7c45a85817f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__item2-allMyAppsView--sapUshellAllMyAppsDataSourcesList-11-titleText&quot;)</value>
      <webElementGuid>6693c355-db7a-45f3-bff1-5219aa1462c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__item2-allMyAppsView--sapUshellAllMyAppsDataSourcesList-11-titleText']</value>
      <webElementGuid>f1f9611f-2822-4ce4-9ad2-5ba7bd5833f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__item2-allMyAppsView--sapUshellAllMyAppsDataSourcesList-11-content']/div/div/span</value>
      <webElementGuid>a40b4afd-89c2-4e32-891c-68cd55951ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compras'])[1]/following::span[1]</value>
      <webElementGuid>1bdb4b03-7a1e-4f96-996d-377458c5b522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autorización de gestor (X) - Contenido'])[1]/following::span[2]</value>
      <webElementGuid>3ae4179a-1f50-4d6b-9e4c-8cff8aac2cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excepciones Factura'])[1]/preceding::span[1]</value>
      <webElementGuid>4cc5183d-52c0-4254-a44c-10eaba7b8fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FI - Conformador Facturas'])[1]/preceding::span[2]</value>
      <webElementGuid>704df918-50f0-4129-83f7-3a3435395954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Creación de Órdenes Correctivo']/parent::*</value>
      <webElementGuid>dc74cb5e-d322-4aac-a668-1ef147e3adc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]/div/div/div/span</value>
      <webElementGuid>fba55ec4-f876-479b-89ec-51c9aedc853c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__item2-allMyAppsView--sapUshellAllMyAppsDataSourcesList-11-titleText' and (text() = 'Creación de Órdenes Correctivo' or . = 'Creación de Órdenes Correctivo')]</value>
      <webElementGuid>a5845a48-b3fe-4a70-bb3a-7148454eb844</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
