<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Combustibles Vehculos Tcnicos_InputField_PRCNETO</name>
   <tag></tag>
   <elementGuidId>cde49dba-0d3a-4ea2-b051-bc65d39bc766</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M0:46:1[1,8]_c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03ae2573-483e-4260-bac9-8320629e6162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>CBS</value>
      <webElementGuid>7782260c-d952-463b-b450-e6189d078052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;1&quot;:&quot;FREETEXT&quot;,&quot;2&quot;:false,&quot;3&quot;:&quot;M0:46:1::1:6_TALB&quot;,&quot;7&quot;:true,&quot;11&quot;:&quot;NUMERIC&quot;,&quot;14&quot;:&quot;SERVER&quot;,&quot;17&quot;:false,&quot;20&quot;:false,&quot;21&quot;:&quot;{\&quot;SID\&quot;:\&quot;wnd[0]/usr/tblSAPMM06ETC_0220/txtEKPO-KTMNG[5,0]\&quot;,\&quot;Type\&quot;:\&quot;GuiTextField\&quot;,\&quot;value\&quot;:\&quot;\&quot;,\&quot;halign\&quot;:\&quot;r\&quot;,\&quot;maxlen\&quot;:17,\&quot;i_state\&quot;:\&quot;e\&quot;,\&quot;focusable\&quot;:\&quot;X\&quot;}&quot;,&quot;23&quot;:&quot;&quot;,&quot;25&quot;:&quot;FILL_FIXED_LAYOUT&quot; }</value>
      <webElementGuid>1fb70554-dd92-49ed-82ff-86836b08efdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1[1,6]_c</value>
      <webElementGuid>ee23f205-1ca7-4c01-946d-d16502478191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f9c62b0-530a-4c07-8d7b-3bd60d500487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>309303c9-efd0-49eb-8533-8108b308f605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>938d63c1-af20-46be-a961-f5f3fb836760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e81f32d8-750d-46e3-8d2f-47bea942b7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>89eadb01-d674-482e-b04f-86e6ecf9f938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>165840ce-c3ef-4028-9bc9-319971da34c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField__input</value>
      <webElementGuid>afd92ca9-5a33-4708-99d9-01d1dfe482ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>bc8fc2fb-6fcb-4739-bc76-606ce36aded1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2a06c511-ef26-409f-b115-338f230c123a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InputField</value>
      <webElementGuid>308e3e89-d63a-4aac-8871-c8238f471b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1[1,6]_c&quot;)</value>
      <webElementGuid>8c20a293-0dd6-4cfb-8ec7-2da3a234268c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Contratos Autopistas/Page_Crear Pedido abierto  Resumen de posiciones/iframe_Ms_application-PurchaseContract-crea_3eec77</value>
      <webElementGuid>b8579660-dca9-453e-bea9-dda7fa524f7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M0:46:1[1,6]_c']</value>
      <webElementGuid>7c741800-10cb-4307-8815-030bb19fc15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1[1,6]_c-r']/input</value>
      <webElementGuid>d8123871-919f-438e-8c0f-c017b6400aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/input</value>
      <webElementGuid>c4f428a9-e13c-4f80-9c27-f6be5457078b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'M0:46:1[1,6]_c' and @type = 'text' and @name = 'InputField']</value>
      <webElementGuid>81e883f0-b6ba-46ac-b58f-608ba889eacc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
