<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UN_InputField</name>
   <tag></tag>
   <elementGuidId>5f19ef6d-a191-4939-83bf-d6a9fb48e04b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M0:46:1[1,8]_c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c27cb71-1a87-49c3-85a6-c3684e313c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>CBS</value>
      <webElementGuid>4947499b-45be-47d3-b398-ffa597610d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;1&quot;:&quot;FREETEXT&quot;,&quot;2&quot;:false,&quot;3&quot;:&quot;M0:46:1::1:8_TALB&quot;,&quot;7&quot;:true,&quot;11&quot;:&quot;NUMERIC&quot;,&quot;14&quot;:&quot;SERVER&quot;,&quot;17&quot;:false,&quot;20&quot;:false,&quot;21&quot;:&quot;{\&quot;SID\&quot;:\&quot;wnd[0]/usr/tblSAPMM06ETC_0220/txtEKPO-NETPR[7,0]\&quot;,\&quot;Type\&quot;:\&quot;GuiTextField\&quot;,\&quot;value\&quot;:\&quot;\&quot;,\&quot;halign\&quot;:\&quot;r\&quot;,\&quot;maxlen\&quot;:14,\&quot;i_state\&quot;:\&quot;e\&quot;,\&quot;focusable\&quot;:\&quot;X\&quot;}&quot;,&quot;23&quot;:&quot;&quot;,&quot;25&quot;:&quot;FILL_FIXED_LAYOUT&quot; }</value>
      <webElementGuid>494009f0-5541-4f05-a12d-d8d42dad9f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1[1,8]_c</value>
      <webElementGuid>77e0bedf-7552-4f29-a2a9-796c92698888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93bfa680-cc3f-4d1d-9675-cb6a70658eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4cbe0e23-d30e-443c-ace6-9e0c0e8336fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>1a5ab749-6a6f-4c32-adfb-535d63ff8466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ac2ca123-f0e7-4cac-a4f5-f091dce858af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>879bfaf6-4d4f-4601-bd10-15a0e108417b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>bf14bf45-0248-40f2-b855-8d767522b78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField__input</value>
      <webElementGuid>d7e3112d-1d6c-4cb4-b19b-5bd4897f7494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>57d16634-87fe-4895-908f-8946e9e79c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5c69bb7e-978c-46d8-b797-37bb2f94e6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InputField</value>
      <webElementGuid>34bc3826-f390-4d87-a1ef-c4f17fc0de6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1[1,8]_c&quot;)</value>
      <webElementGuid>85f8024d-b7a0-40c6-9680-7a9353a9d552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Contratos Autopistas/Page_Crear Pedido abierto  Resumen de posiciones/iframe_Ms_application-PurchaseContract-crea_3eec77</value>
      <webElementGuid>42cd4cb6-c904-4921-8d4c-4e778b74953d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M0:46:1[1,8]_c']</value>
      <webElementGuid>bb0fbe6c-870c-4bf8-b332-93c9362ebfbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1[1,8]_c-r']/input</value>
      <webElementGuid>2064230b-52a3-4de2-a279-b32df8d4f4dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/input</value>
      <webElementGuid>6cd299ba-7704-4892-8672-2aa382b57e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'M0:46:1[1,8]_c' and @type = 'text' and @name = 'InputField']</value>
      <webElementGuid>d38a7638-7a1d-4361-a6c6-332344eacf89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
