<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ty.txteTxteSuite txtStatutCommentaires _ce8de2</name>
   <tag></tag>
   <elementGuidId>b713d325-c755-4288-ba78-5760826588a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:46:::4:0-scrl-cnt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e27c964d-4dae-4205-98f1-e004bbb78513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:::4:0-scrl-cnt</value>
      <webElementGuid>1833f853-3783-4762-aa4b-307a5c644809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsScrollArea__content lsScrollArea__content--height  urBorderBox lsScrollArea__content--position lsScrollArea__content--top</value>
      <webElementGuid>50ab2740-1db7-4e21-8d23-b0e2bde10009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ty.txteTxteSuite txtStatutCommentaires au approbateur</value>
      <webElementGuid>1d7f6b2d-5f79-40e1-93db-731e886ead3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:::4:0-scrl-cnt&quot;)</value>
      <webElementGuid>ddbcdaf7-47bf-4cb8-b25a-e41ad426c362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Contratos Sanef/Page_Crer Contrat  textes en-tte/iframe_Plus_application-PurchaseContract-cr_6ea6a7</value>
      <webElementGuid>14de6198-a784-474b-bb71-5dc6bd784a21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M0:46:::4:0-scrl-cnt']</value>
      <webElementGuid>97801b2d-e959-44d8-95c8-48b3791ed225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46:::4:0-scrl']/div</value>
      <webElementGuid>5f48014c-41a6-4728-bca7-6d41bcfa4bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[1]/following::div[3]</value>
      <webElementGuid>02638610-553c-40ca-aa99-f18d5db64c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/div/div</value>
      <webElementGuid>0f0ec356-e784-428d-bf01-f08b90e9203c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M0:46:::4:0-scrl-cnt' and (text() = 'Ty.txteTxteSuite txtStatutCommentaires au approbateur' or . = 'Ty.txteTxteSuite txtStatutCommentaires au approbateur')]</value>
      <webElementGuid>5f65ca32-d7b4-413d-869e-5ccfe483f32e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
