<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_C_M0461121021-btn</name>
   <tag></tag>
   <elementGuidId>29eceb17-d1cc-4f37-ad3d-b5b90c639c33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:1:1:2:1::0:21-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5d9985e9-d802-4eed-9fbf-865c5761a47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:1:2:1::0:21-btn</value>
      <webElementGuid>fb59ebb5-798a-4b81-932f-89a91d161bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField__help</value>
      <webElementGuid>e8bd8242-2bd2-4675-a2be-c6163ec8b58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8b584f51-cd4c-412a-9a17-1da927b0563f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>dcfc0f2b-b203-4c57-8f7d-750c7982b646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:1:2:1::0:21-btn&quot;)</value>
      <webElementGuid>074f808d-6143-4ba0-aeaa-e66b998ac2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BP Crear Proveedor New ID/Page_Crear Organizacin/iframe_Ms_application-BusinessPartner-creat_97ef72</value>
      <webElementGuid>1776c1ab-daeb-4e2a-93fe-5daa116f165d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:1:2:1::0:21-btn']</value>
      <webElementGuid>c61a59a6-7b31-48a7-88e6-96cb2df98ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='M0:46:1:1:2:1::0:21-r']/tbody/tr/td[2]/span</value>
      <webElementGuid>bbe12e51-842d-483a-a7ac-98e47b7c890d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/table/tbody/tr/td[2]/span</value>
      <webElementGuid>b1ad87e2-ece8-493f-9b38-389105a36297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'M0:46:1:1:2:1::0:21-btn']</value>
      <webElementGuid>5ba27409-d201-40ed-983f-74adf1358521</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
