<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_F110___xmlview4--standardTileContent-___a2a714</name>
   <tag></tag>
   <elementGuidId>31541396-3dac-49c9-b910-03cce9167ffe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__xmlview4--standardTileContent-__clone119']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview4--standardTileContent-__clone119</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>347e80db-57f8-44dc-9df3-8bdd65412358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview4--standardTileContent-__clone119</value>
      <webElementGuid>464acb63-6b8a-478e-8bc4-fe0df288ba71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__xmlview4--standardTileContent-__clone119</value>
      <webElementGuid>7a14ac67-f02b-4c00-a159-47457c2f0ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMTileCnt sapMFrameTypeAuto sapMGTNoPriority</value>
      <webElementGuid>8c8dfd1d-8f75-4773-b19c-b79c38bfc1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview4--standardTileContent-__clone119&quot;)</value>
      <webElementGuid>7efcb7b8-0294-4c38-a582-b212a905a1b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__xmlview4--standardTileContent-__clone119']</value>
      <webElementGuid>8de880a6-ccce-4d65-8d08-0d64ea3b7510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__tile142-content']/div</value>
      <webElementGuid>33142c74-aaa0-4b4b-aa72-2842b1379f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F110'])[3]/following::div[2]</value>
      <webElementGuid>a91bfd1a-d032-4f6e-8a77-00250a6c2881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parámetros para pagos autom.'])[1]/following::div[3]</value>
      <webElementGuid>f57944c6-19f7-4229-b99c-85682a1853d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Planif.automática programa pagos'])[1]/preceding::div[4]</value>
      <webElementGuid>2efdac12-ba6e-42e7-a77b-a76f634be632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div</value>
      <webElementGuid>13c3b948-28b7-4e6d-8d93-771508b59ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__xmlview4--standardTileContent-__clone119']</value>
      <webElementGuid>5ea1ff79-9375-4771-826a-f734b3226e78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
