<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ME31K___xmlview2--standardTileContent-__4ea92c</name>
   <tag></tag>
   <elementGuidId>c2acf623-8481-4864-a24f-1dc3200ff97f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__xmlview2--standardTileContent-__clone99</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__xmlview2--standardTileContent-__clone99']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>44fa5cdc-72a0-43d2-92b7-41872430a589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview2--standardTileContent-__clone99</value>
      <webElementGuid>69db9857-0389-41b3-a8c3-24087badc616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__xmlview2--standardTileContent-__clone99</value>
      <webElementGuid>0d675d0b-38a2-41bc-b915-374ad9905ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMTileCnt sapMFrameTypeAuto sapMGTNoPriority</value>
      <webElementGuid>a9d65a3d-3bb8-46ff-a73d-d97de326f012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview2--standardTileContent-__clone99&quot;)</value>
      <webElementGuid>d66d9dee-7174-4373-92cc-c0d100a69d9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__xmlview2--standardTileContent-__clone99']</value>
      <webElementGuid>1a869c79-8a5b-42ab-83db-4633c9ac11ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__tile6-content']/div</value>
      <webElementGuid>c306cea0-8bd4-435f-9128-9082db7f8d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ME31K'])[1]/following::div[2]</value>
      <webElementGuid>549eda07-095e-4962-88fc-56b514e491bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear pedido abierto'])[1]/following::div[3]</value>
      <webElementGuid>4fb6b41f-8834-4010-bb17-0b7b1dd6309c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temas de ayuda'])[1]/preceding::div[45]</value>
      <webElementGuid>11f9349b-d16c-4fa9-bda4-16b0255c2335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div</value>
      <webElementGuid>483c4c1f-138d-44d6-ae10-b10ba297c52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__xmlview2--standardTileContent-__clone99']</value>
      <webElementGuid>989b13d1-8e38-4c02-8271-580e99989a42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
