<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_F_InputField</name>
   <tag></tag>
   <elementGuidId>7580dd52-61ed-453f-824d-89f2276ec5e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M0:46:::1:34']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6972fd1-c60b-4d01-b810-733a3b9181fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:::1:34</value>
      <webElementGuid>9c2c14d2-1709-4d12-ae46-817935a1f5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>CBS</value>
      <webElementGuid>df9ea81c-5c2b-4c8b-b3ce-bf28088028a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;x&quot;:0,&quot;1&quot;:&quot;FREETEXT&quot;,&quot;3&quot;:&quot;M0:46:::1:34_TALB&quot;,&quot;7&quot;:true,&quot;11&quot;:&quot;NUMERIC&quot;,&quot;12&quot;:true,&quot;13&quot;:&quot;F&quot;,&quot;14&quot;:&quot;SERVER&quot;,&quot;16&quot;:true,&quot;20&quot;:false,&quot;21&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/ctxtS_BLDAT-LOW&quot;,&quot;Type&quot;:&quot;GuiCTextField&quot;,&quot;value&quot;:&quot;&quot;,&quot;ctmenu&quot;:true,&quot;maxlen&quot;:10,&quot;focusable&quot;:&quot;X&quot;},&quot;22&quot;:&quot;pstxt&quot;,&quot;29&quot;:&quot;M0:46:::1:2&quot;}</value>
      <webElementGuid>167d7a71-e82c-4341-a10b-591fb86aff1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Change&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Select&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Validate&quot;:[{},{}],&quot;DeleteItem&quot;:[{},{&quot;3&quot;:true}],&quot;ListAccess&quot;:[{&quot;ResponseData&quot;:&quot;delta&quot;,&quot;TransportMethod&quot;:&quot;full&quot;,&quot;EnqueueCardinality&quot;:&quot;none&quot;},{&quot;3&quot;:true,&quot;8&quot;:&quot;history&quot;,&quot;limitlen&quot;:&quot;X&quot;}],&quot;DoubleClick&quot;:[{},{&quot;1&quot;:&quot;action/2&quot;,&quot;2&quot;:true,&quot;3&quot;:true}],&quot;FieldHelpPress&quot;:[{},{&quot;1&quot;:&quot;vkey/4&quot;,&quot;2&quot;:true,&quot;5&quot;:true}],&quot;ClipboardTablePaste&quot;:[{},{&quot;0&quot;:&quot;GuiTextField&quot;,&quot;1&quot;:&quot;action/25&quot;,&quot;2&quot;:true,&quot;3&quot;:true}]}</value>
      <webElementGuid>b51a9375-5fa0-4822-a99a-e1878d2db666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cust-sid</name>
      <type>Main</type>
      <value>ao9OhYIuVKzSkTugli45eA==</value>
      <webElementGuid>6a238b03-2274-4db6-b627-da10d276ae00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b38c3c0d-4cb3-4457-a7ac-626a437fafc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>F</value>
      <webElementGuid>78bb14c5-6829-47e7-9b54-115d1a368159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>F</value>
      <webElementGuid>8c106b89-c473-4e32-82b6-cba493ef8ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2adc7592-eeb8-4cc5-97f3-14836eba69a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e6fdd502-7166-4531-b2a5-47c11ea60d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1d4e7fac-5874-43b4-885c-a114461dda91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a1b54c35-f0b9-4a96-9216-4b540a5a0aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Fecha de documento en documento</value>
      <webElementGuid>11e9e0ef-d965-4d35-820f-8d187d383c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>1dde4425-900a-4dd9-a713-d5a38fa91cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField__input</value>
      <webElementGuid>80dfe135-ef22-4a05-b3da-73c748281b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>84ca558b-0799-4d0b-87fd-11db2cca1afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a5612794-3abb-43be-8062-d173fa56af95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value> ARIA_CB_F4Lookup_TUT M0:46:::1:34-ariatooltip</value>
      <webElementGuid>8ce5f285-8853-4675-9f6a-bb976eb5108f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>M0:46:::1:2</value>
      <webElementGuid>cbcc91bd-081f-4d10-b2c1-a6633d95b96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InputField</value>
      <webElementGuid>3116ea5d-83dc-4694-a521-5b7cb50bc7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:::1:34&quot;)</value>
      <webElementGuid>aeef1cb4-5312-4797-9df4-5f1efc2d3a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VIM Creacion factura sin pedido sin diferencias/Page_VIM Analytics/iframe_Ms_application-zgui_opt_vim_wp-displ_b9e7ed</value>
      <webElementGuid>a4d70718-0a32-43aa-ba00-726ac836faf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M0:46:::1:34']</value>
      <webElementGuid>62524bf4-5a3d-46bd-b62d-a9c5d3f6bf54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='M0:46:::1:34-r']/tbody/tr/td/input</value>
      <webElementGuid>9dc7e5b0-f7c8-448f-ba05-a8d3cecb4770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>2bb25dff-5f81-4438-8904-618532d792a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'M0:46:::1:34' and @type = 'text' and @title = 'Fecha de documento en documento' and @name = 'InputField']</value>
      <webElementGuid>583202b7-6703-4d3a-a09e-dfca495985e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
