<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Datos Generales</name>
   <tag></tag>
   <elementGuidId>53a5bae4-a847-430c-871e-f736137475d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaseorder-displayContract-component---detail--ObjectPageLayout-anchBar-application-zpurchaseorder-displayContract-component---detail--general-anchor-BDI-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='application-zpurchaseorder-displayContract-component---detail--ObjectPageLayout-anchBar-application-zpurchaseorder-displayContract-component---detail--general-anchor-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>dcf89d4e-32ab-4e53-92bc-9e6dc9abf855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaseorder-displayContract-component---detail--ObjectPageLayout-anchBar-application-zpurchaseorder-displayContract-component---detail--general-anchor-BDI-content</value>
      <webElementGuid>f00642e7-b3b7-4954-a08c-4193e9fd24fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>a1281bf7-06f7-4f20-9544-9bf887cb65ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Datos Generales</value>
      <webElementGuid>beabaf15-54b5-41bd-98f2-183d3c737688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaseorder-displayContract-component---detail--ObjectPageLayout-anchBar-application-zpurchaseorder-displayContract-component---detail--general-anchor-BDI-content&quot;)</value>
      <webElementGuid>39305424-6844-44c4-8daf-31215d25df5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='application-zpurchaseorder-displayContract-component---detail--ObjectPageLayout-anchBar-application-zpurchaseorder-displayContract-component---detail--general-anchor-BDI-content']</value>
      <webElementGuid>d1652869-7035-4afb-bedf-fdf15eacb42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-zpurchaseorder-displayContract-component---detail--ObjectPageLayout-anchBar-application-zpurchaseorder-displayContract-component---detail--general-anchor-content']/bdi</value>
      <webElementGuid>dc86526d-5a8d-428e-ac01-a0f47af8bdf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desplazarse hacia la izquierda'])[1]/following::bdi[1]</value>
      <webElementGuid>7bf36224-5763-458f-b2e5-cc169e265588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desplegar cabecera'])[1]/following::bdi[1]</value>
      <webElementGuid>2f9b1198-a98a-485b-84db-14a0de5b7e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posiciones'])[3]/preceding::bdi[1]</value>
      <webElementGuid>df00ab6d-2e4a-4562-817a-1da2a4dcf033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estrategia Liberación'])[2]/preceding::bdi[2]</value>
      <webElementGuid>2e9550be-3fad-4e3f-94a3-3864276ad28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span/span/bdi</value>
      <webElementGuid>3e0a9e82-87cf-44d7-84ca-9f14476b0832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'application-zpurchaseorder-displayContract-component---detail--ObjectPageLayout-anchBar-application-zpurchaseorder-displayContract-component---detail--general-anchor-BDI-content' and (text() = 'Datos Generales' or . = 'Datos Generales')]</value>
      <webElementGuid>ae0f199c-fdba-4f8d-98fb-8ceaaa7ce206</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
