<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OK</name>
   <tag></tag>
   <elementGuidId>62acf3f6-fe73-4ae9-87b8-c6d1509cc00d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='UpDownDialogChoose']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#UpDownDialogChoose</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>906152a8-5bfc-410b-85d1-dc2f8f011077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5e6e7b1a-08fc-4f96-9e2a-5536cca18426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UpDownDialogChoose</value>
      <webElementGuid>97170073-a42d-47c2-afd8-be79f17502b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>B</value>
      <webElementGuid>9cf7e830-2a5f-4ab7-9c46-a7782989480a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;OK&quot;,&quot;2&quot;:&quot;TRANSPARENT&quot;,&quot;11&quot;:&quot;https://saps4-pre.abertis.com/sap/public/bc/themes/~client-100/~cache-EffUt0nnNFsxi7WxmjEKOoghmzc/UR/c2/sap_horizon/svg/libs/SAPGUI-icons.svg#s_s_okay&quot;,&quot;12&quot;:&quot;https://saps4-pre.abertis.com/sap/public/bc/themes/~client-100/~cache-EffUt0nnNFsxi7WxmjEKOoghmzc/UR/c2/sap_horizon/svg/libs/SAPGUI-icons.svg#s_s_okay&quot;,&quot;17&quot;:&quot;O&quot;,&quot;26&quot;:&quot; LS_Button31&quot; }</value>
      <webElementGuid>a8396898-33c4-42e4-8a43-795caa240a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>2ab4227a-99fb-415f-9bcc-739f4b56a671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>878b0c73-a173-42f9-896d-a3b8e5b819e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>O</value>
      <webElementGuid>65bd86b7-1fb8-4565-b3ce-c0a50041f0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>O</value>
      <webElementGuid>a188f5ac-0515-4b54-b91c-20457b467f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a44a83db-00ce-466c-b9fc-bdb1a7332854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2dbc3e78-9c61-48ce-9f03-46fc01a08f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsButton lsButton--base urNoUserSelect LS_Button31 urBtnRadius lsButton--active lsButton--focusable lsButton--up lsButton--design-transparent lsButton--hoverable</value>
      <webElementGuid>99a35aab-52d8-4277-97fe-10de8d4bf567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>4d6b8028-0bfa-4d1b-9837-c57df08d1571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UpDownDialogChoose&quot;)</value>
      <webElementGuid>5ed57e4e-e427-44b8-9173-4895173874f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cargar fichero zche pruebas/Page_Carga de Asientos contables va Excel/iframe_Ms_application-zgui_zche_mx-change-iframe</value>
      <webElementGuid>56c19e31-402b-4c95-90e1-f4d387bddabf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='UpDownDialogChoose']</value>
      <webElementGuid>b2d4c55d-8252-459c-8b2a-5c524c32be5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='webguiPopupWindow10000-footer']/div/div</value>
      <webElementGuid>4f45c0cc-876e-4d47-97fa-01d35b1bf693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*.*'])[2]/following::div[2]</value>
      <webElementGuid>a9eb7973-f093-4740-a675-323f574be82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*.*'])[1]/following::div[5]</value>
      <webElementGuid>0fa7ac0f-8163-4f71-b4be-24f4ef8fdc5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div</value>
      <webElementGuid>7571784e-59fe-4f95-8906-a86a0d877a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'UpDownDialogChoose' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>8bee26a8-424c-4f13-8de4-511223935ddb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
