<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Proveedor_application-zpurchaserequisi_797b13</name>
   <tag></tag>
   <elementGuidId>42c44fc6-20d4-4acf-ad7e-e394eeaeee13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-vhi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-vhi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5f266d83-87a9-4685-8f8e-fd208ce2b29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-vhi</value>
      <webElementGuid>5a212c60-b01f-44cb-b762-d92b00ef4a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-vhi</value>
      <webElementGuid>aa85a04f-cae9-46ce-b249-38e4e794b144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d2d5fb19-896a-4d69-bd5f-ec28aff09f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Mostrar ayuda para entradas</value>
      <webElementGuid>db8b7e29-5508-4163-9b59-ca667aaf09ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>6a2661f9-62bc-4642-8fde-e364ee31f260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapUiIconPointer sapMInputBaseIcon</value>
      <webElementGuid>6b209467-8353-4f56-a2a7-288eff51c66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-vhi&quot;)</value>
      <webElementGuid>b48bb6a6-b2f9-4b2a-9572-e8751c06d55b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-vhi']</value>
      <webElementGuid>4f0c7dfb-6acc-4f6e-8b30-5ced0b7507b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-content']/div/span</value>
      <webElementGuid>b7b355a9-cffe-48e0-9cfc-fbb40deadc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/span</value>
      <webElementGuid>98a08f84-887c-4de1-932d-5d9743a34405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-zpurchaserequisition-createMP-component---detail--idHVendorNumber-vhi']</value>
      <webElementGuid>d13e704d-ee8e-41f0-88cd-c60000d35d83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
