<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S_InputField</name>
   <tag></tag>
   <elementGuidId>13a8e77f-8d19-4780-a617-dc688499bd32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M0:46:1:1::0:17']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cad3c8e-b616-4dc5-965c-c61d44dfa09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:1::0:17</value>
      <webElementGuid>807dc030-26f0-4bbc-81bf-b45eefa3bd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>CBS</value>
      <webElementGuid>b6f6e4cf-dcf8-4cf1-afd2-17a2c0d3da6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;x&quot;:0,&quot;1&quot;:&quot;FREETEXT&quot;,&quot;3&quot;:&quot;M0:46:1:1::0:17_TALB&quot;,&quot;7&quot;:true,&quot;12&quot;:true,&quot;13&quot;:&quot;S&quot;,&quot;14&quot;:&quot;SERVER&quot;,&quot;16&quot;:true,&quot;20&quot;:false,&quot;21&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/subSUBSCREEN_HEADER:SAPMV45A:4021/subPART-SUB:SAPMV45A:4701/ctxtKUAGV-KUNNR&quot;,&quot;Type&quot;:&quot;GuiCTextField&quot;,&quot;value&quot;:&quot;&quot;,&quot;ctmenu&quot;:true,&quot;maxlen&quot;:10,&quot;focusable&quot;:&quot;X&quot;,&quot;showTypeAhead&quot;:&quot;true&quot;},&quot;22&quot;:&quot;pstxt&quot;,&quot;23&quot;:&quot;UNDERLINE&quot;,&quot;29&quot;:&quot;M0:46:1:1::0:0&quot;}</value>
      <webElementGuid>229c1aa8-f026-4180-97b5-db62f419e30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Change&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Select&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Validate&quot;:[{},{}],&quot;DeleteItem&quot;:[{},{&quot;3&quot;:true}],&quot;ListAccess&quot;:[{&quot;ResponseData&quot;:&quot;delta&quot;,&quot;TransportMethod&quot;:&quot;full&quot;,&quot;EnqueueCardinality&quot;:&quot;none&quot;},{&quot;3&quot;:true,&quot;8&quot;:&quot;typeahead&quot;,&quot;maxlen&quot;:0,&quot;parentid&quot;:&quot;PART-SUB:SAPMV45A:4701&quot;}],&quot;DoubleClick&quot;:[{},{&quot;1&quot;:&quot;action/2&quot;,&quot;2&quot;:true,&quot;3&quot;:true}],&quot;FieldHelpPress&quot;:[{},{&quot;1&quot;:&quot;vkey/4&quot;,&quot;2&quot;:true,&quot;5&quot;:true}],&quot;ActionItemActivate&quot;:[{},{&quot;1&quot;:&quot;vkey/0/ses[0]&quot;,&quot;2&quot;:true}],&quot;ClipboardTablePaste&quot;:[{},{&quot;0&quot;:&quot;GuiTextField&quot;,&quot;1&quot;:&quot;action/25&quot;,&quot;2&quot;:true,&quot;3&quot;:true}]}</value>
      <webElementGuid>93eac655-d9c4-4f22-a65a-1c655d79fe42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cust-sid</name>
      <type>Main</type>
      <value>UmN7VALAG/I2hGT9ZBXn9Q==</value>
      <webElementGuid>702e3b05-20b1-4c4c-808e-dea6a1b98eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b012e6b2-34ec-4b55-8c0d-4a589dbf7ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>4f425b4c-f7fc-43f2-b2a0-0ff6d8398a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>87187b9e-4b48-42db-af76-d083c79c2b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8628a032-a657-4d86-b496-b8a8f47642cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>55601da6-00d1-44e9-b291-8b5a5a27681b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1536d27e-f238-49bd-856a-b3e80974478a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Solicitante</value>
      <webElementGuid>b4c2ab1e-ed10-4a2a-96de-92ec6725fdb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField__input</value>
      <webElementGuid>5afe0242-6cc3-433f-bcaa-e624ec45f3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>9986a4d3-b943-4051-acd7-998ec8b0d688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>faa50a24-2731-4cb8-b17d-f6f32d54c8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value> ARIA_CB_F4Lookup_TUT M0:46:1:1::0:17-ariatooltip</value>
      <webElementGuid>6c11efbf-7580-44bd-9a2c-a476dca889ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>M0:46:1:1::0:0</value>
      <webElementGuid>4e1ce017-1f4c-48a6-8b3d-544c98a51cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InputField</value>
      <webElementGuid>ce0bd164-6d32-469d-b840-4247a8509cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:1::0:17&quot;)</value>
      <webElementGuid>e5bbc5cf-1f3f-4b90-8d88-4b0b21dbcfe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SDCreacion pedido todos los campos/Page_Crear Plan factu canti A4 Resumen/iframe_Ms_application-SalesDocument-create-iframe</value>
      <webElementGuid>4efba919-90c5-4e61-a402-c69886d4aeaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M0:46:1:1::0:17']</value>
      <webElementGuid>51aebf04-8658-45db-ba08-e7104d41dace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='M0:46:1:1::0:17-r']/tbody/tr/td/input</value>
      <webElementGuid>89770d66-d66a-41eb-955f-597a3dffc9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>f6339855-7186-464c-954b-327cddaf59e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'M0:46:1:1::0:17' and @type = 'text' and @title = 'Solicitante' and @name = 'InputField']</value>
      <webElementGuid>cec10221-74fa-483a-b075-9e4c41834337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
