<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cont.Resaltado</name>
   <tag></tag>
   <elementGuidId>1fad0b69-6fd4-4f66-808d-4596db7274a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:50::btn[0]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ffbce26-6240-4e95-8760-251cfef15598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7e7eb7eb-63b1-4434-adaa-370167eeecd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:50::btn[0]</value>
      <webElementGuid>701d5e09-685c-4a2c-870b-c18f84adad51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>B</value>
      <webElementGuid>38afa212-b24a-4b68-9733-5d69887a9c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;Cont.&quot;,&quot;2&quot;:&quot;EMPHASIZED&quot;,&quot;4&quot;:&quot;Cont. (Entrada)&quot;,&quot;17&quot;:&quot;C&quot;,&quot;18&quot;:&quot;ENTER&quot;,&quot;21&quot;:true,&quot;25&quot;:&quot;TOGGLE&quot;,&quot;27&quot;:{&quot;SID&quot;:&quot;wnd[0]/tbar[0]/btn[0]&quot;,&quot;Type&quot;:&quot;GuiButton&quot;,&quot;SubType&quot;:&quot;toolbar&quot;}}</value>
      <webElementGuid>bf83241e-4308-4063-80a4-f4d6c111cceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Press&quot;:[{},{&quot;0&quot;:&quot;GuiOkCodeButton&quot;,&quot;1&quot;:&quot;vkey/0/ses[0]&quot;,&quot;2&quot;:true}]}</value>
      <webElementGuid>c1dbbf04-2e13-41a0-8d5d-194a8c45ae9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>547e51da-c488-4ec9-b9df-0b81c2ccaadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cont. (Entrada)</value>
      <webElementGuid>56f98d80-1377-4b17-bd86-305ddfcce5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>C</value>
      <webElementGuid>a634f7a5-4181-4b69-97d2-9d5808fa3756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>C</value>
      <webElementGuid>22b7f5d6-2a5b-481a-aba6-9350e0baacc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a3ade7bd-3048-4e13-a8b8-93d9d6ee6279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e833ad4c-9d67-43a8-a04d-00fc2a03c83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsButton lsButton--base urNoUserSelect urBtnRadius lsButton--useintoolbar lsButton--active lsButton--focusable lsButton--up lsButton--design-emphasized lsButton--hoverable</value>
      <webElementGuid>9d51d5b6-e716-4c3a-bc25-ff07e0e5120f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toolbaritem-id</name>
      <type>Main</type>
      <value>M0:50::btn[0]-r</value>
      <webElementGuid>89e19d21-732a-48af-81b7-a21ec1fdb14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cont. Resaltado</value>
      <webElementGuid>7b142a6d-6b69-4743-b532-1889bc5dd602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:50::btn[0]&quot;)</value>
      <webElementGuid>4ca25d86-5212-415b-83f9-6ea3672296d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Creacion cuenta mayor/Page_Cta.mayor Visualizar Central/iframe_Ms_application-GLAccount-editGLAccou_e2c8b9</value>
      <webElementGuid>4fb725a3-7c72-4a07-9b83-b4e609531c29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M0:50::btn[0]']</value>
      <webElementGuid>c9fd59b9-9993-4852-b015-4f77b0dac7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='M0:50::btn[0]-r']/div</value>
      <webElementGuid>164923c8-76ef-4823-90ee-3c346178f3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nota de contabilidad'])[1]/following::div[18]</value>
      <webElementGuid>930b4535-3faa-4df2-8561-e5c81bc25f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ES'])[2]/following::div[19]</value>
      <webElementGuid>484f147f-d52b-439c-827b-1f843f283f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div</value>
      <webElementGuid>76011a78-0960-40ae-b28c-3bc50cb98f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M0:50::btn[0]' and @title = 'Cont. (Entrada)' and (text() = 'Cont. Resaltado' or . = 'Cont. Resaltado')]</value>
      <webElementGuid>4f8fbb3a-1717-4356-9cf3-97c4c86bc5e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
