<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Se crea el material 28440</name>
   <tag></tag>
   <elementGuidId>8f3ca138-c918-49fa-8db1-7f5c58d9790a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='wnd[0]/sbar_msg-txt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e3bbef05-8d61-43a0-a8f4-e9c477d5414c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>e5081cc1-310e-470e-8eb4-7102ba82a6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0fd69ce0-f886-4f04-a4a6-171a74550178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wnd[0]/sbar_msg-txt</value>
      <webElementGuid>4d71aa5e-9b96-4995-bb54-d2b93e5fbc6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsMessageBar__text lsMessageBar__text--overflow</value>
      <webElementGuid>7c636294-229f-4a24-a082-4f95c74dbc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Se crea el material 28440 .</value>
      <webElementGuid>5baef5bc-3a26-4ef3-9649-071dfd1016a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Se crea el material 28440 .</value>
      <webElementGuid>36fdc2aa-5559-45eb-8d8d-7c32a8ae9ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wnd[0]/sbar_msg-txt&quot;)</value>
      <webElementGuid>f51f592b-c4b2-4ce2-a192-3cbefd73b97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Creación Material/Page_Crear material (Acceso)/iframe_Ms_application-Material-create-iframe</value>
      <webElementGuid>fca94b69-067a-4a17-853f-93575a0b572e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='wnd[0]/sbar_msg-txt']</value>
      <webElementGuid>918a0f2c-567b-4fc0-9bf3-d11f0620912f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wnd[0]/sbar_msg']/span[2]</value>
      <webElementGuid>de89ab6f-2c69-43dd-b22f-f57cf385a5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[3]/following::span[3]</value>
      <webElementGuid>f82c6156-1c8c-404c-aabd-5e056f565033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[1]/preceding::span[2]</value>
      <webElementGuid>dcbbf0d7-b5f0-4795-a05d-0d59ca7a6c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Se crea el material 28440 .']/parent::*</value>
      <webElementGuid>a75076ec-cc47-47c3-bef0-7c45be00368b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/span[2]</value>
      <webElementGuid>c2f83884-27be-487e-8eb1-c781870bc57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'wnd[0]/sbar_msg-txt' and @title = 'Se crea el material 28440 .' and (text() = 'Se crea el material 28440 .' or . = 'Se crea el material 28440 .')]</value>
      <webElementGuid>c0f6ca0c-d5d6-42ef-9a14-a38a8ac8f059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
