<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_COPEC S.A. (4500857822)</name>
   <tag></tag>
   <elementGuidId>72ea1a5c-8e79-43c2-b023-24b7da4a3f8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__text149-__clone173</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__text149-__clone173']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4b489113-cbe2-43dd-a774-42540f4d37c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text149-__clone173</value>
      <webElementGuid>a25d9514-7dd1-457e-aa2b-659ce4ce2cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text149-__clone173</value>
      <webElementGuid>5eae892e-e576-4214-8120-263c6d8b1cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>d5185ee4-1664-4a34-b981-844a600a921e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextMaxWidth</value>
      <webElementGuid>f66d5897-96cc-4256-9614-720b51bad9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COPEC S.A. (4500857822)</value>
      <webElementGuid>b9a861bd-a202-4b47-bbe2-b83b5bece426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text149-__clone173&quot;)</value>
      <webElementGuid>52ecc41f-2ed9-445c-9a69-8c2794d71f4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__text149-__clone173']</value>
      <webElementGuid>38a0faa3-67cc-413f-b8df-5b863bcfccfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='com.abertis.mm.zgrdesdepo::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PEDIDOSCOMPRA--template:::ListReportTable:::QuickVariantSelectionXColumnListItem:::sQuickVariantKey::MisPedidos-__clone173-cell0']/span</value>
      <webElementGuid>fb3255ed-e519-43d0-a506-4123acf73d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Objeto Compra'])[1]/following::span[2]</value>
      <webElementGuid>7718e762-fad9-408e-929b-8a2bc9048b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visualizar'])[1]/following::span[4]</value>
      <webElementGuid>466c03ab-8a2c-4121-888a-40056edefc1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLP'])[1]/preceding::span[2]</value>
      <webElementGuid>ddab13f0-e6ab-4f93-af86-362836a771dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLP'])[2]/preceding::span[4]</value>
      <webElementGuid>c6b26767-ac40-4e29-b6d3-69579b8d24b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COPEC S.A. (4500857822)']/parent::*</value>
      <webElementGuid>ad02f50c-c417-4179-8924-bc6bb3a9dc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>fbedc58b-6ae3-4552-8dba-b0302c3762a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__text149-__clone173' and (text() = 'COPEC S.A. (4500857822)' or . = 'COPEC S.A. (4500857822)')]</value>
      <webElementGuid>f12696f8-2c79-41ee-970c-3cd6b391037c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
