<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Seleccin mltiple___xmlview18--myInbox_ba508b</name>
   <tag></tag>
   <elementGuidId>411004d2-4171-46b5-980a-2d6d0861ae23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, '--myInbox_SEARCH-I')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview18--myInbox_SEARCH-I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3858943-446e-4d4b-90a7-d4fe7ec2a9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview18--myInbox_SEARCH-I</value>
      <webElementGuid>ecf3b02c-d526-4d1b-9513-a76fe3148444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>056a24c2-cbcd-4835-97a3-4cdbc6688bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>6c81b6ce-05a9-4aa1-8cc6-367096698777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0313dafa-2d74-4240-b26e-052173c14ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>a444fcdd-4773-4b9c-8824-ed4eabd900fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text563 __text564</value>
      <webElementGuid>65881b7f-bcb8-467d-8062-eed2c52fdccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSFI</value>
      <webElementGuid>3bf0e0f3-0bc4-49a3-9394-f7d6abee1349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview18--myInbox_SEARCH-I&quot;)</value>
      <webElementGuid>a865dc51-44e2-4db4-a86b-f2fdce5f5d5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__xmlview18--myInbox_SEARCH-I']</value>
      <webElementGuid>e9f1fcdf-d357-4432-8b21-68d72978897e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='__xmlview18--myInbox_SEARCH-F']/input</value>
      <webElementGuid>b2be0e96-7e52-45bb-8461-6082718689a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/form/input</value>
      <webElementGuid>a943981c-3b46-480e-9a12-9079e66d4689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '__xmlview18--myInbox_SEARCH-I' and @type = 'search' and @placeholder = 'Buscar']</value>
      <webElementGuid>cca75472-f5f8-437e-ae73-bd67cf858884</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
