<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_C_InputField</name>
   <tag></tag>
   <elementGuidId>092bec47-ceca-48c0-a423-c71de1161994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M0:46:1:1:2:3B256:9:1:2B257::1:17']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>371ca698-93e1-4873-985f-5465042aa40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:1:2:3B256:9:1:2B257::1:17</value>
      <webElementGuid>e7d22ac9-42ec-4395-8769-70121acdd22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>CBS</value>
      <webElementGuid>acdaf610-6aeb-400f-9bdf-e215463f2549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;x&quot;:0,&quot;1&quot;:&quot;FREETEXT&quot;,&quot;3&quot;:&quot;M0:46:1:1:2:3B256:9:1:2B257::1:17_TALB&quot;,&quot;7&quot;:true,&quot;12&quot;:true,&quot;13&quot;:&quot;C&quot;,&quot;14&quot;:&quot;SERVER&quot;,&quot;16&quot;:true,&quot;20&quot;:false,&quot;21&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/tabsTS_1100/tabpIHKZ/ssubSUB_AUFTRAG:SAPLCOIH:1120/subNOTIFICATION_DATA:SAPLIQS0:7010/tabsTSTRIP_7010/tabp$TS02/ssubTSTRIP_SCREEN:SAPLIQS0:7030/ctxtVIQMUR-URGRP&quot;,&quot;Type&quot;:&quot;GuiCTextField&quot;,&quot;value&quot;:&quot;&quot;,&quot;maxlen&quot;:8,&quot;focusable&quot;:&quot;X&quot;,&quot;showTypeAhead&quot;:&quot;true&quot;},&quot;22&quot;:&quot;pstxt&quot;,&quot;29&quot;:&quot;M0:46:1:1:2:3B256:9:1:2B257::1:0&quot;}</value>
      <webElementGuid>73c44d8d-0a95-4c0f-bcc6-097e47a0df03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Change&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Select&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Validate&quot;:[{},{}],&quot;DeleteItem&quot;:[{},{&quot;3&quot;:true}],&quot;ListAccess&quot;:[{&quot;ResponseData&quot;:&quot;delta&quot;,&quot;TransportMethod&quot;:&quot;full&quot;,&quot;EnqueueCardinality&quot;:&quot;none&quot;},{&quot;3&quot;:true,&quot;8&quot;:&quot;typeahead&quot;,&quot;maxlen&quot;:0,&quot;parentid&quot;:&quot;TSTRIP_SCREEN:SAPLIQS0:7030&quot;}],&quot;DoubleClick&quot;:[{},{&quot;1&quot;:&quot;action/2&quot;,&quot;2&quot;:true,&quot;3&quot;:true}],&quot;FieldHelpPress&quot;:[{},{&quot;1&quot;:&quot;vkey/4&quot;,&quot;2&quot;:true,&quot;5&quot;:true}],&quot;ActionItemActivate&quot;:[{},{&quot;1&quot;:&quot;vkey/0/ses[0]&quot;,&quot;2&quot;:true}],&quot;ClipboardTablePaste&quot;:[{},{&quot;0&quot;:&quot;GuiTextField&quot;,&quot;1&quot;:&quot;action/25&quot;,&quot;2&quot;:true,&quot;3&quot;:true}]}</value>
      <webElementGuid>ede442b0-27f4-4394-b017-75f6da90851a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cust-sid</name>
      <type>Main</type>
      <value>vDR5IolanS5uPrbZfZglrg==</value>
      <webElementGuid>cb0bfb45-c5b8-439c-b8a9-53b3a6bb64a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7da97f8b-ceee-4e8a-9225-a4f7327e2561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>C</value>
      <webElementGuid>d9ac4dd1-e2fc-4c66-a1f9-95bb888a1634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>C</value>
      <webElementGuid>87227e4a-8af4-48ea-94e4-3902ff736692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0e3463b3-a8b3-4f42-b6ac-e559bc51490c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8093381b-fe4a-4b67-936b-7c04d3fd4c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0a956638-e735-4f0d-90db-d592fb2d2505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Grupo de códigos: Causas</value>
      <webElementGuid>d8e37352-4ad2-4016-b769-f38f613461c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField__input</value>
      <webElementGuid>8e018d1a-636f-4b59-bcbb-c5c10f56070d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>16557cdd-c604-40ad-8b89-ff2b989b7c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f01531c3-40dc-45ec-a7a0-92d5e855753c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value> ARIA_CB_F4Lookup_TUT M0:46:1:1:2:3B256:9:1:2B257::1:17-ariatooltip</value>
      <webElementGuid>7f524de5-64b1-479e-a862-4e8477d6f205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>M0:46:1:1:2:3B256:9:1:2B257::1:0</value>
      <webElementGuid>247e312a-2c20-440d-ae4f-c1fb030c621f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InputField</value>
      <webElementGuid>69a0936f-ea5f-45ee-9310-621c3a4a804b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:1:2:3B256:9:1:2B257::1:17&quot;)</value>
      <webElementGuid>07bdca4c-eda1-4115-8b9a-b7eb1cb55ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Creación Orden de Correctico Unae new id/Page_Crear Correctivo Autopista  Cabecera central/iframe_Ms_application-MaintenanceOrder-crea_93f4a2</value>
      <webElementGuid>0acfc2d2-3360-4660-abc9-a91cef45fdc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M0:46:1:1:2:3B256:9:1:2B257::1:17']</value>
      <webElementGuid>030df011-82ee-4415-bc4c-111c12672d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='M0:46:1:1:2:3B256:9:1:2B257::1:17-r']/tbody/tr/td/input</value>
      <webElementGuid>fc3c22cc-b5d3-4913-b715-d692103065ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div[6]/table/tbody/tr/td/input</value>
      <webElementGuid>639a32ae-2352-4af7-8a4d-6671edfd53f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'M0:46:1:1:2:3B256:9:1:2B257::1:17' and @type = 'text' and @title = 'Grupo de códigos: Causas' and @name = 'InputField']</value>
      <webElementGuid>c67b025e-acc8-4a55-b659-32b9c6a0691f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
