<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Gestione Ticket Programmata</name>
   <tag></tag>
   <elementGuidId>03d6167e-ed22-4b57-904e-1b908dd2d96b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__text108']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__text108</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dacb6ca7-042f-45c6-843c-1224c0a1bc0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text108</value>
      <webElementGuid>35399972-934b-4f1b-8cef-95a1c91d97cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text108</value>
      <webElementGuid>7df21b61-54e7-4b34-8f86-02535c1dd06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>a09384e7-69c7-4ec7-90bc-0819fc248d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextNoWrap sapMTextMaxWidth suggestText suggestNavItem suggestListItemCell</value>
      <webElementGuid>c569f4ce-6e51-49a1-8044-c9acfe8e698b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gestione Ticket Programmata</value>
      <webElementGuid>0e2790eb-4836-4607-945a-4282be935913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text108&quot;)</value>
      <webElementGuid>f61782a4-c5eb-4d11-85c3-9c62e5c3e000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__text108']</value>
      <webElementGuid>998cb7ab-9d03-409d-8312-bfafd6193ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__data110']/span</value>
      <webElementGuid>2c5dcdea-8040-460a-b94d-8da461ba2ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apps'])[1]/following::span[3]</value>
      <webElementGuid>7b52c07d-1b2e-404b-a7b3-9d316847a81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagina iniziale'])[2]/preceding::span[3]</value>
      <webElementGuid>7d65035d-48a1-4844-989e-e589cdba9286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='rogrammata']/parent::*</value>
      <webElementGuid>0fb43e57-c648-4211-a459-b634f6939134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/span</value>
      <webElementGuid>0d2dbbac-ed6c-4afd-832c-b0916d0ffac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__text108' and (text() = 'Gestione Ticket Programmata' or . = 'Gestione Ticket Programmata')]</value>
      <webElementGuid>b5d1a5f4-45e4-49a4-a960-69d05715b5f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
