<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Comments to approver_application-z_06e354</name>
   <tag></tag>
   <elementGuidId>06623ee3-e260-49d5-814e-72c80db9798e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createMP-component---cartView--idHB05-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='application-zpurchaserequisition-createMP-component---cartView--idHB05-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e13f8d09-b627-4ab3-8986-e3539a495916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createMP-component---cartView--idHB05-inner</value>
      <webElementGuid>5d9c3436-a433-432f-9d42-cb0bc084601b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createMP-component---cartView--idHB05E-label</value>
      <webElementGuid>303bc352-99d2-46aa-a0b4-7a5001782674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>a8c2abb5-ec60-4b40-acef-15059472a1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>81792e67-4e57-4317-b581-f6dda978a98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner sapMTextAreaInner</value>
      <webElementGuid>269411bd-c6cd-484e-81fb-35f404d2a5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createMP-component---cartView--idHB05-inner&quot;)</value>
      <webElementGuid>1295f0d5-bc9b-4548-8077-9005fe648488</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='application-zpurchaserequisition-createMP-component---cartView--idHB05-inner']</value>
      <webElementGuid>3e062c41-5a5c-4398-a038-18173281b344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaserequisition-createMP-component---cartView--idHB05-content']/textarea</value>
      <webElementGuid>dd6e0518-aff2-44ec-aa2b-08b13246782d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comments to approver'])[1]/following::textarea[1]</value>
      <webElementGuid>957ffb86-4ec6-4a8a-a63c-a1761f1d807d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comments to supplier'])[1]/following::textarea[2]</value>
      <webElementGuid>0e7ae515-f123-4768-9c51-466908681ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show More'])[4]/preceding::textarea[1]</value>
      <webElementGuid>bc8d5a7b-df8b-4dc7-8b3f-6328083a8770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partner Functions'])[4]/preceding::textarea[1]</value>
      <webElementGuid>9c98c3ca-75e7-44f1-8942-d09a7ff200ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/textarea</value>
      <webElementGuid>33ec9dbb-fd75-4e9d-a5ac-bddd9c3c46b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'application-zpurchaserequisition-createMP-component---cartView--idHB05-inner']</value>
      <webElementGuid>7ae0c5b7-5617-4ebe-95c1-b95ba07583fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
