<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CA - CatalDE - DeutschEN - EnglishES_e3f430</name>
   <tag></tag>
   <elementGuidId>86059584-3956-4e7d-a002-af2c2fdeba9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LANGUAGE_SELECT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='LANGUAGE_SELECT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fa790a69-01c8-4e55-a32d-3cc15bc6c075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LANGUAGE_SELECT</value>
      <webElementGuid>0941b036-93bf-4aad-bc6a-3c3eb25ba7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4ce3e06e-7d91-4ab0-afb8-793cb7c1dc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginSelect</value>
      <webElementGuid>f51aeab7-c2d1-466b-a6ef-2ea029e2476c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Language</value>
      <webElementGuid>e08be2c4-d512-41a2-aea0-155c7faf8766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>LANGUAGE_LABEL</value>
      <webElementGuid>3176e80e-7af4-4a3b-b1b9-6f7ab81a032a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA - CatalàDE - DeutschEN - EnglishES - EspañolFR - FrançaisHR - HrvatskiIT - ItalianoPT - PortuguêsSV - Svenska</value>
      <webElementGuid>7ebc65e0-b85e-44de-a0f7-fdd744fa26e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LANGUAGE_SELECT&quot;)</value>
      <webElementGuid>dd4c4a34-aa6e-4a0f-a4ca-fd449d98f987</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='LANGUAGE_SELECT']</value>
      <webElementGuid>3fd5f954-741c-4c01-8061-0f61ec372ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LANGUAGE_SELECT_BLOCK']/select</value>
      <webElementGuid>93cbac2f-0ae6-4cc4-8382-4d5de4d90a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/following::select[1]</value>
      <webElementGuid>46e030eb-fd03-4746-9f6c-5421c74805b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::select[1]</value>
      <webElementGuid>938a3adb-b96b-4353-bb7e-06cf4fae9786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log On'])[1]/preceding::select[1]</value>
      <webElementGuid>d272118f-f428-40a2-af1d-544db8a665d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/preceding::select[1]</value>
      <webElementGuid>71e18f80-aedd-4b89-b1e3-b9270cd3ce3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>78041373-8717-4b19-b598-1097d07787bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'LANGUAGE_SELECT' and @title = 'Language' and (text() = 'CA - CatalàDE - DeutschEN - EnglishES - EspañolFR - FrançaisHR - HrvatskiIT - ItalianoPT - PortuguêsSV - Svenska' or . = 'CA - CatalàDE - DeutschEN - EnglishES - EspañolFR - FrançaisHR - HrvatskiIT - ItalianoPT - PortuguêsSV - Svenska')]</value>
      <webElementGuid>41fbf28a-32db-47c3-83e2-75f6a47135ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
