<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Visualizar propuesta</name>
   <tag></tag>
   <elementGuidId>bbae6ee8-5081-4b5c-a507-0d4e76a1d474</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:48::btn[21]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>243eddd3-c673-4545-885c-ae5378f0cbe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6317f142-3a60-4a10-8b61-8ced99d9fe00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:48::btn[21]</value>
      <webElementGuid>48acc299-20e7-4254-b398-99759f78f208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>B</value>
      <webElementGuid>edbe924e-167d-416b-bd4f-362fe867bf96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;Visualizar propuesta&quot;,&quot;4&quot;:&quot;Visualizar propuesta (Mayús+F9)&quot;,&quot;17&quot;:&quot;V&quot;,&quot;18&quot;:&quot;SHIFT_F9&quot;,&quot;21&quot;:true,&quot;25&quot;:&quot;TOGGLE&quot;,&quot;27&quot;:{&quot;SID&quot;:&quot;wnd[0]/tbar[1]/btn[21]&quot;,&quot;Type&quot;:&quot;GuiButton&quot;,&quot;SubType&quot;:&quot;toolbar&quot;}}</value>
      <webElementGuid>64467f11-06ba-4cb9-9a61-f1db714ea132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Press&quot;:[{},{&quot;1&quot;:&quot;action/3&quot;,&quot;2&quot;:true,&quot;3&quot;:true}]}</value>
      <webElementGuid>73cb7f55-90bb-41b0-b8e4-2631a42800d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9bd53e5e-2d9e-489c-a3d5-f7926b4180c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Visualizar propuesta (Mayús+F9)</value>
      <webElementGuid>75cf76ea-2757-413c-85fe-8ca2e623613f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>aaf454fb-5689-440c-a827-ff1e2eccc209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>224d9e28-7405-48da-aa44-ca48b47af1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eb92a6d6-6653-46d4-b219-e80030673127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>572030ec-c10f-42a2-9fca-d3d4ac5f1687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsButton lsButton--base urNoUserSelect urBtnRadius lsButton--useintoolbar lsButton--active lsButton--focusable lsButton--up lsButton--behaviour-toggle lsButton--design-standard lsButton--hoverable</value>
      <webElementGuid>336c0ca3-eded-4cb1-b66c-3edd75956e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toolbaritem-id</name>
      <type>Main</type>
      <value>M0:48::btn[21]-r</value>
      <webElementGuid>4a3acb2d-48fc-482a-88cc-095c6022b692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visualizar propuesta</value>
      <webElementGuid>0178e147-f213-401d-a40d-ce64e94b8b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:48::btn[21]&quot;)</value>
      <webElementGuid>9d885e8f-fd9a-42cd-a647-84f8674f19e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Ejecucion lote pagos/Page_Pagos automticos Status/iframe_Ms_application-AutomaticPayment-sche_417424</value>
      <webElementGuid>63e9dc0d-df42-43e2-ba23-17d3d42ffe7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M0:48::btn[21]']</value>
      <webElementGuid>94909ddd-67f7-41b8-8355-13fe56da1824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='M0:48::btn[21]-r']/div</value>
      <webElementGuid>de5eaffd-9805-4cdc-9bef-ecfc7c9e00e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T'])[1]/following::div[1]</value>
      <webElementGuid>1eea8482-2374-48ba-8818-cb0329bfbf9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[7]/div</value>
      <webElementGuid>b62bf480-5dda-4a14-a389-b29365563a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M0:48::btn[21]' and @title = 'Visualizar propuesta (Mayús+F9)' and (text() = 'Visualizar propuesta' or . = 'Visualizar propuesta')]</value>
      <webElementGuid>6abae8f7-46c8-4b6b-b2d0-ba9a35492352</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
