<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Aprobacin de Compras</name>
   <tag></tag>
   <elementGuidId>0867bb30-6eb2-4aab-b005-088ba1b048b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__tile28-title-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__tile28-title-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>206c1b7d-ef8e-4eaa-86bd-80ef194ad0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__tile28-title-inner</value>
      <webElementGuid>658e5557-de39-463d-99f5-9e8de99751d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMTextMaxLine sapMTextLineClamp</value>
      <webElementGuid>ae54fbef-0b65-4653-b2ea-9999985ad882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aprobación de Compras</value>
      <webElementGuid>ceebd247-89b2-4615-a6fa-4d28e7e97f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__tile28-title-inner&quot;)</value>
      <webElementGuid>893e264d-80aa-41d4-bca8-85eedd13ca01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__tile28-title-inner']</value>
      <webElementGuid>a74d15a4-c3e9-4bdc-aeac-a333027b49c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__tile28-title']/span</value>
      <webElementGuid>967ad0cd-0989-46dc-8ffe-2aed8df9133e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mostrar detalles'])[2]/following::span[5]</value>
      <webElementGuid>0e614653-fc55-4750-a6d7-8ab56cee2b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Más'])[5]/following::span[8]</value>
      <webElementGuid>a227d1cc-a82b-44f7-931d-727c0d108053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/span/span</value>
      <webElementGuid>48407671-bc9c-47c8-b4e1-6f2f0994eacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__tile28-title-inner' and (text() = 'Aprobación de Compras' or . = 'Aprobación de Compras')]</value>
      <webElementGuid>5cb84e25-f995-4def-a97c-5a8be5780e43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
