<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Value State Information_application-z_f5e223</name>
   <tag></tag>
   <elementGuidId>b786810a-5203-4dec-9174-7af121878d4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'application-zpurchaserequisition-createMP-component---detail--idPDeliveryDate-')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createMP-component---detail--idPDeliveryDate-__clone149-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;e.g. 31.12.2025&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19fd523e-e25a-4dce-9242-518e6287edca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createMP-component---detail--idPDeliveryDate-__clone149-inner</value>
      <webElementGuid>c32b5f4e-cbbd-4528-a435-7bc349476e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. 31.12.2025</value>
      <webElementGuid>f219510c-dba2-450a-b256-c8b1866fab78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-roledescription</name>
      <type>Main</type>
      <value>Date Input</value>
      <webElementGuid>331046b0-8697-4ab0-9035-4754814bb16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>grid</value>
      <webElementGuid>24af432d-7b71-4752-b9bc-93a69c481523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fe6d8770-50d2-4f69-bee4-075ad48b9945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>10d5cfdd-082d-4501-89d6-dba3622c4fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createMP-component---detail--idPDeliveryDate-__clone149-inner&quot;)</value>
      <webElementGuid>f76dda6d-898b-4737-81b3-dbb9c8dbd3b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-zpurchaserequisition-createMP-component---detail--idPDeliveryDate-__clone149-inner']</value>
      <webElementGuid>7bc8697f-c2ad-454a-8480-274a73945cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaserequisition-createMP-component---detail--idPDeliveryDate-__clone149-content']/input</value>
      <webElementGuid>49c2a296-10a1-4251-90c5-ef6771a21e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/div/div/input</value>
      <webElementGuid>641935c9-d558-409e-8c4c-7b34a575a73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-zpurchaserequisition-createMP-component---detail--idPDeliveryDate-__clone149-inner' and @placeholder = 'e.g. 31.12.2025' and @type = 'text']</value>
      <webElementGuid>8e12ca14-0049-4f27-8af5-31baeebb2e11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
