<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_sap-password</name>
   <tag></tag>
   <elementGuidId>179e1155-f7c4-4e7d-9600-6510b6afdeef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PASSWORD_FIELD-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PASSWORD_FIELD-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6bb1dbc-0388-4aa4-9108-5e2952ccf6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PASSWORD_FIELD-inner</value>
      <webElementGuid>f24b8b64-0aab-4861-8f62-1bd3a0361635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2014299b-a02a-4a4c-a532-d70de7a04447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3010f857-e695-467a-96c9-99d866823ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginInputField</value>
      <webElementGuid>30c5d097-fd0c-4093-a22b-aadf584d7337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sap-password</value>
      <webElementGuid>2b8aa223-5bd7-470b-a5b8-1b036ededa86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>verbatim</value>
      <webElementGuid>23747c95-dead-47b2-ac12-9cd7c34a6ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>5e7a6b76-5470-4c90-82b6-9d701102dad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>6e55a861-c384-412c-aa1d-d2c393f97271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e91379fd-814e-44a7-bbb2-9468d93ea0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d1e1fb82-3ad2-4688-8282-d2c9ee87d9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>PASSWORD_LABEL</value>
      <webElementGuid>29f1fe1e-d930-4edb-b960-03e0398b1c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PASSWORD_FIELD-inner&quot;)</value>
      <webElementGuid>d8a8524b-cb64-45c2-98db-d2bc0a6646f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PASSWORD_FIELD-inner']</value>
      <webElementGuid>a7bf51cd-ccce-434a-8fd1-a80443edac4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PASSWORD_BLOCK']/input</value>
      <webElementGuid>1c89127e-50e2-4297-a871-e07b61a51e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2a65b550-65c7-4933-b5ff-2f2614e64289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PASSWORD_FIELD-inner' and @type = 'password' and @name = 'sap-password' and @placeholder = 'Password' and @title = 'Password']</value>
      <webElementGuid>31d1dda4-a622-4763-96a5-c5f5b488b4cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
