<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cuenta de mayoraSociedada</name>
   <tag></tag>
   <elementGuidId>a12df652-42f0-4531-85e3-4aba24c3df3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:46:::0:0_rl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19ec0d75-dcd2-4aa7-8702-680af24d946e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:::0:0_rl</value>
      <webElementGuid>d775ee2e-8b3b-4e16-9b85-342b3a037195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>RL</value>
      <webElementGuid>1521d756-e74c-428a-8831-280e4d91b6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:4.00,&quot;2&quot;:1.25}</value>
      <webElementGuid>b70128a1-225e-4bd0-99b2-dbbf7237b1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bnoposrefcontainer</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>853796fe-5698-4276-842e-101db38b9f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>5fee2300-36c1-4edf-b96f-2aecfcd3427b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsRasterLayout  lsRL--absolute</value>
      <webElementGuid>b16bb633-4f6e-416d-a633-f4f4736ec65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-style</name>
      <type>Main</type>
      <value>;height:64px;width:820px</value>
      <webElementGuid>b14a3414-6156-4d17-ba24-3a1cec19d60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cuenta de mayora Sociedada </value>
      <webElementGuid>c82881dc-6062-42c7-8299-99c801af93e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:::0:0_rl&quot;)</value>
      <webElementGuid>11e27717-d8ef-4a60-9d2a-d519ce5e9fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Exportación Excel C Mayor/Page_Cuentas de mayor, lista de partidas in_2c585a/iframe_Ms_application-GLAccount-displayGLAc_527227</value>
      <webElementGuid>c3322ff9-7603-405c-9171-21f43336cd90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M0:46:::0:0_rl']</value>
      <webElementGuid>be6a1c8d-52b3-448d-9cb8-9a9cbadb0464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46:::0:0-scrl-cnt']/div</value>
      <webElementGuid>519d1dec-7efa-4799-95f8-7aa8be589b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selección cuenta mayor'])[1]/following::div[3]</value>
      <webElementGuid>92b3a284-fb6c-426d-b27c-0c59f36f9888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[2]/following::div[11]</value>
      <webElementGuid>ea0795e6-070d-4603-9c4f-c721d134cedf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/div/div/div</value>
      <webElementGuid>a9432845-c6da-4486-8aff-392ac15ecb7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M0:46:::0:0_rl' and (text() = 'Cuenta de mayora Sociedada ' or . = 'Cuenta de mayora Sociedada ')]</value>
      <webElementGuid>a17d5970-5001-4808-8063-97b062fa9c24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
