<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SM35___xmlview9--standardTileContent-___11dcd8</name>
   <tag></tag>
   <elementGuidId>cd0648ca-870e-4eeb-b211-bc3edcc77039</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__xmlview9--standardTileContent-__clone122']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview9--standardTileContent-__clone122</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6fefcab7-5bce-455d-b7fd-db0135c38fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview9--standardTileContent-__clone122</value>
      <webElementGuid>125dd953-c4bf-40f5-8a63-5092259ce06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__xmlview9--standardTileContent-__clone122</value>
      <webElementGuid>45bf0a54-9bd2-451b-a576-2b8d5bb4b56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMTileCnt sapMFrameTypeAuto sapMGTNoPriority</value>
      <webElementGuid>7146cc44-71d2-4928-8da7-d2912d543c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview9--standardTileContent-__clone122&quot;)</value>
      <webElementGuid>f79d8efd-d9a2-47b1-96e5-162296d5f843</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__xmlview9--standardTileContent-__clone122']</value>
      <webElementGuid>a9c75df3-0a9e-4785-ad00-56b2eb21521a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__tile137-content']/div</value>
      <webElementGuid>7832fc5b-d11a-405f-8d79-e3eb58db2a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SM35'])[3]/following::div[2]</value>
      <webElementGuid>d2d0708f-5c16-4332-9051-42271d4e8c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supervisión batch input'])[1]/following::div[3]</value>
      <webElementGuid>7e83d975-d65e-42d9-89cd-58ce2662beb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch input: Mis logs'])[1]/preceding::div[4]</value>
      <webElementGuid>c08c95ab-658d-4916-bd8e-907fe61008d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch input: Logs en mi área'])[1]/preceding::div[16]</value>
      <webElementGuid>51ecc940-853a-4a37-b2db-db522d45bc44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div</value>
      <webElementGuid>f4d09c4a-0a0c-4822-9542-d9a8519811e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__xmlview9--standardTileContent-__clone122']</value>
      <webElementGuid>1751d064-cf97-4bb3-93a8-90da8b105318</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
