<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User_sap-user</name>
   <tag></tag>
   <elementGuidId>56d151ef-953c-44de-a6ea-e59de667fd5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='USERNAME_FIELD-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#USERNAME_FIELD-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10e519ac-08eb-4bb4-ab48-17d8b1bdc1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USERNAME_FIELD-inner</value>
      <webElementGuid>dc6dedf8-542c-4c6b-8a40-277325ceaafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>906ef6ad-1676-4413-b835-67453e3fdb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ad03494-d18b-4052-880b-8117d8a591ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginInputField ltrInput</value>
      <webElementGuid>84a8a1b3-6447-4b6a-85ff-2845f282a592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sap-user</value>
      <webElementGuid>18dd3ed8-bab3-4c9b-9fd7-fcc4376ad1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12 </value>
      <webElementGuid>c6d95ffa-0f20-4182-8d27-e4e5d45f1613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>verbatim</value>
      <webElementGuid>039340ce-2eec-48ca-aa48-5cbf21eb9383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2b07be5a-d256-4b6a-9a63-5392ddc1a9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>66a1e634-5cd8-4e22-9b7a-22c39b8e142f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User</value>
      <webElementGuid>5093b423-890b-45e9-9c9f-aa116d7767ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>User</value>
      <webElementGuid>fc1a86e3-e063-4a89-8a2f-330c1c796fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c8a8958b-ddd3-4032-8e53-b6492bb8600f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>51373308-54b4-4b58-8229-0127b17e682f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>USERNAME_LABEL</value>
      <webElementGuid>339b43b1-1ed1-49b1-8c08-5633a927fdb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USERNAME_FIELD-inner&quot;)</value>
      <webElementGuid>15bccd6b-508e-4810-adc8-0954bfe03342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='USERNAME_FIELD-inner']</value>
      <webElementGuid>2b61dd48-a645-4d46-9f2e-ae8cc906fb1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='USERNAME_BLOCK']/input</value>
      <webElementGuid>4fe9a0dc-bfc6-4738-ae31-cb5e5c65dfd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>6917af9e-1f0c-4b69-8564-c24cf992fdc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'USERNAME_FIELD-inner' and @type = 'text' and @name = 'sap-user' and @placeholder = 'User' and @title = 'User']</value>
      <webElementGuid>9835529b-1f8d-45a5-9202-711c8c9f43ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
