<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CA - CatalDE - DeutschEN - EnglishES_e3f430</name>
   <tag></tag>
   <elementGuidId>8849c337-6bcd-4f22-b2c4-231db0e8442e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='LANGUAGE_SELECT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LANGUAGE_SELECT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c832a635-99cf-4ec6-ab88-e99b95d624a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LANGUAGE_SELECT</value>
      <webElementGuid>83286d47-0862-4fd1-8253-5c753e41e05a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>423bd853-2648-4824-ac84-06648bdeeaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginSelect</value>
      <webElementGuid>7e8563f6-8524-4605-972d-5db027ec652e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Language</value>
      <webElementGuid>4b2835e9-3df5-417f-9190-61e61ae1567a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>LANGUAGE_LABEL</value>
      <webElementGuid>c1c86f08-e45c-4a28-975d-1c984e122738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA - CatalàDE - DeutschEN - EnglishES - EspañolFR - FrançaisHR - HrvatskiIT - ItalianoPT - PortuguêsSV - Svenska</value>
      <webElementGuid>c2b7948b-0e4d-4a5d-be10-609d3fbff9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LANGUAGE_SELECT&quot;)</value>
      <webElementGuid>941e57a1-1bee-4f38-ae9f-b645a464339b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='LANGUAGE_SELECT']</value>
      <webElementGuid>403b00d7-666f-4b70-998c-5ff4d2d820a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LANGUAGE_SELECT_BLOCK']/select</value>
      <webElementGuid>d83c44d7-61f8-4e98-8ace-c4f0ac48b90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/following::select[1]</value>
      <webElementGuid>9ebbe6f5-aad1-4f7e-92a2-6ba5e7ec8fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::select[1]</value>
      <webElementGuid>49b06893-8568-4ec5-a013-4cf04107426e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log On'])[1]/preceding::select[1]</value>
      <webElementGuid>5616eb91-33bc-41d3-9913-9610829aa068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/preceding::select[1]</value>
      <webElementGuid>31ac01ea-72c7-4300-888b-b8e795395783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1f3cb391-62c9-4aff-9bd0-b99a47ccf317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'LANGUAGE_SELECT' and @title = 'Language' and (text() = 'CA - CatalàDE - DeutschEN - EnglishES - EspañolFR - FrançaisHR - HrvatskiIT - ItalianoPT - PortuguêsSV - Svenska' or . = 'CA - CatalàDE - DeutschEN - EnglishES - EspañolFR - FrançaisHR - HrvatskiIT - ItalianoPT - PortuguêsSV - Svenska')]</value>
      <webElementGuid>0b11a572-11a0-4efc-b920-f07c05d288d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
