<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Data inizio_application-ZPM_SMART-GEST_6f4ce1</name>
   <tag></tag>
   <elementGuidId>7110b9ac-02b8-4d8c-90ce-ac388a25f0a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-StartDate-input-vhi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-StartDate-input-vhi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>deb5fcaf-3707-47df-a02c-bdaf88ed3651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-StartDate-input-vhi</value>
      <webElementGuid>1668e97e-7265-49ff-ad14-0f31d239c9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-StartDate-input-vhi</value>
      <webElementGuid>76b645bd-3a33-4703-9fb4-bcff6c1ef632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>07d25526-a79f-4f9e-afa8-9d452c22d846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>22d14ff9-0724-48ca-a340-bc5e70f39c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Visualizza help valori</value>
      <webElementGuid>5cfde16c-3b6a-40fb-ba09-843eba5b284d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>f69bd59a-0b6c-4b4b-8d53-caf093e2ba2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconPointer sapMInputBaseIcon</value>
      <webElementGuid>8655db40-ea5f-45a5-8a22-9918be5e54ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-StartDate-input-vhi&quot;)</value>
      <webElementGuid>785d3e4a-18ed-40b4-a6e5-d24252c35878</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-StartDate-input-vhi']</value>
      <webElementGuid>cce7a480-4526-4285-9f39-3dbb3f108d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-StartDate-input-content']/div/span</value>
      <webElementGuid>eed74c7a-2d70-43a0-8533-e89c529dd29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/div/div/span</value>
      <webElementGuid>7d2ce554-d0ad-4224-a9c5-8714efd52787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-StartDate-input-vhi']</value>
      <webElementGuid>699c6110-701e-43a6-b3b7-9000390798b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
