<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Avvio</name>
   <tag></tag>
   <elementGuidId>b56c0f9d-fe45-4373-8acf-e7632d5698a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dfdd48cb-56df-40e1-aa33-d3e691bda458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-inner</value>
      <webElementGuid>306e7ac3-5f32-472f-869c-cddb3374ea92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnInner sapMBtnHoverable sapMFocusable sapMBtnText sapMBtnEmphasized</value>
      <webElementGuid>1258558a-b842-4606-812f-1d2875429e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Avvio</value>
      <webElementGuid>0c657341-a440-48c6-bff4-9211cfe85c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-inner&quot;)</value>
      <webElementGuid>fa2e7162-d09f-4ebe-8b14-a343e6ca635a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-inner']</value>
      <webElementGuid>5157fe82-b6f4-4847-9383-a0a91d1c2514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo']/span</value>
      <webElementGuid>1b1e0be8-ea3b-4350-b5d9-8bef1aab0cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleziona view'])[1]/following::span[2]</value>
      <webElementGuid>934c9c74-9f9e-46a8-b9f4-fceaa52dddd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[5]</value>
      <webElementGuid>7be868c8-14d8-414a-956f-427c4949677f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nascondi barra filtri'])[1]/preceding::span[2]</value>
      <webElementGuid>f8ad4c90-79a0-46a8-9d41-2010eb91868a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/button/span</value>
      <webElementGuid>07a6a3fd-a00c-4e8e-a045-f4a6541b16c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-inner' and (text() = 'Avvio' or . = 'Avvio')]</value>
      <webElementGuid>42ce00c0-62d8-4f4c-ac2f-32138ca4e069</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
