<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_rea de trabajo de VIM</name>
   <tag></tag>
   <elementGuidId>4bf31aa1-5224-4270-a3c9-9ca1182caac5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__tile114-title-inner']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__tile114-title-inner > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c8406bc7-1380-4d3d-8546-8212316f001b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Área de trabajo de VIM</value>
      <webElementGuid>9d6018fd-e0f4-43c7-a5dd-7826c9304fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__tile114-title-inner&quot;)/span[1]</value>
      <webElementGuid>cf53dc82-7d1c-47a0-b983-e5ec505e7553</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__tile114-title-inner']/span</value>
      <webElementGuid>a4ae0d06-b38b-4ef8-82ff-c4f465f6a47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resultados (2)'])[1]/following::span[6]</value>
      <webElementGuid>a4a54e3e-a217-4729-a04d-b205cfdff825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compartir'])[1]/following::span[18]</value>
      <webElementGuid>c4fd1ba1-af00-4790-ae64-16a40602218e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPT/VIM_WP'])[1]/preceding::span[1]</value>
      <webElementGuid>5ba5aeae-f52c-4852-b1e3-f47aad6f2819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Área de trabajo de VIM']/parent::*</value>
      <webElementGuid>f582aff2-af58-486a-8b09-864939adb372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/span/span/span</value>
      <webElementGuid>0c12faaa-9e9e-4699-a77a-f3934e012077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Área de trabajo de VIM' or . = 'Área de trabajo de VIM')]</value>
      <webElementGuid>76e2d6ce-169d-4fe2-9092-10cf953bd59b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
