<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Ms_application-zgui_zpm_prev_maint-c_997e30</name>
   <tag></tag>
   <elementGuidId>4c8fac8f-1abf-424c-af8b-f24999d3b483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zgui_zpm_prev_maint-change-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='application-zgui_zpm_prev_maint-change-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>410af938-8ef1-4f77-9268-91fca754a679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zgui_zpm_prev_maint-change-iframe</value>
      <webElementGuid>27ae5534-18d7-43ef-a6ad-d4f291ed34e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-zgui_zpm_prev_maint-change-iframe</value>
      <webElementGuid>4b07d906-0b76-4f45-bbcb-ea1a317bc28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application-zgui_zpm_prev_maint-change-iframe</value>
      <webElementGuid>0d7b0e68-4a9f-4190-ba7d-153272a13425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-orig-src</name>
      <type>Main</type>
      <value>/sap/bc/gui/sap/its/webgui;~sysid=R3Q;~service=3200?~transaction=ZPM_PREV_MAINT&amp;sap-client=100&amp;sap-language=ES&amp;~nosplash=1&amp;sap-iframe-hint=GUI&amp;sap-ie=edge&amp;sap-theme=abertis_theme_corp%40https%3A%2F%2Fsaps4-pre.abertis.com%2Fsap%2Fpublic%2Fbc%2Fthemes%2F~client-100%2F~cache-EffUt0nnNFsxi7WxmjEKOoghmzc&amp;sap-touch=0&amp;sap-target-navmode=inplace&amp;sap-keepclientsession=2&amp;sap-ushell-timeout=25&amp;sap-shell=FLP1.120.28</value>
      <webElementGuid>8ceaf560-2a40-4aa6-8aa6-c9fb09657b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aplicación</value>
      <webElementGuid>6c3555f0-b9f4-471c-92f2-790d91f205b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-iframe-idx</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2d259306-1a72-4f0d-9bee-3fa08f8ba5f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay ;battery ;camera ;display-capture ;geolocation ;gyroscope ;magnetometer ;microphone ;midi ;clipboard-write ;clipboard-read ;fullscreen ;serial ;</value>
      <webElementGuid>09a9928a-9163-443a-aefd-e4f9a2f60b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUShellApplicationContainer</value>
      <webElementGuid>13a4b16f-4f1a-4c2c-893d-c2c166fb526a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zgui_zpm_prev_maint-change-iframe&quot;)</value>
      <webElementGuid>8207dd5a-093c-43b5-8a28-f58c97c76525</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='application-zgui_zpm_prev_maint-change-iframe']</value>
      <webElementGuid>f35bd8c4-684e-4512-9137-c4fe73406dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zgui_zpm_prev_maint-change']/iframe</value>
      <webElementGuid>ceab905c-0ebe-4926-bccf-19d39f63b4a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>fa695b9b-2489-4324-a958-736250994fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'application-zgui_zpm_prev_maint-change-iframe' and @name = 'application-zgui_zpm_prev_maint-change-iframe' and @title = 'Aplicación']</value>
      <webElementGuid>b323b423-073d-4557-bf6e-3b2c73e53244</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
