<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Eq___xmlview2--imageTileContent-__clone99</name>
   <tag></tag>
   <elementGuidId>394e4c3a-9a1c-4f4a-8a37-2e2bad35b634</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__xmlview2--imageTileContent-__clone99</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__xmlview2--imageTileContent-__clone99']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>83668df2-241b-4abe-bfd6-5e4f7859e176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview2--imageTileContent-__clone99</value>
      <webElementGuid>c15b069d-b66d-4848-8415-52e9e051fa82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__xmlview2--imageTileContent-__clone99</value>
      <webElementGuid>e5171bd6-e027-4bc6-a38a-2ae2e33d95fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMTileCnt sapMFrameTypeAuto sapMGTNoPriority</value>
      <webElementGuid>4d7cc719-6e2c-4e3e-b476-95b1b4bdc980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview2--imageTileContent-__clone99&quot;)</value>
      <webElementGuid>63cce09b-8c8d-4fc6-9011-ecf6c7156969</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__xmlview2--imageTileContent-__clone99']</value>
      <webElementGuid>0db5945e-c349-4a96-ab33-54a1cbb4a757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__tile6-content']/div</value>
      <webElementGuid>09b8cf24-ef71-4c5c-9f7e-33966448c42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eq'])[1]/following::div[2]</value>
      <webElementGuid>b4604cf3-ed56-4145-b4d8-74b65f54b2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='de'])[1]/following::div[2]</value>
      <webElementGuid>0d99d243-f03c-425d-b15e-8b9b00c47eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temas de ayuda'])[1]/preceding::div[47]</value>
      <webElementGuid>5c70ec82-bb20-4f96-b22a-e136963b398e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div</value>
      <webElementGuid>fdaa7d65-4eee-4039-8c84-76d6026b0dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__xmlview2--imageTileContent-__clone99']</value>
      <webElementGuid>896de016-e817-46d8-a10d-3cd868992927</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
