<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Posiciones de documentos de pago</name>
   <tag></tag>
   <elementGuidId>272b43b3-d55e-4ef9-a5fd-db3adf08393d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:1:2B264::5:1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b558e6cb-0a87-426c-88b3-a19543367769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>C_standards</value>
      <webElementGuid>157cfc46-b4cf-47f2-8d8a-7c657f1e71a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;CheckBox&quot;,&quot;4&quot;:&quot;Posiciones de documentos de pago&quot;,&quot;5&quot;:&quot;Indicador: ¿Requiere Trace para documentos de pago?&quot;,&quot;9&quot;:&quot;P&quot;,&quot;14&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/tabsF110_TABSTRIP/tabpLOG/ssubSUBSCREEN_BODY:SAPF110V:0204/chkF110V-XTRBL&quot;,&quot;Type&quot;:&quot;GuiCheckBox&quot;,&quot;focusable&quot;:&quot;X&quot;},&quot;16&quot;:true}</value>
      <webElementGuid>4e982b90-9cbd-4986-b8a5-ff1ec9ffa963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Enter&quot;:[{},{&quot;1&quot;:&quot;vkey/0/ses[0]&quot;,&quot;2&quot;:true}],&quot;Change&quot;:[{},{&quot;1&quot;:&quot;action/7&quot;,&quot;3&quot;:true}]}</value>
      <webElementGuid>6aa88501-3f26-4a42-8d40-71fdf7a2fcdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-currentselectionstate</name>
      <type>Main</type>
      <value>API_DRIVEN</value>
      <webElementGuid>9db95660-9096-43c7-90ff-5724dc2b604f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsSelector--generic lsSelector--text lsSelector--strechedForEllipsis lsSelector--pushedToStart--spacing lsCheckBox lsCheckBox--unchecked  </value>
      <webElementGuid>b98d8ddb-9213-40a5-adf5-513f025298ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c645282e-3557-4d9b-a75e-3c677633e7bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2f22ddcc-cde4-4e05-a987-079ef629c908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Indicador: ¿Requiere Trace para documentos de pago?</value>
      <webElementGuid>b26e9cd1-8d25-4beb-8e81-95c53d801d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>2c9d0718-8ad7-4a87-875a-629d0ad8a493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>b1df988b-590c-4d1b-8286-2618b2dc2e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CheckBox</value>
      <webElementGuid>a6987be9-76ed-4fd1-90e0-c42f3fc0920a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:2B264::5:1</value>
      <webElementGuid>468907be-884d-488b-9abe-7f6aecc6b5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>04cbe41b-9426-4c90-8c87-4c0403867634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bf6f27b7-01c0-4a51-933c-a37e76c5d4db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ae9e3afb-7bbc-4ee7-ae81-45704e84b73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>298de279-d357-48c6-8992-8ec7b5b25e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Posiciones de documentos de pago</value>
      <webElementGuid>778e54ce-aca4-43e8-90a1-51220cf45887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ba123ce6-e54f-467c-a3fa-bbb4e98780ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-controlusage</name>
      <type>Main</type>
      <value>API_DRIVEN</value>
      <webElementGuid>cb294d17-c5de-464a-afc9-fc2cfdba3da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Posiciones de documentos de pago</value>
      <webElementGuid>898110ef-9acf-44fe-b0ee-d235f5b9cc0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:2B264::5:1&quot;)</value>
      <webElementGuid>5b825971-5e02-4d40-b870-75896deeb5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Ejecucion lote pagos/Page_Pagos automticos Log adicional/iframe_Ms_application-AutomaticPayment-sche_417424</value>
      <webElementGuid>0e0287e6-6dcc-4d1a-9840-b2abdc014a79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:2B264::5:1']</value>
      <webElementGuid>ddea3824-22e7-4c41-8aad-7602aa26bdcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u6089']/span</value>
      <webElementGuid>f5209379-7761-443d-8c7e-3dbe5f0b4b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::span[1]</value>
      <webElementGuid>de10895c-ec75-43d6-83b9-dd3a3ccf1033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span</value>
      <webElementGuid>31aac496-68f4-4336-98f9-46f531f62385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Indicador: ¿Requiere Trace para documentos de pago?' and @name = 'CheckBox' and @id = 'M0:46:1:2B264::5:1' and (text() = 'Posiciones de documentos de pago' or . = 'Posiciones de documentos de pago')]</value>
      <webElementGuid>660770a9-48bc-4192-a7cd-eb1e555a239a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
