<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ir</name>
   <tag></tag>
   <elementGuidId>3e2e3917-eb1a-48fa-abb4-058a9b2be49c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-ListMeasDoc-component---main--iSmartFilterBar-btnGo-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-ZPM_SMART-ListMeasDoc-component---main--iSmartFilterBar-btnGo-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b6b6d14c-d360-4dd4-8bb3-5f213ce971a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-ListMeasDoc-component---main--iSmartFilterBar-btnGo-inner</value>
      <webElementGuid>e7204732-d4d3-41f7-9e8d-821e26300307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnInner sapMBtnHoverable sapMFocusable sapMBtnText sapMBtnEmphasized</value>
      <webElementGuid>1b732e40-00db-41be-93ba-33976cb3c1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ir</value>
      <webElementGuid>d1c1093e-e15f-4017-ac28-b7d5cb2cbfd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-ListMeasDoc-component---main--iSmartFilterBar-btnGo-inner&quot;)</value>
      <webElementGuid>4e6746af-9eec-4589-84ec-6ef48bfaf4a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-ListMeasDoc-component---main--iSmartFilterBar-btnGo-inner']</value>
      <webElementGuid>b1137f29-74c6-44ff-b092-d6a842ed524e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='application-ZPM_SMART-ListMeasDoc-component---main--iSmartFilterBar-btnGo']/span</value>
      <webElementGuid>6db6c76d-fdf4-4e56-932a-55ee2602a7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar vista'])[1]/following::span[2]</value>
      <webElementGuid>9c1ff8e2-2eb1-437d-9593-8f2aa9438428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[5]</value>
      <webElementGuid>6629f613-710d-4091-a6b7-326c067dc995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ocultar barra de filtros'])[1]/preceding::span[2]</value>
      <webElementGuid>bc9b3b0f-f373-4530-b638-6b11322b8e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/button/span</value>
      <webElementGuid>56e746fa-c15b-4c61-8ddd-c8d4b1f79ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-ZPM_SMART-ListMeasDoc-component---main--iSmartFilterBar-btnGo-inner' and (text() = 'Ir' or . = 'Ir')]</value>
      <webElementGuid>316d7f2c-6576-4882-bd8d-7a884fab8f9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
