<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_sap-password</name>
   <tag></tag>
   <elementGuidId>f9826b41-8be1-4b5c-ba56-04dd096e93d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PASSWORD_FIELD-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PASSWORD_FIELD-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2965814b-13e4-466a-a54a-31a910fa9796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PASSWORD_FIELD-inner</value>
      <webElementGuid>010a77bd-8d32-4f2d-9823-ff9d75495098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d5ad2574-528a-409c-b10f-0d149a1f238d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8cf6e6b5-5c73-4e73-a3c2-499604b937eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginInputField</value>
      <webElementGuid>5c8cd331-f376-4aa9-9ec8-2c26f6053689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sap-password</value>
      <webElementGuid>3f869b2c-2670-4e06-9c88-0ff0eb1f387b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>verbatim</value>
      <webElementGuid>bd24efb2-75e7-43b4-b938-04cbdd7f117f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>c6883592-3b9e-4117-bffb-1d56c7df8784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>aa15692d-056c-4145-ba3f-a716bf3c03f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>25676310-d331-4cc0-bbae-cca44645ffd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a886eb81-7da6-440f-a945-f09d61324339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>PASSWORD_LABEL</value>
      <webElementGuid>518847b7-4266-47d3-a092-fa405f6a38cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PASSWORD_FIELD-inner&quot;)</value>
      <webElementGuid>a73d24ed-aaf1-46eb-9387-4e87a0267c63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PASSWORD_FIELD-inner']</value>
      <webElementGuid>34fc30b1-17d4-4158-8ccc-b111a91849ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PASSWORD_BLOCK']/input</value>
      <webElementGuid>f1bf6a8f-f5d5-4a08-a532-f4ad6629c30d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>1181a22b-d211-4d54-b591-c7ccec03d594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PASSWORD_FIELD-inner' and @type = 'password' and @name = 'sap-password' and @placeholder = 'Password' and @title = 'Password']</value>
      <webElementGuid>766f9143-2b68-4cd0-a313-d38e70972f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
