<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sauvegarder Prliminaire_application-zp_41e66c</name>
   <tag></tag>
   <elementGuidId>d040ab7d-2b4c-4c76-81ca-0bbbfda0b6eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createMP-component---detail--saveButton-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-zpurchaserequisition-createMP-component---detail--saveButton-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Enregistrer&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>05b0d1c4-dd93-4d43-aaf2-0875be214519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createMP-component---detail--saveButton-inner</value>
      <webElementGuid>033ebc0c-1d94-4d8d-aafd-1fabbb6352af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnInner sapMBtnHoverable sapMFocusable sapMBtnText sapMBtnAccept</value>
      <webElementGuid>6b04cc9f-487b-4904-8b2a-81b3996c929e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enregistrer</value>
      <webElementGuid>760af2db-6937-45a6-8ae8-9b775d3be5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createMP-component---detail--saveButton-inner&quot;)</value>
      <webElementGuid>5cfc9076-52e1-4409-ba06-5ca216b078d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-zpurchaserequisition-createMP-component---detail--saveButton-inner']</value>
      <webElementGuid>a39a2ad8-1a44-4263-b630-0207abadf8af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='application-zpurchaserequisition-createMP-component---detail--saveButton']/span</value>
      <webElementGuid>542b6cde-1717-46dc-a4d6-f4b9002c3528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sauvegarder Préliminaire'])[1]/following::span[1]</value>
      <webElementGuid>d84d46c7-4f70-41d1-b223-540ac2dbdb3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Afficher plus'])[2]/following::span[7]</value>
      <webElementGuid>3f12107f-b5cd-4a38-866a-350d0f7f6eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annuler'])[2]/preceding::span[2]</value>
      <webElementGuid>2123edcb-5ff3-447b-a3f7-5328872cf0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/button[3]/span</value>
      <webElementGuid>9105c9d0-4d00-431a-98d9-f334d2e7a8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-zpurchaserequisition-createMP-component---detail--saveButton-inner' and (text() = 'Enregistrer' or . = 'Enregistrer')]</value>
      <webElementGuid>be073a7f-fa1d-4535-93a4-678a305849df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
