<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Russite___text408</name>
   <tag></tag>
   <elementGuidId>703efd39-30ae-4162-8e21-b8c5b22b1c4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__text408</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__text408']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Demande d'achat 2000615160 crée&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>58a17ee1-d520-423f-9b39-d55e14924e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text408</value>
      <webElementGuid>49bcf6e3-32c2-408c-b298-8d8c2e7e00fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text408</value>
      <webElementGuid>4168e467-05c1-4485-939e-f299f5c2135e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c8a8922b-bb59-418c-ac27-cb2678079437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextMaxWidth sapMMsgBoxText</value>
      <webElementGuid>107bbdc4-5c58-4ad1-9a7c-176e10cf970f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demande d'achat 2000615160 crée</value>
      <webElementGuid>7862a17c-d5eb-4b2b-b438-0d4d41a9602c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text408&quot;)</value>
      <webElementGuid>32e14e12-0e89-478e-9318-34c3f152e11c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__text408']</value>
      <webElementGuid>116d3c0f-9ac6-4b02-9975-f0dc3cb2f374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__success1-scrollCont']/span</value>
      <webElementGuid>e8a39bfa-cd1a-48d5-bcf4-08f85b5ad46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Réussite'])[1]/following::span[2]</value>
      <webElementGuid>7223ceb3-f730-4f6b-a152-ac487c5ccf42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOC PGN-THEROUANNE'])[1]/following::span[8]</value>
      <webElementGuid>c9389922-18e9-493f-a5fd-53924b41be09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::span[1]</value>
      <webElementGuid>9de91bf8-30f0-43ed-9372-c9840a88153d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::span[6]</value>
      <webElementGuid>9c484972-0a61-47a0-b219-f0a19cc3111c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/span</value>
      <webElementGuid>e7fa4baa-2170-40e7-84b4-55abb9780d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__text408' and (text() = concat(&quot;Demande d&quot; , &quot;'&quot; , &quot;achat 2000615160 crée&quot;) or . = concat(&quot;Demande d&quot; , &quot;'&quot; , &quot;achat 2000615160 crée&quot;))]</value>
      <webElementGuid>3fe247e3-0d4b-4396-bc3c-1791d4789b4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
