<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ordre_application-zpurchaserequisition_c3fc1a</name>
   <tag></tag>
   <elementGuidId>6da2bebf-058a-4e18-ab64-b9828a522a06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createMP-component---cartView--idPOrderNumber-vhi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-zpurchaserequisition-createMP-component---cartView--idPOrderNumber-vhi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#application-zpurchaserequisition-createMP-component---cartView--idPOrderNumber-vhi</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>77bf17fc-9934-428f-a1ab-de553aabe9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createMP-component---cartView--idPOrderNumber-vhi</value>
      <webElementGuid>f6bf21cc-f4cd-4534-bf1b-99f794c440a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createMP-component---cartView--idPOrderNumber-vhi</value>
      <webElementGuid>e62ffffc-42a7-4d4b-a056-330c9520eafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6a900cd1-9372-481e-a86f-26703f39348c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Afficher aide à la saisie</value>
      <webElementGuid>ce7cee4d-3009-445f-849e-0ce8d4fef03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>3b29a47d-c2bd-4071-9f90-f5d2e74a5f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapUiIconPointer sapMInputBaseIcon</value>
      <webElementGuid>9b037cf4-b4a3-4173-b109-8d1768624e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createMP-component---cartView--idPOrderNumber-vhi&quot;)</value>
      <webElementGuid>bdb8ecb7-0945-4f39-914a-cbde86dc09dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-zpurchaserequisition-createMP-component---cartView--idPOrderNumber-vhi']</value>
      <webElementGuid>0e6f84ee-1fdb-4df6-a971-e3044c75f255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaserequisition-createMP-component---cartView--idPOrderNumber-content']/div/span</value>
      <webElementGuid>05d1e53a-33aa-470b-9a3f-19d379a173fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div/span</value>
      <webElementGuid>30a22f39-4943-4ac0-a53b-e14f8c507a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-zpurchaserequisition-createMP-component---cartView--idPOrderNumber-vhi']</value>
      <webElementGuid>a1def4e5-cc75-4ea2-994f-cbf1703b2859</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
