<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User_sap-user</name>
   <tag></tag>
   <elementGuidId>cca60445-1194-4ed7-90c6-a442f4365792</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#USERNAME_FIELD-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='USERNAME_FIELD-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4c9c72d-1dcb-4eeb-975d-20fd1c13038b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USERNAME_FIELD-inner</value>
      <webElementGuid>9764d5d2-ef8f-4a6c-86f6-b4b8af80eb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>46336328-a26a-40c8-8530-17f6fecbdb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4f120f8a-6303-4e9b-86c8-f649787edaac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginInputField</value>
      <webElementGuid>d7ed9a2c-9ad5-4e98-8076-f91e3d4e323f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sap-user</value>
      <webElementGuid>8f2d2681-1ded-4d34-89c9-22f5534da031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12 </value>
      <webElementGuid>38d3bdd7-2b8a-42f6-b7e6-4c63067f99ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>verbatim</value>
      <webElementGuid>89e6f90d-2a94-43ed-83f6-ea2404ab90db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b4eae106-51d5-48a2-857e-d2148463b257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>0ad57b32-40a9-49ee-97c7-e76e8fd76c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User</value>
      <webElementGuid>9ccff55f-4f6d-41de-a1f4-52d379d6aa61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>User</value>
      <webElementGuid>dbfbe6c6-a4dd-4cc8-8053-4c60898e3377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0413d571-c826-4fff-b783-0b918e0bd0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>da9869cf-28b2-40eb-bfaf-9445b92bfffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>USERNAME_LABEL</value>
      <webElementGuid>f0fb2798-a585-4e9f-a249-06c6febb8858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USERNAME_FIELD-inner&quot;)</value>
      <webElementGuid>4ce9945c-a41f-4e0b-b2ed-4a762e2e0323</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='USERNAME_FIELD-inner']</value>
      <webElementGuid>b4c30604-fe7b-49de-8769-0663c72d271f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='USERNAME_BLOCK']/input</value>
      <webElementGuid>5657b342-9ccb-4de3-9c79-0ea7ba932a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>087e8912-5b97-4c54-a3f7-2a00225f7dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'USERNAME_FIELD-inner' and @type = 'text' and @name = 'sap-user' and @placeholder = 'User' and @title = 'User']</value>
      <webElementGuid>2129577f-5596-493b-9390-9ef3f98e4382</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
