<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Posicin OK</name>
   <tag></tag>
   <elementGuidId>539dded5-7aaa-449e-8777-a2e870ab354f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:1:4:1:34::0:0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5b66a4cd-2f22-4368-a17b-2cacbba8c9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>C_standards</value>
      <webElementGuid>635e32ac-3317-44f9-a6c2-0ec004490f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;CheckBox&quot;,&quot;4&quot;:&quot;Posición OK&quot;,&quot;5&quot;:&quot;Posición tomada en el documento&quot;,&quot;9&quot;:&quot;P&quot;,&quot;14&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/ssubSUB_MAIN_CARRIER:SAPLMIGO:0003/subSUB_ITEMDETAIL:SAPLMIGO:0301/subSUB_DETAIL:SAPLMIGO:0300/subSUB_DETAIL_TAKE:SAPLMIGO:0304/chkGODYNPRO-DETAIL_TAKE&quot;,&quot;Type&quot;:&quot;GuiCheckBox&quot;,&quot;focusable&quot;:&quot;X&quot;},&quot;16&quot;:true}</value>
      <webElementGuid>9290157f-4d47-4d39-a726-5aedf4f2ac73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Enter&quot;:[{},{&quot;1&quot;:&quot;vkey/0/ses[0]&quot;,&quot;2&quot;:true}],&quot;Change&quot;:[{},{&quot;1&quot;:&quot;action/7&quot;,&quot;3&quot;:true}],&quot;DoubleClick&quot;:[{},{&quot;1&quot;:&quot;action/2&quot;,&quot;2&quot;:true,&quot;3&quot;:true}]}</value>
      <webElementGuid>8b3f6164-d9bd-41be-a1a6-a23fc2db452f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-currentselectionstate</name>
      <type>Main</type>
      <value>API_DRIVEN</value>
      <webElementGuid>567c1144-d3fa-4d87-a083-49fe52c3f6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsSelector--generic lsSelector--text lsSelector--strechedForEllipsis lsSelector--pushedToStart--spacing lsCheckBox lsCheckBox--unchecked  </value>
      <webElementGuid>948ea6ce-968b-4115-9310-a28d9f255500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>48d50805-12c7-4558-baf1-dd3b4b652a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>de44b549-8e6d-4ea0-a535-38c658b6f36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Posición tomada en el documento</value>
      <webElementGuid>ecf1274a-6b87-4fbe-b07b-67cbacce61be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>f7153ea1-311f-4302-9535-c4167bd2b71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>d8b64cb0-0868-4167-9bda-3e647e12ca85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CheckBox</value>
      <webElementGuid>455b25c3-cf77-434d-a5e5-ddf3529871d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:4:1:34::0:0</value>
      <webElementGuid>48d7b4e0-9cab-483a-9a06-c0b2731e2629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>33973746-11e1-4e4e-88fb-6e95627dd7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5c254ca8-89a0-4217-8d4e-11bcecbb22d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d3ea0b33-b961-4018-b1ba-32146524cc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c2a9bb28-603c-4b8d-9d60-9a6ccd279621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Posición OK</value>
      <webElementGuid>bdce68df-8652-482e-8eef-942440f4a359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e8734028-cec7-448b-84c5-cb98be206330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-controlusage</name>
      <type>Main</type>
      <value>API_DRIVEN</value>
      <webElementGuid>7a2d2f29-b5c7-4d9a-9ee9-4b9e37ca14b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Posición OK</value>
      <webElementGuid>04e334b6-9fcb-4d7c-9a48-e4acd44ce76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:4:1:34::0:0&quot;)</value>
      <webElementGuid>9275e6ac-f9b7-44d7-8346-178f7e8a14f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Movimientos Recepciones/Page_Entrada de mercancas Pedido 4500856944/iframe_Ms_application-Material-goodsReceipt-iframe</value>
      <webElementGuid>0db4cd91-0622-4829-816f-36a0c91c9bd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:4:1:34::0:0']</value>
      <webElementGuid>80853d9c-ca7e-4a86-a530-fc92edfee5c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uCA8']/span</value>
      <webElementGuid>e1a760e5-15ad-4839-b01d-2333d0ae6be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[1]/following::span[7]</value>
      <webElementGuid>115f78bd-a6d1-41e7-9695-75aba79b0046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/span</value>
      <webElementGuid>0f48e1c3-3436-414d-9a18-4a4499b81903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Posición tomada en el documento' and @name = 'CheckBox' and @id = 'M0:46:1:4:1:34::0:0' and (text() = 'Posición OK' or . = 'Posición OK')]</value>
      <webElementGuid>8e32f91f-a7de-43a4-bc40-728f9c25121e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
