<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Documento para inventario 100009770 co_74ec40</name>
   <tag></tag>
   <elementGuidId>901078a5-640f-4264-b137-315ea1de2887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='wnd[0]/sbar_msg-txt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ab9e2774-2b3d-4b3a-9962-65ff43ee9f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>ba67d82e-a786-4d6b-8617-0dc1354e25be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ae19c120-e69a-4fcb-8fc9-c26be52630e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wnd[0]/sbar_msg-txt</value>
      <webElementGuid>1bb936ca-bad9-47ee-98e6-5e472dbff7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsMessageBar__text lsMessageBar__text--overflow</value>
      <webElementGuid>42f6d70e-a3aa-4c8a-931a-ef5bfe826ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Documento para inventario 100009770 contabilizado sin diferencias</value>
      <webElementGuid>4159d9e4-b988-434a-8238-e7f3bbbe6dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Documento para inventario 100009770 contabilizado sin diferencias</value>
      <webElementGuid>5acfaa01-b590-449e-bc17-abfd33d63854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wnd[0]/sbar_msg-txt&quot;)</value>
      <webElementGuid>78b4d1b2-0f24-465d-a4a8-f9ba0d6b9b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Eliminar diferencias Invent/Page_Eliminar diferencias Acceso/iframe_Ms_application-PhysicalInventoryDocu_1d60b6</value>
      <webElementGuid>9d392eab-eb40-46eb-8ed0-01defbe2e906</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='wnd[0]/sbar_msg-txt']</value>
      <webElementGuid>0abe205f-8439-4801-9335-f30b4d07c659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wnd[0]/sbar_msg']/span[2]</value>
      <webElementGuid>42f50eb8-74cf-48ba-9c90-b51184b6a857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='V'])[1]/following::span[3]</value>
      <webElementGuid>9b5b035c-cccb-42e5-895c-99ac3fedb481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visualizar detalles'])[1]/preceding::span[1]</value>
      <webElementGuid>5a7ff0aa-89dc-4598-8bec-8367bcd188f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Documento para inventario 100009770 contabilizado sin diferencias']/parent::*</value>
      <webElementGuid>e90cc540-8c9a-457d-94ff-92496552b3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/span[2]</value>
      <webElementGuid>e2876935-9273-450d-b571-e58d71b3b11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'wnd[0]/sbar_msg-txt' and @title = 'Documento para inventario 100009770 contabilizado sin diferencias' and (text() = 'Documento para inventario 100009770 contabilizado sin diferencias' or . = 'Documento para inventario 100009770 contabilizado sin diferencias')]</value>
      <webElementGuid>ed03b28b-db61-4043-b5f9-6ad426448262</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
