<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Clientes Generales</name>
   <tag></tag>
   <elementGuidId>8903311f-4860-42ec-995c-c279afd6ea09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='u3613-second']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u3613-second</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6bd13cea-11e0-49c1-9d5f-1bc13ff3bf9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u3613-second</value>
      <webElementGuid>fe72855f-cd85-4196-bbfa-7bab5601882a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsListbox__value lsListbox__value--hover</value>
      <webElementGuid>c473f27d-96ab-448c-8dd1-f023113eee60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemid</name>
      <type>Main</type>
      <value>u3613</value>
      <webElementGuid>c3ce0975-c39d-41eb-a559-8fabf52aca64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d3e5bb68-786a-4e15-b6c6-210afa3f1e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>u3613-ariaItemValues</value>
      <webElementGuid>da2c4010-251d-4794-9f30-84e992972b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clientes Generales</value>
      <webElementGuid>75edad38-ae8e-4d62-834e-7c33c3026410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u3613-second&quot;)</value>
      <webElementGuid>43204b48-359b-4f77-b6e0-e15b82d99100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BP Crear Cliente New ID/Page_Crear Organizacin Rol Cliente Datos Sociedad/iframe_Ms_application-BusinessPartner-creat_97ef72</value>
      <webElementGuid>a1726777-75ba-48b1-8b01-d700272d8c0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='u3613-second']</value>
      <webElementGuid>732bace0-0bca-4576-9a18-c36e3af4a0ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BUS_JOEL_MAIN-CREATION_GROUPSAPLBUPA_DIALOG_JOEL_ei-scrl']/div[2]/div[48]</value>
      <webElementGuid>37bcae7c-f609-403c-9574-ddd242b53b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clientes Grupo y Empresas Asociadas'])[2]/following::div[1]</value>
      <webElementGuid>ed4c52d1-5526-4365-86ca-4837648117d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proveedores Direcciones'])[2]/following::div[2]</value>
      <webElementGuid>fe1de1e0-74d6-4003-bc25-1306f5af61f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proveedores Empleados'])[3]/preceding::div[1]</value>
      <webElementGuid>95b1ac7d-0ab2-4700-bb87-244fcd18eb99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proveedores Consejeros y Directivos'])[1]/preceding::div[2]</value>
      <webElementGuid>9f8e7310-8618-4c08-bc48-0476dc4e8433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[48]</value>
      <webElementGuid>b3d7388b-9b9f-42a9-85fc-b871f5115c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'u3613-second' and (text() = 'Clientes Generales' or . = 'Clientes Generales')]</value>
      <webElementGuid>fcc2ae11-84bd-439e-bc24-b12405844ae3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
