<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Para seleccionar una lnea, pulse la ba_b2680d</name>
   <tag></tag>
   <elementGuidId>076888d0-f251-411a-bc0b-1572fdcf2037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:1:1:2:2:1:2B258:1:23:1[1,1]_c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>294f9205-7a9a-4861-973a-9dd3bf8ecf6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>cb4b5b35-1c57-4539-8843-b2bb6c066a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a7a41816-ec92-43e4-a641-8c0eba700269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value> ARIA_CB_F4Lookup_TUT</value>
      <webElementGuid>0388e4b1-0fa6-4dc6-aec8-8bbaacdbcc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a15bbc81-c895-4676-9876-5c27d817d824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9f16ad97-b011-4ffc-9781-8b932f2c0b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:1:2:2:1:2B258:1:23:1[1,1]_c</value>
      <webElementGuid>7e5bcab7-c73f-48be-a72a-c9057af62573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>CBS</value>
      <webElementGuid>530ea732-6f2d-44a7-a947-c0a07cf2545f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;x&quot;:0,&quot;1&quot;:&quot;FREETEXT&quot;,&quot;3&quot;:&quot;M0:46:1:1:2:2:1:2B258:1:23:1::1:1_TALB&quot;,&quot;7&quot;:true,&quot;12&quot;:true,&quot;14&quot;:&quot;SERVER&quot;,&quot;16&quot;:true,&quot;20&quot;:false,&quot;21&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/subSCREEN_3000_RESIZING_AREA:SAPLBUS_LOCATOR:2000/subSCREEN_1010_RIGHT_AREA:SAPLBUPA_DIALOG_JOEL:1000/ssubSCREEN_1000_WORKAREA_AREA:SAPLBUPA_DIALOG_JOEL:1100/ssubSCREEN_1100_MAIN_AREA:SAPLBUPA_DIALOG_JOEL:1101/tabsGS_SCREEN_1100_TABSTRIP/tabpSCREEN_1100_TAB_03/ssubSCREEN_1100_TABSTRIP_AREA:SAPLBUSS:0028/ssubGENSUB:SAPLBUSS:7046/subA07P01:SAPLBUPA_BUTX_DIALOG:0100/tblSAPLBUPA_BUTX_DIALOGTCTRL_BPTAX/ctxtDFKKBPTAXNUM-TAXTYPE[0,0]&quot;,&quot;Type&quot;:&quot;GuiCTextField&quot;,&quot;value&quot;:&quot;&quot;,&quot;maxlen&quot;:4,&quot;focusable&quot;:&quot;X&quot;},&quot;25&quot;:&quot;FILL_FIXED_LAYOUT&quot;}</value>
      <webElementGuid>27eaba53-8fc9-4e5c-837f-f44e6d9ed513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Change&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Select&quot;:[{},{&quot;1&quot;:&quot;value&quot;,&quot;3&quot;:true,&quot;7&quot;:true}],&quot;Validate&quot;:[{},{}],&quot;DeleteItem&quot;:[{},{&quot;3&quot;:true}],&quot;ListAccess&quot;:[{&quot;ResponseData&quot;:&quot;delta&quot;,&quot;TransportMethod&quot;:&quot;full&quot;,&quot;EnqueueCardinality&quot;:&quot;none&quot;},{&quot;3&quot;:true,&quot;8&quot;:&quot;history&quot;,&quot;limitlen&quot;:&quot;X&quot;}],&quot;FieldHelpPress&quot;:[{},{&quot;1&quot;:&quot;vkey/4&quot;,&quot;2&quot;:true,&quot;5&quot;:true}]}</value>
      <webElementGuid>ced90fb0-a284-4084-8bfa-cb49e2d1203a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InputField</value>
      <webElementGuid>1ea72fec-cdf9-47a4-a3e3-6c94a3ae9267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>bd494b3a-3ea1-4fd3-bd6f-f1eaa99266f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsField__input</value>
      <webElementGuid>b137d0c7-3c46-474f-ba8a-f3e5188c3fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cust-sid</name>
      <type>Main</type>
      <value>b0/2XLUdPIKOKNJOJaatXQ==</value>
      <webElementGuid>91684d57-cbbb-48fd-a1a4-2d1157b3d524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:1:2:2:1:2B258:1:23:1[1,1]_c&quot;)</value>
      <webElementGuid>bf1b66e9-f0b8-43fa-9c02-59a35d95d997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BP Crear Cliente New ID/Page_Crear Organizacin Rol Cliente Datos Sociedad/iframe_Ms_application-BusinessPartner-creat_97ef72</value>
      <webElementGuid>b362c799-1c86-43ea-929c-bc6c3f50f650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:1:2:2:1:2B258:1:23:1[1,1]_c']</value>
      <webElementGuid>880d488b-6010-4af2-8357-6e548c09298e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:1:2:2:1:2B258:1:23:1[1,1]_c-r']/span</value>
      <webElementGuid>405cc4f4-fe26-49a6-a225-4df716cf9bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div/table/tbody[2]/tr[2]/td[2]/div/div[2]/table/tbody/tr/td/div/span/span</value>
      <webElementGuid>6727e119-9f1e-4c5e-8bff-3ea0c0bee2fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'M0:46:1:1:2:2:1:2B258:1:23:1[1,1]_c' and @name = 'InputField']</value>
      <webElementGuid>e591d10a-963d-4b25-aecd-4c2bd63992c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
