<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Log On</name>
   <tag></tag>
   <elementGuidId>c551410a-c4c3-44a4-978c-8de7e00c8438</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='LOGIN_LINK']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LOGIN_LINK</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>994c5df8-a7cc-4f33-bfc1-d9add10138c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LOGIN_LINK</value>
      <webElementGuid>1111e5f6-074a-4857-a4c2-0793784fb97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>adb2c117-4d06-4973-8fd7-39fc0e08072f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginButton sapUiButtonEmphasized</value>
      <webElementGuid>c52f412d-a856-4607-abb1-93eb054f495e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5c151c45-d57a-4c59-9d78-b3817551c906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Log On</value>
      <webElementGuid>376663f8-1148-4666-bf44-4bc3602c0d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log On</value>
      <webElementGuid>ee470938-5123-4043-9c2e-eb765a9cd9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LOGIN_LINK&quot;)</value>
      <webElementGuid>97723936-399c-4ba5-ad93-3a7e2538c633</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='LOGIN_LINK']</value>
      <webElementGuid>e7bd9548-5c30-4c78-b0ca-18bdf0fa370e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LOGIN_SUBMIT_BLOCK']/button</value>
      <webElementGuid>d66a9268-26b5-4ee0-bce3-a041064bc268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/following::button[1]</value>
      <webElementGuid>af67411f-c1f8-4e15-a2b7-1091111b3232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>9c2d06b2-ca90-45c2-b81c-4647b3cdf8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/preceding::button[1]</value>
      <webElementGuid>c28861dc-170c-4667-9e22-daa16ffb3657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2025 SAP SE All Rights Reserved.'])[1]/preceding::button[2]</value>
      <webElementGuid>c479a241-7b52-4321-b436-bf1e6ecaa74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log On']/parent::*</value>
      <webElementGuid>4488844e-d1ba-4570-8ca4-5f62fee59c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>06d62840-6abd-4897-99c9-f705983a9fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'LOGIN_LINK' and @type = 'submit' and @title = 'Log On' and (text() = 'Log On' or . = 'Log On')]</value>
      <webElementGuid>9c375895-c650-4d2b-a0bc-0872f46884b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
