<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Correttiva_application-ZPM_SMART-GESTP_8bc314</name>
   <tag></tag>
   <elementGuidId>c5d00cc5-462f-455d-a0bc-ba88fee406aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTPREVEN-component---main--idLiberarBtn-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-ZPM_SMART-GESTAUDIT-component---main--idLiberacionBtn-img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>685c1bc8-10c4-4921-8926-5f9f074ccd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---main--idLiberarBtn-img</value>
      <webElementGuid>15cc5d26-465c-4315-935f-fd3ba502c543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---main--idLiberarBtn-img</value>
      <webElementGuid>bf95a220-8a17-4cc2-9491-90a609d36975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>f2ff49ea-46c5-402a-a15d-6bdd2d7ba8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eeac8917-b711-47a6-b268-36e9b914d975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>eec7a0fe-5a4a-44a3-b147-6f6a71c82b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapMBtnCustomIcon sapMBtnIcon sapMBtnIconLeft</value>
      <webElementGuid>d3522f78-83ec-4b39-a031-c26c85cc1c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTPREVEN-component---main--idLiberarBtn-img&quot;)</value>
      <webElementGuid>b9e33d02-0eef-4529-b081-a5e00837c230</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-GESTAUDIT-component---main--idLiberarBtn-img']</value>
      <webElementGuid>d0b0f998-f84a-42f0-8c00-e616122bdf76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-GESTAUDIT-component---main--idLiberarBtn-inner']/span</value>
      <webElementGuid>b89f73ba-818b-4259-b53a-baf71c5af681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button[3]/span/span</value>
      <webElementGuid>e20fe66c-2c2e-4417-a8ec-d783759ef392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-ZPM_SMART-GESTAUDIT-component---main--idLiberarBtn-img']</value>
      <webElementGuid>5eae3026-e20d-457c-a473-13471ef841bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
