<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Ms Datos</name>
   <tag></tag>
   <elementGuidId>52ac7ac3-b6b9-4afa-a07f-10c7b2484154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='application-zpurchaserequisition-createMP-component---detail--idMoreDataPosition-BDI-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createMP-component---detail--idMoreDataPosition-BDI-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>da2ad5e3-503e-4398-b4a0-a64af3ddd06d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createMP-component---detail--idMoreDataPosition-BDI-content</value>
      <webElementGuid>3e806f0a-3bf1-4e19-8a49-06d4d5111aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>716137b4-3778-4da3-b7c2-f586f7299178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Más Datos</value>
      <webElementGuid>db854134-44b9-4c47-9f91-ab1603a56580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createMP-component---detail--idMoreDataPosition-BDI-content&quot;)</value>
      <webElementGuid>a2cfd772-da69-4faa-96f1-03e1b15fbdc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='application-zpurchaserequisition-createMP-component---detail--idMoreDataPosition-BDI-content']</value>
      <webElementGuid>e90d0631-35e5-4a6b-b495-de78460c79f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-zpurchaserequisition-createMP-component---detail--idMoreDataPosition-content']/bdi</value>
      <webElementGuid>79d2bdff-26d0-440e-b09a-48507b90535e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posiciones'])[4]/following::bdi[1]</value>
      <webElementGuid>a012189f-e9ea-4db4-8d04-2d75ebf8be89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mostrar más'])[1]/following::bdi[1]</value>
      <webElementGuid>998cf5cf-f89a-4df4-ba2d-1738c9ff282a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copia Masiva'])[1]/preceding::bdi[1]</value>
      <webElementGuid>d8e39bd2-5a75-4530-aba2-824732c137f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copiar'])[1]/preceding::bdi[2]</value>
      <webElementGuid>c3a2ac33-03e2-4fbd-b023-93d6d8d20c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/button/span/span[2]/bdi</value>
      <webElementGuid>45d5a09a-9690-4ca0-97c6-37c43103b34d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'application-zpurchaserequisition-createMP-component---detail--idMoreDataPosition-BDI-content' and (text() = 'Más Datos' or . = 'Más Datos')]</value>
      <webElementGuid>12d2fad8-9b85-4295-98b9-80b062d82c27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
