<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sociedad CORCO (CG59)Plan de cuentasPla_a0a4a7</name>
   <tag></tag>
   <elementGuidId>c17c7e77-1f2c-42c3-a8e6-6b5a97b381dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__container50--Grid']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__container50--Grid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e1c6760b-a578-40c2-96e5-e58c657fb3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__container50--Grid</value>
      <webElementGuid>cd9d732f-8d65-4c84-9340-852fdc18e943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__container50--Grid</value>
      <webElementGuid>e892d06b-6c33-4231-b36b-bf0a5b465b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiRespGrid sapUiRespGridMedia-Std-Phone sapUiRespGridHSpace0 sapUiRespGridVSpace0 sapUiFormResGridCont sapUiRespGridOverflowHidden</value>
      <webElementGuid>a4d4e218-7a42-4656-9716-73765a4eb0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sociedad CORCO (CG59)Plan de cuentasPlan de cuentas de México (PCMX)Tipo de imputaciónProyecto Inversión (O)Cuenta de mayorPinturas (6220030001)Centro de costeElemento PEPNecesidadEstado de valor: Error Pos CG5922001193 - código de impuesto   no válidoCentro de beneficio</value>
      <webElementGuid>cabfabb4-657b-4f1e-a5cb-cee889d3d8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__container50--Grid&quot;)</value>
      <webElementGuid>8c03d848-3b30-48a8-a19f-0fc3cf913305</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__container50--Grid']</value>
      <webElementGuid>041da9ea-e4ba-4847-87e3-04308943680d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaserequisition-createMP-component---cartView--idLytAccountAssignment']/div</value>
      <webElementGuid>750e705a-4696-40a9-8ef0-fc950480ab3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imputación'])[5]/following::div[12]</value>
      <webElementGuid>615f48bf-a1f9-4f54-bbe6-7a685c16aba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mostrar más'])[3]/following::div[14]</value>
      <webElementGuid>37516370-dcb3-45cb-8235-7b7a944e2080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/section/div/div/div/section[2]/section[2]/div[2]/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>19380da2-c22b-4d7d-bd34-34aa7721679f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__container50--Grid' and (text() = 'Sociedad CORCO (CG59)Plan de cuentasPlan de cuentas de México (PCMX)Tipo de imputaciónProyecto Inversión (O)Cuenta de mayorPinturas (6220030001)Centro de costeElemento PEPNecesidadEstado de valor: Error Pos CG5922001193 - código de impuesto   no válidoCentro de beneficio' or . = 'Sociedad CORCO (CG59)Plan de cuentasPlan de cuentas de México (PCMX)Tipo de imputaciónProyecto Inversión (O)Cuenta de mayorPinturas (6220030001)Centro de costeElemento PEPNecesidadEstado de valor: Error Pos CG5922001193 - código de impuesto   no válidoCentro de beneficio')]</value>
      <webElementGuid>32b29069-3e89-40f3-80d0-1929023262c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
