<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_57900002</name>
   <tag></tag>
   <elementGuidId>51dbbc46-cd09-42e0-b004-389efc0955f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:46:2:1:2B256:4::2:30_TALB-item-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4822ef06-197f-4112-9231-6c6f92499ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:2:1:2B256:4::2:30_TALB-item-1</value>
      <webElementGuid>10785670-ad90-4fc0-92d7-a40815ebbb3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsListbox__value lsListbox__value--hover</value>
      <webElementGuid>5d700af0-6082-4ad5-b697-8c515c77c17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemid</name>
      <type>Main</type>
      <value>M0:46:2:1:2B256:4::2:30_TALB-item-1</value>
      <webElementGuid>567f423e-f8d4-47d9-9e17-fb9f30d6fbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>LIB_I</value>
      <webElementGuid>7e907dbd-e1d1-4acf-a2f7-d9f24e91bd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;1&quot;:&quot;&quot;,&quot;4&quot;:&quot;&quot; }</value>
      <webElementGuid>33870be4-2dc9-44a4-a462-1e4c77fddc47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3b717cd9-ae46-4f0b-82f3-4e076acfa3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemkey</name>
      <type>Main</type>
      <value>3ta__57900002</value>
      <webElementGuid>4ed72154-1750-4118-8936-aba24e804494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemvalue1</name>
      <type>Main</type>
      <value>57900002</value>
      <webElementGuid>00c1c043-b4a0-4b19-abdc-0131475afa21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0045e83f-0076-41ac-9a7a-70d938b53a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>173456dc-8c8b-4e81-ad98-425e7ada736e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>691b7279-7b3e-4180-afc2-8944043c9267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>M0:46:2:1:2B256:4::2:30_TALB-item-1-ariaItemValues</value>
      <webElementGuid>03c22521-f594-409e-851e-8bf871c6bcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>57900002</value>
      <webElementGuid>082cd101-3a7d-4bf9-a115-92cbcb647a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:2:1:2B256:4::2:30_TALB-item-1&quot;)</value>
      <webElementGuid>fb9fbeb9-9384-456b-abf7-a94eee5c676d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Creacion cuenta mayor/Page_Cta.mayor Crear Central/iframe_Ms_application-GLAccount-editGLAccou_e2c8b9</value>
      <webElementGuid>dde8225f-74f6-44c5-816e-59e733bed576</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M0:46:2:1:2B256:4::2:30_TALB-item-1']</value>
      <webElementGuid>82815e84-d32a-44c3-a536-33032ee589c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46:2:1:2B256:4::2:30_TALB-1']/div[4]</value>
      <webElementGuid>d0f3658a-f20e-4f78-a68d-4e73c57ac889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vacía'])[5]/following::div[6]</value>
      <webElementGuid>6565af65-c289-4232-99e5-3d27cbda57c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[7]/preceding::div[3]</value>
      <webElementGuid>3325413a-7dd9-4443-ac94-7092a9443e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[8]/preceding::div[4]</value>
      <webElementGuid>464b1895-9262-4ac5-8149-7446c5e4fb47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[4]</value>
      <webElementGuid>773153bd-027b-4104-838c-c9da575eee33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M0:46:2:1:2B256:4::2:30_TALB-item-1' and (text() = '57900002' or . = '57900002')]</value>
      <webElementGuid>b0c038fc-8e1e-4b86-9b3e-967afa4899d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
