<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Ms_application-GLAccount-editGLAccou_e2c8b9</name>
   <tag></tag>
   <elementGuidId>2728eceb-3c0e-411b-afff-7643b098f9a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='application-Shell-startGUI-iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-GLAccount-editGLAccountCentrally-iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8dc31470-18e8-4401-b9b4-f95860e98e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-GLAccount-editGLAccountCentrally-iframe</value>
      <webElementGuid>fe24423f-8e4a-4e51-837b-98d1a77f796b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-GLAccount-editGLAccountCentrally-iframe</value>
      <webElementGuid>8ec7cff6-45cc-4c4a-84db-cab744f2f233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application-GLAccount-editGLAccountCentrally-iframe</value>
      <webElementGuid>1d1832e9-0921-49d8-b6df-0b47c43df624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-orig-src</name>
      <type>Main</type>
      <value>/sap/bc/gui/sap/its/webgui;~sysid=R3Q;~service=3200?~transaction=FS00&amp;sap-client=100&amp;sap-language=ES&amp;~nosplash=1&amp;sap-iframe-hint=GUI&amp;sap-ie=edge&amp;sap-theme=abertis_theme_corp%40https%3A%2F%2Fsaps4-pre.abertis.com%2Fsap%2Fpublic%2Fbc%2Fthemes%2F~client-100%2F~cache-EffUt0nnNFsxi7WxmjEKOoghmzc&amp;sap-touch=0&amp;sap-target-navmode=inplace&amp;sap-keepclientsession=2&amp;sap-ushell-timeout=25&amp;sap-shell=FLP1.120.28</value>
      <webElementGuid>3c8316d4-152e-443e-a613-7c7bd17c84e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aplicación</value>
      <webElementGuid>96bfba99-acdd-4bf7-8e7f-5c4c0873117a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-iframe-idx</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0189ae33-204f-48d6-99b8-46eb898fdf4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay ;battery ;camera ;display-capture ;geolocation ;gyroscope ;magnetometer ;microphone ;midi ;clipboard-write ;clipboard-read ;fullscreen ;serial ;</value>
      <webElementGuid>1f0c336e-eb23-472f-b5dd-b704a9d8e5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUShellApplicationContainer</value>
      <webElementGuid>b15e4daf-5692-41e1-a692-d500f3a51683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-GLAccount-editGLAccountCentrally-iframe&quot;)</value>
      <webElementGuid>b79052f5-e753-4062-9fd1-804cd64fdb9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='application-GLAccount-editGLAccountCentrally-iframe']</value>
      <webElementGuid>6ea2ad47-e20d-4f9b-a7a1-8eb588777824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-GLAccount-editGLAccountCentrally']/iframe</value>
      <webElementGuid>f0715099-a0e3-4109-a6e6-471a85f528dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>df332ac9-06ac-456a-a42e-5483aaaa0bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'application-GLAccount-editGLAccountCentrally-iframe' and @name = 'application-GLAccount-editGLAccountCentrally-iframe' and @title = 'Aplicación']</value>
      <webElementGuid>9b15fd4a-7008-4a67-a573-6696a6479585</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
