<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pedido Contr. Valor creado bajo el nme_6c9e60</name>
   <tag></tag>
   <elementGuidId>a1a6c611-2ada-4f1e-afc1-3e2346af8995</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__text571</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__text571']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8242b1e6-1fd3-46b4-b98c-10e75a231e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text571</value>
      <webElementGuid>6ccc9273-9dec-4ec0-a74a-787c7f6c0c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text571</value>
      <webElementGuid>aadd5175-0140-40a9-8750-6e2b4ccd4307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>5d09edef-a1b7-4e2d-a003-015d100264ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextMaxWidth sapMMsgBoxText</value>
      <webElementGuid>f8dbacbf-5516-43d9-9557-65a301fefaa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pedido Contr. Valor creado bajo el número 4500857942</value>
      <webElementGuid>771939a6-793c-442d-9972-76dcfedbb04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text571&quot;)</value>
      <webElementGuid>7ff4fab5-1cc5-4385-b134-b06079749aa9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__text571']</value>
      <webElementGuid>347b91fc-563b-439e-859f-59836b8623ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__success1-scrollCont']/span</value>
      <webElementGuid>2d8b9d70-67bd-47e9-936d-4a79aa4a50f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Éxito'])[1]/following::span[2]</value>
      <webElementGuid>d88d3fbf-bb7d-4e45-9cee-e067909a63c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sin presupuesto para las posiciones 00010'])[1]/following::span[13]</value>
      <webElementGuid>d44ccdbd-fbaf-467f-8784-4e667237478d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::span[1]</value>
      <webElementGuid>8651db84-a2c0-4469-823d-7d38be5888d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::span[6]</value>
      <webElementGuid>406cd609-4314-4baf-ab4b-c67afa405a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pedido Contr. Valor creado bajo el número 4500857942']/parent::*</value>
      <webElementGuid>cd7fcf4a-7426-4fef-b395-d4f6caecebcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/span</value>
      <webElementGuid>647402d1-0c0f-483f-a5f1-ad8ae138467e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__text571' and (text() = 'Pedido Contr. Valor creado bajo el número 4500857942' or . = 'Pedido Contr. Valor creado bajo el número 4500857942')]</value>
      <webElementGuid>b8b7ed66-edc1-42a9-b499-48fda2815117</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
