<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_200049209210</name>
   <tag></tag>
   <elementGuidId>817dc349-3c9c-40b7-8270-ac873dce3597</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div[2]/div/section/div/div[2]/div[2]/div[2]/div/div/div/div/div/div/article/div[2]/div/div/div[1]/div[2]/div/div/div/div/table/tbody/tr[2]/td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__link11-__clone551</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71e8ee88-d51f-427e-878c-96f4e6ff3390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__link11-__clone551</value>
      <webElementGuid>e7a85a9c-5d02-43ce-a797-547b2bea333a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__link11-__clone551</value>
      <webElementGuid>37f569e4-4a30-44a6-8c7c-33022e78c1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>af487f20-c515-48d3-bdbe-a27153fbf4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>com.abertis.mm.zpurchaserequisitionlr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosPurchaseRequisitionLR--template:::TableColumn:::DataFieldWithIntentBasedNavigation:::sSmartTableId::listReport-Group:::sProperty::PRObjectId:::sSemanticObject::zpurchaserequisition:::sAction::display __text724 __link11-__clone551</value>
      <webElementGuid>d5142156-6b64-4aeb-8cd2-17719907ee3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9bd8a24-0628-431a-a5ce-5c3bc84eed7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMLnk sapMLnkWrapping sapMLnkMaxWidth</value>
      <webElementGuid>c5271be3-2f46-4f30-8787-5eae8fd25f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2000492092/10</value>
      <webElementGuid>4c12cc6f-f426-46ec-ad5e-c62c5929eb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__link11-__clone551&quot;)</value>
      <webElementGuid>921995af-da75-43f7-982d-8ba0a7441729</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='__link11-__clone551']</value>
      <webElementGuid>2d86a808-2b60-4dd7-89be-4ea1addb17b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='com.abertis.mm.zpurchaserequisitionlr::sap.suite.ui.generic.template.ListReport.view.ListReport::ZC_PosPurchaseRequisitionLR--template:::ListReportTable:::QuickVariantSelectionXColumnListItem:::sQuickVariantKey::Group-__clone551_cell0']/a</value>
      <webElementGuid>09cce5e3-a58f-4ae0-b22a-864918bf3ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2000492092/10')]</value>
      <webElementGuid>94abe475-ff10-4239-828d-46f58fc68940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prezzo totale'])[1]/following::a[1]</value>
      <webElementGuid>f7b873dc-6da6-46c3-bb08-07295b5f0225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qtà richiesta'])[1]/following::a[1]</value>
      <webElementGuid>38a1b6b8-3a45-4e19-a6f8-0fc56f37e23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autorizzazione in corso'])[1]/preceding::a[2]</value>
      <webElementGuid>e8f821fd-bb41-41bd-9252-8ffe9792ff51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autostrada BS VR VI PD (3301)'])[1]/preceding::a[2]</value>
      <webElementGuid>654346a0-af5b-4bde-a0a2-2b8df0a133dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2000492092/10']/parent::*</value>
      <webElementGuid>cdd3f8ed-a187-41ad-94dd-40a38fcb16e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>255baba1-2e5f-4124-99d0-4d4461a308de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '__link11-__clone551' and (text() = '2000492092/10' or . = '2000492092/10')]</value>
      <webElementGuid>881d67d9-cd6f-43d3-afd8-392e873a11f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
