<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Valorazzione</name>
   <tag></tag>
   <elementGuidId>51e2fa6f-e4d5-44d7-8d61-389eee181b08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div[2]/div/section/div/div[2]/div[2]/div[2]/div/div/div/div/div[2]/div[1]/div/div/div/div/section/div/div[2]/div/section[2]/section[2]/div[2]/div/div[1]/div/div/div/table/tbody/tr/td[12]/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-display-component---detail--idPPrice-__clone552-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7075760a-fb63-4418-bba0-76027cb815e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-display-component---detail--idPPrice-__clone552-inner</value>
      <webElementGuid>0fed118f-12d6-498e-9072-f657d2fbe54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1,00</value>
      <webElementGuid>8c0a065b-2778-44b6-b776-8ee945fcf7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__label384</value>
      <webElementGuid>2bf5b3ee-c499-4203-a12c-a115e908e6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec201d54-7ed4-429c-b3c7-0b34a74c7b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8750a9df-ff77-4baa-b940-8b256bc1b7b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>614590a1-8971-4938-9f4c-c67f8f966d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-display-component---detail--idPPrice-__clone552-inner&quot;)</value>
      <webElementGuid>07c02db9-2355-4982-8194-8c9d333c3e68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-zpurchaserequisition-display-component---detail--idPPrice-__clone552-inner']</value>
      <webElementGuid>c38709b9-62df-4c96-98db-774b2da81db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaserequisition-display-component---detail--idPPrice-__clone552-content']/input</value>
      <webElementGuid>1551b5a0-39fb-4d0d-a2b4-65e75bdde8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/div/div/input</value>
      <webElementGuid>a8b3a3b5-26a6-4cfc-b68b-a3198e82ea64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-zpurchaserequisition-display-component---detail--idPPrice-__clone552-inner' and @type = 'text']</value>
      <webElementGuid>58a4755f-65df-4b73-908f-ed787f2bfc91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
