<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Division</name>
   <tag></tag>
   <elementGuidId>7ceb5bd7-674c-4c58-a087-8078a6b646e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[4]/div/div[4]/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaseorder-createPOfromContract-component---detail--idPPlant2-__clone81-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbce9712-0647-4120-b319-d3a108ae1081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaseorder-createPOfromContract-component---detail--idPPlant2-__clone81-inner</value>
      <webElementGuid>461f8e1b-f4f3-4811-ae75-5d8127570713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>cdca2b78-d38a-46b6-9cdc-d7f1c89d2d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__label90-__clone81</value>
      <webElementGuid>f82f805c-9745-43f9-bbcc-00bfd102c82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text37 application-zpurchaseorder-createPOfromContract-component---detail--idPPlant2-__clone81-SuggDescr</value>
      <webElementGuid>4a695df1-bfd9-4556-9210-5ac5c50586f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>845ec62a-d9bb-4dd3-b41f-e01b0cd57fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>555ad191-6a2e-4bd7-93ab-bec757d531b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a815fb6e-85b9-4d48-9ab9-59b243edd629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>38ccb167-d141-4e11-a002-03865a390bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaseorder-createPOfromContract-component---detail--idPPlant2-__clone81-inner&quot;)</value>
      <webElementGuid>aa9450cf-63a3-4c6f-b837-5155460c1720</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-zpurchaseorder-createPOfromContract-component---detail--idPPlant2-__clone81-inner']</value>
      <webElementGuid>7fa3d934-34b0-44a2-9639-81d16a852346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaseorder-createPOfromContract-component---detail--idPPlant2-__clone81-content']/input</value>
      <webElementGuid>444fde22-a4e7-4e0f-8947-0e6263166979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div[4]/div/div/input</value>
      <webElementGuid>319a6a70-594e-4f7e-952a-87a755e44875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-zpurchaseorder-createPOfromContract-component---detail--idPPlant2-__clone81-inner' and @type = 'text']</value>
      <webElementGuid>bdc3154d-ef25-4b90-b2fc-a3aca1b63067</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
