<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Quantita_3</name>
   <tag></tag>
   <elementGuidId>5bc2c55f-6fbb-4684-a466-a0e6cc63eabb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div[2]/div/section/div/div[2]/div[2]/div[2]/div/div/div/div/div[2]/div[4]/div/div/div/div/section/div/div[2]/div/section[2]/section[2]/div[2]/div/div[1]/div/div/div/table/tbody/tr[3]/td[5]/div/div[4]/div/div[1]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaseorder-createPOfromContract-component---detail--idPQuantity2-__clone151-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>511aa3d5-33a3-4043-af82-7b11e1ebaece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaseorder-createPOfromContract-component---detail--idPQuantity2-__clone151-inner</value>
      <webElementGuid>86ed4f23-8054-472f-b8b8-43d3c8dc2d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0,000</value>
      <webElementGuid>016f2d4a-b184-4dbe-a90e-08dfaf5da5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-zpurchaseorder-createPOfromContract-component---detail--idPQuantity2-__clone151-descr</value>
      <webElementGuid>39e23f57-7088-4938-bb1c-7d38e4daca7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>75e3f51a-9784-41ce-af91-b452d8975ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1114b0fe-078e-4533-bb35-145f7ffbc695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>bf556c86-e1f9-4516-af89-cb02fa7050cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaseorder-createPOfromContract-component---detail--idPQuantity2-__clone151-inner&quot;)</value>
      <webElementGuid>0e4903ae-6014-406f-9578-0a3d35ced62d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-zpurchaseorder-createPOfromContract-component---detail--idPQuantity2-__clone151-inner']</value>
      <webElementGuid>cc9c1d06-2327-4ed1-a5c4-028f861cdd8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zpurchaseorder-createPOfromContract-component---detail--idPQuantity2-__clone151-content']/input</value>
      <webElementGuid>305785d6-f58b-4e07-b9bb-6e0acf5cd5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/div/div[4]/div/div/input</value>
      <webElementGuid>0e59c81f-69ff-4c53-8e02-35df0cb3f3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-zpurchaseorder-createPOfromContract-component---detail--idPQuantity2-__clone151-inner' and @type = 'text']</value>
      <webElementGuid>b764c59b-1fc9-427b-adc2-1b7691949a4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
