<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CheckVerde</name>
   <tag></tag>
   <elementGuidId>63c2f867-33b4-48bc-b6ab-27f45d0949e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[7]/div/div/div/div/footer/div/button/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaseorder-createPOfromContract-component---cartView--idButtonPosition-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>174191cb-0b6c-44b8-8e45-0049a94548de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaseorder-createPOfromContract-component---cartView--idButtonPosition-img</value>
      <webElementGuid>f19898b4-a606-46fa-8dd4-2090ee20444f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-zpurchaseorder-createPOfromContract-component---cartView--idButtonPosition-img</value>
      <webElementGuid>1e55725c-7927-4c95-9d3f-76670128c8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>65c8671c-48d7-49ac-9c2f-8a05ba2fa235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>09518956-1023-4805-92e4-6b94264dc067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>71cca4c4-1200-43cd-ba0a-2a434d40a0fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapMBtnCustomIcon sapMBtnIcon sapMBtnIconLeft</value>
      <webElementGuid>8d1ea80a-2d5d-4a6c-80ab-1ec155ace3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaseorder-createPOfromContract-component---cartView--idButtonPosition-img&quot;)</value>
      <webElementGuid>7821ea19-a25a-46f6-8cb6-05cb838e4ec7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-zpurchaseorder-createPOfromContract-component---cartView--idButtonPosition-img']</value>
      <webElementGuid>c92792e7-e6b5-4fe1-8e9a-4a7a8680524b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-zpurchaseorder-createPOfromContract-component---cartView--idButtonPosition-inner']/span</value>
      <webElementGuid>2afd8589-4b81-47c8-864a-b5fb3a3b05e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/footer/div/button/span/span</value>
      <webElementGuid>cf4ac928-59a0-46d9-94d1-479b4f3a7dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-zpurchaseorder-createPOfromContract-component---cartView--idButtonPosition-img']</value>
      <webElementGuid>c0469675-2ecd-4272-936e-179ccf1e06c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
