<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Seleccin mltiple___xmlview12--myInbox_45e9a0</name>
   <tag></tag>
   <elementGuidId>2bd9e023-f613-499d-949e-324a109c8537</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, '--myInbox_SEARCH-I')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview12--myInbox_SEARCH-I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>865ef33d-4fcb-4178-a9c4-e3f45423ff73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview12--myInbox_SEARCH-I</value>
      <webElementGuid>f7bb7d3f-dfdf-4b20-96ac-69cad117a62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>84f6d2ee-28fc-43ef-89b6-4fd66a75276f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>2a54fde8-dccd-43bf-9df7-1fc4ae635263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>567d91b9-d0e4-4434-bc8d-10b3f564755d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>17069a78-69b8-4af7-9588-a912d539a7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text336 __text337</value>
      <webElementGuid>be0de34a-b01c-4df5-993b-ba664563169b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSFI</value>
      <webElementGuid>d6ecf9f4-05f6-4f0a-b84c-7609fa2fa2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview12--myInbox_SEARCH-I&quot;)</value>
      <webElementGuid>992c0f0d-56ca-412c-9398-a5097c89a28b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__xmlview12--myInbox_SEARCH-I']</value>
      <webElementGuid>b407e1f2-0903-4e8f-9ef6-047bcb66da41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='__xmlview12--myInbox_SEARCH-F']/input</value>
      <webElementGuid>f5c47f58-5f18-480d-a1b4-9eaf2089083b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>547b3c84-7892-4650-aa09-70639513868d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '__xmlview12--myInbox_SEARCH-I' and @type = 'search' and @placeholder = 'Buscar']</value>
      <webElementGuid>9bca0ed5-2669-45d6-a3b2-469576c68c84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
