<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aplicar</name>
   <tag></tag>
   <elementGuidId>3e2ee083-1c9f-4887-a7aa-db34fe01326a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:46:1:2B256::0:0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b935b13d-ac7a-4aa4-b329-180784fc8d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d3b986fe-9635-48bf-9d6a-aa8988d27110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:2B256::0:0</value>
      <webElementGuid>54ffa1ea-2f80-4b95-82cb-b3c1534d5dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>B</value>
      <webElementGuid>f2961dd0-929b-4f43-8681-7c55a7f22cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;Aplicar&quot;,&quot;3&quot;:&quot;100%&quot;,&quot;17&quot;:&quot;A&quot;,&quot;20&quot;:true,&quot;21&quot;:true,&quot;27&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/tabsTAB_MAIN/tabpTAB1/ssubTAB_MAIN_SUBSCREEN:/OPT/SAPLVIM_PMC_UI_COMP:1001/btnBT_H_APPLY&quot;,&quot;Type&quot;:&quot;GuiButton&quot;}}</value>
      <webElementGuid>f605a21a-ba68-473c-ada2-7117f9df9a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Press&quot;:[{},{&quot;1&quot;:&quot;action/3&quot;,&quot;2&quot;:true,&quot;3&quot;:true}]}</value>
      <webElementGuid>31e4832f-c46c-4770-a66c-d78d17965532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cust-sid</name>
      <type>Main</type>
      <value>TvY14DJJ0wqztMeGYP60fQ==</value>
      <webElementGuid>81e02103-dc19-44fb-9638-834d560b300e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56a8fd78-b639-4751-8a99-8516ba18a38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>A</value>
      <webElementGuid>a9c9a84b-cc8c-4bd5-aecc-d824a3afbd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>A</value>
      <webElementGuid>6b09c8b9-9160-4403-9d41-63d95539c477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>20d10eac-ac7a-40a1-8f37-c7e32d5c9d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9a6d42a4-c571-484c-9640-bf0e879ab633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsControl--explicitwidth lsControl--fullwidth lsButton lsButton--base lsButton--overflow urNoUserSelect urBtnRadius lsButton--active lsButton--focusable lsButton--up lsButton--design-standard lsButton--hoverable</value>
      <webElementGuid>209800d7-fd09-462b-b1c7-b2d5e34f19d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aplicar</value>
      <webElementGuid>345aba58-2295-4d88-baa6-95fd743057f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:2B256::0:0&quot;)</value>
      <webElementGuid>2ed67e53-a3ac-4d14-9a87-5a3bdbf0668f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VIM Creacion factura sin pedido sin diferencias/Page_rea de trabajo de VIM Invoice  Todas l_8ce86e/iframe_Ms_application-zgui_opt_vim_wp-displ_b9e7ed</value>
      <webElementGuid>6e4baa92-1e33-4060-afd7-e2c21198c6a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M0:46:1:2B256::0:0']</value>
      <webElementGuid>b6f4821e-c7b0-4715-a23c-7206e981c7af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u3B9E']/div</value>
      <webElementGuid>a2149740-26fa-4608-8fdb-1773eb4a22c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todas ba.'])[2]/following::div[5]</value>
      <webElementGuid>64430f42-f798-43a4-8937-5184cc952e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todas comple.'])[1]/following::div[7]</value>
      <webElementGuid>d114dc57-08f7-4df0-bf5f-a20a13774a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/table/tbody/tr/td/div/div/div/div/div</value>
      <webElementGuid>fed97ba8-5492-4c5a-91b0-611e1204a690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M0:46:1:2B256::0:0' and (text() = 'Aplicar' or . = 'Aplicar')]</value>
      <webElementGuid>a5c15759-e0cb-406f-a562-2b9ef67f16a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
