<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_VA01___xmlview3--standardTileContent-___0d8dae</name>
   <tag></tag>
   <elementGuidId>3329e2e6-e060-4214-8ee3-781fde547fa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__xmlview3--standardTileContent-__clone102</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__xmlview3--standardTileContent-__clone102']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>61133994-ac04-4e37-b6d5-0f5a115f3625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview3--standardTileContent-__clone102</value>
      <webElementGuid>c20c6159-6d5e-4e37-affe-2fd8b1d87296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__xmlview3--standardTileContent-__clone102</value>
      <webElementGuid>9149f0e9-5a92-4383-bbe9-67423a7337b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMTileCnt sapMFrameTypeAuto sapMGTNoPriority</value>
      <webElementGuid>efcbfbb2-ff70-46b2-9ede-e6855b22c1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview3--standardTileContent-__clone102&quot;)</value>
      <webElementGuid>a935fc0a-d487-4bc7-9b85-eda8ead2937b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__xmlview3--standardTileContent-__clone102']</value>
      <webElementGuid>89ab1945-5ddf-4c44-ab0f-086cf6ca1ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__tile19-content']/div</value>
      <webElementGuid>10b098ba-41a3-4e72-8476-173632a0b637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VA01'])[1]/following::div[2]</value>
      <webElementGuid>0ad368e7-17ab-491f-b759-63d86033f90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creación de pedidos de cliente'])[1]/following::div[3]</value>
      <webElementGuid>e432d1e0-0010-462b-af02-a7f8499d270f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aviso de mantenimiento'])[3]/preceding::div[10]</value>
      <webElementGuid>baaa788b-57de-42b0-8f0a-be484beac063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denominación del aviso'])[3]/preceding::div[12]</value>
      <webElementGuid>0c13be31-dc07-4ee9-a925-7f7c9dae5f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div</value>
      <webElementGuid>c3385411-3333-45a3-9e11-d2d5252ef920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__xmlview3--standardTileContent-__clone102']</value>
      <webElementGuid>cded6000-50b5-4574-a035-b9fae71a6680</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
