<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_V330</name>
   <tag></tag>
   <elementGuidId>f4fd25a2-984f-4e28-af72-2eb3915ad3ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:46:::5:22_TALB-item-0']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1343b76d-188c-4708-b691-d4502a9c4f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsListbox__highlight</value>
      <webElementGuid>259b749a-ffb3-4b98-9756-a3e16500ea31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>V330</value>
      <webElementGuid>46de2148-2f34-49b9-8091-375154f84166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:::5:22_TALB-item-0&quot;)/span[@class=&quot;lsListbox__highlight&quot;]</value>
      <webElementGuid>5bd77411-5ed0-455a-ae57-2d4017266052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SDCreacion pedido todos los campos/Page_Crear documentos de ventas/iframe_Ms_application-SalesDocument-create-iframe</value>
      <webElementGuid>f6e77440-c42f-4c48-8ae2-004d7259e2ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46:::5:22_TALB-item-0']/span</value>
      <webElementGuid>371712bb-9051-4fd3-845c-73a24427b5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vacía'])[2]/following::span[1]</value>
      <webElementGuid>88dbafe3-9bb6-407e-9295-146975ba85b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OrgVt V336 Descripción Serenissima Trading Elemento de resultado de búsqueda'])[1]/following::span[2]</value>
      <webElementGuid>544fd4a0-3a30-43d0-b3a7-261a8d6eb81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='V335'])[1]/preceding::span[1]</value>
      <webElementGuid>9d34d02d-e00d-49ed-8724-2e055cdf8956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='V336'])[1]/preceding::span[2]</value>
      <webElementGuid>ec414228-84f5-470d-bc8f-65b406d04226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='V330']/parent::*</value>
      <webElementGuid>7e30115e-5265-4cc9-b63b-02c48b91a2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/span</value>
      <webElementGuid>0fd55722-c93f-439a-abcd-6f24b2461787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'V330' or . = 'V330')]</value>
      <webElementGuid>8b37fb7b-a036-40b4-96a1-e0a8bab1c9b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
