<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Procder lachat_2</name>
   <tag></tag>
   <elementGuidId>bcfa2995-355e-4c43-bba9-1b7d3f983a5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div[2]/div/section/div/div[2]/div[2]/div[2]/div/div/div/div/div[2]/section/div/section/div[3]/button/span/span/bdi</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-zcompraguiada-create-component---View1--idProceedWithThePurchase-BDI-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>01c65cfd-01f7-4fa0-bdb0-c823d8dd188c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zcompraguiada-create-component---View1--idProceedWithThePurchase-BDI-content</value>
      <webElementGuid>96e377a6-d576-4709-addb-6c489941b0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Procéder à l'achat</value>
      <webElementGuid>79e8a984-bb63-4f89-ada3-405152409563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zcompraguiada-create-component---View1--idProceedWithThePurchase-BDI-content&quot;)</value>
      <webElementGuid>a3795189-a6d4-4428-95e5-22791ae22811</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='application-zcompraguiada-create-component---View1--idProceedWithThePurchase-BDI-content']</value>
      <webElementGuid>d7d98bfe-59b4-46c2-a1d7-3b193f066782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-zcompraguiada-create-component---View1--idProceedWithThePurchase-content']/bdi</value>
      <webElementGuid>29f660a8-2be3-4df8-a720-1ea5a8c7c4a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contrats Disponibles'])[1]/following::bdi[1]</value>
      <webElementGuid>1d71a2f3-034e-4a6c-9405-2a32801f3a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dés'])[1]/following::bdi[1]</value>
      <webElementGuid>367d1450-9a0c-4e21-9dfa-872942d68502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type de contrat'])[1]/preceding::bdi[1]</value>
      <webElementGuid>7a64c99e-c4bf-4de6-abde-74032f316bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contract'])[1]/preceding::bdi[1]</value>
      <webElementGuid>3fbf6e8d-59a6-42e2-b92b-9b4a1f9dbda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/bdi</value>
      <webElementGuid>38bfa9f0-14dc-4149-8337-02dafebd7af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'application-zcompraguiada-create-component---View1--idProceedWithThePurchase-BDI-content' and (text() = concat(&quot;Procéder à l&quot; , &quot;'&quot; , &quot;achat&quot;) or . = concat(&quot;Procéder à l&quot; , &quot;'&quot; , &quot;achat&quot;))]</value>
      <webElementGuid>e216d16f-ee04-46cf-885a-b77da6bfe576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='application-zcompraguiada-create-component---View1--otros-nextButton-BDI-content']</value>
      <webElementGuid>f66b42d1-45f6-460d-9001-c251839390b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-zcompraguiada-create-component---View1--otros-nextButton-content']/bdi</value>
      <webElementGuid>8fa6f103-da69-4e15-9dd1-6d85c84c75aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Description brève de l', &quot;'&quot;, 'achat')])[1]/following::bdi[1]</value>
      <webElementGuid>636d0607-c10d-4c3c-926b-0f9abcf61db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fournisseur'])[2]/following::bdi[2]</value>
      <webElementGuid>d6c85ec1-e13d-4e64-97f3-d42923915405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::bdi[1]</value>
      <webElementGuid>d36aef94-f04c-4d91-9627-d5cdf65f47ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span/span/bdi</value>
      <webElementGuid>234c071d-bf95-464e-9aba-6ac8c0376add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'application-zcompraguiada-create-component---View1--otros-nextButton-BDI-content' and (text() = concat(&quot;Procéder à l&quot; , &quot;'&quot; , &quot;achat&quot;) or . = concat(&quot;Procéder à l&quot; , &quot;'&quot; , &quot;achat&quot;))]</value>
      <webElementGuid>0bd96796-8406-413c-9352-fab80df82eab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
