<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fornitore</name>
   <tag></tag>
   <elementGuidId>2d9b71d9-134b-4307-afba-a1b9b48e6dba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='application-zcompraguiada-create-component---View1--idHVendorNumber-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-zcompraguiada-create-component---View1--idHVendorNumber-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c098a3fe-5aa2-4808-9bdd-219b019e1dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zcompraguiada-create-component---View1--idHVendorNumber-inner</value>
      <webElementGuid>feb0d459-5207-4999-8e75-44a7b5f39d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>777ed3c8-a67a-4076-ba18-658635612817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eb1d8e1f-1834-47fa-9f15-0d371cd7962f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-zcompraguiada-create-component---View1--idHEVendorNumber-label</value>
      <webElementGuid>75788cb2-6278-465c-8991-1e000915bb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text198 application-zcompraguiada-create-component---View1--idHVendorNumber-SuggDescr</value>
      <webElementGuid>022e71ad-77db-4c23-9578-66c17a76ff7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>591d8cc6-ce9e-41f4-b701-bd02e897eba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4123878-3915-457f-b2f2-ebb1ec1b079b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>532efea0-c08b-4acb-9cbc-e254d214c053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>a1ea3a14-fc06-4768-8efe-2f6f27c40e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zcompraguiada-create-component---View1--idHVendorNumber-inner&quot;)</value>
      <webElementGuid>f7fb46c1-f786-4a13-904f-21eae7926438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-zcompraguiada-create-component---View1--idHVendorNumber-inner']</value>
      <webElementGuid>62a03fc2-8109-4796-bf08-c7da272aa8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zcompraguiada-create-component---View1--idHVendorNumber-content']/input</value>
      <webElementGuid>103e4941-eef4-4181-b2d6-4657ac650399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[14]/div/div/input</value>
      <webElementGuid>c1d0f3e3-c327-4ec6-b657-ec2b7c8f87e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-zcompraguiada-create-component---View1--idHVendorNumber-inner' and @type = 'text']</value>
      <webElementGuid>f8bbb5a8-1e60-4f47-ba5e-053fb1876cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/input</value>
      <webElementGuid>e2abe25b-8c8b-47c8-8a10-418e7c4bbfdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/input</value>
      <webElementGuid>06a3b02a-b963-4326-99bf-1fb2d0418b4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
