<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Centro di costo</name>
   <tag></tag>
   <elementGuidId>554a80d6-136e-498e-bbfe-e97e15807704</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='application-zcompraguiada-create-component---View1--idPCostCenter-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-zcompraguiada-create-component---View1--idPCostCenter-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef217551-8331-4f25-86b9-263ade1aae83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zcompraguiada-create-component---View1--idPCostCenter-inner</value>
      <webElementGuid>984557e2-76bd-4de3-8f73-e2efbb2e190c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>283e82d0-09f8-4792-897f-e8a33f8a2822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e36b6e0b-5528-423c-883a-fe8c2a53cd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__element31-label</value>
      <webElementGuid>b1435c4b-90a9-4f61-9836-01fccd9c5dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text198 application-zcompraguiada-create-component---View1--idPCostCenter-SuggDescr</value>
      <webElementGuid>031e4c78-fec6-4111-af65-c2ceb368871b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>09208e9f-4d8b-4c93-982e-b6e5a7599ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a91d7e82-a64a-4c57-b647-ec6c14558387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a363de79-ba90-4b95-8ae8-0a72db8d2e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>a31f7136-70ba-40dc-92c7-a4c2e057d884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zcompraguiada-create-component---View1--idPCostCenter-inner&quot;)</value>
      <webElementGuid>9f2cdb6f-946d-4204-bd2b-f1c5e994a970</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-zcompraguiada-create-component---View1--idPCostCenter-inner']</value>
      <webElementGuid>1aab62b0-8e84-45c9-b1c1-576f4950857a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-zcompraguiada-create-component---View1--idPCostCenter-content']/input</value>
      <webElementGuid>f8b4af9d-7959-4842-9e7c-483c2314d133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/input</value>
      <webElementGuid>a3cc874b-cf6c-4061-b5e3-26523f8d0ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-zcompraguiada-create-component---View1--idPCostCenter-inner' and @type = 'text']</value>
      <webElementGuid>f20488a4-602f-4bb4-b13c-6e150d4e2a7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
