<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Ms_application-PhysicalInventoryDocu_075725</name>
   <tag></tag>
   <elementGuidId>108549fb-278c-4a10-b5c3-2cf8eab760be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-PhysicalInventoryDocument-createPhysicalInventoryDocumentInWebGUI-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='application-PhysicalInventoryDocument-createPhysicalInventoryDocumentInWebGUI-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d667412d-78e7-4bd9-8b07-9cd6eb5c6f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-PhysicalInventoryDocument-createPhysicalInventoryDocumentInWebGUI-iframe</value>
      <webElementGuid>427d08f9-fbd5-4354-ad45-36db20f9aed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-PhysicalInventoryDocument-createPhysicalInventoryDocumentInWebGUI-iframe</value>
      <webElementGuid>a599d9e1-f9d7-4db9-8710-3bdee00372f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application-PhysicalInventoryDocument-createPhysicalInventoryDocumentInWebGUI-iframe</value>
      <webElementGuid>4fff9213-048a-453a-9f2b-b49faf729445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-orig-src</name>
      <type>Main</type>
      <value>/sap/bc/gui/sap/its/webgui;~sysid=R3Q;~service=3200?~transaction=MI01&amp;sap-client=100&amp;sap-language=ES&amp;~nosplash=1&amp;sap-iframe-hint=GUI&amp;sap-ie=edge&amp;sap-theme=abertis_theme_corp%40https%3A%2F%2Fsaps4-pre.abertis.com%2Fsap%2Fpublic%2Fbc%2Fthemes%2F~client-100%2F~cache-EffUt0nnNFsxi7WxmjEKOoghmzc&amp;sap-touch=0&amp;sap-target-navmode=inplace&amp;sap-keepclientsession=2&amp;sap-ushell-timeout=25&amp;sap-shell=FLP1.120.28</value>
      <webElementGuid>d1f18eb7-4476-4712-bc24-1dd334cb256c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aplicación</value>
      <webElementGuid>aea0078b-0175-467d-9925-526b76abf8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sap-iframe-idx</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>67177f0c-8f35-41fa-b7e6-b3d589457735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay ;battery ;camera ;display-capture ;geolocation ;gyroscope ;magnetometer ;microphone ;midi ;clipboard-write ;clipboard-read ;fullscreen ;serial ;</value>
      <webElementGuid>d4d884fa-bbdf-40d3-86e0-3d2904d2c920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUShellApplicationContainer</value>
      <webElementGuid>42c0d0ae-716d-4ea5-a8e2-36cb84f806aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-PhysicalInventoryDocument-createPhysicalInventoryDocumentInWebGUI-iframe&quot;)</value>
      <webElementGuid>2c4e3d30-a851-47c4-9aa0-5bc2e29ba5ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='application-PhysicalInventoryDocument-createPhysicalInventoryDocumentInWebGUI-iframe']</value>
      <webElementGuid>50adf4ca-f2fb-476b-9a50-7626de76614f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-PhysicalInventoryDocument-createPhysicalInventoryDocumentInWebGUI']/iframe</value>
      <webElementGuid>88b5528d-4733-4e81-a72e-1b1e1ea5846d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8fcf7942-666f-44bc-88a3-d663ae7b6c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'application-PhysicalInventoryDocument-createPhysicalInventoryDocumentInWebGUI-iframe' and @name = 'application-PhysicalInventoryDocument-createPhysicalInventoryDocumentInWebGUI-iframe' and @title = 'Aplicación']</value>
      <webElementGuid>03125fc4-8da6-4792-802a-e06e8722a826</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
