<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ticket_application-ZPM_SMART-GESTPREV_113cc2</name>
   <tag></tag>
   <elementGuidId>d2cbfd8f-4128-4ae2-bd79-d4c152256f99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28db7475-e1ac-419e-935d-a633ad3ce855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner</value>
      <webElementGuid>007aff62-2611-4b4d-9120-8aab8aab8e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>b4348d0f-45e1-4b91-baeb-6044a3eb77ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItem-OrdenesSet-Orderid</value>
      <webElementGuid>33129e91-4fe1-4936-ac8b-547f43d32b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text192</value>
      <webElementGuid>41f80369-b6dc-4662-8095-ca2bb3c7e81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>fc85ddd9-1ea5-448b-8f4b-6363a3d8410d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-roledescription</name>
      <type>Main</type>
      <value>Inserimento multivalore</value>
      <webElementGuid>9dccdb5c-d99b-452f-b627-2181cfc8e088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2492e5e4-b35f-462e-8b15-b97cf94bd726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2c8b24f3-5812-43a3-b913-6e9f67999bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>976dd00d-1df9-4c92-bbe3-5f97efeb2e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner&quot;)</value>
      <webElementGuid>8774160e-c84d-4bf3-a11e-a56e202d6f39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner']</value>
      <webElementGuid>e70e39e2-ff87-4333-b7da-70348ef6e007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-content']/input</value>
      <webElementGuid>55a72f7d-3333-498d-8022-703c6b65d725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>0dc4b1b0-cd5c-47d3-ba85-b46e76f2f90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner' and @type = 'text']</value>
      <webElementGuid>f1d868ae-0f74-45d0-ac75-8e47fa3b5453</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
