<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Avvio</name>
   <tag></tag>
   <elementGuidId>647bb3f3-bcfd-4dac-9c92-b2ff136018a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-BDI-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>d454b7dc-44fb-4d2f-97ad-43f6464f2842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-BDI-content</value>
      <webElementGuid>f6141654-2013-406b-8f71-be2ac0ff3503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>5d03b4b9-3bd9-4bc9-b3a8-2a154b0157cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Avvio</value>
      <webElementGuid>9666b5fe-f52c-4bfa-8a16-e721c7061328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-BDI-content&quot;)</value>
      <webElementGuid>1018295e-9a0c-4bef-85a1-c7a2840da42d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-BDI-content']</value>
      <webElementGuid>12c66869-a3ed-479d-8405-7ebd140f8d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-content']/bdi</value>
      <webElementGuid>e04a4757-d5b7-483b-b0bc-e48eef488d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleziona view'])[1]/following::bdi[1]</value>
      <webElementGuid>4d6a46fb-ecff-4811-8e40-30dd2a7e734f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::bdi[1]</value>
      <webElementGuid>9604d9e6-1caa-4706-9c59-ef91ba79f308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nascondi barra filtri'])[1]/preceding::bdi[1]</value>
      <webElementGuid>9982d0c6-2aac-490d-9d28-fde3219ca33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtri (2)'])[1]/preceding::bdi[2]</value>
      <webElementGuid>0fe5326b-d29b-44ae-9af5-fe07db8d8fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Avvio']/parent::*</value>
      <webElementGuid>b6bd68d0-f9bf-4904-be85-75cb8a5e0bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bdi</value>
      <webElementGuid>caa1855e-b792-4fa1-b4f9-e5d99162ea89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-btnGo-BDI-content' and (text() = 'Avvio' or . = 'Avvio')]</value>
      <webElementGuid>375cb50a-3734-4968-b090-3113427bce8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
