<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Chiusura Tecnica</name>
   <tag></tag>
   <elementGuidId>86606e76-0ecf-4f34-88ca-5462d0eef44f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='application-ZPM_SMART-GESTICKET-component---Detalle--iCierreTecnico']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTPREVEN-component---Detalle--iCierreTecnico-BDI-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>fe37212e-cfab-4eaf-945c-1dc982fbda33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---Detalle--iCierreTecnico-BDI-content</value>
      <webElementGuid>22a21266-8454-4f19-a79c-2d34a64f8082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>35ffb98f-8f58-4979-8884-b5ebf8cdfde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chiusura Tecnica</value>
      <webElementGuid>8314a7f3-7933-4f32-bd3b-05b14e3bf314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTPREVEN-component---Detalle--iCierreTecnico-BDI-content&quot;)</value>
      <webElementGuid>2121f025-05b7-41d4-8c5c-96579056f5cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='application-ZPM_SMART-GESTPREVEN-component---Detalle--iCierreTecnico-BDI-content']</value>
      <webElementGuid>f0e06281-1063-4617-bac7-6f6d8672950a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-GESTPREVEN-component---Detalle--iCierreTecnico-content']/bdi</value>
      <webElementGuid>fd2d311d-fd1c-4f58-89b6-a1a31f2f363a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contatore gruppi cicli'])[1]/following::bdi[1]</value>
      <webElementGuid>f0caeee2-3461-494d-9cff-bd0c9cb53cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gruppo cicli'])[1]/following::bdi[2]</value>
      <webElementGuid>caa35211-46ee-4c60-a2d0-6acc4250af52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annullare Chiusura Tecnica'])[2]/preceding::bdi[1]</value>
      <webElementGuid>ed1f14eb-76ba-4692-8380-51283c9b9c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rilasciare'])[2]/preceding::bdi[2]</value>
      <webElementGuid>d03c689c-b6bc-40c3-9d32-01e075bebe0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/bdi</value>
      <webElementGuid>ab64378c-f067-48d1-9831-436ec985a21a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'application-ZPM_SMART-GESTPREVEN-component---Detalle--iCierreTecnico-BDI-content' and (text() = 'Chiusura Tecnica' or . = 'Chiusura Tecnica')]</value>
      <webElementGuid>ffab88a4-41f7-44dc-9399-167b0eba4fc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
