<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_rea de trabajo de VIM - OPTVIM_WP</name>
   <tag></tag>
   <elementGuidId>f56c0ec9-0c5f-485a-9295-16299bc97bd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__text106']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__text106</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b31edf88-d02d-40e2-b15d-c469e6a95da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__text106</value>
      <webElementGuid>4be672dd-bfd3-45be-af64-2b05e52acfda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__text106</value>
      <webElementGuid>d6293b09-e79f-4599-8a37-b62d63434668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>56c5b445-86b4-4a8b-b590-0ea6613652ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMText sapUiSelectable sapMTextNoWrap sapMTextMaxWidth suggestText suggestNavItem suggestListItemCell</value>
      <webElementGuid>0e92404f-f3b8-40a7-8e93-63a6d9779fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Área de trabajo de VIM - /OPT/VIM_WP</value>
      <webElementGuid>3955d6ed-2452-420f-b6f5-b663d35fb714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__text106&quot;)</value>
      <webElementGuid>e7aab582-7ae7-4e10-9be8-2f13314d9d04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__text106']</value>
      <webElementGuid>f4c5b8ef-1fd0-45a9-ad47-80a6762fe344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__data359']/span</value>
      <webElementGuid>f375cb20-d8f7-4ad2-810f-b6f06468ff98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aplicaciones'])[1]/following::span[3]</value>
      <webElementGuid>7b3228d6-5c67-43b9-89ae-d947ebf66cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIM Invoice Workplace - Invoice Management'])[1]/preceding::span[2]</value>
      <webElementGuid>1a08cfa6-c58d-446e-9d56-74f73a88c39d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Área de trabajo de VIM - /']/parent::*</value>
      <webElementGuid>9b9538b9-caba-4955-9b82-879e4c007ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>9584fb8b-71e0-44ef-8ee4-0950a5c9781b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__text106' and (text() = 'Área de trabajo de VIM - /OPT/VIM_WP' or . = 'Área de trabajo de VIM - /OPT/VIM_WP')]</value>
      <webElementGuid>e60293bf-d59b-4b07-bd4f-746df2d6277f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
