<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Da de ejecucinIdentificador.lsPanelsCon_0a786c</name>
   <tag></tag>
   <elementGuidId>fb8840d3-82d8-456b-a462-4ea5a65ec0b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:46']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b71536d2-daff-45c0-8c91-2dfd471139a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46</value>
      <webElementGuid>b6f1731a-6d54-44fe-88ab-417d1badfa5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>RL</value>
      <webElementGuid>6e328a9e-9bbe-474b-aa18-c35de7208dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:4.00,&quot;2&quot;:1.25,&quot;4&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr&quot;,&quot;Type&quot;:&quot;GuiUserArea&quot;},&quot;6&quot;:&quot;AUTO&quot;}</value>
      <webElementGuid>6899a0b0-4816-44e0-b00a-903dd4db946c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Scroll&quot;:[{},{}]}</value>
      <webElementGuid>4f4218fd-bda2-477d-8c4e-3ccb33b7e4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bnoposrefcontainer</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>313f507e-92e5-4513-9792-29c899230e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsscrl</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>df44bfeb-0052-43bd-90cd-257836588bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>10164762-6135-46cf-aa63-8eeb53bb8ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsRasterLayout  lsRL--relative lsRL--scrollingmode-auto lsRasterLayout--lrpad lsResponsivePadding</value>
      <webElementGuid>6264b531-afcc-4b82-b726-66933cee3e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-style</name>
      <type>Main</type>
      <value>;height:100%;width:100%</value>
      <webElementGuid>7a7003b6-e177-43d2-819c-15781d5bdf20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Día de ejecuciónIdentificador.lsPanelsContainer--root{container-type: inline-size; container-name: PanelsContainer;} @container PanelsContainer (width&lt;600px) { .lsPanelsContainer--panel { --sapUrPanels_HorizontalSpacing: var(--sapUrPanels_HorizontalSpacing_Responsive_Small);}}EstadoParámetroSelección libreLog adicionalImpresión y sop.datos&lt;div id=&quot;M0:46:1_mnu-container&quot; class=&quot;urMnu lsPOMNContainer lsPopupMenu__metaData&quot; class=&quot;lsMnu-display-inline-block&quot;>&lt;div id=&quot;M0:46:1_mnu-scrlup&quot; role=&quot;presentation&quot; title=&quot;Arriba&quot; class=&quot;urMnuScr urMnuScrUp lsElement--invisible&quot;>&lt;span class=&quot;lsPopupMenuItem_Spacer&quot; role=&quot;presentation&quot; aria-hidden=&quot;true&quot;>&lt;/span>&lt;/div>&lt;div id=&quot;M0:46:1_mnu-cnt&quot; class=&quot;lsMnuCnt&quot; data-sap-ls-style=&quot;;width:100%;overflow:hidden&quot;>&lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; id=&quot;M0:46:1_mnu&quot; ct=&quot;POMN&quot; lsdata='{&quot;x&quot;:0,&quot;5&quot;:{&quot;Type&quot;:&quot;GuiMenu&quot;,&quot;ModalNo&quot;:0}}' lsevents='{&quot;Select&quot;:[{},{}]}' class=&quot;lsMnuTable&quot; role=&quot;menu&quot; data-sap-ls-style=&quot;;width:100%&quot;>&lt;col/>&lt;col/>&lt;col/>&lt;col/>&lt;col/>&lt;tbody>&lt;tr ct=&quot;POMNI&quot; lsdata='{&quot;x&quot;:0,&quot;1&quot;:&quot;Estado&quot;}' id=&quot;M0:46:1::0:0_mnuid&quot; role=&quot;menuitem&quot; aria-posinset=&quot;1&quot; aria-setsize=&quot;5&quot; aria-label=&quot;Estado&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span data-sap-ls-style=&quot;;white-space:nowrap&quot;>Estado&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; data-sap-ls-style=&quot;;white-space:nowrap&quot;>&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;tr ct=&quot;POMNI&quot; lsdata='{&quot;x&quot;:0,&quot;1&quot;:&quot;Parámetro&quot;}' id=&quot;M0:46:1::0:1_mnuid&quot; role=&quot;menuitem&quot; aria-posinset=&quot;2&quot; aria-setsize=&quot;5&quot; aria-label=&quot;Par&amp;#xe1;metro&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span data-sap-ls-style=&quot;;white-space:nowrap&quot;>Parámetro&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; data-sap-ls-style=&quot;;white-space:nowrap&quot;>&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;tr ct=&quot;POMNI&quot; lsdata='{&quot;x&quot;:0,&quot;1&quot;:&quot;Selección libre&quot;}' id=&quot;M0:46:1::0:2_mnuid&quot; role=&quot;menuitem&quot; aria-posinset=&quot;3&quot; aria-setsize=&quot;5&quot; aria-label=&quot;Selecci&amp;#xf3;n&amp;#x20;libre&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span data-sap-ls-style=&quot;;white-space:nowrap&quot;>Selección libre&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; data-sap-ls-style=&quot;;white-space:nowrap&quot;>&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;tr ct=&quot;POMNI&quot; lsdata='{&quot;x&quot;:0,&quot;1&quot;:&quot;Log adicional&quot;}' id=&quot;M0:46:1::0:3_mnuid&quot; role=&quot;menuitem&quot; aria-posinset=&quot;4&quot; aria-setsize=&quot;5&quot; aria-label=&quot;Log&amp;#x20;adicional&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span data-sap-ls-style=&quot;;white-space:nowrap&quot;>Log adicional&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; data-sap-ls-style=&quot;;white-space:nowrap&quot;>&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;tr ct=&quot;POMNI&quot; lsdata='{&quot;x&quot;:0,&quot;1&quot;:&quot;Impresión y sop.datos&quot;}' id=&quot;M0:46:1::0:4_mnuid&quot; role=&quot;menuitem&quot; aria-posinset=&quot;5&quot; aria-setsize=&quot;5&quot; aria-label=&quot;Impresi&amp;#xf3;n&amp;#x20;y&amp;#x20;sop.datos&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span data-sap-ls-style=&quot;;white-space:nowrap&quot;>Impresión y sop.datos&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; data-sap-ls-style=&quot;;white-space:nowrap&quot;>&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;/tbody>&lt;/table>&lt;/div>&lt;div id=&quot;M0:46:1_mnu-scrldwn&quot; role=&quot;presentation&quot; title=&quot;Abajo&quot; class=&quot;urMnuScr urMnuScrDwn lsElement--invisible&quot;>&lt;span class=&quot;lsPopupMenuItem_Spacer&quot; role=&quot;presentation&quot; aria-hidden=&quot;true&quot;>&lt;/span>&lt;/div>&lt;div id=&quot;M0:46:1_mnu-pointer&quot; class=&quot;lsQVPointer&quot;>&lt;/div>&lt;/div>Estado Aún no se han registrado parámetros    </value>
      <webElementGuid>a5805a9f-c451-4d52-abdf-aa592de7de56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46&quot;)</value>
      <webElementGuid>12bbeb29-6f88-4328-b299-6975282cf51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SD Cobros/Page_Pagos automticos Status/iframe_Ms_application-AutomaticPayment-sche_417424</value>
      <webElementGuid>2d0d8492-528d-46d1-9945-5ca05161f207</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M0:46']</value>
      <webElementGuid>8bcaf310-8c33-4755-970d-26221bc243dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userpanel']/div</value>
      <webElementGuid>23117bce-9f93-434f-8372-a4ff2a49cc9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[1]/following::div[7]</value>
      <webElementGuid>aa908ca3-39f6-4554-88d2-c01ab1d9ab13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>94e33d53-59a8-4193-93af-88adf78c4136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M0:46' and (text() = concat(&quot;Día de ejecuciónIdentificador.lsPanelsContainer--root{container-type: inline-size; container-name: PanelsContainer;} @container PanelsContainer (width&lt;600px) { .lsPanelsContainer--panel { --sapUrPanels_HorizontalSpacing: var(--sapUrPanels_HorizontalSpacing_Responsive_Small);}}EstadoParámetroSelección libreLog adicionalImpresión y sop.datos&lt;div id=&quot;M0:46:1_mnu-container&quot; class=&quot;urMnu lsPOMNContainer lsPopupMenu__metaData&quot; class=&quot;lsMnu-display-inline-block&quot;>&lt;div id=&quot;M0:46:1_mnu-scrlup&quot; role=&quot;presentation&quot; title=&quot;Arriba&quot; class=&quot;urMnuScr urMnuScrUp lsElement--invisible&quot;>&lt;span class=&quot;lsPopupMenuItem_Spacer&quot; role=&quot;presentation&quot; aria-hidden=&quot;true&quot;>&lt;/span>&lt;/div>&lt;div id=&quot;M0:46:1_mnu-cnt&quot; class=&quot;lsMnuCnt&quot; data-sap-ls-style=&quot;;width:100%;overflow:hidden&quot;>&lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; id=&quot;M0:46:1_mnu&quot; ct=&quot;POMN&quot; lsdata=&quot; , &quot;'&quot; , &quot;{&quot;x&quot;:0,&quot;5&quot;:{&quot;Type&quot;:&quot;GuiMenu&quot;,&quot;ModalNo&quot;:0}}&quot; , &quot;'&quot; , &quot; lsevents=&quot; , &quot;'&quot; , &quot;{&quot;Select&quot;:[{},{}]}&quot; , &quot;'&quot; , &quot; class=&quot;lsMnuTable&quot; role=&quot;menu&quot; data-sap-ls-style=&quot;;width:100%&quot;>&lt;col/>&lt;col/>&lt;col/>&lt;col/>&lt;col/>&lt;tbody>&lt;tr ct=&quot;POMNI&quot; lsdata=&quot; , &quot;'&quot; , &quot;{&quot;x&quot;:0,&quot;1&quot;:&quot;Estado&quot;}&quot; , &quot;'&quot; , &quot; id=&quot;M0:46:1::0:0_mnuid&quot; role=&quot;menuitem&quot; aria-posinset=&quot;1&quot; aria-setsize=&quot;5&quot; aria-label=&quot;Estado&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span data-sap-ls-style=&quot;;white-space:nowrap&quot;>Estado&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; data-sap-ls-style=&quot;;white-space:nowrap&quot;>&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;tr ct=&quot;POMNI&quot; lsdata=&quot; , &quot;'&quot; , &quot;{&quot;x&quot;:0,&quot;1&quot;:&quot;Parámetro&quot;}&quot; , &quot;'&quot; , &quot; id=&quot;M0:46:1::0:1_mnuid&quot; role=&quot;menuitem&quot; aria-posinset=&quot;2&quot; aria-setsize=&quot;5&quot; aria-label=&quot;Par&amp;#xe1;metro&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span data-sap-ls-style=&quot;;white-space:nowrap&quot;>Parámetro&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; data-sap-ls-style=&quot;;white-space:nowrap&quot;>&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;tr ct=&quot;POMNI&quot; lsdata=&quot; , &quot;'&quot; , &quot;{&quot;x&quot;:0,&quot;1&quot;:&quot;Selección libre&quot;}&quot; , &quot;'&quot; , &quot; id=&quot;M0:46:1::0:2_mnuid&quot; role=&quot;menuitem&quot; aria-posinset=&quot;3&quot; aria-setsize=&quot;5&quot; aria-label=&quot;Selecci&amp;#xf3;n&amp;#x20;libre&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span data-sap-ls-style=&quot;;white-space:nowrap&quot;>Selección libre&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; data-sap-ls-style=&quot;;white-space:nowrap&quot;>&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;tr ct=&quot;POMNI&quot; lsdata=&quot; , &quot;'&quot; , &quot;{&quot;x&quot;:0,&quot;1&quot;:&quot;Log adicional&quot;}&quot; , &quot;'&quot; , &quot; id=&quot;M0:46:1::0:3_mnuid&quot; role=&quot;menuitem&quot; aria-posinset=&quot;4&quot; aria-setsize=&quot;5&quot; aria-label=&quot;Log&amp;#x20;adicional&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span data-sap-ls-style=&quot;;white-space:nowrap&quot;>Log adicional&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; data-sap-ls-style=&quot;;white-space:nowrap&quot;>&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;tr ct=&quot;POMNI&quot; lsdata=&quot; , &quot;'&quot; , &quot;{&quot;x&quot;:0,&quot;1&quot;:&quot;Impresión y sop.datos&quot;}&quot; , &quot;'&quot; , &quot; id=&quot;M0:46:1::0:4_mnuid&quot; role=&quot;menuitem&quot; aria-posinset=&quot;5&quot; aria-setsize=&quot;5&quot; aria-label=&quot;Impresi&amp;#xf3;n&amp;#x20;y&amp;#x20;sop.datos&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span data-sap-ls-style=&quot;;white-space:nowrap&quot;>Impresión y sop.datos&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; data-sap-ls-style=&quot;;white-space:nowrap&quot;>&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;/tbody>&lt;/table>&lt;/div>&lt;div id=&quot;M0:46:1_mnu-scrldwn&quot; role=&quot;presentation&quot; title=&quot;Abajo&quot; class=&quot;urMnuScr urMnuScrDwn lsElement--invisible&quot;>&lt;span class=&quot;lsPopupMenuItem_Spacer&quot; role=&quot;presentation&quot; aria-hidden=&quot;true&quot;>&lt;/span>&lt;/div>&lt;div id=&quot;M0:46:1_mnu-pointer&quot; class=&quot;lsQVPointer&quot;>&lt;/div>&lt;/div>Estado Aún no se han registrado parámetros    &quot;) or . = concat(&quot;Día de ejecuciónIdentificador.lsPanelsContainer--root{container-type: inline-size; container-name: PanelsContainer;} @container PanelsContainer (width&lt;600px) { .lsPanelsContainer--panel { --sapUrPanels_HorizontalSpacing: var(--sapUrPanels_HorizontalSpacing_Responsive_Small);}}EstadoParámetroSelección libreLog adicionalImpresión y sop.datos&lt;div id=&quot;M0:46:1_mnu-container&quot; class=&quot;urMnu lsPOMNContainer lsPopupMenu__metaData&quot; class=&quot;lsMnu-display-inline-block&quot;>&lt;div id=&quot;M0:46:1_mnu-scrlup&quot; role=&quot;presentation&quot; title=&quot;Arriba&quot; class=&quot;urMnuScr urMnuScrUp lsElement--invisible&quot;>&lt;span class=&quot;lsPopupMenuItem_Spacer&quot; role=&quot;presentation&quot; aria-hidden=&quot;true&quot;>&lt;/span>&lt;/div>&lt;div id=&quot;M0:46:1_mnu-cnt&quot; class=&quot;lsMnuCnt&quot; data-sap-ls-style=&quot;;width:100%;overflow:hidden&quot;>&lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; id=&quot;M0:46:1_mnu&quot; ct=&quot;POMN&quot; lsdata=&quot; , &quot;'&quot; , &quot;{&quot;x&quot;:0,&quot;5&quot;:{&quot;Type&quot;:&quot;GuiMenu&quot;,&quot;ModalNo&quot;:0}}&quot; , &quot;'&quot; , &quot; lsevents=&quot; , &quot;'&quot; , &quot;{&quot;Select&quot;:[{},{}]}&quot; , &quot;'&quot; , &quot; class=&quot;lsMnuTable&quot; role=&quot;menu&quot; data-sap-ls-style=&quot;;width:100%&quot;>&lt;col/>&lt;col/>&lt;col/>&lt;col/>&lt;col/>&lt;tbody>&lt;tr ct=&quot;POMNI&quot; lsdata=&quot; , &quot;'&quot; , &quot;{&quot;x&quot;:0,&quot;1&quot;:&quot;Estado&quot;}&quot; , &quot;'&quot; , &quot; id=&quot;M0:46:1::0:0_mnuid&quot; role=&quot;menuitem&quot; aria-posinset=&quot;1&quot; aria-setsize=&quot;5&quot; aria-label=&quot;Estado&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span data-sap-ls-style=&quot;;white-space:nowrap&quot;>Estado&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; data-sap-ls-style=&quot;;white-space:nowrap&quot;>&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;tr ct=&quot;POMNI&quot; lsdata=&quot; , &quot;'&quot; , &quot;{&quot;x&quot;:0,&quot;1&quot;:&quot;Parámetro&quot;}&quot; , &quot;'&quot; , &quot; id=&quot;M0:46:1::0:1_mnuid&quot; role=&quot;menuitem&quot; aria-posinset=&quot;2&quot; aria-setsize=&quot;5&quot; aria-label=&quot;Par&amp;#xe1;metro&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span data-sap-ls-style=&quot;;white-space:nowrap&quot;>Parámetro&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; data-sap-ls-style=&quot;;white-space:nowrap&quot;>&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;tr ct=&quot;POMNI&quot; lsdata=&quot; , &quot;'&quot; , &quot;{&quot;x&quot;:0,&quot;1&quot;:&quot;Selección libre&quot;}&quot; , &quot;'&quot; , &quot; id=&quot;M0:46:1::0:2_mnuid&quot; role=&quot;menuitem&quot; aria-posinset=&quot;3&quot; aria-setsize=&quot;5&quot; aria-label=&quot;Selecci&amp;#xf3;n&amp;#x20;libre&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span data-sap-ls-style=&quot;;white-space:nowrap&quot;>Selección libre&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; data-sap-ls-style=&quot;;white-space:nowrap&quot;>&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;tr ct=&quot;POMNI&quot; lsdata=&quot; , &quot;'&quot; , &quot;{&quot;x&quot;:0,&quot;1&quot;:&quot;Log adicional&quot;}&quot; , &quot;'&quot; , &quot; id=&quot;M0:46:1::0:3_mnuid&quot; role=&quot;menuitem&quot; aria-posinset=&quot;4&quot; aria-setsize=&quot;5&quot; aria-label=&quot;Log&amp;#x20;adicional&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span data-sap-ls-style=&quot;;white-space:nowrap&quot;>Log adicional&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; data-sap-ls-style=&quot;;white-space:nowrap&quot;>&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;tr ct=&quot;POMNI&quot; lsdata=&quot; , &quot;'&quot; , &quot;{&quot;x&quot;:0,&quot;1&quot;:&quot;Impresión y sop.datos&quot;}&quot; , &quot;'&quot; , &quot; id=&quot;M0:46:1::0:4_mnuid&quot; role=&quot;menuitem&quot; aria-posinset=&quot;5&quot; aria-setsize=&quot;5&quot; aria-label=&quot;Impresi&amp;#xf3;n&amp;#x20;y&amp;#x20;sop.datos&quot; td=&quot;ltr&quot; class=&quot;urMnuRowOff lsMnuItemHeight&quot;>&lt;td class=&quot;urMnuColumn urMnuColumnColor&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuIconColumnColor lsMenuItemIcon lsMnuNoIcon&quot;>&lt;span class=&quot;lsMnuNbsp&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt&quot;>&lt;span data-sap-ls-style=&quot;;white-space:nowrap&quot;>Impresión y sop.datos&lt;/span>&lt;/td>&lt;td class=&quot;urMnuTxt lsMnuHK&quot; data-sap-ls-style=&quot;;white-space:nowrap&quot;>&lt;/td>&lt;td>&lt;span class=&quot;urMnuSub lsMirrorRtl&quot;>&amp;nbsp;&lt;/span>&lt;/td>&lt;/tr>&lt;/tbody>&lt;/table>&lt;/div>&lt;div id=&quot;M0:46:1_mnu-scrldwn&quot; role=&quot;presentation&quot; title=&quot;Abajo&quot; class=&quot;urMnuScr urMnuScrDwn lsElement--invisible&quot;>&lt;span class=&quot;lsPopupMenuItem_Spacer&quot; role=&quot;presentation&quot; aria-hidden=&quot;true&quot;>&lt;/span>&lt;/div>&lt;div id=&quot;M0:46:1_mnu-pointer&quot; class=&quot;lsQVPointer&quot;>&lt;/div>&lt;/div>Estado Aún no se han registrado parámetros    &quot;))]</value>
      <webElementGuid>3cad976c-102e-4ff6-bc38-9212ec5fda4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
