<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ejecucin inmediata</name>
   <tag></tag>
   <elementGuidId>4affbd88-c601-42ab-8b85-dbb0ed2bd0a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M1:46:::1:32']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3fb01d03-5096-4d2e-ab70-61be7c17115e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>C_standards</value>
      <webElementGuid>6a3a97a7-1914-47be-a153-0514f846d57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;CheckBox&quot;,&quot;4&quot;:&quot;Ejecución inmediata&quot;,&quot;5&quot;:&quot;Indicador: Ejecución inmediata&quot;,&quot;9&quot;:&quot;E&quot;,&quot;14&quot;:{&quot;SID&quot;:&quot;wnd[1]/usr/chkF110V-XSTRF&quot;,&quot;Type&quot;:&quot;GuiCheckBox&quot;,&quot;focusable&quot;:&quot;X&quot;},&quot;16&quot;:true}</value>
      <webElementGuid>f8681252-1ce9-43e2-b1ce-0394a6410edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Enter&quot;:[{},{&quot;1&quot;:&quot;vkey/0/ses[0]&quot;,&quot;2&quot;:true}],&quot;Change&quot;:[{},{&quot;1&quot;:&quot;action/7&quot;,&quot;3&quot;:true}],&quot;DoubleClick&quot;:[{},{&quot;1&quot;:&quot;action/2&quot;,&quot;2&quot;:true,&quot;3&quot;:true}]}</value>
      <webElementGuid>18da82a6-8886-4540-ab39-3cef3c7e9d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-currentselectionstate</name>
      <type>Main</type>
      <value>API_DRIVEN</value>
      <webElementGuid>ef49f9f3-370a-40e5-9a3c-8739fd43e561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsSelector--generic lsSelector--text lsSelector--strechedForEllipsis lsSelector--pushedToStart--spacing lsCheckBox lsCheckBox--unchecked  </value>
      <webElementGuid>1bee83d5-6abe-4218-bc65-bc4e75f1dda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a0cdfde3-b96d-4d1d-87f7-c4cdad8626ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8a1632b5-519f-4ce9-bbbb-4125520424f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Indicador: Ejecución inmediata</value>
      <webElementGuid>6423f51e-9279-4253-9fa4-ab21890820af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>E</value>
      <webElementGuid>5e983ac2-e57b-4b9a-8c7b-b5a8e5039589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>E</value>
      <webElementGuid>bb6dd1f3-af2c-4b17-a8d4-9c303ca854d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CheckBox</value>
      <webElementGuid>e6de194e-3c5c-47b9-a8b8-161852905d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M1:46:::1:32</value>
      <webElementGuid>2c9b058d-e5cd-43a1-b891-1d9b83522f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4afdb0b3-4fcb-40f7-a386-103edabcd2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b591593b-482c-4b3d-9ae0-3b63061cfe61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>50d648c6-73a5-4457-a7c8-f7e30da9bcb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ad250592-b8a5-4bb1-b68b-356dbb5c0257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Ejecución inmediata</value>
      <webElementGuid>31c3f4ad-9d1a-426b-8d9b-363443be6b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d1db08b6-cb50-41b1-be80-fde90a28a152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-controlusage</name>
      <type>Main</type>
      <value>API_DRIVEN</value>
      <webElementGuid>358d01f8-c900-44ff-8047-8ab09ed0bdcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ejecución inmediata</value>
      <webElementGuid>d90383a0-35a7-42e7-8a16-eb27bab41fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M1:46:::1:32&quot;)</value>
      <webElementGuid>95d35a89-c554-4a58-9836-779c91502ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SD Cobros/Page_Pagos automticos Status/iframe_Ms_application-AutomaticPayment-sche_417424</value>
      <webElementGuid>9e1226db-b641-4013-98a4-e5f3aeee6fa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M1:46:::1:32']</value>
      <webElementGuid>2398c763-466e-4b97-ab5e-155331fb9eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u3EA']/span</value>
      <webElementGuid>b27e2321-8b8b-419d-8cdd-be60bf15622f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[2]/following::span[2]</value>
      <webElementGuid>62c19dc3-b632-4408-940d-081d84193078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/span</value>
      <webElementGuid>51e111d2-6d4d-4257-9517-8331a95be2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Indicador: Ejecución inmediata' and @name = 'CheckBox' and @id = 'M1:46:::1:32' and (text() = 'Ejecución inmediata' or . = 'Ejecución inmediata')]</value>
      <webElementGuid>f44d7a4a-ceaa-45a8-9abf-367c657c6ec3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
