<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Notificar</name>
   <tag></tag>
   <elementGuidId>b8a83be7-f0f0-463a-9890-9ba8171a1f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTPREVEN-component---Detalle--iCreateNotif-BDI-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='application-ZPM_SMART-GESTPREVEN-component---Detalle--iCreateNotif-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>30108d37-b538-4df4-8d29-72ad4048519f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---Detalle--iCreateNotif-BDI-content</value>
      <webElementGuid>5ebade56-3423-4638-8509-f3b00129a8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>37487c66-8876-4780-be14-5a62cbcf235a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notificar</value>
      <webElementGuid>dad845c3-07bd-4e4d-b5c1-39b23c9bcecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTPREVEN-component---Detalle--iCreateNotif-BDI-content&quot;)</value>
      <webElementGuid>a9c77e4e-457b-4c23-9868-7072918247f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='application-ZPM_SMART-GESTPREVEN-component---Detalle--iCreateNotif-BDI-content']</value>
      <webElementGuid>fa1d9467-7445-4f75-bfb3-39fd33b80ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-GESTPREVEN-component---Detalle--iCreateNotif-content']/bdi</value>
      <webElementGuid>2ac77480-f7c9-404a-8bed-f62664ecec4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sin Notificar'])[1]/following::bdi[1]</value>
      <webElementGuid>d41241ab-d464-40db-b9ba-a67d906f148e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notificadas'])[1]/following::bdi[1]</value>
      <webElementGuid>3f833d22-99a4-4230-b7f1-1dae21cfea51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notificar'])[2]/preceding::bdi[1]</value>
      <webElementGuid>b3acfbe9-633d-458c-b6b8-f608e7b4c5b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Añadir Operación'])[1]/preceding::bdi[1]</value>
      <webElementGuid>49e15dc4-6f0b-4131-b2a7-248c9c50179a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Notificar']/parent::*</value>
      <webElementGuid>86930e21-e4ae-4fd2-bd73-fa2f6173e02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/bdi</value>
      <webElementGuid>15eb4081-d89b-424a-b344-2ff572760e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'application-ZPM_SMART-GESTPREVEN-component---Detalle--iCreateNotif-BDI-content' and (text() = 'Notificar' or . = 'Notificar')]</value>
      <webElementGuid>c362f399-2fa8-4bd5-9258-4810747e6294</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
