<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Orden_application-ZPM_SMART-GESTPREVE_e275c9</name>
   <tag></tag>
   <elementGuidId>ce6a5f97-4ed5-4f98-ad3d-283926dad07b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>044dbd0d-7bba-43d1-b027-feb249202fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner</value>
      <webElementGuid>dbfd69a8-f889-4535-82d4-6a5263e8d512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>1add0fd2-769f-49a0-b372-032726c9555c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItem-OrdenesSet-Orderid</value>
      <webElementGuid>630d9fe3-f3a8-4bf8-a30d-fc158e0378e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text187</value>
      <webElementGuid>a975353e-63c7-4542-9685-a5db3c5745cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>7e2fd080-7b18-464c-ab0b-fa7b11d399b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-roledescription</name>
      <type>Main</type>
      <value>Entrada de varios valores</value>
      <webElementGuid>d3381954-499a-4a37-a514-99d7198f5caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a8937d7-9356-4a72-a914-05b5af9a8bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>10255a97-bd0e-4bf2-9264-36544bededee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>4de51ea2-37e8-4ac5-b763-7b310a16addc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner&quot;)</value>
      <webElementGuid>fa922337-9590-46c6-b886-10bfb3274dee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner']</value>
      <webElementGuid>64775334-b28a-438c-a0bd-05c66c9a0121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-content']/input</value>
      <webElementGuid>e51d5c89-6340-4a5e-b68c-faac4658cfe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>053c044a-7d2a-41c2-a112-012ca8413189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner' and @type = 'text']</value>
      <webElementGuid>e6a8ce1d-a078-4eaa-bb38-3934ef32de8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
