<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Orden_application-ZPM_SMART-GESTPREVE_e275c9</name>
   <tag></tag>
   <elementGuidId>15578990-81fa-4ff7-a672-5aa58faec6cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cee7fa5-f27b-42f9-8d8e-2450400f3845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner</value>
      <webElementGuid>127f003f-b415-415e-830c-b891ed2a6118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>f0503edf-c5bf-4c4d-9da5-0cf7ea21a813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItem-OrdenesSet-Orderid</value>
      <webElementGuid>e747ae85-767d-484a-9af3-281632ccd6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text189</value>
      <webElementGuid>30b9be1f-3b68-4b38-8bf7-66feaea66849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>c4271ea8-77a4-4e4b-aced-78c5db11b99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-roledescription</name>
      <type>Main</type>
      <value>Entrada de varios valores</value>
      <webElementGuid>ea64e993-bc49-4f1a-9b78-9b5cc19e3e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43ca5c29-4d41-4005-abd6-7eed26e0c807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>18c5e503-fdf8-47ea-8f1f-41ca54f951a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>316330ac-5139-49b0-8268-0330a3251eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner&quot;)</value>
      <webElementGuid>70820cb0-a9f0-4efe-9c59-38d45c020e04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner']</value>
      <webElementGuid>d6e82058-59d1-4f72-ac57-a7363416b023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-content']/input</value>
      <webElementGuid>019709fe-f802-4551-afaa-b531b4a55ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>ef9532aa-9698-46b0-9ac8-a02aab0c0837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-ZPM_SMART-GESTPREVEN-component---main--smartFilterBar-filterItemControlA_-Orderid-inner' and @type = 'text']</value>
      <webElementGuid>d5ccccbb-ef2e-41c7-be13-81bd211228a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
