<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Standard</name>
   <tag></tag>
   <elementGuidId>55afe3e7-3b47-4d3d-8a2b-11d135402482</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[contains(@id, '-application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-list-0')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__item45-application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-list-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9e050be5-d04f-4133-81a9-942f45ab506a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__item45-application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-list-0</value>
      <webElementGuid>54d73707-348a-4d75-879c-eef8ddba941a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__item45-application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-list-0</value>
      <webElementGuid>29a54d08-fcac-440c-a831-eeb0012e8a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cd94444c-5745-4d82-b48a-b1c3361cad89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0c37b4f8-a1bc-4ce1-8c69-2e27167ee555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f2821803-9bd2-4603-8c35-a671e97e5dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1d6aa66f-bbaf-4f4f-9abe-a3ca0e5a8e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b5c5a475-9bf8-47b5-8039-c5d2a7c5d60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSelectListItemBase sapMSelectListItem sapMSelectListItemBaseHoverable sapMSelectListItemBaseSelected sapMSelectListItemBasePressed</value>
      <webElementGuid>ad5edadc-f030-49d4-96d4-8f1c2326f3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Standard</value>
      <webElementGuid>1da8e0ac-6e63-462f-aa72-4f43cc93af41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__item45-application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-list-0&quot;)</value>
      <webElementGuid>106a599f-d4b7-49cf-a59b-bc0fb54d3de6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='__item45-application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-list-0']</value>
      <webElementGuid>5ec53f58-1801-4a96-8942-259ca277979f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-list']/li</value>
      <webElementGuid>0026910c-5f17-44cf-8c3e-270d760abff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Le mie view'])[1]/following::li[1]</value>
      <webElementGuid>380da4fa-bf33-4cc8-87e7-b7b85413a517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salva con nome'])[1]/preceding::li[1]</value>
      <webElementGuid>627caa25-0a49-49ee-8f0a-97fe78901936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestisci'])[1]/preceding::li[1]</value>
      <webElementGuid>4450fadf-4499-4547-8810-5887cf9216e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Standard']/parent::*</value>
      <webElementGuid>ee7b8be8-ed1e-44ad-81b1-322897d32fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>5daf371b-7acd-4bd9-87ab-208bf0277f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '__item45-application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-list-0' and (text() = 'Standard' or . = 'Standard')]</value>
      <webElementGuid>d8d56b73-cead-41ab-9bfa-06427460c650</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
