<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Standard_application-ZPM_SMART-GESTICK_bc967c</name>
   <tag></tag>
   <elementGuidId>3896d6ae-4109-47a9-a763-f5e7856733a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-trigger-img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-trigger-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9e7de6c6-9c84-4346-8c69-dc1d5094d9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-trigger-img</value>
      <webElementGuid>dfe6de24-ca76-44a7-9baf-985d188aeb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-trigger-img</value>
      <webElementGuid>884b7838-1af7-448a-b014-dbe1a2a99533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>cc72736e-3040-4298-8856-52bd4bf6b5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9da0c579-1492-4da4-b093-ca66cb55b911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>df3da9c4-fdde-4471-b2ec-308586149a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapMBtnCustomIcon sapMBtnIcon sapMBtnIconLeft</value>
      <webElementGuid>f39b7e13-1762-48a8-9661-21f318d055a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-trigger-img&quot;)</value>
      <webElementGuid>98317579-5935-4b07-ad45-a4e5133cd9d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-trigger-img']</value>
      <webElementGuid>4ba35f80-1a77-4424-b9b9-57c9dd8fd6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-trigger-inner']/span</value>
      <webElementGuid>074fc27d-919e-46be-9898-1f2a413ac653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[3]/button/span/span</value>
      <webElementGuid>58f05a4a-0265-4181-8395-e754d40c1aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-variant-vm-trigger-img']</value>
      <webElementGuid>acc58bd2-9327-4d70-92d4-2135cb8d5789</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
