<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Fecha contabiliz.Doc.creados hastaPos.d_c73de7</name>
   <tag></tag>
   <elementGuidId>af06b70c-cec0-492e-a195-65f7b44bec9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:46:1:2B262']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8c7954fb-ce0e-488f-8ab9-eaebc059bb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:2B262</value>
      <webElementGuid>761ba4d6-a22c-4afb-94d5-0bf5ba77445e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>RL</value>
      <webElementGuid>81a7b9c5-1f69-4fef-b5d2-3012e8219f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:4.00,&quot;2&quot;:1.25,&quot;4&quot;:{&quot;SID&quot;:&quot;wnd[0]/usr/tabsF110_TABSTRIP/tabpPAR/ssubSUBSCREEN_BODY:SAPF110V:0202&quot;,&quot;Type&quot;:&quot;GuiScrollContainer&quot;}}</value>
      <webElementGuid>5827b3ff-727e-4759-bd38-0bb08df16f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bnoposrefcontainer</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>e72d6c5f-7b5d-4197-80f9-98ca40ff2582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>c3a0de66-3d5f-415f-9886-a10909463a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsRasterLayout  lsRL--relative</value>
      <webElementGuid>61dbcda5-637f-4259-9014-a4ee3c2bc6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-style</name>
      <type>Main</type>
      <value>;height:544px;width:1250px</value>
      <webElementGuid>693a964b-f517-46e5-bb26-5f0466ee230f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fecha contabiliz.Doc.creados hastaPos.de deudor vencen elControl de pagosSociedades Vías pago Sig.fe.cont.  4     CuentasProveedora Clientea Monedas extranjerasTp.cotiz.p.conversión</value>
      <webElementGuid>6ef88b0a-c861-4113-be60-6230f93c99e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:2B262&quot;)</value>
      <webElementGuid>64ac7e94-29ae-463a-8cd8-05f8140a1a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SD Cobros/Page_Pagos automticos Parmetros/iframe_Ms_application-AutomaticPayment-sche_417424</value>
      <webElementGuid>4c3ace4d-41cd-499a-a184-1afd0680daa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M0:46:1:2B262']</value>
      <webElementGuid>54cec4fc-47b5-4be7-8cc6-b97d2e4096c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46:1::0:1-scrl-cnt']/div</value>
      <webElementGuid>5493315c-7a3d-4a45-813e-4b9021e2a628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impresión y sop.datos'])[1]/following::div[7]</value>
      <webElementGuid>f28a4b3c-319a-42f4-982b-f7d59f26c41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log adicional'])[1]/following::div[9]</value>
      <webElementGuid>fa8a7f44-d18e-4e91-82a4-73b81c015ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/div/div/div</value>
      <webElementGuid>b317a85d-b143-4bbb-9748-9c63716513fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M0:46:1:2B262' and (text() = 'Fecha contabiliz.Doc.creados hastaPos.de deudor vencen elControl de pagosSociedades Vías pago Sig.fe.cont.  4     CuentasProveedora Clientea Monedas extranjerasTp.cotiz.p.conversión' or . = 'Fecha contabiliz.Doc.creados hastaPos.de deudor vencen elControl de pagosSociedades Vías pago Sig.fe.cont.  4     CuentasProveedora Clientea Monedas extranjerasTp.cotiz.p.conversión')]</value>
      <webElementGuid>75e9c7f3-cbea-48bc-98b1-7025ab90d704</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
