<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CA - CatalDE - DeutschEN - EnglishES_e3f430</name>
   <tag></tag>
   <elementGuidId>48eae278-ff9f-40de-bea8-08a91c37a1eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='LANGUAGE_SELECT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LANGUAGE_SELECT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8096d4a0-d04a-4e5a-8139-4f232a37bec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LANGUAGE_SELECT</value>
      <webElementGuid>83ac9840-6220-4fb6-bc56-8639d3f75482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9873010d-9031-49a5-befe-e75be3050dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginSelect</value>
      <webElementGuid>9f35c150-1b2b-4a97-b9a4-32f605429d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Language</value>
      <webElementGuid>f73afaca-6dec-436e-be57-d166c39fd606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>LANGUAGE_LABEL</value>
      <webElementGuid>00b9dce2-5414-4c07-b4d7-cebb25072e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA - CatalàDE - DeutschEN - EnglishES - EspañolFR - FrançaisHR - HrvatskiIT - ItalianoPT - PortuguêsSV - Svenska</value>
      <webElementGuid>6e7be008-2985-4114-9e8c-b9b302f887ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LANGUAGE_SELECT&quot;)</value>
      <webElementGuid>b9e2bf52-64ed-45d2-ad1d-5e79b6c0a4a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='LANGUAGE_SELECT']</value>
      <webElementGuid>de7418b7-be2a-4a55-aae0-17de81fa8ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LANGUAGE_SELECT_BLOCK']/select</value>
      <webElementGuid>2910ceb0-d8f1-4066-8e4d-42d26fdda58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/following::select[1]</value>
      <webElementGuid>1eebcd94-436c-4e17-af9a-e6100fd228b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::select[1]</value>
      <webElementGuid>c6d28bd9-f081-416e-816c-e0d55bad7136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log On'])[1]/preceding::select[1]</value>
      <webElementGuid>ebf20733-fd04-4cc0-9493-45ac9c575cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/preceding::select[1]</value>
      <webElementGuid>942533df-75dc-4f9a-b1a8-8f0b2992954e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a73f6083-688b-455a-8922-64ebff8128f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'LANGUAGE_SELECT' and @title = 'Language' and (text() = 'CA - CatalàDE - DeutschEN - EnglishES - EspañolFR - FrançaisHR - HrvatskiIT - ItalianoPT - PortuguêsSV - Svenska' or . = 'CA - CatalàDE - DeutschEN - EnglishES - EspañolFR - FrançaisHR - HrvatskiIT - ItalianoPT - PortuguêsSV - Svenska')]</value>
      <webElementGuid>e54cee9e-b70e-439c-b114-09d5836d5532</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
