<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CJ88___xmlview4--standardTileContent-___e222a0</name>
   <tag></tag>
   <elementGuidId>76be6362-c7ed-455c-b6bb-e29d5ebf7a9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__xmlview4--standardTileContent-__clone103']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__xmlview4--standardTileContent-__clone103</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7495f3f6-df20-488d-a69a-e6840a15e8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview4--standardTileContent-__clone103</value>
      <webElementGuid>d98a2ee7-8dd2-457f-8ead-af6393d4e620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__xmlview4--standardTileContent-__clone103</value>
      <webElementGuid>7eeb6b2f-b074-41a9-911d-e6be5b36c264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMTileCnt sapMFrameTypeAuto sapMGTNoPriority</value>
      <webElementGuid>1852eed9-bb6e-4ed9-97a9-1ac0d453fd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview4--standardTileContent-__clone103&quot;)</value>
      <webElementGuid>dc8a0aa3-0f1e-4f38-90fb-11eb9b508a25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__xmlview4--standardTileContent-__clone103']</value>
      <webElementGuid>90234d37-ebb9-4b32-8ea8-4ce5511a581c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__tile126-content']/div</value>
      <webElementGuid>939c6539-b088-4c3f-a01a-d73723c67cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CJ88'])[1]/following::div[2]</value>
      <webElementGuid>6bd5b0b9-1beb-4cf5-b4ca-313501e2f1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liquidación real: Proyectos/Grafos'])[1]/following::div[3]</value>
      <webElementGuid>44703f6a-a06d-4600-be33-b6a998ee1b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ejecutar liquidación'])[1]/preceding::div[4]</value>
      <webElementGuid>a9c7ece3-73df-4294-93fa-13725b1e2d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proyectos - Real'])[1]/preceding::div[5]</value>
      <webElementGuid>0742eed2-f037-4cc2-9da8-7324e5dd5604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div</value>
      <webElementGuid>1d84d605-ad76-447a-981f-78db26159922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__xmlview4--standardTileContent-__clone103']</value>
      <webElementGuid>186045ab-347c-41b9-aed4-a356a35dcac5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
