<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Referente___xmlview2--izzcontactp-inner</name>
   <tag></tag>
   <elementGuidId>bd5c3833-3056-4b8b-8fc0-e302cf54961a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__xmlview2--izzcontactp-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__xmlview2--izzcontactp-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4126d37-7003-4956-927c-cad6e591d4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__xmlview2--izzcontactp-inner</value>
      <webElementGuid>6d11bcfd-f0e0-4940-9c89-9b3363bc5c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Testo esplicativo o libero</value>
      <webElementGuid>a171afbd-1ada-4075-acb6-65f44052948c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>c8d13d18-9bd9-4039-9d8a-f0f8b2947b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__xmlview2--izzcontactpl</value>
      <webElementGuid>3997d9ca-95ea-4597-b4d8-d7aa577bd12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__text143</value>
      <webElementGuid>9c868262-1ad0-4c98-8001-2734884de737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e1bfd8b-ebc4-4bba-9306-7bfc05596a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>08569742-cf10-46ad-948c-cdc4ca6a3456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>d61a6c60-dc17-4385-aabd-41dd2f99cb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__xmlview2--izzcontactp-inner&quot;)</value>
      <webElementGuid>3c3d9656-7004-4245-9ff8-a81e0aba434c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__xmlview2--izzcontactp-inner']</value>
      <webElementGuid>6bf72a51-80e5-4dc5-b81e-e4b0f9da8664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__xmlview2--izzcontactp-content']/input</value>
      <webElementGuid>d7730813-a657-451f-8a2e-fba0e147ec90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>9b96d6d3-8f4b-45ff-9668-58b8f7e658b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '__xmlview2--izzcontactp-inner' and @placeholder = 'Testo esplicativo o libero' and @type = 'text']</value>
      <webElementGuid>eaf6962d-65dd-4f05-8fb9-84cd0ea3fb31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
