<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ocultar Panel de detalles</name>
   <tag></tag>
   <elementGuidId>87a53acc-44c0-4ff9-9ec7-506fb618d2e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='M0:48::btn[26]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>acdeb52b-fabf-481f-9c49-94bf6c6f71af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ccc996f9-abd3-491b-b90d-b40a2c9c6201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:48::btn[26]</value>
      <webElementGuid>f02a6dfd-44d1-4331-b653-1795e7ceaea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ct</name>
      <type>Main</type>
      <value>B</value>
      <webElementGuid>f17257d1-7173-4050-99cf-ca16e019557a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsdata</name>
      <type>Main</type>
      <value>{&quot;0&quot;:&quot;Ocultar Panel de detalles&quot;,&quot;4&quot;:&quot; (Ctrl+F2)&quot;,&quot;17&quot;:&quot;O&quot;,&quot;18&quot;:&quot;CTRL_F2&quot;,&quot;21&quot;:true,&quot;25&quot;:&quot;TOGGLE&quot;,&quot;27&quot;:{&quot;SID&quot;:&quot;wnd[0]/tbar[1]/btn[26]&quot;,&quot;Type&quot;:&quot;GuiButton&quot;,&quot;SubType&quot;:&quot;toolbar&quot;}}</value>
      <webElementGuid>68bee994-b749-41a7-b13d-0c7d69aba1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lsevents</name>
      <type>Main</type>
      <value>{&quot;Press&quot;:[{},{&quot;1&quot;:&quot;action/3&quot;,&quot;2&quot;:true,&quot;3&quot;:true}]}</value>
      <webElementGuid>37a5475b-f53f-4c6a-85b9-31ec9e777130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cust-sid</name>
      <type>Main</type>
      <value>HAac42OfWXf/4dY1766nHA==</value>
      <webElementGuid>5c18e5df-6f17-4536-a861-d8e1e0794cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dfa17e17-eea8-4ded-aa06-ad037e774cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> (Ctrl+F2)</value>
      <webElementGuid>08cfbb4f-354a-49b9-b15e-2d0e4e23a79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ls-accesskey</name>
      <type>Main</type>
      <value>O</value>
      <webElementGuid>eac75a85-8ccc-42fe-996d-9d50171ab843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>O</value>
      <webElementGuid>fc2413b2-b43c-4d88-a6d6-5bdf7d65170a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>42d76208-bd33-4163-84d3-d2e969004fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ti</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e2502b68-e112-4a9e-b6a9-5bf3ab3dd07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsButton lsButton--base urNoUserSelect urBtnRadius lsButton--useintoolbar lsButton--active lsButton--focusable lsButton--up lsButton--behaviour-toggle lsButton--design-standard lsButton--hoverable</value>
      <webElementGuid>050c9324-e671-4fdb-a4d8-41c3cb857925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toolbaritem-id</name>
      <type>Main</type>
      <value>M0:48::btn[26]-r</value>
      <webElementGuid>d7255da4-d464-421e-8d6f-ec3fd7fec1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ocultar Panel de detalles</value>
      <webElementGuid>bb1b3238-7440-4f45-8b17-10b7a8fc0569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:48::btn[26]&quot;)</value>
      <webElementGuid>2c1d028b-c924-45b2-8f66-e99e798db978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Creacion facturas CP SD TR VIM_WP/Page_rea de trabajo de VIM Invoice  Todas l_8ce86e/iframe_Ms_application-zgui_opt_vim_wp-displ_b9e7ed</value>
      <webElementGuid>c1ef0e7a-91d4-4798-be23-4faa7c7ee523</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='M0:48::btn[26]']</value>
      <webElementGuid>66c79e0c-e766-48c8-a23b-889faced1095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='M0:48::btn[26]-r']/div</value>
      <webElementGuid>2116235b-68ad-4ab9-9b53-cd0d12b4e7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[1]/following::div[1]</value>
      <webElementGuid>0e496084-8532-43cb-bf7c-957b8cc345d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/div</value>
      <webElementGuid>05a8b917-24e1-41e2-8c15-67cd606905ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'M0:48::btn[26]' and @title = ' (Ctrl+F2)' and (text() = 'Ocultar Panel de detalles' or . = 'Ocultar Panel de detalles')]</value>
      <webElementGuid>87a873ef-6258-430f-acb0-1b50bed1da49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
