<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Proceso</name>
   <tag></tag>
   <elementGuidId>b281aef8-014c-467c-9c31-7cd1fea61028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:1:2:1::0:4-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>704c6719-21c8-453a-bc2d-b92797065c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:2:1::0:4-text</value>
      <webElementGuid>ab5863ff-c4cf-461e-84f9-00941bb767a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsTabStrip--item-text</value>
      <webElementGuid>2e10e50c-0cae-43d5-8316-3731dbe8fce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceso</value>
      <webElementGuid>508d2ffc-2c4d-4090-8e26-3a20745b1a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:2:1::0:4-text&quot;)</value>
      <webElementGuid>070c366e-86ce-4b92-8129-d82676d22e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VIM creacion de facturas sin pedido con wf autorizacion/Page_Proceso Gestin de facturas sin pedido _4a26f4/iframe_Ms_application-zgui_opt_vim_wp-displ_b9e7ed</value>
      <webElementGuid>5fcf6001-74b4-456a-bc04-654de8e03ddf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:2:1::0:4-text']</value>
      <webElementGuid>222a3469-e232-4d3a-a2d9-5b2742f99e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46:1:2:1::0:4-title']/span</value>
      <webElementGuid>12899ee2-daa3-4a74-b80b-35a68672ebad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impuesto'])[1]/following::span[1]</value>
      <webElementGuid>a879ddd2-e6f5-4218-8e87-0be564e2b651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contabilidad'])[1]/following::span[2]</value>
      <webElementGuid>5f7a3c77-6b5a-4c09-a078-4980b87c93e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otros datos'])[1]/preceding::span[1]</value>
      <webElementGuid>c42095ae-534b-471d-892c-d1aeb2273dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos básicos'])[2]/preceding::span[5]</value>
      <webElementGuid>111edc67-b684-4408-b184-d28a84482ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proceso']/parent::*</value>
      <webElementGuid>058fd2e4-4858-4d0c-a81a-b5737c62e306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/span</value>
      <webElementGuid>47e54b5e-82dd-425f-a587-d3353bae7e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'M0:46:1:2:1::0:4-text' and (text() = 'Proceso' or . = 'Proceso')]</value>
      <webElementGuid>84ec16dc-f670-4f77-893e-03996dbb4716</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
