<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Ms Datos</name>
   <tag></tag>
   <elementGuidId>143be424-80e8-40f1-ad7e-3d30934ef8bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='application-zpurchaserequisition-createMP-component---detail--idMoreDataPosition-BDI-content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-zpurchaserequisition-createMP-component---detail--idMoreDataPosition-BDI-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>eca53364-2bed-4b3e-979d-8d0b8bc20efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-zpurchaserequisition-createMP-component---detail--idMoreDataPosition-BDI-content</value>
      <webElementGuid>79aa7fa4-ac3d-41a5-9aae-a7d4c8f9b0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>8d4565e6-2c9b-4653-addc-448645f1d067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Más Datos</value>
      <webElementGuid>2d5f953e-c820-409b-b35e-a09cfc24242c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-zpurchaserequisition-createMP-component---detail--idMoreDataPosition-BDI-content&quot;)</value>
      <webElementGuid>7864a9ea-d362-4699-ab9d-37345897c1fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='application-zpurchaserequisition-createMP-component---detail--idMoreDataPosition-BDI-content']</value>
      <webElementGuid>1892a512-d1dd-4b89-9764-deb5d7056edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='application-zpurchaserequisition-createMP-component---detail--idMoreDataPosition-content']/bdi</value>
      <webElementGuid>645f6c28-107f-4c57-b992-80a1dbcff7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posiciones'])[4]/following::bdi[1]</value>
      <webElementGuid>fd677026-5c55-4779-8143-b08e60821c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mostrar más'])[1]/following::bdi[1]</value>
      <webElementGuid>20124dca-415e-4d12-b0f4-b7617229c344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copia Masiva'])[1]/preceding::bdi[1]</value>
      <webElementGuid>21f075d5-3b13-49f6-9b64-8b9cfc0d9e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copiar'])[1]/preceding::bdi[2]</value>
      <webElementGuid>4c53f98d-c82a-49ac-9cc5-6eb2e3e2e47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/button/span/span[2]/bdi</value>
      <webElementGuid>3d4baa6d-269d-42c1-ba1c-ea0232d98990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = 'application-zpurchaserequisition-createMP-component---detail--idMoreDataPosition-BDI-content' and (text() = 'Más Datos' or . = 'Más Datos')]</value>
      <webElementGuid>f7eeb9d3-9673-4576-81d2-7875dc11be51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
