<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Data inizio_application-ZPM_SMART-GEST_ab4b7d</name>
   <tag></tag>
   <elementGuidId>e9f14ae0-36fd-4d33-a762-6c16fdce982b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-StartDate-input-vhi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-StartDate-input-vhi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1ac1f30e-603e-4967-abb8-5e5a95b830dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-StartDate-input-vhi</value>
      <webElementGuid>6b89c913-350f-42f7-9907-8aa9c4cff931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-StartDate-input-vhi</value>
      <webElementGuid>e017bed3-ad2b-4d04-9f94-f73f9607b6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>2169d03a-9a74-4672-8f78-03a8f3f76f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ad2eb6e0-b6ef-4ad4-b5ea-b504b756ff3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Visualizza help valori</value>
      <webElementGuid>98f51a5c-ada2-42dd-931d-0d389001f35d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2f87332c-c8f0-4b51-9df8-fac804a5bc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconPointer sapMInputBaseIcon</value>
      <webElementGuid>fb7238d8-c0a0-4639-8c66-442c46e123b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-StartDate-input-vhi&quot;)</value>
      <webElementGuid>94c58a62-bc3a-4355-afa7-0e3e0d2770d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-StartDate-input-vhi']</value>
      <webElementGuid>256847f9-3817-4485-91a2-09ecc25f901f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-StartDate-input-content']/div/span</value>
      <webElementGuid>8eab1a79-78c4-4b9c-8f1f-4699e15e3f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div/div/div/span</value>
      <webElementGuid>76afbefa-2ae3-4a97-ab07-bb45c2a0bde7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'application-ZPM_SMART-GESTICKET-component---main--smartFilterBar-filterItemControlA_-StartDate-input-vhi']</value>
      <webElementGuid>a65351e0-95f7-41a8-ad8e-7dc2fa9b3895</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
