<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Material</name>
   <tag></tag>
   <elementGuidId>1bfc69fd-5d23-4ce9-baf5-a46c72f569c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:1:4:1:1::0:0-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>07c11dda-ce0d-4064-a0d6-e7b2793018d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:4:1:1::0:0-text</value>
      <webElementGuid>6c2ccf3d-66f1-4dab-91bd-36ddaf341c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsTabStrip--item-text</value>
      <webElementGuid>b39a7bbb-ee68-4e3a-b13d-4108d74d8d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Material</value>
      <webElementGuid>56522b76-e99e-44aa-b48f-c525062de2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:4:1:1::0:0-text&quot;)</value>
      <webElementGuid>865bc222-96c0-4cfc-8046-4f43dab14ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Movimientos salidas/Page_Salida de mercancas Otros/iframe_Ms_application-Material-goodsReceipt-iframe</value>
      <webElementGuid>a427d190-136d-4277-a930-d5e31a5b5454</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:4:1:1::0:0-text']</value>
      <webElementGuid>b632d7ff-e1fc-413f-a0b5-8c10bd8223ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46:1:4:1:1::0:0-title']/span</value>
      <webElementGuid>a253c224-786e-4673-b187-745b407364b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contenido'])[1]/following::span[10]</value>
      <webElementGuid>d7ec500f-b0bb-49ff-a7a1-0392e55f9dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrar'])[1]/following::span[12]</value>
      <webElementGuid>103ed716-65cb-4ed6-8ae4-2e9699486f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantidad'])[2]/preceding::span[1]</value>
      <webElementGuid>5db67d05-ad61-4ade-bd87-b09e9073b2a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donde'])[1]/preceding::span[2]</value>
      <webElementGuid>4de46314-9c0a-4af6-af8b-b8c8a50752d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/table/tbody/tr/td/table/tbody/tr/td[2]/div/div/div/span</value>
      <webElementGuid>6cfe9dfd-f6ef-49cb-9c8a-78931e36b624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'M0:46:1:4:1:1::0:0-text' and (text() = 'Material' or . = 'Material')]</value>
      <webElementGuid>f288a4de-10b9-4477-8826-af65bbafa990</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
