<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Imputacin</name>
   <tag></tag>
   <elementGuidId>05c05718-004d-4736-9b8e-020d27087e75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='M0:46:1:4:1:1::0:10-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f2c4e8fb-7746-44db-babc-460bcfefc958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M0:46:1:4:1:1::0:10-text</value>
      <webElementGuid>313176cd-6dfb-41d9-8145-d8cfbdb98fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsTabStrip--item-text</value>
      <webElementGuid>6b04adf7-29c5-44dd-a731-d8de75a13043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Imputación</value>
      <webElementGuid>3f75e37d-a839-4286-944f-71a58c115394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M0:46:1:4:1:1::0:10-text&quot;)</value>
      <webElementGuid>5f5d5951-c8ad-4c40-a35f-f833de780b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Movimientos salidas/Page_Salida de mercancas Otros/iframe_Ms_application-Material-goodsReceipt-iframe</value>
      <webElementGuid>4cfedbfe-d914-4523-8dff-08af892c8d42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='M0:46:1:4:1:1::0:10-text']</value>
      <webElementGuid>90b997d0-be29-466b-801f-dcbfca28d97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M0:46:1:4:1:1::0:10-title']/span</value>
      <webElementGuid>161fbf45-0917-4035-a273-3b4cf48f70b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donde'])[1]/following::span[1]</value>
      <webElementGuid>eedb94b3-5421-48c1-8f80-fd147d10f1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantidad'])[2]/following::span[2]</value>
      <webElementGuid>5854086d-c40c-44c5-a65b-0fe3ad348f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[2]/preceding::span[4]</value>
      <webElementGuid>542a0244-0920-4ca7-a6f6-870174e2f2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Imputación']/parent::*</value>
      <webElementGuid>feea5a7a-a086-4e10-b7d8-e0b6fa744328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div[4]/div/span</value>
      <webElementGuid>7c532ae1-6ea9-4a30-9be2-7a645c58c9a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'M0:46:1:4:1:1::0:10-text' and (text() = 'Imputación' or . = 'Imputación')]</value>
      <webElementGuid>39c07a9d-1afd-4d58-b648-5624e4ed0767</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
