<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Todo_search</name>
   <tag></tag>
   <elementGuidId>152fc3e5-69c4-4a37-a4a6-0d7bd2e5b1f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchFieldInShell-input-inner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchFieldInShell-input-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>910ec0d7-4332-4afc-841a-84328e0c3929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchFieldInShell-input-inner</value>
      <webElementGuid>30af4c75-79c1-4dfd-9b68-8fdb3fc165f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>be15a33d-73ae-4233-bb3e-7997b8add100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>searchFieldInShell-input-No-Results-Description</value>
      <webElementGuid>a6e2bef4-57c4-4517-b835-059ab9521f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>eb7bca08-e221-4304-b040-6b912f9d466e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>7b89aa03-5396-4f87-8e54-1b4a7ca16379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>27fad099-2733-4d6d-a046-6b21ce0798c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>e1a0edf6-f851-426f-a36e-6fe7bd08d751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fd571217-3c2f-4c16-aead-44b39eefa9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>13ed9cbd-02f7-4096-9d83-e9ea2e266f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchFieldInShell-input-inner&quot;)</value>
      <webElementGuid>71837f97-5bd3-455c-81d5-5e343069535b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchFieldInShell-input-inner']</value>
      <webElementGuid>dc3653f3-730b-404c-bf86-1a416d34cb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchFieldInShell-input-content']/input</value>
      <webElementGuid>3e3d6f6c-9e51-42f2-8f9a-62a0501a5038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>9732f809-1218-4db9-8c50-cc8b2934c7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchFieldInShell-input-inner' and @placeholder = 'Buscar' and @type = 'search' and @name = 'search']</value>
      <webElementGuid>190006bb-798e-44fd-ad15-ca6cbabd053c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
