<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Se ha creado la ubicacin tcnica E1-004_76d384</name>
   <tag></tag>
   <elementGuidId>488cc919-7beb-49a2-b1bc-c55aef5ba752</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='wnd[0]/sbar_msg-txt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eb5745af-52ac-4914-8f41-f876e4298253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>ac413815-82a3-41bd-a0ef-2715e062ac2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9480b20e-f5d2-4c74-a494-c7e3465742f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wnd[0]/sbar_msg-txt</value>
      <webElementGuid>6c000997-c279-4be4-af19-0d3bad0f10f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lsMessageBar__text lsMessageBar__text--overflow</value>
      <webElementGuid>175894c6-c19d-4273-a017-a5bdb14891bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Se ha creado la ubicación técnica E1-004-0012,040-TES--21</value>
      <webElementGuid>d273c1a2-0d6c-430d-b60e-b6e5da838e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Se ha creado la ubicación técnica E1-004-0012,040-TES--21</value>
      <webElementGuid>b932ac78-ce40-4a15-91b0-245952db5ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wnd[0]/sbar_msg-txt&quot;)</value>
      <webElementGuid>da327ee0-3269-4085-95b4-b91acd8a2c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Crear ubicacion tecnica/Page_Crear ubicacin tcnica Acceso/iframe_Ms_application-MaintenanceObject-cre_4115a2</value>
      <webElementGuid>215dee2c-ef19-48eb-9622-6b386170981c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='wnd[0]/sbar_msg-txt']</value>
      <webElementGuid>60e3ae5b-1446-44cf-a3c6-cbd72a8c7d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wnd[0]/sbar_msg']/span[2]</value>
      <webElementGuid>038b27ff-28fc-4afd-be67-35e1acbc3dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D'])[1]/following::span[2]</value>
      <webElementGuid>85cd17d4-73f6-4931-9da7-8b91ab620f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vacía'])[1]/preceding::span[51]</value>
      <webElementGuid>9e04c4da-c253-46a6-a89f-ad00e8f5202e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Se ha creado la ubicación técnica E1-004-0012,040-TES--21']/parent::*</value>
      <webElementGuid>7b507972-1361-4e3f-bf4b-0dad360fda36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/span[2]</value>
      <webElementGuid>ed282582-a51c-44c7-bc46-8bb832016333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'wnd[0]/sbar_msg-txt' and @title = 'Se ha creado la ubicación técnica E1-004-0012,040-TES--21' and (text() = 'Se ha creado la ubicación técnica E1-004-0012,040-TES--21' or . = 'Se ha creado la ubicación técnica E1-004-0012,040-TES--21')]</value>
      <webElementGuid>01068a7a-300d-49f7-9a4d-2c5e151a4d49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
